(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^q (e+f x^2)^r*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^q (e+f x^2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2) (c+d x^2)^q (e+f x^2)^r*)


(* ::Subsubsection::Closed:: *)
(*q>0*)


{(a + b*x^2)*(c + d*x^2)*(e + f*x^2)^4, x, 2, a*c*e^4*x + (1/3)*e^3*(b*c*e + a*d*e + 4*a*c*f)*x^3 + (1/5)*e^2*(2*a*f*(2*d*e + 3*c*f) + b*e*(d*e + 4*c*f))*x^5 + (2/7)*e*f*(a*f*(3*d*e + 2*c*f) + b*e*(2*d*e + 3*c*f))*x^7 + (1/9)*f^2*(a*f*(4*d*e + c*f) + 2*b*e*(3*d*e + 2*c*f))*x^9 + (1/11)*f^3*(4*b*d*e + b*c*f + a*d*f)*x^11 + (1/13)*b*d*f^4*x^13}
{(a + b*x^2)*(c + d*x^2)*(e + f*x^2)^3, x, 2, a*c*e^3*x + (1/3)*e^2*(b*c*e + a*d*e + 3*a*c*f)*x^3 + (1/5)*e*(3*a*f*(d*e + c*f) + b*e*(d*e + 3*c*f))*x^5 + (1/7)*f*(3*b*e*(d*e + c*f) + a*f*(3*d*e + c*f))*x^7 + (1/9)*f^2*(3*b*d*e + b*c*f + a*d*f)*x^9 + (1/11)*b*d*f^3*x^11}
{(a + b*x^2)*(c + d*x^2)*(e + f*x^2)^2, x, 2, a*c*e^2*x + (1/3)*e*(b*c*e + a*d*e + 2*a*c*f)*x^3 + (1/5)*(a*f*(2*d*e + c*f) + b*e*(d*e + 2*c*f))*x^5 + (1/7)*f*(2*b*d*e + b*c*f + a*d*f)*x^7 + (1/9)*b*d*f^2*x^9}
{(a + b*x^2)*(c + d*x^2)*(e + f*x^2)^1, x, 2, a*c*e*x + (1/3)*(b*c*e + a*d*e + a*c*f)*x^3 + (1/5)*(b*d*e + b*c*f + a*d*f)*x^5 + (1/7)*b*d*f*x^7}
{(a + b*x^2)*(c + d*x^2)/(e + f*x^2)^1, x, 3, -(((3*b*d*e - 3*b*c*f - 2*a*d*f)*x)/(3*f^2)) + (d*x*(a + b*x^2))/(3*f) + ((b*e - a*f)*(d*e - c*f)*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(Sqrt[e]*f^(5/2))}
{(a + b*x^2)*(c + d*x^2)/(e + f*x^2)^2, x, 3, (b*(3*d*e - c*f)*x)/(2*e*f^2) - ((d*e - c*f)*x*(a + b*x^2))/(2*e*f*(e + f*x^2)) - ((b*e*(3*d*e - c*f) - a*f*(d*e + c*f))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(2*e^(3/2)*f^(5/2))}
{(a + b*x^2)*(c + d*x^2)/(e + f*x^2)^3, x, 3, -(((d*e - c*f)*x*(a + b*x^2))/(4*e*f*(e + f*x^2)^2)) - ((b*e*(3*d*e + c*f) - a*f*(d*e + 3*c*f))*x)/(8*e^2*f^2*(e + f*x^2)) + ((b*e*(3*d*e + c*f) + a*f*(d*e + 3*c*f))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(8*e^(5/2)*f^(5/2))}
{(a + b*x^2)*(c + d*x^2)/(e + f*x^2)^4, x, 4, -(((d*e - c*f)*x*(a + b*x^2))/(6*e*f*(e + f*x^2)^3)) - ((3*b*e*(d*e + c*f) - a*f*(d*e + 5*c*f))*x)/(24*e^2*f^2*(e + f*x^2)^2) + ((b*e*(d*e + c*f) + a*f*(d*e + 5*c*f))*x)/(16*e^3*f^2*(e + f*x^2)) + ((b*e*(d*e + c*f) + a*f*(d*e + 5*c*f))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(16*e^(7/2)*f^(5/2))}


{(a + b*x^2)*(c + d*x^2)^2*(e + f*x^2)^3, x, 2, a*c^2*e^3*x + (1/3)*c*e^2*(b*c*e + 2*a*d*e + 3*a*c*f)*x^3 + (1/5)*e*(b*c*e*(2*d*e + 3*c*f) + a*(d^2*e^2 + 6*c*d*e*f + 3*c^2*f^2))*x^5 + (1/7)*(a*f*(3*d^2*e^2 + 6*c*d*e*f + c^2*f^2) + b*e*(d^2*e^2 + 6*c*d*e*f + 3*c^2*f^2))*x^7 + (1/9)*f*(a*d*f*(3*d*e + 2*c*f) + b*(3*d^2*e^2 + 6*c*d*e*f + c^2*f^2))*x^9 + (1/11)*d*f^2*(3*b*d*e + 2*b*c*f + a*d*f)*x^11 + (1/13)*b*d^2*f^3*x^13}
{(a + b*x^2)*(c + d*x^2)^2*(e + f*x^2)^2, x, 2, a*c^2*e^2*x + (1/3)*c*e*(b*c*e + 2*a*(d*e + c*f))*x^3 + (1/5)*(2*b*c*e*(d*e + c*f) + a*(d^2*e^2 + 4*c*d*e*f + c^2*f^2))*x^5 + (1/7)*(2*a*d*f*(d*e + c*f) + b*(d^2*e^2 + 4*c*d*e*f + c^2*f^2))*x^7 + (1/9)*d*f*(a*d*f + 2*b*(d*e + c*f))*x^9 + (1/11)*b*d^2*f^2*x^11}
{(a + b*x^2)*(c + d*x^2)^2*(e + f*x^2)^1, x, 2, a*c^2*e*x + (1/3)*c*(b*c*e + 2*a*d*e + a*c*f)*x^3 + (1/5)*(b*c*(2*d*e + c*f) + a*d*(d*e + 2*c*f))*x^5 + (1/7)*d*(b*d*e + 2*b*c*f + a*d*f)*x^7 + (1/9)*b*d^2*f*x^9}
{(a + b*x^2)*(c + d*x^2)^2/(e + f*x^2)^1, x, 4, -(((5*a*d*f*(3*d*e - 5*c*f) - b*(15*d^2*e^2 - 25*c*d*e*f + 8*c^2*f^2))*x)/(15*f^3)) - ((5*b*d*e - 4*b*c*f - 5*a*d*f)*x*(c + d*x^2))/(15*f^2) + (b*x*(c + d*x^2)^2)/(5*f) - ((b*e - a*f)*(d*e - c*f)^2*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(Sqrt[e]*f^(7/2))}
{(a + b*x^2)*(c + d*x^2)^2/(e + f*x^2)^2, x, 4, -((d*(b*e*(15*d*e - 13*c*f) - 3*a*f*(3*d*e - c*f))*x)/(6*e*f^3)) + (d*(5*b*e - 3*a*f)*x*(c + d*x^2))/(6*e*f^2) - ((b*e - a*f)*x*(c + d*x^2)^2)/(2*e*f*(e + f*x^2)) + ((d*e - c*f)*(b*e*(5*d*e - c*f) - a*f*(3*d*e + c*f))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(2*e^(3/2)*f^(7/2))}
{(a + b*x^2)*(c + d*x^2)^2/(e + f*x^2)^3, x, 4, (d*(b*e*(15*d*e - c*f) - 3*a*f*(d*e + c*f))*x)/(8*e^2*f^3) - ((b*e - a*f)*x*(c + d*x^2)^2)/(4*e*f*(e + f*x^2)^2) - ((b*e*(5*d*e - c*f) - a*f*(d*e + 3*c*f))*x*(c + d*x^2))/(8*e^2*f^2*(e + f*x^2)) - ((b*e*(15*d^2*e^2 - 6*c*d*e*f - c^2*f^2) - a*f*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(8*e^(5/2)*f^(7/2))}
{(a + b*x^2)*(c + d*x^2)^2/(e + f*x^2)^4, x, 4, -(((b*e - a*f)*x*(c + d*x^2)^2)/(6*e*f*(e + f*x^2)^3)) - ((d*e*(5*b*e + a*f) - c*f*(b*e + 5*a*f))*x*(c + d*x^2))/(24*e^2*f^2*(e + f*x^2)^2) - ((a*f*(3*d^2*e^2 + 4*c*d*e*f - 15*c^2*f^2) + b*e*(15*d^2*e^2 - 4*c*d*e*f - 3*c^2*f^2))*x)/(48*e^3*f^3*(e + f*x^2)) + ((b*e*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2) + a*f*(d^2*e^2 + 2*c*d*e*f + 5*c^2*f^2))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(16*e^(7/2)*f^(7/2))}


{(a + b*x^2)*(c + d*x^2)^3*(e + f*x^2)^3, x, 2, a*c^3*e^3*x + (1/3)*c^2*e^2*(b*c*e + 3*a*(d*e + c*f))*x^3 + (3/5)*c*e*(b*c*e*(d*e + c*f) + a*(d^2*e^2 + 3*c*d*e*f + c^2*f^2))*x^5 + (1/7)*(3*b*c*e*(d^2*e^2 + 3*c*d*e*f + c^2*f^2) + a*(d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + c^3*f^3))*x^7 + (1/9)*(3*a*d*f*(d^2*e^2 + 3*c*d*e*f + c^2*f^2) + b*(d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + c^3*f^3))*x^9 + (3/11)*d*f*(a*d*f*(d*e + c*f) + b*(d^2*e^2 + 3*c*d*e*f + c^2*f^2))*x^11 + (1/13)*d^2*f^2*(a*d*f + 3*b*(d*e + c*f))*x^13 + (1/15)*b*d^3*f^3*x^15}
{(a + b*x^2)*(c + d*x^2)^3*(e + f*x^2)^2, x, 2, a*c^3*e^2*x + (1/3)*c^2*e*(b*c*e + 3*a*d*e + 2*a*c*f)*x^3 + (1/5)*c*(b*c*e*(3*d*e + 2*c*f) + a*(3*d^2*e^2 + 6*c*d*e*f + c^2*f^2))*x^5 + (1/7)*(b*c*(3*d^2*e^2 + 6*c*d*e*f + c^2*f^2) + a*d*(d^2*e^2 + 6*c*d*e*f + 3*c^2*f^2))*x^7 + (1/9)*d*(a*d*f*(2*d*e + 3*c*f) + b*(d^2*e^2 + 6*c*d*e*f + 3*c^2*f^2))*x^9 + (1/11)*d^2*f*(2*b*d*e + 3*b*c*f + a*d*f)*x^11 + (1/13)*b*d^3*f^2*x^13}
{(a + b*x^2)*(c + d*x^2)^3*(e + f*x^2)^1, x, 2, a*c^3*e*x + (1/3)*c^2*(b*c*e + 3*a*d*e + a*c*f)*x^3 + (1/5)*c*(3*a*d*(d*e + c*f) + b*c*(3*d*e + c*f))*x^5 + (1/7)*d*(3*b*c*(d*e + c*f) + a*d*(d*e + 3*c*f))*x^7 + (1/9)*d^2*(b*d*e + 3*b*c*f + a*d*f)*x^9 + (1/11)*b*d^3*f*x^11}
{(a + b*x^2)*(c + d*x^2)^3/(e + f*x^2)^1, x, 5, ((7*a*d*f*(15*d^2*e^2 - 40*c*d*e*f + 33*c^2*f^2) - b*(105*d^3*e^3 - 280*c*d^2*e^2*f + 231*c^2*d*e*f^2 - 48*c^3*f^3))*x)/(105*f^4) - ((7*a*d*f*(5*d*e - 9*c*f) - b*(35*d^2*e^2 - 63*c*d*e*f + 24*c^2*f^2))*x*(c + d*x^2))/(105*f^3) - ((7*b*d*e - 6*b*c*f - 7*a*d*f)*x*(c + d*x^2)^2)/(35*f^2) + (b*x*(c + d*x^2)^3)/(7*f) + ((b*e - a*f)*(d*e - c*f)^3*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(Sqrt[e]*f^(9/2))}
{(a + b*x^2)*(c + d*x^2)^3/(e + f*x^2)^2, x, 5, -((d*(5*a*f*(15*d^2*e^2 - 22*c*d*e*f + 3*c^2*f^2) - b*e*(105*d^2*e^2 - 190*c*d*e*f + 81*c^2*f^2))*x)/(30*e*f^4)) - (d*(b*e*(35*d*e - 33*c*f) - 5*a*f*(5*d*e - 3*c*f))*x*(c + d*x^2))/(30*e*f^3) + (d*(7*b*e - 5*a*f)*x*(c + d*x^2)^2)/(10*e*f^2) - ((b*e - a*f)*x*(c + d*x^2)^3)/(2*e*f*(e + f*x^2)) - ((d*e - c*f)^2*(b*e*(7*d*e - c*f) - a*f*(5*d*e + c*f))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(2*e^(3/2)*f^(9/2))}
{(a + b*x^2)*(c + d*x^2)^3/(e + f*x^2)^3, x, 5, (d*(3*a*f*(15*d^2*e^2 - 4*c*d*e*f - 3*c^2*f^2) - b*e*(105*d^2*e^2 - 100*c*d*e*f + 3*c^2*f^2))*x)/(24*e^2*f^4) + (d*(b*e*(35*d*e - 3*c*f) - 3*a*f*(5*d*e + 3*c*f))*x*(c + d*x^2))/(24*e^2*f^3) - ((b*e - a*f)*x*(c + d*x^2)^3)/(4*e*f*(e + f*x^2)^2) - ((b*e*(7*d*e - c*f) - 3*a*f*(d*e + c*f))*x*(c + d*x^2)^2)/(8*e^2*f^2*(e + f*x^2)) + ((d*e - c*f)*(b*e*(35*d^2*e^2 - 10*c*d*e*f - c^2*f^2) - 3*a*f*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(8*e^(5/2)*f^(9/2))}
{(a + b*x^2)*(c + d*x^2)^3/(e + f*x^2)^4, x, 5, (d*(b*e*(105*d^2*e^2 - 10*c*d*e*f - 3*c^2*f^2) - a*f*(15*d^2*e^2 + 14*c*d*e*f + 15*c^2*f^2))*x)/(48*e^3*f^4) - ((b*e - a*f)*x*(c + d*x^2)^3)/(6*e*f*(e + f*x^2)^3) - ((b*e*(7*d*e - c*f) - a*f*(d*e + 5*c*f))*x*(c + d*x^2)^2)/(24*e^2*f^2*(e + f*x^2)^2) - ((b*e*(35*d^2*e^2 - 8*c*d*e*f - 3*c^2*f^2) - a*f*(5*d^2*e^2 + 4*c*d*e*f + 15*c^2*f^2))*x*(c + d*x^2))/(48*e^3*f^3*(e + f*x^2)) - ((b*e*(35*d^3*e^3 - 15*c*d^2*e^2*f - 3*c^2*d*e*f^2 - c^3*f^3) - a*f*(5*d^3*e^3 + 3*c*d^2*e^2*f + 3*c^2*d*e*f^2 + 5*c^3*f^3))*ArcTan[(Sqrt[f]*x)/Sqrt[e]])/(16*e^(7/2)*f^(9/2))}


(* ::Subsubsection:: *)
(*q<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) (e+f x^2)*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{(a + b*x^2)*(e + f*x^2)^(1/2)*(c + d*x^2)^(3/2), x, 7, -(((7*a*d*f*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) - b*(8*d^3*e^3 - 19*c*d^2*e^2*f + 9*c^2*d*e*f^2 - 6*c^3*f^3))*x*Sqrt[c + d*x^2])/(105*d^2*f^2*Sqrt[e + f*x^2])) + ((7*a*d*f*(d*e + 3*c*f) - b*(4*d^2*e^2 - 6*c*d*e*f + 6*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*d*f^2) + ((b*d*e - 2*b*c*f + 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*d*f) + (b*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*d) + (Sqrt[e]*(7*a*d*f*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) - b*(8*d^3*e^3 - 19*c*d^2*e^2*f + 9*c^2*d*e*f^2 - 6*c^3*f^3))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*d^2*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (e^(3/2)*(7*a*d*f*(d*e - 9*c*f) - b*(4*d^2*e^2 - 9*c*d*e*f - 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*d*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)*(c + d*x^2)^(1/2), x, 6, ((5*a*d*f*(d*e + c*f) - 2*b*(d^2*e^2 - c*d*e*f + c^2*f^2))*x*Sqrt[c + d*x^2])/(15*d^2*f*Sqrt[e + f*x^2]) + ((b*d*e - 2*b*c*f + 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*d*f) + (b*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*d) - (Sqrt[e]*(5*a*d*f*(d*e + c*f) - 2*b*(d^2*e^2 - c*d*e*f + c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*d^2*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (e^(3/2)*(b*d*e + b*c*f - 10*a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*d*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(1/2), x, 5, ((b*d*e - 2*b*c*f + 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*d^2*Sqrt[e + f*x^2]) + (b*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*d) - (Sqrt[e]*(b*d*e - 2*b*c*f + 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*d^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - ((b*c - 3*a*d)*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c*d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(3/2), x, 5, ((2*b*c - a*d)*f*x*Sqrt[c + d*x^2])/(c*d^2*Sqrt[e + f*x^2]) - ((b*c - a*d)*x*Sqrt[e + f*x^2])/(c*d*Sqrt[c + d*x^2]) - ((2*b*c - a*d)*Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*d^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(5/2), x, 4, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(3*c*d*(c + d*x^2)^(3/2))) + ((d*(b*c + 2*a*d)*e - c*(2*b*c + a*d)*f)*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(3*c^(3/2)*d^(3/2)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + ((b*c - a*d)*e^(3/2)*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*d*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(7/2), x, 5, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(5*c*d*(c + d*x^2)^(5/2))) + ((a*d*(4*d*e - 3*c*f) + b*c*(d*e - 2*c*f))*x*Sqrt[e + f*x^2])/(15*c^2*d*(d*e - c*f)*(c + d*x^2)^(3/2)) + ((2*b*c*(d^2*e^2 - c*d*e*f + c^2*f^2) + a*d*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(15*c^(5/2)*d^(3/2)*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (e^(3/2)*Sqrt[f]*(2*a*d*(2*d*e - 3*c*f) + b*c*(d*e + c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c^3*d*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


{(a + b*x^2)*(e + f*x^2)^(3/2)*(c + d*x^2)^(1/2), x, 7, ((7*a*d*f*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2) - b*(6*d^3*e^3 - 9*c*d^2*e^2*f + 19*c^2*d*e*f^2 - 8*c^3*f^3))*x*Sqrt[c + d*x^2])/(105*d^3*f*Sqrt[e + f*x^2]) + ((14*a*d*f*(3*d*e - c*f) + b*(3*d^2*e^2 - 15*c*d*e*f + 8*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*d^2*f) + ((3*b*d*e - 4*b*c*f + 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*d^2) + (b*x*(c + d*x^2)^(3/2)*(e + f*x^2)^(3/2))/(7*d) - (Sqrt[e]*(7*a*d*f*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2) - b*(6*d^3*e^3 - 9*c*d^2*e^2*f + 19*c^2*d*e*f^2 - 8*c^3*f^3))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*d^3*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(7*a*d*f*(9*d*e - c*f) - b*(3*d^2*e^2 + 9*c*d*e*f - 4*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*d^2*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(1/2), x, 6, ((10*a*d*f*(2*d*e - c*f) + b*(3*d^2*e^2 - 13*c*d*e*f + 8*c^2*f^2))*x*Sqrt[c + d*x^2])/(15*d^3*Sqrt[e + f*x^2]) + ((3*b*d*e - 4*b*c*f + 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*d^2) + (b*x*Sqrt[c + d*x^2]*(e + f*x^2)^(3/2))/(5*d) - (Sqrt[e]*(10*a*d*f*(2*d*e - c*f) + b*(3*d^2*e^2 - 13*c*d*e*f + 8*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*d^3*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(5*a*d*(3*d*e - c*f) - b*(6*c*d*e - 4*c^2*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c*d^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(3/2), x, 6, (f*(b*c*(7*d*e - 8*c*f) - 3*a*d*(d*e - 2*c*f))*x*Sqrt[c + d*x^2])/(3*c*d^3*Sqrt[e + f*x^2]) + ((4*b*c - 3*a*d)*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*c*d^2) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(c*d*Sqrt[c + d*x^2]) - (Sqrt[e]*Sqrt[f]*(b*c*(7*d*e - 8*c*f) - 3*a*d*(d*e - 2*c*f))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c*d^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(3*b*d*e - 4*b*c*f + 3*a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c*d^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(5/2), x, 6, -((f*(b*c*(d*e - 8*c*f) + 2*a*d*(d*e + c*f))*x*Sqrt[c + d*x^2])/(3*c^2*d^3*Sqrt[e + f*x^2])) + ((b*c*(d*e - 4*c*f) + a*d*(2*d*e + c*f))*x*Sqrt[e + f*x^2])/(3*c^2*d^2*Sqrt[c + d*x^2]) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(3*c*d*(c + d*x^2)^(3/2)) + (Sqrt[e]*Sqrt[f]*(b*c*(d*e - 8*c*f) + 2*a*d*(d*e + c*f))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*d^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((4*b*c - a*d)*e^(3/2)*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*d^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(7/2), x, 5, ((d*(b*c + 4*a*d)*e - c*(4*b*c + a*d)*f)*x*Sqrt[e + f*x^2])/(15*c^2*d^2*(c + d*x^2)^(3/2)) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(5*c*d*(c + d*x^2)^(5/2)) + ((b*c*(2*d^2*e^2 + 3*c*d*e*f - 8*c^2*f^2) + a*d*(8*d^2*e^2 - 3*c*d*e*f - 2*c^2*f^2))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(15*c^(5/2)*d^(5/2)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (e^(3/2)*Sqrt[f]*(b*c*(d*e - 4*c*f) + a*d*(4*d*e - c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c^3*d^2*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(9/2), x, 6, ((d*(b*c + 6*a*d)*e - c*(4*b*c + 3*a*d)*f)*x*Sqrt[e + f*x^2])/(35*c^2*d^2*(c + d*x^2)^(5/2)) + ((b*c*(4*d^2*e^2 + c*d*e*f - 8*c^2*f^2) + 3*a*d*(8*d^2*e^2 - 5*c*d*e*f - 2*c^2*f^2))*x*Sqrt[e + f*x^2])/(105*c^3*d^2*(d*e - c*f)*(c + d*x^2)^(3/2)) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(7*c*d*(c + d*x^2)^(7/2)) + ((6*a*d*(8*d^3*e^3 - 12*c*d^2*e^2*f + 2*c^2*d*e*f^2 + c^3*f^3) + b*c*(8*d^3*e^3 - 5*c*d^2*e^2*f - 5*c^2*d*e*f^2 + 8*c^3*f^3))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(105*c^(7/2)*d^(5/2)*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (e^(3/2)*Sqrt[f]*(3*a*d*(8*d^2*e^2 - 11*c*d*e*f + c^2*f^2) + 2*b*c*(2*d^2*e^2 - c*d*e*f + 2*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*c^4*d^2*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


(* ::Subsubsection::Closed:: *)
(*q<0*)


{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(5/2), x, 7, ((7*a*d*f*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2) - b*(48*d^3*e^3 - 128*c*d^2*e^2*f + 103*c^2*d*e*f^2 - 15*c^3*f^3))*x*Sqrt[c + d*x^2])/(105*d*f^3*Sqrt[e + f*x^2]) - ((28*a*d*f*(d*e - 2*c*f) - b*(24*d^2*e^2 - 43*c*d*e*f + 15*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*f^3) - ((6*b*d*e - 5*b*c*f - 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*f^2) + (b*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*f) - (Sqrt[e]*(7*a*d*f*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2) - b*(48*d^3*e^3 - 128*c*d^2*e^2*f + 103*c^2*d*e*f^2 - 15*c^3*f^3))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*d*f^(7/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[e]*(7*a*f*(4*d^2*e^2 - 11*c*d*e*f + 15*c^2*f^2) - b*e*(24*d^2*e^2 - 61*c*d*e*f + 45*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(105*f^(7/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(3/2), x, 6, -(((10*a*d*f*(d*e - 2*c*f) - b*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*x*Sqrt[c + d*x^2])/(15*d*f^2*Sqrt[e + f*x^2])) - ((4*b*d*e - 3*b*c*f - 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*f^2) + (b*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*f) + (Sqrt[e]*(10*a*d*f*(d*e - 2*c*f) - b*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*d*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(5*a*f*(d*e - 3*c*f) - b*(4*d*e^2 - 6*c*e*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(1/2), x, 5, -(((2*b*d*e - b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*d*f*Sqrt[e + f*x^2])) + (b*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*f) + (Sqrt[e]*(2*b*d*e - b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*d*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(b*e - 3*a*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(1/2), x, 4, (b*x*Sqrt[c + d*x^2])/(d*Sqrt[e + f*x^2]) - (b*Sqrt[e]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (a*Sqrt[e]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(3/2), x, 3, -(((b*c - a*d)*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*Sqrt[d]*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])) + (Sqrt[e]*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*Sqrt[f]*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(5/2), x, 4, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(3*c*(d*e - c*f)*(c + d*x^2)^(3/2))) + ((2*a*d*(d*e - 2*c*f) + b*c*(d*e + c*f))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(3*c^(3/2)*Sqrt[d]*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (Sqrt[e]*Sqrt[f]*(2*b*c*e + a*d*e - 3*a*c*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(7/2), x, 5, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(5*c*(d*e - c*f)*(c + d*x^2)^(5/2))) + ((4*a*d*(d*e - 2*c*f) + b*c*(d*e + 3*c*f))*x*Sqrt[e + f*x^2])/(15*c^2*(d*e - c*f)^2*(c + d*x^2)^(3/2)) + ((b*c*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) + a*d*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(15*c^(5/2)*Sqrt[d]*(d*e - c*f)^3*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (Sqrt[e]*Sqrt[f]*(b*c*e*(d*e - 9*c*f) + a*(4*d^2*e^2 - 11*c*d*e*f + 15*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c^3*(d*e - c*f)^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(5/2), x, 7, -(((5*a*f*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) - 2*b*e*(24*d^2*e^2 - 44*c*d*e*f + 19*c^2*f^2))*x*Sqrt[c + d*x^2])/(15*e*f^3*Sqrt[e + f*x^2])) - ((b*e - a*f)*x*(c + d*x^2)^(5/2))/(e*f*Sqrt[e + f*x^2]) - (d*(b*e*(24*d*e - 23*c*f) - 5*a*f*(4*d*e - 3*c*f))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*e*f^3) + (d*(6*b*e - 5*a*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*e*f^2) + ((5*a*f*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) - 2*b*e*(24*d^2*e^2 - 44*c*d*e*f + 19*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*Sqrt[e]*f^(7/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(10*a*d*f*(2*d*e - 3*c*f) - b*(24*d^2*e^2 - 41*c*d*e*f + 15*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*f^(7/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(3/2), x, 6, -(((b*e*(8*d*e - 7*c*f) - 3*a*f*(2*d*e - c*f))*x*Sqrt[c + d*x^2])/(3*e*f^2*Sqrt[e + f*x^2])) - ((b*e - a*f)*x*(c + d*x^2)^(3/2))/(e*f*Sqrt[e + f*x^2]) + (d*(4*b*e - 3*a*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*e*f^2) + ((b*e*(8*d*e - 7*c*f) - 3*a*f*(2*d*e - c*f))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*Sqrt[e]*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(4*b*d*e - 3*b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*f^(5/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(1/2), x, 5, -(((b*e - a*f)*x*Sqrt[c + d*x^2])/(e*f*Sqrt[e + f*x^2])) + ((2*b*e - a*f)*x*Sqrt[c + d*x^2])/(e*f*Sqrt[e + f*x^2]) - ((2*b*e - a*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(Sqrt[e]*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b*Sqrt[e]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(1/2), x, 3, ((b*e - a*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(Sqrt[e]*Sqrt[f]*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - ((b*c - a*d)*Sqrt[e]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*Sqrt[f]*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(3/2), x, 4, -(((b*c - a*d)*x)/(c*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) - (Sqrt[f]*(2*b*c*e - a*d*e - a*c*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*Sqrt[e]*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[e]*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*Sqrt[f]*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(5/2), x, 5, -(((b*c - a*d)*x)/(3*c*(d*e - c*f)*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])) + ((2*a*d*(d*e - 3*c*f) + b*c*(d*e + 3*c*f))*x)/(3*c^2*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[f]*(b*c*e*(d*e + 7*c*f) + a*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*Sqrt[e]*(d*e - c*f)^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[f]*(a*d*(d*e - 9*c*f) + b*c*(5*d*e + 3*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(d*e - c*f)^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


{(e + f*x^2)/(Sqrt[a + b*x^2]*(c + d*x^2)^(3/2)), x, 3, -(((d*e - c*f)*Sqrt[a + b*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (b*c)/(a*d)])/(Sqrt[c]*Sqrt[d]*(b*c - a*d)*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2])) + (Sqrt[c]*(b*e - a*f)*Sqrt[a + b*x^2]*EllipticF[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (b*c)/(a*d)])/(a*Sqrt[d]*(b*c - a*d)*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2])}
{(e + f*x^2)/(Sqrt[a - b*x^2]*(c + d*x^2)^(3/2)), x, 8, ((d*e - c*f)*x*Sqrt[a - b*x^2])/(c*(b*c + a*d)*Sqrt[c + d*x^2]) + (Sqrt[a]*Sqrt[b]*(d*e - c*f)*Sqrt[1 - (b*x^2)/a]*Sqrt[c + d*x^2]*EllipticE[ArcSin[(Sqrt[b]*x)/Sqrt[a]], -((a*d)/(b*c))])/(c*d*(b*c + a*d)*Sqrt[a - b*x^2]*Sqrt[1 + (d*x^2)/c]) + (Sqrt[a]*f*Sqrt[1 - (b*x^2)/a]*Sqrt[1 + (d*x^2)/c]*EllipticF[ArcSin[(Sqrt[b]*x)/Sqrt[a]], -((a*d)/(b*c))])/(Sqrt[b]*d*Sqrt[a - b*x^2]*Sqrt[c + d*x^2])}
{(e + f*x^2)/(Sqrt[a + b*x^2]*(c - d*x^2)^(3/2)), x, 8, ((d*e + c*f)*x*Sqrt[a + b*x^2])/(c*(b*c + a*d)*Sqrt[c - d*x^2]) - ((d*e + c*f)*Sqrt[a + b*x^2]*Sqrt[1 - (d*x^2)/c]*EllipticE[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((b*c)/(a*d))])/(Sqrt[c]*Sqrt[d]*(b*c + a*d)*Sqrt[1 + (b*x^2)/a]*Sqrt[c - d*x^2]) + (e*Sqrt[1 + (b*x^2)/a]*Sqrt[1 - (d*x^2)/c]*EllipticF[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((b*c)/(a*d))])/(Sqrt[c]*Sqrt[d]*Sqrt[a + b*x^2]*Sqrt[c - d*x^2])}
{(e + f*x^2)/(Sqrt[a - b*x^2]*(c - d*x^2)^(3/2)), x, 8, -(((d*e + c*f)*x*Sqrt[a - b*x^2])/(c*(b*c - a*d)*Sqrt[c - d*x^2])) + ((d*e + c*f)*Sqrt[a - b*x^2]*Sqrt[1 - (d*x^2)/c]*EllipticE[ArcSin[(Sqrt[d]*x)/Sqrt[c]], (b*c)/(a*d)])/(Sqrt[c]*Sqrt[d]*(b*c - a*d)*Sqrt[1 - (b*x^2)/a]*Sqrt[c - d*x^2]) + (e*Sqrt[1 - (b*x^2)/a]*Sqrt[1 - (d*x^2)/c]*EllipticF[ArcSin[(Sqrt[d]*x)/Sqrt[c]], (b*c)/(a*d)])/(Sqrt[c]*Sqrt[d]*Sqrt[a - b*x^2]*Sqrt[c - d*x^2])}


{(a + b*x^2)/(Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2]), x, 4, (b*x*Sqrt[2 + d*x^2])/(d*Sqrt[3 + f*x^2]) - (Sqrt[2]*b*Sqrt[2 + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(d*Sqrt[f]*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2]) + (a*Sqrt[2 + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(Sqrt[2]*Sqrt[f]*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2])}
{(a + b*x^2)*Sqrt[2 + d*x^2]/Sqrt[3 + f*x^2], x, 5, -(((6*b*d - 2*b*f - 3*a*d*f)*x*Sqrt[2 + d*x^2])/(3*d*f*Sqrt[3 + f*x^2])) + (b*x*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2])/(3*f) + (Sqrt[2]*(6*b*d - 2*b*f - 3*a*d*f)*Sqrt[2 + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(3*d*f^(3/2)*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2]) - (Sqrt[2]*(b - a*f)*Sqrt[2 + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(f^(3/2)*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2])}
{(a + b*x^2)*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2], x, 6, ((5*a*d*f*(3*d + 2*f) - 2*b*(9*d^2 - 6*d*f + 4*f^2))*x*Sqrt[2 + d*x^2])/(15*d^2*f*Sqrt[3 + f*x^2]) + ((3*b*d - 4*b*f + 5*a*d*f)*x*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2])/(15*d*f) + (b*x*(2 + d*x^2)^(3/2)*Sqrt[3 + f*x^2])/(5*d) - (Sqrt[2]*(5*a*d*f*(3*d + 2*f) - 2*b*(9*d^2 - 6*d*f + 4*f^2))*Sqrt[2 + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(15*d^2*f^(3/2)*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2]) - (Sqrt[2]*(3*b*d + 2*b*f - 10*a*d*f)*Sqrt[2 + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(5*d*f^(3/2)*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2])}


{(-b - Sqrt[b^2 - 4*a*c] + 2*c*x^2)/(Sqrt[1 + (2*c*x^2)/(-b - Sqrt[b^2 - 4*a*c])]*Sqrt[1 + (2*c*x^2)/(-b + Sqrt[b^2 - 4*a*c])]), x, 2, -((Sqrt[b - Sqrt[b^2 - 4*a*c]]*(b + Sqrt[b^2 - 4*a*c])*EllipticE[ArcSin[(Sqrt[2]*Sqrt[c]*x)/Sqrt[b - Sqrt[b^2 - 4*a*c]]], (b - Sqrt[b^2 - 4*a*c])/(b + Sqrt[b^2 - 4*a*c])])/(Sqrt[2]*Sqrt[c]))}
{(b - Sqrt[b^2 - 4*a*c] + 2*c*x^2)/(Sqrt[1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c])]*Sqrt[1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c])]), x, 5, ((b - Sqrt[b^2 - 4*a*c])*x*Sqrt[1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c])])/Sqrt[1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c])] - ((b - Sqrt[b^2 - 4*a*c])*Sqrt[b + Sqrt[b^2 - 4*a*c]]*Sqrt[1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c])]*EllipticE[ArcTan[(Sqrt[2]*Sqrt[c]*x)/Sqrt[b + Sqrt[b^2 - 4*a*c]]], -((2*Sqrt[b^2 - 4*a*c])/(b - Sqrt[b^2 - 4*a*c]))])/(Sqrt[2]*Sqrt[c]*Sqrt[(1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c]))/(1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c]))]*Sqrt[1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c])]) + ((b - Sqrt[b^2 - 4*a*c])*Sqrt[b + Sqrt[b^2 - 4*a*c]]*Sqrt[1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c])]*EllipticF[ArcTan[(Sqrt[2]*Sqrt[c]*x)/Sqrt[b + Sqrt[b^2 - 4*a*c]]], -((2*Sqrt[b^2 - 4*a*c])/(b - Sqrt[b^2 - 4*a*c]))])/(Sqrt[2]*Sqrt[c]*Sqrt[(1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c]))/(1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c]))]*Sqrt[1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c])])}


(* ::Section:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^q (e+f x^2)^2*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^q / (e+f x^2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^(q/2) / (e+f x^2)*)


(* ::Subsubsection::Closed:: *)
(*q>0*)


{(a + b*x^2)*Sqrt[c + d*x^2]/(e + f*x^2), x, 6, (b*x*Sqrt[c + d*x^2])/(2*f) - ((2*b*d*e - b*c*f - 2*a*d*f)*ArcTanh[(Sqrt[d]*x)/Sqrt[c + d*x^2]])/(2*Sqrt[d]*f^2) + ((b*e - a*f)*Sqrt[d*e - c*f]*ArcTanh[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])])/(Sqrt[e]*f^2)}


(* ::Subsubsection::Closed:: *)
(*q<0*)


{(a + b*x^2)^3/((c + d*x^2)*Sqrt[e + f*x^2]), x, 14, -((b^2*(b*c - a*d)*x*Sqrt[e + f*x^2])/(2*d^2*f)) - (3*b^2*(b*e - 2*a*f)*x*Sqrt[e + f*x^2])/(8*d*f^2) + (b^2*x*(a + b*x^2)*Sqrt[e + f*x^2])/(4*d*f) - ((b*c - a*d)^3*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d^3*Sqrt[d*e - c*f]) + (b*(b*c - a*d)^2*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d^3*Sqrt[f]) + (b*(b*c - a*d)*(b*e - 2*a*f)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(2*d^2*f^(3/2)) + (b*(3*b^2*e^2 - 8*a*b*e*f + 8*a^2*f^2)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(8*d*f^(5/2))}
{(a + b*x^2)^2/((c + d*x^2)*Sqrt[e + f*x^2]), x, 9, (b^2*x*Sqrt[e + f*x^2])/(2*d*f) + ((b*c - a*d)^2*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d^2*Sqrt[d*e - c*f]) - (b*(b*c - a*d)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d^2*Sqrt[f]) - (b*(b*e - 2*a*f)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(2*d*f^(3/2))}
{(a + b*x^2)^1/((c + d*x^2)*Sqrt[e + f*x^2]), x, 5, -(((b*c - a*d)*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d*Sqrt[d*e - c*f])) + (b*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d*Sqrt[f])}
{(a + b*x^2)^0/((c + d*x^2)*Sqrt[e + f*x^2]), x, 2, ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])]/(Sqrt[c]*Sqrt[d*e - c*f])}
{1/((a + b*x^2)^1*(c + d*x^2)*Sqrt[e + f*x^2]), x, 5, (b*ArcTan[(Sqrt[b*e - a*f]*x)/(Sqrt[a]*Sqrt[e + f*x^2])])/(Sqrt[a]*(b*c - a*d)*Sqrt[b*e - a*f]) - (d*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*(b*c - a*d)*Sqrt[d*e - c*f])}
{1/((a + b*x^2)^2*(c + d*x^2)*Sqrt[e + f*x^2]), x, 7, (b^2*x*Sqrt[e + f*x^2])/(2*a*(b*c - a*d)*(b*e - a*f)*(a + b*x^2)) + (b*(b^2*c*e - 3*a*b*d*e - 2*a*b*c*f + 4*a^2*d*f)*ArcTan[(Sqrt[b*e - a*f]*x)/(Sqrt[a]*Sqrt[e + f*x^2])])/(2*a^(3/2)*(b*c - a*d)^2*(b*e - a*f)^(3/2)) + (d^2*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*(b*c - a*d)^2*Sqrt[d*e - c*f])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) / (e+f x^2)*)


(* ::Subsubsection::Closed:: *)
(*q>0*)


{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(5/2), x, 14, (d*(7*c*e - (2*d*e^2)/f + (3*c^2*f)/d)*x*Sqrt[c + d*x^2])/(15*b*Sqrt[e + f*x^2]) + ((b*c - a*d)*(b*d*e + 4*b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^3*Sqrt[e + f*x^2]) + (d*(b*c - a*d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) - (2*d*(d*e - 3*c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b*f) + (d^2*x*Sqrt[c + d*x^2]*(e + f*x^2)^(3/2))/(5*b*f) - (Sqrt[e]*(15*a^2*d^2*f^2 - 5*a*b*d*f*(d*e + 7*c*f) + b^2*(-2*d^2*e^2 + 12*c*d*e*f + 23*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^3*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*e^(3/2)*(-40*a*b*c*d*f + 15*a^2*d^2*f + b^2*c*((-d)*e + 34*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^3*c*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^3*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b^3*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]), (d*(7*c*e - (2*d*e^2)/f + (3*c^2*f)/d)*x*Sqrt[c + d*x^2])/(15*b*Sqrt[e + f*x^2]) + ((b*c - a*d)*(b*d*e + 4*b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^3*Sqrt[e + f*x^2]) + (d*(b*c - a*d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) - (2*d*(d*e - 3*c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b*f) + (d^2*x*Sqrt[c + d*x^2]*(e + f*x^2)^(3/2))/(5*b*f) - ((b*c - a*d)*Sqrt[e]*(b*d*e + 4*b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^3*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[e]*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*(5*b*c - 3*a*d)*(b*c - a*d)*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^3*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d*e^(3/2)*(d*e - 9*c*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^3*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b^3*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(3/2), x, 7, ((b*d*e + 4*b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^2*Sqrt[e + f*x^2]) + (d*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b) - (Sqrt[e]*(b*d*e + 4*b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*(5*b*c - 3*a*d)*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^2*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b^2*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(1/2), x, 6, (f*x*Sqrt[c + d*x^2])/(b*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(1/2), x, 1, (e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(3/2), x, 3, -((Sqrt[d]*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])) + (b*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(5/2), x, 6, -((d*x*Sqrt[e + f*x^2])/(3*c*(b*c - a*d)*(c + d*x^2)^(3/2))) - (Sqrt[d]*(b*c*(5*d*e - 4*c*f) - a*d*(2*d*e - c*f))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(3*c^(3/2)*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + (d*e^(3/2)*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(b*c - a*d)*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^2*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(7/2), x, 9, -((d*x*Sqrt[e + f*x^2])/(5*c*(b*c - a*d)*(c + d*x^2)^(5/2))) - (d*(b*c*(9*d*e - 8*c*f) - a*d*(4*d*e - 3*c*f))*x*Sqrt[e + f*x^2])/(15*c^2*(b*c - a*d)^2*(d*e - c*f)*(c + d*x^2)^(3/2)) - (b^2*Sqrt[d]*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*(b*c - a*d)^3*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + (Sqrt[d]*(a*d*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) - 2*b*c*(9*d^2*e^2 - 14*c*d*e*f + 4*c^2*f^2))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(15*c^(5/2)*(b*c - a*d)^2*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + (d*e^(3/2)*Sqrt[f]*(b*c*(9*d*e - 11*c*f) - 2*a*d*(2*d*e - 3*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c^3*(b*c - a*d)^2*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^3*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)^3*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


(* {(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(5/2), x, 22, ((b*c - a*d)^2*f*(4*b*d*e + b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^4*d*Sqrt[e + f*x^2]) + ((b*c - a*d)*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*x*Sqrt[c + d*x^2])/(15*b^2*d*Sqrt[e + f*x^2]) - (2*(d*e + c*f)*(d^2*e^2 - 6*c*d*e*f + c^2*f^2)*x*Sqrt[c + d*x^2])/(35*b*d*f*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^3) + (2*(b*c - a*d)*(3*d*e - c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b^2) + (d*(9*c*e + (d*e^2)/f - (2*c^2*f)/d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(35*b) + ((b*c - a*d)*f*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*b^2) + (2*(4*d*e - c*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*b) + (f*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*b) - ((b*c - a*d)^2*Sqrt[e]*Sqrt[f]*(4*b*d*e + b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^4*d*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - ((b*c - a*d)*Sqrt[e]*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^2*d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (2*Sqrt[e]*(d*e + c*f)*(d^2*e^2 - 6*c*d*e*f + c^2*f^2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(35*b*d*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*Sqrt[e]*Sqrt[f]*(5*b*e - 3*a*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^4*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)*e^(3/2)*(9*d*e - c*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (e^(3/2)*(d^2*e^2 - 18*c*d*e*f + c^2*f^2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(35*b*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*c - a*d)^2*(b*e - a*f)^2*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*b^4*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])} *)
{(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(3/2), x, 14, ((b*c - a*d)^2*f^2*x*Sqrt[c + d*x^2])/(b^3*d*Sqrt[e + f*x^2]) + (2*(b*c - a*d)*f*(2*d*e - c*f)*x*Sqrt[c + d*x^2])/(3*b^2*d*Sqrt[e + f*x^2]) + ((3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*x*Sqrt[c + d*x^2])/(15*b*d*Sqrt[e + f*x^2]) + ((b*c - a*d)*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) + (2*(3*d*e - c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b) + (f*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*b) - (Sqrt[e]*(15*a^2*d^2*f^2 - 20*a*b*d*f*(d*e + c*f) + 3*b^2*(d^2*e^2 + 9*c*d*e*f + c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^3*d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(15*a^2*d^2*f + 3*b^2*c*(8*d*e + 3*c*f) - 5*a*b*d*(3*d*e + 5*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b^3*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*e^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b^3*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]), ((b*c - a*d)*f*(4*b*d*e + b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^3*d*Sqrt[e + f*x^2]) + ((3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*x*Sqrt[c + d*x^2])/(15*b*d*Sqrt[e + f*x^2]) + ((b*c - a*d)*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) + (2*(3*d*e - c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b) + (f*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*b) - ((b*c - a*d)*Sqrt[e]*Sqrt[f]*(4*b*d*e + b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^3*d*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b*d*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)*Sqrt[e]*Sqrt[f]*(5*b*e - 3*a*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(9*d*e - c*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*b*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*c - a*d)*(b*e - a*f)^2*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*b^3*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(1/2), x, 7, (f*(4*b*d*e + b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b^2*d*Sqrt[e + f*x^2]) + (f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b) - (Sqrt[e]*Sqrt[f]*(4*b*d*e + b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^2*d*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[e]*Sqrt[f]*(5*b*e - 3*a*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*e - a*f)^2*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*b^2*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(1/2), x, 6, (f^2*x*Sqrt[c + d*x^2])/(b*d*Sqrt[e + f*x^2]) - (Sqrt[e]*f^(3/2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*d*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*c*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (e^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b*c*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(3/2), x, 3, -(((d*e - c*f)*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*Sqrt[d]*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])) + (e^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(5/2), x, 6, -(((d*e - c*f)*x*Sqrt[e + f*x^2])/(3*c*(b*c - a*d)*(c + d*x^2)^(3/2))) - ((b*c*(5*d*e - c*f) - 2*a*d*(d*e + c*f))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(3*c^(3/2)*Sqrt[d]*(b*c - a*d)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + (e^(3/2)*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(b*c - a*d)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b*e^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(7/2), x, 9, -(((d*e - c*f)*x*Sqrt[e + f*x^2])/(5*c*(b*c - a*d)*(c + d*x^2)^(5/2))) - ((3*b*c*(3*d*e - c*f) - 2*a*d*(2*d*e + c*f))*x*Sqrt[e + f*x^2])/(15*c^2*(b*c - a*d)^2*(c + d*x^2)^(3/2)) - (b*Sqrt[d]*(b*e - a*f)*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*(b*c - a*d)^3*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + ((a*d*(8*d^2*e^2 - 3*c*d*e*f - 2*c^2*f^2) - 3*b*c*(6*d^2*e^2 - 6*c*d*e*f + c^2*f^2))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(15*c^(5/2)*Sqrt[d]*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) + (e^(3/2)*Sqrt[f]*(3*b*c*(3*d*e - 2*c*f) - a*d*(4*d*e - c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(15*c^3*(b*c - a*d)^2*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^2*e^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)^3*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


(* ::Subsubsection::Closed:: *)
(*q<0*)


{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(5/2), x, 12, (d*(b*c - a*d)*x*Sqrt[c + d*x^2])/(b^2*Sqrt[e + f*x^2]) - (2*d*(d*e - 2*c*f)*x*Sqrt[c + d*x^2])/(3*b*f*Sqrt[e + f*x^2]) + (d^2*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b*f) - (d*(b*c - a*d)*Sqrt[e]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (2*d*Sqrt[e]*(d*e - 2*c*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*(b*c - a*d)*Sqrt[e]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b^2*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*(d*e - 3*c*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b*f^(3/2)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*c - a*d)^2*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*b^2*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(3/2), x, 6, (d*x*Sqrt[c + d*x^2])/(b*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*Sqrt[e]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(b*Sqrt[f]*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*c - a*d)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*b*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(1/2), x, 1, (c^(3/2)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*Sqrt[d]*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(1/2), x, 3, (Sqrt[-c]*Sqrt[1 + (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[d]*x)/Sqrt[-c]], (c*f)/(d*e)])/(a*Sqrt[d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(3/2), x, 5, -((d^(3/2)*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(Sqrt[c]*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])) - (d*Sqrt[e]*(b*d*e - 2*b*c*f + a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*(b*c - a*d)^2*Sqrt[f]*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^2*c^(3/2)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*Sqrt[d]*(b*c - a*d)^2*e*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(5/2), x, 8, -((d^2*x*Sqrt[e + f*x^2])/(3*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2))) - (d^(3/2)*(b*c*(5*d*e - 7*c*f) - 2*a*d*(d*e - 2*c*f))*Sqrt[e + f*x^2]*EllipticE[ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(3*c^(3/2)*(b*c - a*d)^2*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]) - (d*Sqrt[e]*Sqrt[f]*(a*d*(d*e - 3*c*f) - 2*b*c*(2*d*e - 3*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(b*c - a*d)^2*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^2*Sqrt[-c]*Sqrt[1 + (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[d]*x)/Sqrt[-c]], (c*f)/(d*e)])/(a*Sqrt[d]*(b*c - a*d)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(5/2), x, 14, ((b*c - a*d)*(b*d*e + 4*b*c*f - 3*a*d*f)*x*Sqrt[c + d*x^2])/(3*b*(b*e - a*f)^2*Sqrt[e + f*x^2]) + ((b*e*(6*d^2*e^2 - 7*c*d*e*f - c^2*f^2) - a*f*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*x*Sqrt[c + d*x^2])/(3*e*f*(b*e - a*f)^2*Sqrt[e + f*x^2]) + ((d*e - c*f)*x*(c + d*x^2)^(3/2))/(e*(b*e - a*f)*Sqrt[e + f*x^2]) + (d*(b*c - a*d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*(b*e - a*f)^2) + (d*(a*f*(4*d*e - 3*c*f) - b*e*(3*d*e - 2*c*f))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*e*f*(b*e - a*f)^2) - ((b*c - a*d)*Sqrt[e]*(b*d*e + 4*b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b*Sqrt[f]*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - ((b*e*(6*d^2*e^2 - 7*c*d*e*f - c^2*f^2) - a*f*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*Sqrt[e]*f^(3/2)*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*(5*b*c - 3*a*d)*(b*c - a*d)*e^(3/2)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*b*c*Sqrt[f]*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*(2*a*d*f*(2*d*e - 3*c*f) - b*(3*d^2*e^2 - 2*c*d*e*f - 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*f^(3/2)*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + ((b*c - a*d)^3*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*b*c*Sqrt[f]*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(3/2), x, 3, ((d*e - c*f)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(Sqrt[e]*Sqrt[f]*(b*e - a*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (c^(3/2)*(b*c - a*d)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*Sqrt[d]*e*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(1/2), x, 3, -((Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(Sqrt[e]*(b*e - a*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])) + (b*c^(3/2)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*Sqrt[d]*e*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(1/2), x, 5, (f^(3/2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(Sqrt[e]*(b*e - a*f)*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[f]*(2*b*d*e - b*c*f - a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*(b*e - a*f)^2*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^2*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*Sqrt[f]*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(3/2), x, 8, -((d^2*x)/(c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) - (b^2*Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/((b*c - a*d)^2*Sqrt[e]*(b*e - a*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d*Sqrt[f]*(2*b*c^2*f - a*d*(d*e + c*f))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*(b*c - a*d)^2*Sqrt[e]*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d^2*Sqrt[e]*(b*d*e - 3*b*c*f + 2*a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*(b*c - a*d)^2*Sqrt[f]*(d*e - c*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^3*c^(3/2)*Sqrt[e + f*x^2]*EllipticPi[1 - (b*c)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[c]], 1 - (c*f)/(d*e)])/(a*Sqrt[d]*(b*c - a*d)^2*e*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(5/2), x, 11, -((d^2*x)/(3*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])) - (d^2*(b*c*(5*d*e - 9*c*f) - 2*a*d*(d*e - 3*c*f))*x)/(3*c^2*(b*c - a*d)^2*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b^2*f^(3/2)*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/((b*c - a*d)^2*Sqrt[e]*(b*e - a*f)*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d*Sqrt[f]*(b*c*(5*d^2*e^2 - 7*c*d*e*f - 6*c^2*f^2) - a*d*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2))*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(b*c - a*d)^2*Sqrt[e]*(d*e - c*f)^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (b^2*Sqrt[e]*Sqrt[f]*(2*b*d*e - b*c*f - a*d*f)*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(c*(b*c - a*d)^2*(b*e - a*f)^2*(d*e - c*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d^2*Sqrt[e]*Sqrt[f]*(b*c*(7*d*e - 15*c*f) - a*d*(d*e - 9*c*f))*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(3*c^2*(b*c - a*d)^2*(d*e - c*f)^3*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (b^4*e^(3/2)*Sqrt[c + d*x^2]*EllipticPi[1 - (b*e)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(a*c*(b*c - a*d)^2*Sqrt[f]*(b*e - a*f)^2*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2])}


{(1 + x^2)^(3/2)*Sqrt[2 + x^2]/(a + b*x^2), x, 7, -(((a - 2*b)*x*Sqrt[2 + x^2])/(b^2*Sqrt[1 + x^2])) + (x*Sqrt[1 + x^2]*Sqrt[2 + x^2])/(3*b) + (Sqrt[2]*(a - 2*b)*Sqrt[2 + x^2]*EllipticE[ArcTan[x], 1/2])/(b^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) - ((3*a - 7*b)*Sqrt[2 + x^2]*EllipticF[ArcTan[x], 1/2])/(3*Sqrt[2]*b^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) + ((a - 2*b)*(a - b)*Sqrt[2 + x^2]*EllipticPi[1 - b/a, ArcTan[x], 1/2])/(Sqrt[2]*a*b^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]), -(((a - 2*b)*x*Sqrt[2 + x^2])/(b^2*Sqrt[1 + x^2])) + (x*Sqrt[1 + x^2]*Sqrt[2 + x^2])/(3*b) + (Sqrt[2]*(a - 2*b)*Sqrt[2 + x^2]*EllipticE[ArcTan[x], 1/2])/(b^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) - (Sqrt[2]*(3*a - 5*b)*Sqrt[2 + x^2]*EllipticF[ArcTan[x], 1/2])/(3*b^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) + (2*(a - b)^2*Sqrt[1 + x^2]*EllipticPi[1 - (2*b)/a, ArcTan[x/Sqrt[2]], -1])/(a*b^2*Sqrt[(1 + x^2)/(2 + x^2)]*Sqrt[2 + x^2])}
{(1 + x^2)^(1/2)*Sqrt[2 + x^2]/(a + b*x^2), x, 6, (x*Sqrt[2 + x^2])/(b*Sqrt[1 + x^2]) - (Sqrt[2]*Sqrt[2 + x^2]*EllipticE[ArcTan[x], 1/2])/(b*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) + (Sqrt[2 + x^2]*EllipticF[ArcTan[x], 1/2])/(Sqrt[2]*b*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) - ((a - 2*b)*Sqrt[2 + x^2]*EllipticPi[1 - b/a, ArcTan[x], 1/2])/(Sqrt[2]*a*b*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)])}
{Sqrt[2 + x^2]/((1 + x^2)^(1/2)*(a + b*x^2)), x, 1, (2*Sqrt[1 + x^2]*EllipticPi[1 - (2*b)/a, ArcTan[x/Sqrt[2]], -1])/(a*Sqrt[(1 + x^2)/(2 + x^2)]*Sqrt[2 + x^2])}
{Sqrt[2 + x^2]/((1 + x^2)^(3/2)*(a + b*x^2)), x, 3, (Sqrt[2]*Sqrt[2 + x^2]*EllipticE[ArcTan[x], 1/2])/((a - b)*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) - (2*b*Sqrt[1 + x^2]*EllipticPi[1 - (2*b)/a, ArcTan[x/Sqrt[2]], -1])/(a*(a - b)*Sqrt[(1 + x^2)/(2 + x^2)]*Sqrt[2 + x^2])}
{Sqrt[2 + x^2]/((1 + x^2)^(5/2)*(a + b*x^2)), x, 6, (x*Sqrt[2 + x^2])/(3*(a - b)*(1 + x^2)^(3/2)) + (Sqrt[2]*(a - 2*b)*Sqrt[2 + x^2]*EllipticE[ArcTan[x], 1/2])/((a - b)^2*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) - (Sqrt[2]*Sqrt[2 + x^2]*EllipticF[ArcTan[x], 1/2])/(3*(a - b)*Sqrt[1 + x^2]*Sqrt[(2 + x^2)/(1 + x^2)]) + (2*b^2*Sqrt[1 + x^2]*EllipticPi[1 - (2*b)/a, ArcTan[x/Sqrt[2]], -1])/(a*(a - b)^2*Sqrt[(1 + x^2)/(2 + x^2)]*Sqrt[2 + x^2])}


{Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2]/(a + b*x^2), x, 6, (f*x*Sqrt[2 + d*x^2])/(b*Sqrt[3 + f*x^2]) - (Sqrt[2]*Sqrt[f]*Sqrt[2 + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(b*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2]) + (3*d*Sqrt[2 + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(Sqrt[2]*b*Sqrt[f]*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2]) + (3*(2*b - a*d)*Sqrt[2 + d*x^2]*EllipticPi[1 - (3*b)/(a*f), ArcTan[(Sqrt[f]*x)/Sqrt[3]], 1 - (3*d)/(2*f)])/(Sqrt[2]*a*b*Sqrt[f]*Sqrt[(2 + d*x^2)/(3 + f*x^2)]*Sqrt[3 + f*x^2])}
{Sqrt[2 + d*x^2]/((a + b*x^2)*Sqrt[3 + f*x^2]), x, 1, (2*Sqrt[3 + f*x^2]*EllipticPi[1 - (2*b)/(a*d), ArcTan[(Sqrt[d]*x)/Sqrt[2]], 1 - (2*f)/(3*d)])/(Sqrt[3]*a*Sqrt[d]*Sqrt[2 + d*x^2]*Sqrt[(3 + f*x^2)/(2 + d*x^2)])}
{1/((a + b*x^2)*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2]), x, 1, EllipticPi[(2*b)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[2]], (2*f)/(3*d)]/(Sqrt[3]*a*Sqrt[-d])}


{Sqrt[1 - x^2]/((x^2 - 1)*Sqrt[a + b*x^2]), x, 3, -((Sqrt[1 + (b*x^2)/a]*EllipticF[ArcSin[x], -(b/a)])/Sqrt[a + b*x^2])}


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^q / (e+f x^2)^2*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^p (c+d x^2)^(q/2) / (e+f x^2)^2*)


(* ::Subsubsection:: *)
(*q>0*)


(* ::Subsubsection::Closed:: *)
(*q<0*)


{(a + b*x^2)/(Sqrt[c + d*x^2]*(e + f*x^2)^2), x, 4, ((b*e - a*f)*x*Sqrt[c + d*x^2])/(2*e*(d*e - c*f)*(e + f*x^2)) - ((b*c*e - 2*a*d*e + a*c*f)*ArcTanh[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])])/(2*e^(3/2)*(d*e - c*f)^(3/2))}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) / (e+f x^2)^2*)


(* ::Subsubsection::Closed:: *)
(*q>0*)


{Sqrt[c - d*x^2]*Sqrt[e + f*x^2]/(a + b*x^2)^2, x, 11, (x*Sqrt[c - d*x^2]*Sqrt[e + f*x^2])/(2*a*(a + b*x^2)) + (Sqrt[c]*Sqrt[d]*Sqrt[1 - (d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a*b*Sqrt[c - d*x^2]*Sqrt[1 + (f*x^2)/e]) - (Sqrt[c]*Sqrt[d]*(b*e + a*f)*Sqrt[1 - (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticF[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a*b^2*Sqrt[c - d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b^2*c*e + a^2*d*f)*Sqrt[1 - (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[-((b*c)/(a*d)), ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a^2*b^2*Sqrt[d]*Sqrt[c - d*x^2]*Sqrt[e + f*x^2])}
{Sqrt[c + d*x^2]*Sqrt[e + f*x^2]/(a + b*x^2)^2, x, 8, -((f*x*Sqrt[c + d*x^2])/(2*a*b*Sqrt[e + f*x^2])) + (x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(2*a*(a + b*x^2)) + (Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(2*a*b*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (d*Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(2*b^2*c*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[-c]*(b^2*c*e - a^2*d*f)*Sqrt[1 + (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[d]*x)/Sqrt[-c]], (c*f)/(d*e)])/(2*a^2*b^2*Sqrt[d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


(* ::Subsubsection::Closed:: *)
(*q<0*)


{1/(Sqrt[c - d*x^2]*Sqrt[e + f*x^2]*(a + b*x^2)^2), x, 11, (b^2*x*Sqrt[c - d*x^2]*Sqrt[e + f*x^2])/(2*a*(b*c + a*d)*(b*e - a*f)*(a + b*x^2)) + (b*Sqrt[c]*Sqrt[d]*Sqrt[1 - (d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a*(b*c + a*d)*(b*e - a*f)*Sqrt[c - d*x^2]*Sqrt[1 + (f*x^2)/e]) - (Sqrt[c]*Sqrt[d]*Sqrt[1 - (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticF[ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a*(b*c + a*d)*Sqrt[c - d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b^2*c*e - 3*a^2*d*f + a*b*(2*d*e - 2*c*f))*Sqrt[1 - (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[-((b*c)/(a*d)), ArcSin[(Sqrt[d]*x)/Sqrt[c]], -((c*f)/(d*e))])/(2*a^2*Sqrt[d]*(b*c + a*d)*(b*e - a*f)*Sqrt[c - d*x^2]*Sqrt[e + f*x^2])}
{1/(Sqrt[c + d*x^2]*Sqrt[e + f*x^2]*(a + b*x^2)^2), x, 8, -((b*f*x*Sqrt[c + d*x^2])/(2*a*(b*c - a*d)*(b*e - a*f)*Sqrt[e + f*x^2])) + (b^2*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(2*a*(b*c - a*d)*(b*e - a*f)*(a + b*x^2)) + (b*Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticE[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(2*a*(b*c - a*d)*(b*e - a*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[f]*Sqrt[c + d*x^2]*EllipticF[ArcTan[(Sqrt[f]*x)/Sqrt[e]], 1 - (d*e)/(c*f)])/(2*c*(b*c - a*d)*(b*e - a*f)*Sqrt[(e*(c + d*x^2))/(c*(e + f*x^2))]*Sqrt[e + f*x^2]) + (Sqrt[-c]*(b^2*c*e + 3*a^2*d*f - 2*a*b*(d*e + c*f))*Sqrt[1 + (d*x^2)/c]*Sqrt[1 + (f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[d]*x)/Sqrt[-c]], (c*f)/(d*e)])/(2*a^2*Sqrt[d]*(b*c - a*d)*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


(* ::Title:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) (e+f x^2)^(r/2)*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) / (e+f x^2)^(1/2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^(p/2) (c+d x^2)^(q/2) / (e+f x^2)^(1/2)*)


(* ::Subsubsection::Closed:: *)
(*q>0*)


(* Not sure this is not integrable. *)
{(a + b*x^2)^(3/2)*Sqrt[c + d*x^2]/Sqrt[e + f*x^2], x, 0, Unintegrable[((a + b*x^2)^(3/2)*Sqrt[c + d*x^2])/Sqrt[e + f*x^2], x]}
{(a + b*x^2)^(1/2)*Sqrt[c + d*x^2]/Sqrt[e + f*x^2], x, 7, (d*x*Sqrt[a + b*x^2]*Sqrt[e + f*x^2])/(2*f*Sqrt[c + d*x^2]) - (Sqrt[e]*Sqrt[d*e - c*f]*Sqrt[a + b*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]*EllipticE[ArcSin[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(2*f*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[e + f*x^2]) + (b*Sqrt[e]*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticF[ArcSin[(Sqrt[b*e - a*f]*x)/(Sqrt[e]*Sqrt[a + b*x^2])], ((b*c - a*d)*e)/(c*(b*e - a*f))])/(2*d*f*Sqrt[b*e - a*f]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(b*d*e - b*c*f - a*d*f)*Sqrt[a + b*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]*EllipticPi[(d*e)/(d*e - c*f), ArcSin[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(2*a*d*f*Sqrt[d*e - c*f]*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[e + f*x^2])}
{Sqrt[c + d*x^2]/((a + b*x^2)^(1/2)*Sqrt[e + f*x^2]), x, 2, (c*Sqrt[e]*Sqrt[a + b*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]*EllipticPi[(d*e)/(d*e - c*f), ArcSin[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(a*Sqrt[d*e - c*f]*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[e + f*x^2])}
{Sqrt[c + d*x^2]/((a + b*x^2)^(3/2)*Sqrt[e + f*x^2]), x, 2, (Sqrt[e]*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticE[ArcSin[(Sqrt[b*e - a*f]*x)/(Sqrt[e]*Sqrt[a + b*x^2])], ((b*c - a*d)*e)/(c*(b*e - a*f))])/(a*Sqrt[b*e - a*f]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2])}


(* Not sure this is not integrable. *)
{(a + b*x^2)^(3/2)*Sqrt[c + d*x^2]/(e + f*x^2)^(3/2), x, 0, Unintegrable[((a + b*x^2)^(3/2)*Sqrt[c + d*x^2])/(e + f*x^2)^(3/2), x]}
{(a + b*x^2)^(1/2)*Sqrt[c + d*x^2]/(e + f*x^2)^(3/2), x, 8, -(((d*e - c*f)*x*Sqrt[a + b*x^2])/(e*f*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) + (Sqrt[c]*Sqrt[d*e - c*f]*Sqrt[a + b*x^2]*EllipticE[ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(e*f*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2]) - (c^(3/2)*(b*e - a*f)*Sqrt[a + b*x^2]*EllipticF[ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(a*e*f*Sqrt[d*e - c*f]*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2]) + (b*c*Sqrt[e]*Sqrt[a + b*x^2]*Sqrt[(c*(e + f*x^2))/(e*(c + d*x^2))]*EllipticPi[(d*e)/(d*e - c*f), ArcSin[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(a*f*Sqrt[d*e - c*f]*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[e + f*x^2])}
{Sqrt[c + d*x^2]/((a + b*x^2)^(1/2)*(e + f*x^2)^(3/2)), x, 5, ((d*e - c*f)*x*Sqrt[a + b*x^2])/(e*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) - (Sqrt[c]*Sqrt[d*e - c*f]*Sqrt[a + b*x^2]*EllipticE[ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(e*(b*e - a*f)*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2]) + (c^(3/2)*Sqrt[a + b*x^2]*EllipticF[ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])], -(((b*c - a*d)*e)/(a*(d*e - c*f)))])/(a*e*Sqrt[d*e - c*f]*Sqrt[(c*(a + b*x^2))/(a*(c + d*x^2))]*Sqrt[c + d*x^2])}
{Sqrt[c + d*x^2]/((a + b*x^2)^(3/2)*(e + f*x^2)^(3/2)), x, 0, Unintegrable[Sqrt[c + d*x^2]/((a + b*x^2)^(3/2)*(e + f*x^2)^(3/2)), x]}


{Sqrt[c + d*x^2]*Sqrt[e + f*x^2]/Sqrt[a + b*x^2], x, 7, (x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(2*Sqrt[a + b*x^2]) - (Sqrt[c]*Sqrt[b*c - a*d]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[b*c - a*d]*x)/(Sqrt[c]*Sqrt[a + b*x^2])], (c*(b*e - a*f))/((b*c - a*d)*e)])/(2*b*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]) + ((b*c - a*d)*Sqrt[e]*(2*b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticF[ArcSin[(Sqrt[b*e - a*f]*x)/(Sqrt[e]*Sqrt[a + b*x^2])], ((b*c - a*d)*e)/(c*(b*e - a*f))])/(2*b^2*c*Sqrt[b*e - a*f]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2]) - (a*(a*d*f - b*(d*e + c*f))*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticPi[(b*c)/(b*c - a*d), ArcSin[(Sqrt[b*c - a*d]*x)/(Sqrt[c]*Sqrt[a + b*x^2])], (c*(b*e - a*f))/((b*c - a*d)*e)])/(2*b^2*Sqrt[c]*Sqrt[b*c - a*d]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2])}


(* ::Subsubsection::Closed:: *)
(*q<0*)


(* Not sure this is not integrable. *)
{(a + b*x^2)^(3/2)/(Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x, 0, Unintegrable[(a + b*x^2)^(3/2)/(Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x]}
{(a + b*x^2)^(1/2)/(Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x, 2, (a*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticPi[(b*c)/(b*c - a*d), ArcSin[(Sqrt[b*c - a*d]*x)/(Sqrt[c]*Sqrt[a + b*x^2])], (c*(b*e - a*f))/((b*c - a*d)*e)])/(Sqrt[c]*Sqrt[b*c - a*d]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)^(1/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x, 2, (Sqrt[e]*Sqrt[c + d*x^2]*Sqrt[(a*(e + f*x^2))/(e*(a + b*x^2))]*EllipticF[ArcSin[(Sqrt[b*e - a*f]*x)/(Sqrt[e]*Sqrt[a + b*x^2])], ((b*c - a*d)*e)/(c*(b*e - a*f))])/(c*Sqrt[b*e - a*f]*Sqrt[(a*(c + d*x^2))/(c*(a + b*x^2))]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x, 0, Unintegrable[1/((a + b*x^2)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]), x]}
