(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form P[x] (a+b x)^m (c+d x)^n (e+f x)^p*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (A+B x+C x^2) when b c+a d=0 and m=n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (e+f x)^p (A+B x+C x^2) when b c+a d=0, m=n, a>0 and c>0*)


(* ::Subsubsection::Closed:: *)
(*m>0*)


{(e + f*x)^3*(A + B*x + C*x^2)*Sqrt[1 + d*x]*Sqrt[1 - d*x], x, 7, ((2*C*d^2*e^3 + 8*A*d^4*e^3 + 6*B*d^2*e^2*f + 3*C*e*f^2 + 6*A*d^2*e*f^2 + B*f^3)*x*Sqrt[1 - d^2*x^2])/(16*d^4) - ((7*d^2*f*(B*e + 2*A*f) - C*(3*d^2*e^2 - 8*f^2))*(e + f*x)^2*(1 - d^2*x^2)^(3/2))/(70*d^4*f) + ((3*C*e - 7*B*f)*(e + f*x)^3*(1 - d^2*x^2)^(3/2))/(42*d^2*f) - (C*(e + f*x)^4*(1 - d^2*x^2)^(3/2))/(7*d^2*f) + ((8*(C*(3*d^4*e^4 - 30*d^2*e^2*f^2 - 8*f^4) - 7*d^2*f*(2*A*f*(6*d^2*e^2 + f^2) + B*(d^2*e^3 + 6*e*f^2))) + 3*d^2*f*(6*C*d^2*e^3 - 14*B*d^2*e^2*f - 41*C*e*f^2 - 98*A*d^2*e*f^2 - 35*B*f^3)*x)*(1 - d^2*x^2)^(3/2))/(840*d^6*f) + ((2*C*d^2*e^3 + 8*A*d^4*e^3 + 6*B*d^2*e^2*f + 3*C*e*f^2 + 6*A*d^2*e*f^2 + B*f^3)*ArcSin[d*x])/(16*d^5)}
{(e + f*x)^2*(A + B*x + C*x^2)*Sqrt[1 + d*x]*Sqrt[1 - d*x], x, 6, ((C*(2*d^2*e^2 + f^2) + 2*d^2*(2*B*e*f + A*(4*d^2*e^2 + f^2)))*x*Sqrt[1 - d^2*x^2])/(16*d^4) + ((C*e - 2*B*f)*(e + f*x)^2*(1 - d^2*x^2)^(3/2))/(10*d^2*f) - (C*(e + f*x)^3*(1 - d^2*x^2)^(3/2))/(6*d^2*f) + ((8*(C*(d^2*e^3 - 4*e*f^2) - 2*f*(5*A*d^2*e*f + B*(d^2*e^2 + f^2))) - 3*f*(5*(C + 2*A*d^2)*f^2 - 2*d^2*e*(C*e - 2*B*f))*x)*(1 - d^2*x^2)^(3/2))/(120*d^4*f) + ((C*(2*d^2*e^2 + f^2) + 2*d^2*(2*B*e*f + A*(4*d^2*e^2 + f^2)))*ArcSin[d*x])/(16*d^5)}
{(e + f*x)^1*(A + B*x + C*x^2)*Sqrt[1 + d*x]*Sqrt[1 - d*x], x, 5, ((C*e + 4*A*d^2*e + B*f)*x*Sqrt[1 - d^2*x^2])/(8*d^2) - (C*(e + f*x)^2*(1 - d^2*x^2)^(3/2))/(5*d^2*f) - ((4*(5*d^2*f*(B*e + A*f) - C*(3*d^2*e^2 - 2*f^2)) - 3*d^2*f*(3*C*e - 5*B*f)*x)*(1 - d^2*x^2)^(3/2))/(60*d^4*f) + ((C*e + 4*A*d^2*e + B*f)*ArcSin[d*x])/(8*d^3)}
{(e + f*x)^0*(A + B*x + C*x^2)*Sqrt[1 + d*x]*Sqrt[1 - d*x], x, 5, ((C + 4*A*d^2)*x*Sqrt[1 - d^2*x^2])/(8*d^2) - (B*(1 - d^2*x^2)^(3/2))/(3*d^2) - (C*x*(1 - d^2*x^2)^(3/2))/(4*d^2) + ((C + 4*A*d^2)*ArcSin[d*x])/(8*d^3)}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^1), x, 6, -((C*Sqrt[1 - d^2*x^2])/(d^2*f)) - ((C*e - B*f)*ArcSin[d*x])/(d*f^2) + ((C*e^2 - B*e*f + A*f^2)*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(f^2*Sqrt[d^2*e^2 - f^2])}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^2), x, 6, ((C*e^2 - B*e*f + A*f^2)*Sqrt[1 - d^2*x^2])/(f*(d^2*e^2 - f^2)*(e + f*x)) + (C*ArcSin[d*x])/(d*f^2) - ((C*d^2*e^3 - 2*C*e*f^2 - A*d^2*e*f^2 + B*f^3)*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(f^2*(d^2*e^2 - f^2)^(3/2))}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^3), x, 5, ((C*e^2 - B*e*f + A*f^2)*Sqrt[1 - d^2*x^2])/(2*f*(d^2*e^2 - f^2)*(e + f*x)^2) - ((C*d^2*e^3 + B*d^2*e^2*f - 4*C*e*f^2 - 3*A*d^2*e*f^2 + 2*B*f^3)*Sqrt[1 - d^2*x^2])/(2*f*(d^2*e^2 - f^2)^2*(e + f*x)) + ((C*(d^2*e^2 + 2*f^2) - d^2*(3*B*e*f - A*(2*d^2*e^2 + f^2)))*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(2*(d^2*e^2 - f^2)^(5/2))}


(* ::Subsubsection::Closed:: *)
(*m<0*)


{(e + f*x)^3*(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 6, -(((4*(4*C + 5*A*d^2)*f^2 - 3*d^2*e*(C*e - 5*B*f))*(e + f*x)^2*Sqrt[1 - d^2*x^2])/(60*d^4*f)) + ((C*e - 5*B*f)*(e + f*x)^3*Sqrt[1 - d^2*x^2])/(20*d^2*f) - (C*(e + f*x)^4*Sqrt[1 - d^2*x^2])/(5*d^2*f) + ((4*(C*(3*d^4*e^4 - 52*d^2*e^2*f^2 - 16*f^4) - 5*d^2*f*(4*A*f*(4*d^2*e^2 + f^2) + 3*B*(d^2*e^3 + 4*e*f^2))) + d^2*f*(6*C*d^2*e^3 - 30*B*d^2*e^2*f - 71*C*e*f^2 - 100*A*d^2*e*f^2 - 45*B*f^3)*x)*Sqrt[1 - d^2*x^2])/(120*d^6*f) + ((4*C*d^2*e^3 + 8*A*d^4*e^3 + 12*B*d^2*e^2*f + 9*C*e*f^2 + 12*A*d^2*e*f^2 + 3*B*f^3)*ArcSin[d*x])/(8*d^5)}
{(e + f*x)^2*(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 5, ((C*e - 4*B*f)*(e + f*x)^2*Sqrt[1 - d^2*x^2])/(12*d^2*f) - (C*(e + f*x)^3*Sqrt[1 - d^2*x^2])/(4*d^2*f) + ((4*(C*(d^2*e^3 - 8*e*f^2) - 4*f*(3*A*d^2*e*f + B*(d^2*e^2 + f^2))) - f*(3*(3*C + 4*A*d^2)*f^2 - 2*d^2*e*(C*e - 4*B*f))*x)*Sqrt[1 - d^2*x^2])/(24*d^4*f) + ((C*(4*d^2*e^2 + 3*f^2) + 4*d^2*(2*B*e*f + A*(2*d^2*e^2 + f^2)))*ArcSin[d*x])/(8*d^5)}
{(e + f*x)^1*(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 4, -((C*(e + f*x)^2*Sqrt[1 - d^2*x^2])/(3*d^2*f)) - ((2*(3*d^2*f*(B*e + A*f) - C*(d^2*e^2 - 2*f^2)) - d^2*f*(C*e - 3*B*f)*x)*Sqrt[1 - d^2*x^2])/(6*d^4*f) + ((C*e + 2*A*d^2*e + B*f)*ArcSin[d*x])/(2*d^3)}
{(e + f*x)^0*(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 4, -((B*Sqrt[1 - d^2*x^2])/d^2) - (C*x*Sqrt[1 - d^2*x^2])/(2*d^2) + ((C + 2*A*d^2)*ArcSin[d*x])/(2*d^3)}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^1), x, 6, -((C*Sqrt[1 - d^2*x^2])/(d^2*f)) - ((C*e - B*f)*ArcSin[d*x])/(d*f^2) + ((C*e^2 - B*e*f + A*f^2)*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(f^2*Sqrt[d^2*e^2 - f^2])}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^2), x, 6, ((C*e^2 - B*e*f + A*f^2)*Sqrt[1 - d^2*x^2])/(f*(d^2*e^2 - f^2)*(e + f*x)) + (C*ArcSin[d*x])/(d*f^2) - ((C*d^2*e^3 - 2*C*e*f^2 - A*d^2*e*f^2 + B*f^3)*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(f^2*(d^2*e^2 - f^2)^(3/2))}
{(A + B*x + C*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]*(e + f*x)^3), x, 5, ((C*e^2 - B*e*f + A*f^2)*Sqrt[1 - d^2*x^2])/(2*f*(d^2*e^2 - f^2)*(e + f*x)^2) - ((C*d^2*e^3 + B*d^2*e^2*f - 4*C*e*f^2 - 3*A*d^2*e*f^2 + 2*B*f^3)*Sqrt[1 - d^2*x^2])/(2*f*(d^2*e^2 - f^2)^2*(e + f*x)) + ((C*(d^2*e^2 + 2*f^2) - d^2*(3*B*e*f - A*(2*d^2*e^2 + f^2)))*ArcTan[(f + d^2*e*x)/(Sqrt[d^2*e^2 - f^2]*Sqrt[1 - d^2*x^2])])/(2*(d^2*e^2 - f^2)^(5/2))}


{x^1*(a + b*x + c*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 4, -((c*x^2*Sqrt[1 - d^2*x^2])/(3*d^2)) - ((2*(2*c + 3*a*d^2) + 3*b*d^2*x)*Sqrt[1 - d^2*x^2])/(6*d^4) + (b*ArcSin[d*x])/(2*d^3)}
{x^0*(a + b*x + c*x^2)/(Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 4, -((b*Sqrt[1 - d^2*x^2])/d^2) - (c*x*Sqrt[1 - d^2*x^2])/(2*d^2) + ((c + 2*a*d^2)*ArcSin[d*x])/(2*d^3)}
{(a + b*x + c*x^2)/(x^1*Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 7, -((c*Sqrt[1 - d^2*x^2])/d^2) + (b*ArcSin[d*x])/d - a*ArcTanh[Sqrt[1 - d^2*x^2]]}
{(a + b*x + c*x^2)/(x^2*Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 7, -((a*Sqrt[1 - d^2*x^2])/x) + (c*ArcSin[d*x])/d - b*ArcTanh[Sqrt[1 - d^2*x^2]]}
{(a + b*x + c*x^2)/(x^3*Sqrt[1 + d*x]*Sqrt[1 - d*x]), x, 6, -((a*Sqrt[1 - d^2*x^2])/(2*x^2)) - (b*Sqrt[1 - d^2*x^2])/x - (1/2)*(2*c + a*d^2)*ArcTanh[Sqrt[1 - d^2*x^2]]}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (e+f x)^p (A+B x+C x^2) when b c+a d=0 and m=n*)


(* ::Subsubsection::Closed:: *)
(*m>0*)


{(e + f*x)^3*(A + B*x + C*x^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x], x, 8, ((A*(8*b^4*e^3 + 6*a^2*b^2*e*f^2) + a^2*(a^2*f^2*(3*C*e + B*f) + 2*b^2*e^2*(C*e + 3*B*f)))*x*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])/(16*b^4) - ((8*a^2*C*f^2 - b^2*(3*C*e^2 - 7*f*(B*e + 2*A*f)))*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2*(a^2 - b^2*x^2))/(70*b^4*f) + ((3*C*e - 7*B*f)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^3*(a^2 - b^2*x^2))/(42*b^2*f) - (C*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^4*(a^2 - b^2*x^2))/(7*b^2*f) - (Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(8*(8*a^4*C*f^4 + 2*a^2*b^2*f^2*(15*C*e^2 + 7*f*(3*B*e + A*f)) - b^4*e^2*(3*C*e^2 - 7*f*(B*e + 12*A*f))) + 3*b^2*f*(a^2*f^2*(41*C*e + 35*B*f) - 2*b^2*e*(3*C*e^2 - 7*f*(B*e + 7*A*f)))*x)*(a^2 - b^2*x^2))/(840*b^6*f) + (a^2*Sqrt[c]*(A*(8*b^4*e^3 + 6*a^2*b^2*e*f^2) + a^2*(a^2*f^2*(3*C*e + B*f) + 2*b^2*e^2*(C*e + 3*B*f)))*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(16*b^5*Sqrt[a^2*c - b^2*c*x^2])}
{(e + f*x)^2*(A + B*x + C*x^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x], x, 7, ((2*A*(4*b^4*e^2 + a^2*b^2*f^2) + a^2*(a^2*C*f^2 + 2*b^2*e*(C*e + 2*B*f)))*x*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])/(16*b^4) + ((C*e - 2*B*f)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2*(a^2 - b^2*x^2))/(10*b^2*f) - (C*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^3*(a^2 - b^2*x^2))/(6*b^2*f) - (Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(8*(2*a^2*f^2*(2*C*e + B*f) - b^2*e*(C*e^2 - 2*f*(B*e + 5*A*f))) + 3*f*(5*a^2*C*f^2 - b^2*(2*C*e^2 - 2*f*(2*B*e + 5*A*f)))*x)*(a^2 - b^2*x^2))/(120*b^4*f) + (a^2*Sqrt[c]*(2*A*(4*b^4*e^2 + a^2*b^2*f^2) + a^2*(a^2*C*f^2 + 2*b^2*e*(C*e + 2*B*f)))*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(16*b^5*Sqrt[a^2*c - b^2*c*x^2])}
{(e + f*x)^1*(A + B*x + C*x^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x], x, 6, ((4*A*b^2*e + a^2*(C*e + B*f))*x*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])/(8*b^2) - (C*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2*(a^2 - b^2*x^2))/(5*b^2*f) - (Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(4*(2*a^2*C*f^2 - b^2*(3*C*e^2 - 5*f*(B*e + A*f))) - 3*b^2*f*(3*C*e - 5*B*f)*x)*(a^2 - b^2*x^2))/(60*b^4*f) + (a^2*Sqrt[c]*(4*A*b^2*e + a^2*(C*e + B*f))*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(8*b^3*Sqrt[a^2*c - b^2*c*x^2])}
{(e + f*x)^0*(A + B*x + C*x^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x], x, 6, (1/8)*(4*A + (a^2*C)/b^2)*x*Sqrt[a + b*x]*Sqrt[a*c - b*c*x] - (B*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(a^2 - b^2*x^2))/(3*b^2) - (C*x*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(a^2 - b^2*x^2))/(4*b^2) + (a^2*Sqrt[c]*(4*A*b^2 + a^2*C)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(8*b^3*Sqrt[a^2*c - b^2*c*x^2])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^1), x, 7, -((C*(a^2 - b^2*x^2))/(b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])) - ((C*e - B*f)*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(b*Sqrt[c]*f^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((C*e^2 - B*e*f + A*f^2)*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(Sqrt[c]*f^2*Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2), x, 7, (f*(A + (e*(C*e - B*f))/f^2)*(a^2 - b^2*x^2))/((b^2*e^2 - a^2*f^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)) + (C*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(b*Sqrt[c]*f^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((a^2*f^2*(2*C*e - B*f) - b^2*(C*e^3 - A*e*f^2))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(Sqrt[c]*f^2*(b^2*e^2 - a^2*f^2)^(3/2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^3), x, 5, (f*(A + (e*(C*e - B*f))/f^2)*(a^2 - b^2*x^2))/(2*(b^2*e^2 - a^2*f^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2) + ((2*a^2*f^2*(2*C*e - B*f) - b^2*e*(C*e^2 + f*(B*e - 3*A*f)))*(a^2 - b^2*x^2))/(2*f*(b^2*e^2 - a^2*f^2)^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)) + ((A*(2*b^4*e^2 + a^2*b^2*f^2) + a^2*(2*a^2*C*f^2 + b^2*e*(C*e - 3*B*f)))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(2*Sqrt[c]*(b^2*e^2 - a^2*f^2)^(5/2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}


(* ::Subsubsection::Closed:: *)
(*m<0*)


{(e + f*x)^3*(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]), x, 7, -(((16*a^2*C*f^2 - b^2*(3*C*e^2 - 5*f*(3*B*e + 4*A*f)))*(e + f*x)^2*(a^2 - b^2*x^2))/(60*b^4*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])) + ((C*e - 5*B*f)*(e + f*x)^3*(a^2 - b^2*x^2))/(20*b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) - (C*(e + f*x)^4*(a^2 - b^2*x^2))/(5*b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) - ((4*(16*a^4*C*f^4 + 4*a^2*b^2*f^2*(13*C*e^2 + 5*f*(3*B*e + A*f)) - b^4*e^2*(3*C*e^2 - 5*f*(3*B*e + 16*A*f))) + b^2*f*(a^2*f^2*(71*C*e + 45*B*f) - 2*b^2*e*(3*C*e^2 - 5*f*(3*B*e + 10*A*f)))*x)*(a^2 - b^2*x^2))/(120*b^6*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((4*A*(2*b^4*e^3 + 3*a^2*b^2*e*f^2) + a^2*(3*a^2*f^2*(3*C*e + B*f) + 4*b^2*e^2*(C*e + 3*B*f)))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(8*b^5*Sqrt[c]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(e + f*x)^2*(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]), x, 6, ((C*e - 4*B*f)*(e + f*x)^2*(a^2 - b^2*x^2))/(12*b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) - (C*(e + f*x)^3*(a^2 - b^2*x^2))/(4*b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) - ((4*(4*a^2*f^2*(2*C*e + B*f) - b^2*e*(C*e^2 - 4*f*(B*e + 3*A*f))) + f*(9*a^2*C*f^2 - b^2*(2*C*e^2 - 4*f*(2*B*e + 3*A*f)))*x)*(a^2 - b^2*x^2))/(24*b^4*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((4*A*(2*b^4*e^2 + a^2*b^2*f^2) + a^2*(3*a^2*C*f^2 + 4*b^2*e*(C*e + 2*B*f)))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(8*b^5*Sqrt[c]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(e + f*x)^1*(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]), x, 5, -((C*(e + f*x)^2*(a^2 - b^2*x^2))/(3*b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])) - ((2*(2*a^2*C*f^2 - b^2*(C*e^2 - 3*f*(B*e + A*f))) - b^2*f*(C*e - 3*B*f)*x)*(a^2 - b^2*x^2))/(6*b^4*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((2*A*b^2*e + a^2*(C*e + B*f))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(2*b^3*Sqrt[c]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(e + f*x)^0*(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]), x, 5, -((B*(a^2 - b^2*x^2))/(b^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])) - (C*x*(a^2 - b^2*x^2))/(2*b^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((2*A*b^2 + a^2*C)*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(2*b^3*Sqrt[c]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^1), x, 7, -((C*(a^2 - b^2*x^2))/(b^2*f*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])) - ((C*e - B*f)*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(b*Sqrt[c]*f^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((C*e^2 - B*e*f + A*f^2)*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(Sqrt[c]*f^2*Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2), x, 7, (f*(A + (e*(C*e - B*f))/f^2)*(a^2 - b^2*x^2))/((b^2*e^2 - a^2*f^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)) + (C*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(b*Sqrt[c]*x)/Sqrt[a^2*c - b^2*c*x^2]])/(b*Sqrt[c]*f^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]) + ((a^2*f^2*(2*C*e - B*f) - b^2*(C*e^3 - A*e*f^2))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(Sqrt[c]*f^2*(b^2*e^2 - a^2*f^2)^(3/2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}
{(A + B*x + C*x^2)/(Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^3), x, 5, (f*(A + (e*(C*e - B*f))/f^2)*(a^2 - b^2*x^2))/(2*(b^2*e^2 - a^2*f^2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)^2) + ((2*a^2*f^2*(2*C*e - B*f) - b^2*e*(C*e^2 + f*(B*e - 3*A*f)))*(a^2 - b^2*x^2))/(2*f*(b^2*e^2 - a^2*f^2)^2*Sqrt[a + b*x]*Sqrt[a*c - b*c*x]*(e + f*x)) + ((A*(2*b^4*e^2 + a^2*b^2*f^2) + a^2*(2*a^2*C*f^2 + b^2*e*(C*e - 3*B*f)))*Sqrt[a^2*c - b^2*c*x^2]*ArcTan[(Sqrt[c]*(a^2*f + b^2*e*x))/(Sqrt[b^2*e^2 - a^2*f^2]*Sqrt[a^2*c - b^2*c*x^2])])/(2*Sqrt[c]*(b^2*e^2 - a^2*f^2)^(5/2)*Sqrt[a + b*x]*Sqrt[a*c - b*c*x])}


{x^1*(a + b*x + c*x^2)/(Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 5, (c*x^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(3*d^2) + (Sqrt[-1 + d*x]*Sqrt[1 + d*x]*(2*(2*c + 3*a*d^2) + 3*b*d^2*x))/(6*d^4) + (b*ArcCosh[d*x])/(2*d^3), -((c*x^2*(1 - d^2*x^2))/(3*d^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) - ((2*(2*c + 3*a*d^2) + 3*b*d^2*x)*(1 - d^2*x^2))/(6*d^4*Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + (b*Sqrt[-1 + d^2*x^2]*ArcTanh[(d*x)/Sqrt[-1 + d^2*x^2]])/(2*d^3*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}
{x^0*(a + b*x + c*x^2)/(Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 5, ((2*b + c*x)*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(2*d^2) + ((c + 2*a*d^2)*ArcCosh[d*x])/(2*d^3), -((b*(1 - d^2*x^2))/(d^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) - (c*x*(1 - d^2*x^2))/(2*d^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + ((c + 2*a*d^2)*Sqrt[-1 + d^2*x^2]*ArcTanh[(d*x)/Sqrt[-1 + d^2*x^2]])/(2*d^3*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}
{(a + b*x + c*x^2)/(x^1*Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 8, (c*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/d^2 + (b*ArcCosh[d*x])/d + a*ArcTan[Sqrt[-1 + d*x]*Sqrt[1 + d*x]], -((c*(1 - d^2*x^2))/(d^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) + (a*Sqrt[-1 + d^2*x^2]*ArcTan[Sqrt[-1 + d^2*x^2]])/(Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + (b*Sqrt[-1 + d^2*x^2]*ArcTanh[(d*x)/Sqrt[-1 + d^2*x^2]])/(d*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}
{(a + b*x + c*x^2)/(x^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 8, (a*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/x + (c*ArcCosh[d*x])/d + b*ArcTan[Sqrt[-1 + d*x]*Sqrt[1 + d*x]], -((a*(1 - d^2*x^2))/(x*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) + (b*Sqrt[-1 + d^2*x^2]*ArcTan[Sqrt[-1 + d^2*x^2]])/(Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + (c*Sqrt[-1 + d^2*x^2]*ArcTanh[(d*x)/Sqrt[-1 + d^2*x^2]])/(d*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}
{(a + b*x + c*x^2)/(x^3*Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 6, (a*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(2*x^2) + (b*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/x + (1/2)*(2*c + a*d^2)*ArcTan[Sqrt[-1 + d*x]*Sqrt[1 + d*x]], -((a*(1 - d^2*x^2))/(2*x^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) - (b*(1 - d^2*x^2))/(x*Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + ((2*c + a*d^2)*Sqrt[-1 + d^2*x^2]*ArcTan[Sqrt[-1 + d^2*x^2]])/(2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}
{(a + b*x + c*x^2)/(x^4*Sqrt[-1 + d*x]*Sqrt[1 + d*x]), x, 7, (a*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(3*x^3) + (b*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(2*x^2) + ((3*c + 2*a*d^2)*Sqrt[-1 + d*x]*Sqrt[1 + d*x])/(3*x) + (1/2)*b*d^2*ArcTan[Sqrt[-1 + d*x]*Sqrt[1 + d*x]], -((a*(1 - d^2*x^2))/(3*x^3*Sqrt[-1 + d*x]*Sqrt[1 + d*x])) - (b*(1 - d^2*x^2))/(2*x^2*Sqrt[-1 + d*x]*Sqrt[1 + d*x]) - ((3*c + 2*a*d^2)*(1 - d^2*x^2))/(3*x*Sqrt[-1 + d*x]*Sqrt[1 + d*x]) + (b*d^2*Sqrt[-1 + d^2*x^2]*ArcTan[Sqrt[-1 + d^2*x^2]])/(2*Sqrt[-1 + d*x]*Sqrt[1 + d*x])}


{(a + b*x + c*x^2)/(Sqrt[-1 + x]*Sqrt[1 + x]*(d + e*x)^3), x, 5, -(((c*d^2 - b*d*e + a*e^2)*Sqrt[-1 + x]*Sqrt[1 + x])/(2*e*(d^2 - e^2)*(d + e*x)^2)) + ((c*d^3 + b*d^2*e - (3*a + 4*c)*d*e^2 + 2*b*e^3)*Sqrt[-1 + x]*Sqrt[1 + x])/(2*e*(d^2 - e^2)^2*(d + e*x)) + (((2*a + c)*d^2 - 3*b*d*e + (a + 2*c)*e^2)*ArcTanh[(Sqrt[d + e]*Sqrt[1 + x])/(Sqrt[d - e]*Sqrt[-1 + x])])/((d - e)^(5/2)*(d + e)^(5/2)), ((c*d^2 - b*d*e + a*e^2)*(1 - x^2))/(2*e*(d^2 - e^2)*Sqrt[-1 + x]*Sqrt[1 + x]*(d + e*x)^2) - ((c*(d^3 - 4*d*e^2) - e*(3*a*d*e - b*(d^2 + 2*e^2)))*(1 - x^2))/(2*e*(d^2 - e^2)^2*Sqrt[-1 + x]*Sqrt[1 + x]*(d + e*x)) - ((3*b*d*e - a*(2*d^2 + e^2) - c*(d^2 + 2*e^2))*Sqrt[-1 + x^2]*ArcTanh[(e + d*x)/(Sqrt[d^2 - e^2]*Sqrt[-1 + x^2])])/(2*(d^2 - e^2)^(5/2)*Sqrt[-1 + x]*Sqrt[1 + x])}


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (A+B x+C x^2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (e+f x)^(p/2) (A+B x+C x^2)*)


(* ::Subsubsection::Closed:: *)
(*n>0 & p>0*)


{(a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2), x, 8, (1/(512*d^5*f^5))*((d*e - c*f)*(8*a^2*d^2*f^2*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - 8*a*b*d*f*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))) + b^2*(C*(21*d^4*e^4 + 28*c*d^3*e^3*f + 30*c^2*d^2*e^2*f^2 + 28*c^3*d*e*f^3 + 21*c^4*f^4) + 4*d*f*(2*A*d*f*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) - B*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3))))*Sqrt[c + d*x]*Sqrt[e + f*x]) + (1/(256*d^5*f^4))*((8*a^2*d^2*f^2*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - 8*a*b*d*f*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))) + b^2*(C*(21*d^4*e^4 + 28*c*d^3*e^3*f + 30*c^2*d^2*e^2*f^2 + 28*c^3*d*e*f^3 + 21*c^4*f^4) + 4*d*f*(2*A*d*f*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) - B*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3))))*(c + d*x)^(3/2)*Sqrt[e + f*x]) - ((2*a*C*d*f - b*(4*B*d*f - 3*C*(d*e + c*f)))*(a + b*x)^2*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(20*b*d^2*f^2) + (C*(a + b*x)^3*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(6*b*d*f) - (1/(960*b*d^4*f^4))*((c + d*x)^(3/2)*(e + f*x)^(3/2)*(64*a^3*C*d^3*f^3 - 8*a^2*b*d^2*f^2*(16*B*d*f - 7*C*(d*e + c*f)) - 8*a*b^2*d*f*(C*(35*d^2*e^2 + 38*c*d*e*f + 35*c^2*f^2) + 10*d*f*(8*A*d*f - 5*B*(d*e + c*f))) + b^3*(7*C*(15*d^3*e^3 + 17*c*d^2*e^2*f + 17*c^2*d*e*f^2 + 15*c^3*f^3) + 4*d*f*(50*A*d*f*(d*e + c*f) - B*(35*d^2*e^2 + 38*c*d*e*f + 35*c^2*f^2))) + 6*b*d*f*(10*b*d*f*(2*b*c*C*e + a*C*d*e + a*c*C*f - 4*A*b*d*f) + (4*a*d*f - 7*b*(d*e + c*f))*(2*a*C*d*f - b*(4*B*d*f - 3*C*(d*e + c*f))))*x)) - (1/(512*d^(11/2)*f^(11/2)))*((d*e - c*f)^2*(8*a^2*d^2*f^2*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - 8*a*b*d*f*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))) + b^2*(C*(21*d^4*e^4 + 28*c*d^3*e^3*f + 30*c^2*d^2*e^2*f^2 + 28*c^3*d*e*f^3 + 21*c^4*f^4) + 4*d*f*(2*A*d*f*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) - B*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^1*Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2), x, 7, (1/(128*d^4*f^4))*((d*e - c*f)*(2*a*d*f*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - b*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))))*Sqrt[c + d*x]*Sqrt[e + f*x]) + (1/(64*d^4*f^3))*((2*a*d*f*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - b*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))))*(c + d*x)^(3/2)*Sqrt[e + f*x]) + (C*(a + b*x)^2*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(5*b*d*f) - (1/(240*b*d^3*f^3))*((c + d*x)^(3/2)*(e + f*x)^(3/2)*(48*a^2*C*d^2*f^2 - 10*a*b*d*f*(8*B*d*f - 5*C*(d*e + c*f)) - b^2*(C*(35*d^2*e^2 + 38*c*d*e*f + 35*c^2*f^2) + 10*d*f*(8*A*d*f - 5*B*(d*e + c*f))) + 6*b*d*f*(6*a*C*d*f - b*(10*B*d*f - 7*C*(d*e + c*f)))*x)) - (1/(128*d^(9/2)*f^(9/2)))*((d*e - c*f)^2*(2*a*d*f*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f))) - b*(C*(7*d^3*e^3 + 9*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 7*c^3*f^3) + 2*d*f*(8*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^0*Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2), x, 7, ((d*e - c*f)*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(64*d^3*f^3) + ((C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f)))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(32*d^3*f^2) - ((5*C*d*e + 11*c*C*f - 8*B*d*f)*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(24*d^2*f^2) + (C*(c + d*x)^(5/2)*(e + f*x)^(3/2))/(4*d^2*f) - ((d*e - c*f)^2*(C*(5*d^2*e^2 + 6*c*d*e*f + 5*c^2*f^2) + 8*d*f*(2*A*d*f - B*(d*e + c*f)))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(64*d^(7/2)*f^(7/2))}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^1, x, 9, ((4*b*d*f*(2*A*b*d*f - a*C*(d*e + c*f)) + (b*d*e - b*c*f + 4*a*d*f)*(2*a*C*d*f + b*(C*d*e + c*C*f - 2*B*d*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(8*b^3*d^2*f^2) - ((2*a*C*d*f + b*(C*d*e + c*C*f - 2*B*d*f))*Sqrt[c + d*x]*(e + f*x)^(3/2))/(4*b^2*d*f^2) + (C*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(3*b*d*f) - (1/(8*b^4*d^(5/2)*f^(5/2)))*((16*a^3*C*d^3*f^3 - 8*a^2*b*d^2*f^2*(C*d*e + c*C*f + 2*B*d*f) - 2*a*b^2*d*f*(C*(d*e - c*f)^2 - 4*d*f*(B*d*e + B*c*f + 2*A*d*f)) - b^3*(C*(d*e - c*f)^2*(d*e + c*f) - 2*d*f*(B*(d*e - c*f)^2 - 4*A*d*f*(d*e + c*f))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])]) - (2*(A*b^2 - a*(b*B - a*C))*Sqrt[b*c - a*d]*Sqrt[b*e - a*f]*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/b^4}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^2, x, 9, ((12*a^2*C*d*f^2 - a*b*f*(7*C*d*e + c*C*f + 8*B*d*f) + b^2*(4*d*f*(B*e + A*f) - C*e*(d*e - c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b^3*d*f*(b*e - a*f)) + ((3*a^2*C*d*f + b^2*(c*C*e + 2*A*d*f) - a*b*(C*d*e + c*C*f + 2*B*d*f))*Sqrt[c + d*x]*(e + f*x)^(3/2))/(2*b^2*(b*c - a*d)*f*(b*e - a*f)) - ((A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(b*(b*c - a*d)*(b*e - a*f)*(a + b*x)) + ((24*a^2*C*d^2*f^2 - 8*a*b*d*f*(C*d*e + c*C*f + 2*B*d*f) - b^2*(C*(d*e - c*f)^2 - 4*d*f*(B*d*e + B*c*f + 2*A*d*f)))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(4*b^4*d^(3/2)*f^(3/2)) + ((6*a^3*C*d*f - b^3*(2*B*c*e + A*d*e + A*c*f) + a*b^2*(4*c*C*e + 3*B*d*e + 3*B*c*f + 2*A*d*f) - a^2*b*(4*B*d*f + 5*C*(d*e + c*f)))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/(b^4*Sqrt[b*c - a*d]*Sqrt[b*e - a*f])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^3, x, 9, -(((12*a^3*C*d*f^2 - a^2*b*f*(17*C*d*e + 11*c*C*f + 4*B*d*f) + a*b^2*(B*f*(5*d*e + 3*c*f) + 4*C*e*(d*e + 4*c*f)) - b^3*(A*d*e*f + c*(4*C*e^2 + 4*B*e*f - A*f^2)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b^3*(b*c - a*d)*(b*e - a*f)^2)) + ((6*a^3*C*d*f - b^3*(4*B*c*e - A*d*e - A*c*f) + a*b^2*(8*c*C*e + 3*B*d*e + 3*B*c*f - 2*A*d*f) - a^2*b*(2*B*d*f + 7*C*(d*e + c*f)))*Sqrt[c + d*x]*(e + f*x)^(3/2))/(4*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)) - ((A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(2*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^2) - ((6*a*C*d*f - b*(C*d*e + c*C*f + 2*B*d*f))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(b^4*Sqrt[d]*Sqrt[f]) - (1/(4*b^4*(b*c - a*d)^(3/2)*(b*e - a*f)^(3/2)))*((24*a^4*C*d^2*f^2 - 3*a*b^3*(B*d^2*e^2 + c^2*f*(8*C*e + B*f) + 2*c*d*e*(4*C*e + 3*B*f)) - 8*a^3*b*d*f*(B*d*f + 5*C*(d*e + c*f)) - b^4*(A*d^2*e^2 - 2*c*d*e*(2*B*e + A*f) - c^2*(8*C*e^2 + 4*B*e*f - A*f^2)) + 3*a^2*b^2*(4*B*d*f*(d*e + c*f) + C*(5*d^2*e^2 + 22*c*d*e*f + 5*c^2*f^2)))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])}


(* ::Subsubsection::Closed:: *)
(*n>0 & p<0*)


{(a + b*x)^2*Sqrt[c + d*x]*(A + B*x + C*x^2)/Sqrt[e + f*x], x, 7, -((1/(128*d^4*f^5))*((16*a^2*d^2*f^2*(2*d*f*(3*B*d*e + B*c*f - 4*A*d*f) - C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2)) + 4*a*b*d*f*(C*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3) + 8*d*f*(2*A*d*f*(3*d*e + c*f) - B*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2))) - b^2*(C*(63*d^4*e^4 + 28*c*d^3*e^3*f + 18*c^2*d^2*e^2*f^2 + 12*c^3*d*e*f^3 + 7*c^4*f^4) + 2*d*f*(8*A*d*f*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2) - B*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3))))*Sqrt[c + d*x]*Sqrt[e + f*x])) - ((4*a*C*d*f + b*(9*C*d*e + 7*c*C*f - 10*B*d*f))*(a + b*x)^2*(c + d*x)^(3/2)*Sqrt[e + f*x])/(40*b*d^2*f^2) + (C*(a + b*x)^3*(c + d*x)^(3/2)*Sqrt[e + f*x])/(5*b*d*f) - (1/(960*b*d^4*f^4))*((c + d*x)^(3/2)*Sqrt[e + f*x]*(96*a^3*C*d^3*f^3 + 8*a^2*b*d^2*f^2*(23*C*d*e + 9*c*C*f - 30*B*d*f) + 20*a*b^2*d*f*(8*d*f*(5*B*d*e + 3*B*c*f - 6*A*d*f) - C*(35*d^2*e^2 + 22*c*d*e*f + 15*c^2*f^2)) + b^3*(C*(315*d^3*e^3 + 203*c*d^2*e^2*f + 145*c^2*d*e*f^2 + 105*c^3*f^3) + 10*d*f*(8*A*d*f*(5*d*e + 3*c*f) - B*(35*d^2*e^2 + 22*c*d*e*f + 15*c^2*f^2))) + 4*b*d*f*(8*b*d*f*(6*b*c*C*e + 3*a*C*d*e + a*c*C*f - 10*A*b*d*f) - (7*b*d*e + 5*b*c*f - 4*a*d*f)*(4*a*C*d*f + b*(9*C*d*e + 7*c*C*f - 10*B*d*f)))*x)) + (1/(128*d^(9/2)*f^(11/2)))*((d*e - c*f)*(16*a^2*d^2*f^2*(2*d*f*(3*B*d*e + B*c*f - 4*A*d*f) - C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2)) + 4*a*b*d*f*(C*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3) + 8*d*f*(2*A*d*f*(3*d*e + c*f) - B*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2))) - b^2*(C*(63*d^4*e^4 + 28*c*d^3*e^3*f + 18*c^2*d^2*e^2*f^2 + 12*c^3*d*e*f^3 + 7*c^4*f^4) + 2*d*f*(8*A*d*f*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2) - B*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^1*Sqrt[c + d*x]*(A + B*x + C*x^2)/Sqrt[e + f*x], x, 6, -((1/(64*d^3*f^4))*((8*a*d*f*(2*d*f*(3*B*d*e + B*c*f - 4*A*d*f) - C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2)) + b*(C*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3) + 8*d*f*(2*A*d*f*(3*d*e + c*f) - B*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2))))*Sqrt[c + d*x]*Sqrt[e + f*x])) + (C*(a + b*x)^2*(c + d*x)^(3/2)*Sqrt[e + f*x])/(4*b*d*f) - (1/(96*b*d^3*f^3))*((c + d*x)^(3/2)*Sqrt[e + f*x]*(24*a^2*C*d^2*f^2 + 8*a*b*d*f*(5*C*d*e + 3*c*C*f - 6*B*d*f) + b^2*(8*d*f*(5*B*d*e + 3*B*c*f - 6*A*d*f) - C*(35*d^2*e^2 + 22*c*d*e*f + 15*c^2*f^2)) + 4*b*d*f*(4*a*C*d*f + b*(7*C*d*e + 5*c*C*f - 8*B*d*f))*x)) + (1/(64*d^(7/2)*f^(9/2)))*((d*e - c*f)*(8*a*d*f*(2*d*f*(3*B*d*e + B*c*f - 4*A*d*f) - C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2)) + b*(C*(35*d^3*e^3 + 15*c*d^2*e^2*f + 9*c^2*d*e*f^2 + 5*c^3*f^3) + 8*d*f*(2*A*d*f*(3*d*e + c*f) - B*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^0*Sqrt[c + d*x]*(A + B*x + C*x^2)/Sqrt[e + f*x], x, 6, ((C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2) + 2*d*f*(4*A*d*f - B*(3*d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(8*d^2*f^3) - ((5*C*d*e + 7*c*C*f - 6*B*d*f)*(c + d*x)^(3/2)*Sqrt[e + f*x])/(12*d^2*f^2) + (C*(c + d*x)^(5/2)*Sqrt[e + f*x])/(3*d^2*f) - ((d*e - c*f)*(C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2) + 2*d*f*(4*A*d*f - B*(3*d*e + c*f)))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(8*d^(5/2)*f^(7/2))}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^1*Sqrt[e + f*x]), x, 8, -(((4*a*C*d*f + b*(3*C*d*e + c*C*f - 4*B*d*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b^2*d*f^2)) + (C*(c + d*x)^(3/2)*Sqrt[e + f*x])/(2*b*d*f) + ((2*b*d*f*(4*A*b*d*f - a*C*(3*d*e + c*f)) + (b*d*e - b*c*f + 2*a*d*f)*(4*a*C*d*f + b*(3*C*d*e + c*C*f - 4*B*d*f)))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(4*b^3*d^(3/2)*f^(5/2)) - (2*(A*b^2 - a*(b*B - a*C))*Sqrt[b*c - a*d]*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/(b^3*Sqrt[b*e - a*f])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^2*Sqrt[e + f*x]), x, 8, ((2*a^2*C*d*f + b^2*(c*C*e + A*d*f) - a*b*(C*d*e + c*C*f + B*d*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(b^2*(b*c - a*d)*f*(b*e - a*f)) - ((A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(b*(b*c - a*d)*(b*e - a*f)*(a + b*x)) - ((4*a*C*d*f + b*(C*d*e - c*C*f - 2*B*d*f))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(b^3*Sqrt[d]*f^(3/2)) + ((4*a^3*C*d*f - b^3*(2*B*c*e + A*d*e - A*c*f) + a*b^2*(4*c*C*e + 3*B*d*e + B*c*f) - a^2*b*(5*C*d*e + 3*c*C*f + 2*B*d*f))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/(b^3*Sqrt[b*c - a*d]*(b*e - a*f)^(3/2))}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^3*Sqrt[e + f*x]), x, 8, ((4*a^3*C*d*f - a^2*b*C*(7*d*e + 5*c*f) - b^3*(4*B*c*e - A*d*e - 3*A*c*f) + a*b^2*(8*c*C*e + 3*B*d*e + B*c*f - 4*A*d*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)) - ((A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(2*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^2) + (2*C*Sqrt[d]*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(b^3*Sqrt[f]) - (1/(4*b^3*(b*c - a*d)^(3/2)*(b*e - a*f)^(5/2)))*((8*a^4*C*d^2*f^2 - 4*a^3*b*C*d*f*(5*d*e + 3*c*f) + 3*a^2*b^2*C*(5*d^2*e^2 + 10*c*d*e*f + c^2*f^2) - a*b^3*(d^2*e*(3*B*e - 4*A*f) + c^2*f*(8*C*e - B*f) + 2*c*d*(12*C*e^2 - B*e*f + 2*A*f^2)) - b^4*(A*d^2*e^2 - 2*c*d*e*(2*B*e - A*f) - c^2*(8*C*e^2 - 4*B*e*f + 3*A*f^2)))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^4*Sqrt[e + f*x]), x, 6, ((4*a^3*C*d*f - b^3*(6*B*c*e - 3*A*d*e - 5*A*c*f) + a*b^2*(12*c*C*e + 3*B*d*e + B*c*f - 8*A*d*f) - a^2*b*(9*C*d*e + 7*c*C*f - 2*B*d*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(12*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)^2) - (1/(24*b^2*(b*c - a*d)^2*(b*e - a*f)^3*(a + b*x)))*((8*a^4*C*d^2*f^2 - 2*a^3*b*d*f*(13*C*d*e + 7*c*C*f - 2*B*d*f) - b^4*(3*A*d^2*e^2 - 2*c*d*e*(3*B*e - 2*A*f) - 3*c^2*(8*C*e^2 - 6*B*e*f + 5*A*f^2)) - a*b^3*(d^2*e*(3*B*e - 10*A*f) + 3*c^2*f*(4*C*e - B*f) + 2*c*d*(30*C*e^2 - 14*B*e*f + 13*A*f^2)) - a^2*b^2*(4*d*f*(4*B*d*e + B*c*f - 2*A*d*f) - C*(33*d^2*e^2 + 44*c*d*e*f + 3*c^2*f^2)))*Sqrt[c + d*x]*Sqrt[e + f*x]) - ((A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(3*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^3) - (1/(8*(b*c - a*d)^(5/2)*(b*e - a*f)^(7/2)))*((d*e - c*f)*(b^2*(A*d^2*e^2 - 2*c*d*e*(B*e - A*f) + c^2*(8*C*e^2 - 6*B*e*f + 5*A*f^2)) + a*b*(d^2*e*(B*e - 4*A*f) - c^2*f*(4*C*e - B*f) - 2*c*d*(6*C*e^2 - 7*B*e*f + 6*A*f^2)) - a^2*(2*d*f*(3*B*d*e + B*c*f - 4*A*d*f) - C*(5*d^2*e^2 + 2*c*d*e*f + c^2*f^2)))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])}


(* ::Subsubsection::Closed:: *)
(*n<0 & p<0*)


{(a + b*x)^2*(A + B*x + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]), x, 6, -(((2*a*C*d*f - b*(8*B*d*f - 7*C*(d*e + c*f)))*(a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x])/(24*b*d^2*f^2)) + (C*(a + b*x)^3*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b*d*f) - (1/(192*b*d^4*f^4))*(Sqrt[c + d*x]*Sqrt[e + f*x]*(32*a^3*C*d^3*f^3 - 8*a^2*b*d^2*f^2*(16*B*d*f - 11*C*(d*e + c*f)) - 16*a*b^2*d*f*(C*(15*d^2*e^2 + 14*c*d*e*f + 15*c^2*f^2) + 6*d*f*(4*A*d*f - 3*B*(d*e + c*f))) + b^3*(5*C*(21*d^3*e^3 + 19*c*d^2*e^2*f + 19*c^2*d*e*f^2 + 21*c^3*f^3) + 8*d*f*(18*A*d*f*(d*e + c*f) - B*(15*d^2*e^2 + 14*c*d*e*f + 15*c^2*f^2))) + 2*b*d*f*(6*b*d*f*(6*b*c*C*e + a*C*d*e + a*c*C*f - 8*A*b*d*f) + (4*a*d*f - 5*b*(d*e + c*f))*(2*a*C*d*f - b*(8*B*d*f - 7*C*(d*e + c*f))))*x)) + (1/(64*d^(9/2)*f^(9/2)))*((16*a^2*d^2*f^2*(C*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) + 4*d*f*(2*A*d*f - B*(d*e + c*f))) - 16*a*b*d*f*(C*(5*d^3*e^3 + 3*c*d^2*e^2*f + 3*c^2*d*e*f^2 + 5*c^3*f^3) + 2*d*f*(4*A*d*f*(d*e + c*f) - B*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2))) + b^2*(C*(35*d^4*e^4 + 20*c*d^3*e^3*f + 18*c^2*d^2*e^2*f^2 + 20*c^3*d*e*f^3 + 35*c^4*f^4) + 8*d*f*(2*A*d*f*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) - B*(5*d^3*e^3 + 3*c*d^2*e^2*f + 3*c^2*d*e*f^2 + 5*c^3*f^3))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^1*(A + B*x + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]), x, 5, (C*(a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b*d*f) - (1/(24*b*d^3*f^3))*(Sqrt[c + d*x]*Sqrt[e + f*x]*(8*a^2*C*d^2*f^2 - 6*a*b*d*f*(4*B*d*f - 3*C*(d*e + c*f)) - b^2*(C*(15*d^2*e^2 + 14*c*d*e*f + 15*c^2*f^2) + 6*d*f*(4*A*d*f - 3*B*(d*e + c*f))) + 2*b*d*f*(2*a*C*d*f - b*(6*B*d*f - 5*C*(d*e + c*f)))*x)) + (1/(8*d^(7/2)*f^(7/2)))*((2*a*d*f*(C*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) + 4*d*f*(2*A*d*f - B*(d*e + c*f))) - b*(C*(5*d^3*e^3 + 3*c*d^2*e^2*f + 3*c^2*d*e*f^2 + 5*c^3*f^3) + 2*d*f*(4*A*d*f*(d*e + c*f) - B*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2))))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])}
{(a + b*x)^0*(A + B*x + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]), x, 5, -(((3*C*d*e + 5*c*C*f - 4*B*d*f)*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*d^2*f^2)) + (C*(c + d*x)^(3/2)*Sqrt[e + f*x])/(2*d^2*f) + ((C*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) + 4*d*f*(2*A*d*f - B*(d*e + c*f)))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(4*d^(5/2)*f^(5/2))}
{(A + B*x + C*x^2)/((a + b*x)^1*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 7, (C*Sqrt[c + d*x]*Sqrt[e + f*x])/(b*d*f) - ((2*a*C*d*f + b*(C*d*e + c*C*f - 2*B*d*f))*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(b^2*d^(3/2)*f^(3/2)) - (2*(A*b^2 - a*(b*B - a*C))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/(b^2*Sqrt[b*c - a*d]*Sqrt[b*e - a*f])}
{(A + B*x + C*x^2)/((a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 7, -(((A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(b*(b*c - a*d)*(b*e - a*f)*(a + b*x))) + (2*C*ArcTanh[(Sqrt[f]*Sqrt[c + d*x])/(Sqrt[d]*Sqrt[e + f*x])])/(b^2*Sqrt[d]*Sqrt[f]) + ((2*a^3*C*d*f - 3*a^2*b*C*(d*e + c*f) - b^3*(2*B*c*e - A*d*e - A*c*f) + a*b^2*(4*c*C*e + B*d*e + B*c*f - 2*A*d*f))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])/(b^2*(b*c - a*d)^(3/2)*(b*e - a*f)^(3/2))}
{(A + B*x + C*x^2)/((a + b*x)^3*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 5, -(((A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(2*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^2)) + ((2*a^3*C*d*f + a*b^2*(8*c*C*e + B*d*e + B*c*f - 6*A*d*f) - b^3*(4*B*c*e - 3*A*(d*e + c*f)) + a^2*b*(2*B*d*f - 5*C*(d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(4*b*(b*c - a*d)^2*(b*e - a*f)^2*(a + b*x)) - (1/(4*(b*c - a*d)^(5/2)*(b*e - a*f)^(5/2)))*((b^2*(3*A*d^2*e^2 - 2*c*d*e*(2*B*e - A*f) + c^2*(8*C*e^2 - 4*B*e*f + 3*A*f^2)) + a*b*(d^2*e*(B*e - 8*A*f) - c^2*f*(8*C*e - B*f) - 2*c*d*(4*C*e^2 - 7*B*e*f + 4*A*f^2)) + a^2*(C*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) + 4*d*f*(2*A*d*f - B*(d*e + c*f))))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])}
{(A + B*x + C*x^2)/((a + b*x)^4*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 6, -(((A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^3)) + ((2*a^3*C*d*f + a*b^2*(12*c*C*e + B*d*e + B*c*f - 10*A*d*f) - b^3*(6*B*c*e - 5*A*(d*e + c*f)) + a^2*b*(4*B*d*f - 7*C*(d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(12*b*(b*c - a*d)^2*(b*e - a*f)^2*(a + b*x)^2) + (1/(24*b*(b*c - a*d)^3*(b*e - a*f)^3*(a + b*x)))*((4*a^4*C*d^2*f^2 + 8*a^3*b*d*f*(B*d*f - 2*C*(d*e + c*f)) - b^4*(15*A*d^2*e^2 - 2*c*d*e*(9*B*e - 7*A*f) + 3*c^2*(8*C*e^2 - 6*B*e*f + 5*A*f^2)) - a*b^3*(d^2*e*(3*B*e - 44*A*f) - 3*c^2*f*(4*C*e - B*f) - 2*c*d*(6*C*e^2 - 29*B*e*f + 22*A*f^2)) - a^2*b^2*(C*(3*d^2*e^2 - 34*c*d*e*f + 3*c^2*f^2) + 2*d*f*(22*A*d*f - 5*B*(d*e + c*f))))*Sqrt[c + d*x]*Sqrt[e + f*x]) + (1/(8*(b*c - a*d)^(7/2)*(b*e - a*f)^(7/2)))*((b^3*(5*A*d^3*e^3 - 3*c*d^2*e^2*(2*B*e - A*f) + c^2*d*e*(8*C*e^2 - 4*B*e*f + 3*A*f^2) + c^3*f*(8*C*e^2 - 6*B*e*f + 5*A*f^2)) + a*b^2*(d^3*e^2*(B*e - 18*A*f) - c^3*f^2*(4*C*e - B*f) - c*d^2*e*(4*C*e^2 - 23*B*e*f + 12*A*f^2) - c^2*d*f*(40*C*e^2 - 23*B*e*f + 18*A*f^2)) - 2*a^3*d*f*(C*(3*d^2*e^2 + 2*c*d*e*f + 3*c^2*f^2) + 4*d*f*(2*A*d*f - B*(d*e + c*f))) + a^2*b*(C*(d^3*e^3 + 23*c*d^2*e^2*f + 23*c^2*d*e*f^2 + c^3*f^3) + 4*d*f*(6*A*d*f*(d*e + c*f) - B*(d^2*e^2 + 10*c*d*e*f + c^2*f^2))))*ArcTanh[(Sqrt[b*e - a*f]*Sqrt[c + d*x])/(Sqrt[b*c - a*d]*Sqrt[e + f*x])])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (e+f x)^(p/2) (A+B x+C x^2)*)


(* ::Subsubsection::Closed:: *)
(*n>0 & p>0*)


{(a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2), x, 10, (1/(315*b^3*d^3*f^3))*(2*(8*a^3*C*d^3*f^3 + 3*a^2*b*d^2*f^2*(C*d*e - c*C*f - 4*B*d*f) - 3*a*b^2*d*f^2*((c^2*C - 7*A*d^2)*f + B*d*(d*e - 2*c*f)) - b^3*(C*(16*d^3*e^3 - 3*c^2*d*e*f^2 - 8*c^3*f^3) + 3*d*f*(7*A*d*f*(2*d*e - c*f) - B*(8*d^2*e^2 - c*d*e*f - 4*c^2*f^2))))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]) - (2*(7*b*d*f*(b*c*C*e + a*C*d*e + a*c*C*f - 3*A*b*d*f) + (a*d*f - 4*b*(d*e + c*f))*(2*a*C*d*f - b*(3*B*d*f - 2*C*(d*e + c*f))))*Sqrt[a + b*x]*Sqrt[c + d*x]*(e + f*x)^(3/2))/(105*b^2*d^2*f^3) - (2*(2*a*C*d*f - b*(3*B*d*f - 2*C*(d*e + c*f)))*Sqrt[a + b*x]*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(21*b*d^2*f^2) + (2*C*(a + b*x)^(3/2)*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(9*b*d*f) - (1/(315*b^4*d^(7/2)*f^4*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(16*a^4*C*d^4*f^4 - 8*a^3*b*d^3*f^3*(C*d*e + c*C*f + 3*B*d*f) + 3*a^2*b^2*d^2*f^2*(d*f*(5*B*d*e + 5*B*c*f + 14*A*d*f) - 2*C*(d^2*e^2 - c*d*e*f + c^2*f^2)) - a*b^3*d*f*(C*(8*d^3*e^3 - 6*c*d^2*e^2*f - 6*c^2*d*e*f^2 + 8*c^3*f^3) + 3*d*f*(14*A*d*f*(d*e + c*f) - B*(5*d^2*e^2 - 6*c*d*e*f + 5*c^2*f^2))) + b^4*(2*C*(8*d^4*e^4 - 4*c*d^3*e^3*f - 3*c^2*d^2*e^2*f^2 - 4*c^3*d*e*f^3 + 8*c^4*f^4) + 3*d*f*(14*A*d*f*(d^2*e^2 - c*d*e*f + c^2*f^2) - B*(8*d^3*e^3 - 5*c*d^2*e^2*f - 5*c^2*d*e*f^2 + 8*c^3*f^3))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (1/(315*b^4*d^(7/2)*f^4*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(d*e - c*f)*(8*a^3*C*d^3*f^3 + 3*a^2*b*d^2*f^2*(C*d*e - c*C*f - 4*B*d*f) - 3*a*b^2*d*f^2*((c^2*C - 7*A*d^2)*f + B*d*(d*e - 2*c*f)) - b^3*(C*(16*d^3*e^3 - 3*c^2*d*e*f^2 - 8*c^3*f^3) + 3*d*f*(7*A*d*f*(2*d*e - c*f) - B*(8*d^2*e^2 - c*d*e*f - 4*c^2*f^2))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^(1/2), x, 9, -((2*(5*b*d*f*(3*a*C*(d*e + c*f) + b*(c*C*e - 7*A*d*f)) - (2*b*d*e - b*c*f + 4*a*d*f)*(6*a*C*d*f - b*(7*B*d*f - 4*C*(d*e + c*f))))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(105*b^3*d^2*f^2)) - (2*(6*a*C*d*f - b*(7*B*d*f - 4*C*(d*e + c*f)))*Sqrt[a + b*x]*Sqrt[c + d*x]*(e + f*x)^(3/2))/(35*b^2*d*f^2) + (2*C*Sqrt[a + b*x]*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(7*b*d*f) - (1/(105*b^4*d^(5/2)*f^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(3*b*d*f*(5*b*c*f*(3*a*C*(d*e + c*f) + b*(c*C*e - 7*A*d*f)) - (b*c*e + a*d*e + 3*a*c*f)*(6*a*C*d*f - b*(7*B*d*f - 4*C*(d*e + c*f)))) + 2*((b*d*e)/2 - (b*c + a*d)*f)*(5*b*d*f*(3*a*C*(d*e + c*f) + b*(c*C*e - 7*A*d*f)) - (2*b*d*e - b*c*f + 4*a*d*f)*(6*a*C*d*f - b*(7*B*d*f - 4*C*(d*e + c*f)))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (1/(105*b^4*d^(5/2)*f^3*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(d*e - c*f)*(24*a^2*C*d^2*f^2 + a*b*d*f*(13*C*d*e - 5*c*C*f - 28*B*d*f) - b^2*(7*d*f*(2*B*d*e - B*c*f - 5*A*d*f) - C*(8*d^2*e^2 - c*d*e*f - 4*c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^(3/2), x, 9, (2*(24*a^2*C*d*f^2 - a*b*f*(7*C*d*e + c*C*f + 20*B*d*f) + b^2*(5*d*f*(B*e + 3*A*f) - C*e*(2*d*e - c*f)))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b^3*d*f*(b*e - a*f)) + (2*(6*a^2*C*d*f + b^2*(c*C*e + 5*A*d*f) - a*b*(C*d*e + c*C*f + 5*B*d*f))*Sqrt[a + b*x]*Sqrt[c + d*x]*(e + f*x)^(3/2))/(5*b^2*(b*c - a*d)*f*(b*e - a*f)) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(b*(b*c - a*d)*(b*e - a*f)*Sqrt[a + b*x]) + (1/(15*b^4*d^(3/2)*f^2*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(48*a^2*C*d^2*f^2 - 8*a*b*d*f*(C*d*e + c*C*f + 5*B*d*f) + b^2*(5*d*f*(B*d*e + B*c*f + 6*A*d*f) - 2*C*(d^2*e^2 - c*d*e*f + c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (1/(15*b^4*d^(3/2)*f^2*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(d*e - c*f)*(24*a^2*C*d*f^2 - a*b*f*(7*C*d*e + c*C*f + 20*B*d*f) + b^2*(5*d*f*(B*e + 3*A*f) - C*e*(2*d*e - c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^(5/2), x, 9, (2*(8*a^2*C*d*f + b^2*(c*C*e + 3*B*c*f + A*d*f) - a*b*(C*d*e + 7*c*C*f + 4*B*d*f))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b^3*(b*c - a*d)*(b*e - a*f)) - (2*(b*B - 2*a*C)*Sqrt[c + d*x]*(e + f*x)^(3/2))/(b^2*(b*e - a*f)*Sqrt[a + b*x]) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(3*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(3/2)) + (2*(16*a^3*C*d^2*f^2 - 8*a^2*b*d*f*(B*d*f + 2*C*(d*e + c*f)) - b^3*(c^2*C*e*f + A*d^2*e*f + c*d*(C*e^2 + 6*B*e*f + A*f^2)) + a*b^2*(d*f*(7*B*d*e + 7*B*c*f + 2*A*d*f) + C*(d^2*e^2 + 16*c*d*e*f + c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^4*Sqrt[d]*Sqrt[(-b)*c + a*d]*f*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*(d*e - c*f)*(8*a^2*C*d*f + b^2*(c*C*e + 3*B*c*f + A*d*f) - a*b*(C*d*e + 7*c*C*f + 4*B*d*f))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^4*Sqrt[d]*Sqrt[(-b)*c + a*d]*f*Sqrt[c + d*x]*Sqrt[e + f*x])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^(7/2), x, 9, (2*(24*a^3*C*d^2*f - a^2*b*d*(23*C*d*e + 41*c*C*f + 4*B*d*f) - b^3*(15*c^2*C*e - 2*A*d^2*e + c*d*(5*B*e + A*f)) + a*b^2*(15*c^2*C*f + d^2*(3*B*e - A*f) + c*(40*C*d*e + 6*B*d*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b^3*(b*c - a*d)^2*(b*e - a*f)*Sqrt[a + b*x]) + (2*(6*a^3*C*d*f + a*b^2*(10*c*C*e + 3*B*d*e + 3*B*c*f - 4*A*d*f) - b^3*(5*B*c*e - 2*A*(d*e + c*f)) - a^2*b*(B*d*f + 8*C*(d*e + c*f)))*Sqrt[c + d*x]*(e + f*x)^(3/2))/(15*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)^(3/2)) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(5*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(5/2)) + (2*Sqrt[d]*(48*a^4*C*d^2*f^2 - 8*a^3*b*d*f*(B*d*f + 11*C*(d*e + c*f)) - b^4*(2*A*d^2*e^2 - c*d*e*(5*B*e + 2*A*f) - c^2*(30*C*e^2 + 5*B*e*f - 2*A*f^2)) - a*b^3*(d^2*e*(3*B*e - 2*A*f) + c^2*f*(70*C*e + 3*B*f) + 2*c*d*(35*C*e^2 + 11*B*e*f - A*f^2)) + a^2*b^2*(2*C*(19*d^2*e^2 + 81*c*d*e*f + 19*c^2*f^2) - d*f*(2*A*d*f - 13*B*(d*e + c*f))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^4*((-b)*c + a*d)^(3/2)*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*(d*e - c*f)*(24*a^3*C*d^2*f - a^2*b*d*(23*C*d*e + 41*c*C*f + 4*B*d*f) - b^3*(15*c^2*C*e - 2*A*d^2*e + c*d*(5*B*e + A*f)) + a*b^2*(15*c^2*C*f + d^2*(3*B*e - A*f) + c*(40*C*d*e + 6*B*d*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^4*Sqrt[d]*((-b)*c + a*d)^(3/2)*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[e + f*x])}
{Sqrt[c + d*x]*Sqrt[e + f*x]*(A + B*x + C*x^2)/(a + b*x)^(9/2), x, 10, -((1/(105*b^3*(b*c - a*d)^2*(b*e - a*f)^2*(a + b*x)^(3/2)))*(2*(24*a^4*C*d^2*f^2 - a^3*b*d*f*(61*C*d*e + 43*c*C*f - 4*B*d*f) - 3*a*b^3*(d^2*e*(B*e - 3*A*f) + 2*c^2*f*(7*C*e - B*f) + c*d*(28*C*e^2 - 5*B*e*f + 5*A*f^2)) - b^4*(4*A*d^2*e^2 - c*d*e*(7*B*e - A*f) - c^2*(35*C*e^2 - 14*B*e*f + 8*A*f^2)) - 3*a^2*b^2*(d*f*(3*B*d*e + 2*B*c*f - A*d*f) - C*(15*d^2*e^2 + 37*c*d*e*f + 5*c^2*f^2)))*Sqrt[c + d*x]*Sqrt[e + f*x])) + (1/(105*b^3*(b*c - a*d)^3*(b*e - a*f)^3*Sqrt[a + b*x]))*(2*(48*a^5*C*d^3*f^3 + 8*a^4*b*d^2*f^2*(B*d*f - 16*C*(d*e + c*f)) - b^5*(8*A*d^3*e^3 - c*d^2*e^2*(14*B*e + 5*A*f) + c^2*d*e*(35*C*e^2 + 14*B*e*f - 5*A*f^2) + c^3*f*(35*C*e^2 - 14*B*e*f + 8*A*f^2)) - a*b^4*(d^3*e^2*(6*B*e - 19*A*f) - 6*c^3*f^2*(7*C*e - B*f) - c^2*d*f*(238*C*e^2 - 19*f*(B*e - A*f)) - c*d^2*e*(42*C*e^2 - f*(19*B*e + 20*A*f))) + a^3*b^2*d*f*(C*(103*d^2*e^2 + 344*c*d*e*f + 103*c^2*f^2) + d*f*(6*A*d*f - 19*B*(d*e + c*f))) - 3*a^2*b^3*(C*(5*d^3*e^3 + 94*c*d^2*e^2*f + 94*c^2*d*e*f^2 + 5*c^3*f^3) + d*f*(3*A*d*f*(d*e + c*f) - B*(3*d^2*e^2 + 16*c*d*e*f + 3*c^2*f^2))))*Sqrt[c + d*x]*Sqrt[e + f*x]) + (2*(6*a^3*C*d*f + a*b^2*(14*c*C*e + 3*B*d*e + 3*B*c*f - 8*A*d*f) - b^3*(7*B*c*e - 4*A*(d*e + c*f)) + a^2*b*(B*d*f - 10*C*(d*e + c*f)))*Sqrt[c + d*x]*(e + f*x)^(3/2))/(35*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)^(5/2)) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*(e + f*x)^(3/2))/(7*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(7/2)) + (2*Sqrt[d]*(48*a^5*C*d^3*f^3 + 8*a^4*b*d^2*f^2*(B*d*f - 16*C*(d*e + c*f)) - b^5*(8*A*d^3*e^3 - c*d^2*e^2*(14*B*e + 5*A*f) + c^2*d*e*(35*C*e^2 + 14*B*e*f - 5*A*f^2) + c^3*f*(35*C*e^2 - 14*B*e*f + 8*A*f^2)) - a*b^4*(d^3*e^2*(6*B*e - 19*A*f) - 6*c^3*f^2*(7*C*e - B*f) - c^2*d*f*(238*C*e^2 - 19*f*(B*e - A*f)) - c*d^2*e*(42*C*e^2 - f*(19*B*e + 20*A*f))) + a^3*b^2*d*f*(C*(103*d^2*e^2 + 344*c*d*e*f + 103*c^2*f^2) + d*f*(6*A*d*f - 19*B*(d*e + c*f))) - 3*a^2*b^3*(C*(5*d^3*e^3 + 94*c*d^2*e^2*f + 94*c^2*d*e*f^2 + 5*c^3*f^3) + d*f*(3*A*d*f*(d*e + c*f) - B*(3*d^2*e^2 + 16*c*d*e*f + 3*c^2*f^2))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(105*b^4*((-b)*c + a*d)^(5/2)*(b*e - a*f)^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (1/(105*b^4*((-b)*c + a*d)^(5/2)*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[d]*(d*e - c*f)*(24*a^4*C*d^2*f^2 - a^3*b*d*f*(43*C*d*e + 61*c*C*f - 4*B*d*f) + b^4*(8*A*d^2*e^2 - c*d*e*(14*B*e + A*f) + c^2*(35*C*e^2 + 7*B*e*f - 4*A*f^2)) + 3*a*b^3*(d^2*e*(2*B*e - 5*A*f) - c^2*f*(28*C*e + B*f) - c*d*(14*C*e^2 - 5*B*e*f - 3*A*f^2)) - 3*a^2*b^2*(d*f*(2*B*d*e + 3*B*c*f - A*d*f) - C*(5*d^2*e^2 + 37*c*d*e*f + 15*c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}


(* ::Subsubsection::Closed:: *)
(*n>0 & p<0*)


{(a + b*x)^(3/2)*Sqrt[c + d*x]*(A + B*x + C*x^2)/Sqrt[e + f*x], x, 10, -((1/(945*b^2*d^3*f^4))*(2*(5*b*d*f*(7*a*d*f*(5*b*c*C*e + 3*a*C*d*e + a*c*C*f - 9*A*b*d*f) - (3*b*c*e + 3*a*d*e + a*c*f)*(4*a*C*d*f + b*(8*C*d*e + 6*c*C*f - 9*B*d*f))) + 2*((a*d*f)/2 - b*(2*d*e + c*f))*(7*b*d*f*(5*b*c*C*e + 3*a*C*d*e + a*c*C*f - 9*A*b*d*f) - (6*b*d*e + 4*b*c*f - 3*a*d*f)*(4*a*C*d*f + b*(8*C*d*e + 6*c*C*f - 9*B*d*f))))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])) - (2*(7*b*d*f*(5*b*c*C*e + 3*a*C*d*e + a*c*C*f - 9*A*b*d*f) - (6*b*d*e + 4*b*c*f - 3*a*d*f)*(4*a*C*d*f + b*(8*C*d*e + 6*c*C*f - 9*B*d*f)))*Sqrt[a + b*x]*(c + d*x)^(3/2)*Sqrt[e + f*x])/(315*b*d^3*f^3) - (2*(4*a*C*d*f + b*(8*C*d*e + 6*c*C*f - 9*B*d*f))*(a + b*x)^(3/2)*(c + d*x)^(3/2)*Sqrt[e + f*x])/(63*b*d^2*f^2) + (2*C*(a + b*x)^(5/2)*(c + d*x)^(3/2)*Sqrt[e + f*x])/(9*b*d*f) + (1/(315*b^3*d^(7/2)*f^5*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(8*a^4*C*d^4*f^4 + a^3*b*d^3*f^3*(11*C*d*e - 7*c*C*f - 18*B*d*f) - 3*a^2*b^2*d^2*f^2*(3*d*f*(4*B*d*e - 3*B*c*f - 7*A*d*f) - C*(9*d^2*e^2 - 5*c*d*e*f - 3*c^2*f^2)) - a*b^3*d*f*(2*C*(92*d^3*e^3 - 33*c*d^2*e^2*f - 18*c^2*d*e*f^2 - 16*c^3*f^3) + 3*d*f*(7*A*d*f*(13*d*e - 7*c*f) - B*(72*d^2*e^2 - 29*c*d*e*f - 19*c^2*f^2))) + b^4*(C*(128*d^4*e^4 - 40*c*d^3*e^3*f - 21*c^2*d^2*e^2*f^2 - 16*c^3*d*e*f^3 - 16*c^4*f^4) + 3*d*f*(7*A*d*f*(8*d^2*e^2 - 3*c*d*e*f - 2*c^2*f^2) - B*(48*d^3*e^3 - 16*c*d^2*e^2*f - 9*c^2*d*e*f^2 - 8*c^3*f^3))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) + (1/(315*b^3*d^(7/2)*f^5*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(d*e - c*f)*(4*a^3*C*d^3*f^3 + 3*a^2*b*d^2*f^2*(3*C*d*e - c*C*f - 3*B*d*f) - 3*a*b^2*d*f*(3*d*f*(16*B*d*e + 3*B*c*f - 21*A*d*f) - 5*C*(8*d^2*e^2 + 2*c*d*e*f + c^2*f^2)) - b^3*(C*(128*d^3*e^3 + 24*c*d^2*e^2*f + 15*c^2*d*e*f^2 + 8*c^3*f^3) + 3*d*f*(7*A*d*f*(8*d*e + c*f) - 4*B*(12*d^2*e^2 + 2*c*d*e*f + c^2*f^2))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{(a + b*x)^(1/2)*Sqrt[c + d*x]*(A + B*x + C*x^2)/Sqrt[e + f*x], x, 9, -((2*(5*b*d*f*(3*b*c*C*e + 3*a*C*d*e + a*c*C*f - 7*A*b*d*f) + (a*d*f - 2*b*(2*d*e + c*f))*(4*a*C*d*f + b*(6*C*d*e + 4*c*C*f - 7*B*d*f)))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(105*b^2*d^2*f^3)) - (2*(4*a*C*d*f + b*(6*C*d*e + 4*c*C*f - 7*B*d*f))*Sqrt[a + b*x]*(c + d*x)^(3/2)*Sqrt[e + f*x])/(35*b*d^2*f^2) + (2*C*(a + b*x)^(3/2)*(c + d*x)^(3/2)*Sqrt[e + f*x])/(7*b*d*f) - (1/(105*b^3*d^(5/2)*f^4*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(3*b*d*f*(5*a*d*f*(3*b*c*C*e + 3*a*C*d*e + a*c*C*f - 7*A*b*d*f) - (b*c*e + 3*a*d*e + a*c*f)*(4*a*C*d*f + b*(6*C*d*e + 4*c*C*f - 7*B*d*f))) + 2*((b*c*f)/2 - d*(b*e + a*f))*(5*b*d*f*(3*b*c*C*e + 3*a*C*d*e + a*c*C*f - 7*A*b*d*f) + (a*d*f - 2*b*(2*d*e + c*f))*(4*a*C*d*f + b*(6*C*d*e + 4*c*C*f - 7*B*d*f))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) + (1/(105*b^3*d^(5/2)*f^4*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(d*e - c*f)*(4*a^2*C*d^2*f^2 + a*b*d*f*(8*C*d*e - 2*c*C*f - 7*B*d*f) - b^2*(7*d*f*(8*B*d*e + B*c*f - 10*A*d*f) - 4*C*(12*d^2*e^2 + 2*c*d*e*f + c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^(1/2)*Sqrt[e + f*x]), x, 8, -((2*(4*a*C*d*f + b*(4*C*d*e + 2*c*C*f - 5*B*d*f))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b^2*d*f^2)) + (2*C*Sqrt[a + b*x]*(c + d*x)^(3/2)*Sqrt[e + f*x])/(5*b*d*f) - (1/(15*b^3*d^(3/2)*f^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(3*b*d*f*(b*c*C*e + 3*a*C*d*e + a*c*C*f - 5*A*b*d*f) - (2*b*d*e - b*c*f + 2*a*d*f)*(4*a*C*d*f + b*(4*C*d*e + 2*c*C*f - 5*B*d*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (2*Sqrt[(-b)*c + a*d]*(d*e - c*f)*(4*a^2*C*d*f^2 + a*b*f*(3*C*d*e - c*C*f - 5*B*d*f) - b^2*(5*d*f*(2*B*e - 3*A*f) - C*e*(8*d*e + c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^3*d^(3/2)*f^3*Sqrt[c + d*x]*Sqrt[e + f*x])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^(3/2)*Sqrt[e + f*x]), x, 8, (2*(4*a^2*C*d*f + b^2*(c*C*e + 3*A*d*f) - a*b*(C*d*e + c*C*f + 3*B*d*f))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b^2*(b*c - a*d)*f*(b*e - a*f)) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(b*(b*c - a*d)*(b*e - a*f)*Sqrt[a + b*x]) + (2*Sqrt[(-b)*c + a*d]*(8*a^2*C*d*f^2 - a*b*f*(3*C*d*e + c*C*f + 6*B*d*f) + b^2*(3*d*f*(B*e + A*f) - C*e*(2*d*e - c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^3*Sqrt[d]*f^2*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*Sqrt[(-b)*c + a*d]*(d*e - c*f)*(2*b*C*e - 3*b*B*f + 4*a*C*f)*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^3*Sqrt[d]*f^2*Sqrt[c + d*x]*Sqrt[e + f*x])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^(5/2)*Sqrt[e + f*x]), x, 8, -((2*(4*a^2*C*f + b^2*(3*B*e - 2*A*f) - a*b*(6*C*e + B*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b^2*(b*e - a*f)^2*Sqrt[a + b*x])) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(3*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(3/2)) + (2*Sqrt[d]*(8*a^3*C*d*f^2 - a^2*b*f*(13*C*d*e + 7*c*C*f + 2*B*d*f) + a*b^2*(3*C*e*(d*e + 4*c*f) + f*(4*B*d*e + B*c*f - A*d*f)) - b^3*(A*d*e*f + c*(3*C*e^2 + 3*B*e*f - 2*A*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^3*Sqrt[(-b)*c + a*d]*f*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*(d*e - c*f)*(4*a^2*C*d*f + b^2*(3*c*C*e + A*d*f) - a*b*(B*d*f + 3*C*(d*e + c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^3*Sqrt[d]*Sqrt[(-b)*c + a*d]*f*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[e + f*x])}
{Sqrt[c + d*x]*(A + B*x + C*x^2)/((a + b*x)^(7/2)*Sqrt[e + f*x]), x, 9, (2*(4*a^3*C*d*f - b^3*(5*B*c*e - 2*A*d*e - 4*A*c*f) + a*b^2*(10*c*C*e + 3*B*d*e + B*c*f - 6*A*d*f) - a^2*b*(8*C*d*e + 6*c*C*f - B*d*f))*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b^2*(b*c - a*d)*(b*e - a*f)^2*(a + b*x)^(3/2)) - (1/(15*b^2*(b*c - a*d)^2*(b*e - a*f)^3*Sqrt[a + b*x]))*(2*(8*a^4*C*d^2*f^2 - a^3*b*d*f*(23*C*d*e + 13*c*C*f - 2*B*d*f) - b^4*(2*A*d^2*e^2 - c*d*e*(5*B*e - 3*A*f) - c^2*(15*C*e^2 - 10*B*e*f + 8*A*f^2)) - a^2*b^2*(d*f*(7*B*d*e + 2*B*c*f - 3*A*d*f) - C*(23*d^2*e^2 + 37*c*d*e*f + 3*c^2*f^2)) - a*b^3*(d^2*e*(3*B*e - 7*A*f) + 2*c^2*f*(5*C*e - B*f) + c*d*(40*C*e^2 - 13*f*(B*e - A*f))))*Sqrt[c + d*x]*Sqrt[e + f*x]) - (2*(A*b^2 - a*(b*B - a*C))*(c + d*x)^(3/2)*Sqrt[e + f*x])/(5*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(5/2)) + (2*Sqrt[d]*(8*a^4*C*d^2*f^2 - a^3*b*d*f*(23*C*d*e + 13*c*C*f - 2*B*d*f) - b^4*(2*A*d^2*e^2 - c*d*e*(5*B*e - 3*A*f) - c^2*(15*C*e^2 - 10*B*e*f + 8*A*f^2)) - a^2*b^2*(d*f*(7*B*d*e + 2*B*c*f - 3*A*d*f) - C*(23*d^2*e^2 + 37*c*d*e*f + 3*c^2*f^2)) - a*b^3*(d^2*e*(3*B*e - 7*A*f) + 2*c^2*f*(5*C*e - B*f) + c*d*(40*C*e^2 - 13*f*(B*e - A*f))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^3*((-b)*c + a*d)^(3/2)*(b*e - a*f)^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*Sqrt[d]*(d*e - c*f)*(4*a^3*C*d*f - b^3*(5*B*c*e - 2*A*d*e - 4*A*c*f) + a*b^2*(10*c*C*e + 3*B*d*e + B*c*f - 6*A*d*f) - a^2*b*(8*C*d*e + 6*c*C*f - B*d*f))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^3*((-b)*c + a*d)^(3/2)*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[e + f*x])}


(* ::Subsubsection::Closed:: *)
(*n<0 & p<0*)


{(a + b*x)^(3/2)*(A + B*x + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]), x, 9, -((2*(5*b*d*f*(5*b*c*C*e + a*C*d*e + a*c*C*f - 7*A*b*d*f) + (3*a*d*f - 4*b*(d*e + c*f))*(2*a*C*d*f - b*(7*B*d*f - 6*C*(d*e + c*f))))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(105*b*d^3*f^3)) - (2*(2*a*C*d*f - b*(7*B*d*f - 6*C*(d*e + c*f)))*(a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x])/(35*b*d^2*f^2) + (2*C*(a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x])/(7*b*d*f) - (1/(105*b^2*d^(7/2)*f^4*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(3*b*d*f*(5*a*d*f*(5*b*c*C*e + a*C*d*e + a*c*C*f - 7*A*b*d*f) - (3*b*c*e + a*d*e + a*c*f)*(2*a*C*d*f - b*(7*B*d*f - 6*C*(d*e + c*f)))) + 2*((a*d*f)/2 - b*(d*e + c*f))*(5*b*d*f*(5*b*c*C*e + a*C*d*e + a*c*C*f - 7*A*b*d*f) + (3*a*d*f - 4*b*(d*e + c*f))*(2*a*C*d*f - b*(7*B*d*f - 6*C*(d*e + c*f)))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (1/(105*b^2*d^(7/2)*f^4*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(3*a^2*C*d^2*f^2*(d*e - c*f) - 3*a*b*d*f*(7*d*f*(3*B*d*e + 2*B*c*f - 5*A*d*f) - C*(16*d^2*e^2 + 8*c*d*e*f + 11*c^2*f^2)) - b^2*(C*(48*d^3*e^3 + 16*c*d^2*e^2*f + 17*c^2*d*e*f^2 + 24*c^3*f^3) + 7*d*f*(5*A*d*f*(2*d*e + c*f) - B*(8*d^2*e^2 + 3*c*d*e*f + 4*c^2*f^2))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
{(a + b*x)^(1/2)*(A + B*x + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]), x, 8, -((2*(2*a*C*d*f - b*(5*B*d*f - 4*C*(d*e + c*f)))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b*d^2*f^2)) + (2*C*(a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x])/(5*b*d*f) - (1/(15*b^2*d^(5/2)*f^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]))*(2*Sqrt[(-b)*c + a*d]*(3*b*d*f*(3*b*c*C*e + a*C*d*e + a*c*C*f - 5*A*b*d*f) + (a*d*f - 2*b*(d*e + c*f))*(2*a*C*d*f - b*(5*B*d*f - 4*C*(d*e + c*f))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))]) - (2*Sqrt[(-b)*c + a*d]*(b*e - a*f)*(a*C*d*f*(d*e - c*f) - b*(5*d*f*(2*B*d*e + B*c*f - 3*A*d*f) - C*(8*d^2*e^2 + 3*c*d*e*f + 4*c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^2*d^(5/2)*f^3*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x + C*x^2)/((a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 7, (2*C*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b*d*f) - (2*Sqrt[(-b)*c + a*d]*(2*a*C*d*f - b*(3*B*d*f - 2*C*(d*e + c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^2*d^(3/2)*f^2*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (2*Sqrt[(-b)*c + a*d]*(a*C*f*(d*e - c*f) - b*(3*d*f*(B*e - A*f) - C*e*(2*d*e + c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^2*d^(3/2)*f^2*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x + C*x^2)/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 7, -((2*(A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(b*(b*c - a*d)*(b*e - a*f)*Sqrt[a + b*x])) - (2*(2*a^2*C*d*f + b^2*(c*C*e + A*d*f) - a*b*(C*d*e + c*C*f + B*d*f))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(b^2*Sqrt[d]*Sqrt[(-b)*c + a*d]*f*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) - (2*(a*C*(d*e - c*f) - b*(c*C*e - B*c*f + A*d*f))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(b^2*Sqrt[d]*Sqrt[(-b)*c + a*d]*f*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x + C*x^2)/((a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 8, -((2*(A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(3/2))) + (2*(2*a^3*C*d*f + a*b^2*(6*c*C*e + B*d*e + B*c*f - 4*A*d*f) - b^3*(3*B*c*e - 2*A*(d*e + c*f)) + a^2*b*(B*d*f - 4*C*(d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(3*b*(b*c - a*d)^2*(b*e - a*f)^2*Sqrt[a + b*x]) - (2*Sqrt[d]*(2*a^3*C*d*f + a*b^2*(6*c*C*e + B*d*e + B*c*f - 4*A*d*f) - b^3*(3*B*c*e - 2*A*(d*e + c*f)) + a^2*b*(B*d*f - 4*C*(d*e + c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^2*((-b)*c + a*d)^(3/2)*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) - (2*(a^2*C*d*(d*e - c*f) - b^2*(3*c^2*C*e - 3*B*c*d*e + 2*A*d^2*e + A*c*d*f) + a*b*(3*(c^2*C + A*d^2)*f - B*d*(d*e + 2*c*f)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(3*b^2*Sqrt[d]*((-b)*c + a*d)^(3/2)*(b*e - a*f)*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x + C*x^2)/((a + b*x)^(7/2)*Sqrt[c + d*x]*Sqrt[e + f*x]), x, 9, -((2*(A*b^2 - a*(b*B - a*C))*Sqrt[c + d*x]*Sqrt[e + f*x])/(5*b*(b*c - a*d)*(b*e - a*f)*(a + b*x)^(5/2))) + (2*(2*a^3*C*d*f + a*b^2*(10*c*C*e + B*d*e + B*c*f - 8*A*d*f) - b^3*(5*B*c*e - 4*A*(d*e + c*f)) + 3*a^2*b*(B*d*f - 2*C*(d*e + c*f)))*Sqrt[c + d*x]*Sqrt[e + f*x])/(15*b*(b*c - a*d)^2*(b*e - a*f)^2*(a + b*x)^(3/2)) + (1/(15*b*(b*c - a*d)^3*(b*e - a*f)^3*Sqrt[a + b*x]))*(2*(2*a^4*C*d^2*f^2 + a^3*b*d*f*(3*B*d*f - 7*C*(d*e + c*f)) - b^4*(8*A*d^2*e^2 - c*d*e*(10*B*e - 7*A*f) + c^2*(15*C*e^2 - 10*B*e*f + 8*A*f^2)) - a*b^3*(d^2*e*(2*B*e - 23*A*f) - 2*c^2*f*(5*C*e - B*f) - c*d*(10*C*e^2 - 33*B*e*f + 23*A*f^2)) - a^2*b^2*(C*(3*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) + d*f*(23*A*d*f - 7*B*(d*e + c*f))))*Sqrt[c + d*x]*Sqrt[e + f*x]) + (2*Sqrt[d]*(2*a^4*C*d^2*f^2 + a^3*b*d*f*(3*B*d*f - 7*C*(d*e + c*f)) - b^4*(8*A*d^2*e^2 - c*d*e*(10*B*e - 7*A*f) + c^2*(15*C*e^2 - 10*B*e*f + 8*A*f^2)) - a*b^3*(d^2*e*(2*B*e - 23*A*f) - 2*c^2*f*(5*C*e - B*f) - c*d*(10*C*e^2 - 33*B*e*f + 23*A*f^2)) - a^2*b^2*(C*(3*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) + d*f*(23*A*d*f - 7*B*(d*e + c*f))))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[e + f*x]*EllipticE[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])/(15*b^2*((-b)*c + a*d)^(5/2)*(b*e - a*f)^3*Sqrt[c + d*x]*Sqrt[(b*(e + f*x))/(b*e - a*f)]) + (1/(15*b^2*((-b)*c + a*d)^(5/2)*(b*e - a*f)^2*Sqrt[c + d*x]*Sqrt[e + f*x]))*(2*Sqrt[d]*(a^3*C*d*f*(d*e - c*f) + b^3*(8*A*d^2*e^2 - c*d*e*(10*B*e - 3*A*f) + c^2*(15*C*e^2 - 5*B*e*f + 4*A*f^2)) + a*b^2*(d^2*e*(2*B*e - 19*A*f) - c^2*f*(20*C*e - B*f) - c*d*(10*C*e^2 - 27*B*e*f + 11*A*f^2)) - 3*a^2*b*(d*f*(2*B*d*e + 3*B*c*f - 5*A*d*f) - C*(d^2*e^2 + c*d*e*f + 3*c^2*f^2)))*Sqrt[(b*(c + d*x))/(b*c - a*d)]*Sqrt[(b*(e + f*x))/(b*e - a*f)]*EllipticF[ArcSin[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[(-b)*c + a*d]], ((b*c - a*d)*f)/(d*(b*e - a*f))])}
