(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form P2[x] (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (A+B x) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


(* {(a + b*x)^3*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 10, (1/(105*d^3*f^3*h^3))*(2*b*(5*d*f*h*(7*a*(2*A*b + a*B)*d*f*h - b*B*(5*b*(d*e*g + c*f*g + c*e*h) + 2*a*(d*f*g + d*e*h + c*f*h))) + 2*(a*d*f*h - 2*b*(d*f*g + d*e*h + c*f*h))*(11*a*B*d*f*h + b*(7*A*d*f*h - 6*B*(d*f*g + d*e*h + c*f*h))))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]) + (2*b*(11*a*B*d*f*h + b*(7*A*d*f*h - 6*B*(d*f*g + d*e*h + c*f*h)))*(a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(35*d^2*f^2*h^2) + (2*b*B*(a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(7*d*f*h) - (1/(105*d^4*f^(7/2)*h^4*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]))*(2*Sqrt[(-d)*e + c*f]*(2*b*(d*f*g + d*e*h + c*f*h)*(5*d*f*h*(7*a*(2*A*b + a*B)*d*f*h - b*B*(5*b*(d*e*g + c*f*g + c*e*h) + 2*a*(d*f*g + d*e*h + c*f*h))) + 2*(a*d*f*h - 2*b*(d*f*g + d*e*h + c*f*h))*(11*a*B*d*f*h + b*(7*A*d*f*h - 6*B*(d*f*g + d*e*h + c*f*h)))) + 3*d*f*h*(b*(3*b*(d*e*g + c*f*g + c*e*h) + 2*a*(d*f*g + d*e*h + c*f*h))*(11*a*B*d*f*h + b*(7*A*d*f*h - 6*B*(d*f*g + d*e*h + c*f*h))) + 5*d*f*h*(4*b^3*B*c*e*g - 7*a^3*B*d*f*h + 6*a*b^2*B*(d*e*g + c*f*g + c*e*h) - a^2*b*(21*A*d*f*h - 2*B*(d*f*g + d*e*h + c*f*h)))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))]) - (1/(105*d^4*f^(7/2)*h^4*Sqrt[e + f*x]*Sqrt[g + h*x]))*(2*Sqrt[(-d)*e + c*f]*(105*a^3*d^3*f^3*h^3*(B*g - A*h) + 105*a^2*b*d^2*f^2*h^2*(3*A*d*f*g*h - B*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))) - 21*a*b^2*d*f*h*(5*A*d*f*h*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h)) - B*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2))) + b^3*(7*A*d*f*h*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2)) - B*(24*c^3*f^2*h^3*(f*g - e*h) + c^2*d*f*h^2*(17*f^2*g^2 + 6*e*f*g*h - 23*e^2*h^2) + 2*c*d^2*h*(8*f^3*g^3 + e*f^2*g^2*h + 3*e^2*f*g*h^2 - 12*e^3*h^3) + d^3*g*(48*f^3*g^3 + 16*e*f^2*g^2*h + 17*e^2*f*g*h^2 + 24*e^3*h^3))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])} *)
{(a + b*x)^2*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (2*b*(7*a*B*d*f*h + b*(5*A*d*f*h - 4*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(15*d^2*f^2*h^2) + (2*b*B*(a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(5*d*f*h) + (1/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]))*(2*Sqrt[(-d)*e + c*f]*(15*a^2*B*d^2*f^2*h^2 + 10*a*b*d*f*h*(3*A*d*f*h - 2*B*(d*f*g + d*e*h + c*f*h)) - b^2*(10*A*d*f*h*(d*f*g + d*e*h + c*f*h) - B*(8*c^2*f^2*h^2 + 7*c*d*f*h*(f*g + e*h) + d^2*(8*f^2*g^2 + 7*e*f*g*h + 8*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))]) - (1/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[g + h*x]))*(2*Sqrt[(-d)*e + c*f]*(15*a^2*d^2*f^2*h^2*(B*g - A*h) + 10*a*b*d*f*h*(3*A*d*f*g*h - B*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))) - b^2*(5*A*d*f*h*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h)) - B*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])}
{(a + b*x)^1*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (2*b*B*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*d*f*h) + (2*Sqrt[(-d)*e + c*f]*(3*a*B*d*f*h + b*(3*A*d*f*h - 2*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*Sqrt[(-d)*e + c*f]*(3*a*d*f*h*(B*g - A*h) + b*(3*A*d*f*g*h - B*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(a + b*x)^0*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 6, (2*B*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*Sqrt[(-d)*e + c*f]*(B*g - A*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(A + B*x)/((a + b*x)^1*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (2*B*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*d*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*(A - (a*B)/b)*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(A + B*x)/((a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 12, -((b*(A*b - a*B)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x))) + ((A*b - a*B)*Sqrt[f]*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - ((A*b - a*B)*Sqrt[f]*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*(b*c - a*d)*(b*e - a*f)*Sqrt[e + f*x]*Sqrt[g + h*x]) + (Sqrt[(-d)*e + c*f]*(3*a^2*A*b*d*f*h - a^3*B*d*f*h - b^3*(2*B*c*e*g - A*(d*e*g + c*f*g + c*e*h)) + a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 2*A*(d*f*g + d*e*h + c*f*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*(b*c - a*d)^2*Sqrt[f]*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[g + h*x])}
(* {(A + B*x)/((a + b*x)^3*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 13, -((b*(A*b - a*B)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(2*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^2)) - (b*(5*a^3*B*d*f*h + b^3*(4*B*c*e*g - 3*A*(d*e*g + c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 6*A*(d*f*g + d*e*h + c*f*h)) - a^2*b*(9*A*d*f*h + 2*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(4*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*(a + b*x)) + (Sqrt[f]*Sqrt[(-d)*e + c*f]*(5*a^3*B*d*f*h + b^3*(4*B*c*e*g - 3*A*(d*e*g + c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 6*A*(d*f*g + d*e*h + c*f*h)) - a^2*b*(9*A*d*f*h + 2*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(4*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (Sqrt[f]*Sqrt[(-d)*e + c*f]*(3*a^3*B*d*f*h - a^2*b*d*f*(2*B*g + 7*A*h) + b^3*(4*B*c*e*g - A*(3*d*e*g + 3*c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + 3*c*e*h) - 2*A*(3*d*f*g + 2*d*e*h + 2*c*f*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(4*b*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[g + h*x]) - (Sqrt[(-d)*e + c*f]*(15*a^4*A*b*d^2*f^2*h^2 - 3*a^5*B*d^2*f^2*h^2 + 10*a^3*b^2*d*f*h*(B*(d*e*g + c*f*g + c*e*h) - 2*A*(d*f*g + d*e*h + c*f*h)) + a*b^4*(B*(d^2*e^2*g^2 + 14*c*d*e*g*(f*g + e*h) + c^2*(f^2*g^2 + 14*e*f*g*h + e^2*h^2)) - 4*A*(2*d^2*e*g*(f*g + e*h) + 2*c^2*f*h*(f*g + e*h) + c*d*(2*f^2*g^2 + 3*e*f*g*h + 2*e^2*h^2))) - b^5*(4*B*c*e*g*(d*e*g + c*f*g + c*e*h) - A*(3*d^2*e^2*g^2 + 2*c*d*e*g*(f*g + e*h) + c^2*(3*f^2*g^2 + 2*e*f*g*h + 3*e^2*h^2))) - 2*a^2*b^3*(2*B*(d^2*e*g*(f*g + e*h) + c^2*f*h*(f*g + e*h) + c*d*(f^2*g^2 + 9*e*f*g*h + e^2*h^2)) - A*(4*c^2*f^2*h^2 + 11*c*d*f*h*(f*g + e*h) + d^2*(4*f^2*g^2 + 11*e*f*g*h + 4*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(4*b*(b*c - a*d)^3*Sqrt[f]*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[e + f*x]*Sqrt[g + h*x])} *)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (A+B x) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(a + b*x)^(3/2)*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 10, ((5*a*B*d*f*h + b*(4*A*d*f*h - 3*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(4*d*f^2*h^2*Sqrt[c + d*x]) + (b*B*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(2*d*f*h) - (Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(5*a*B*d*f*h + b*(4*A*d*f*h - 3*B*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(4*d^2*f^2*h^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - ((b*e - a*f)*Sqrt[b*g - a*h]*(3*a*B*d*f*h + b*(4*A*d*f*h - B*(c*f*h + 3*d*(f*g + e*h))))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(4*b*d*f^2*h^2*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (Sqrt[(-d)*g + c*h]*(4*d*f*h*(2*a*(2*A*b + a*B)*d*f*h - b*B*(b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))) - (a*d*f*h + b*(d*f*g + d*e*h + c*f*h))*(5*a*B*d*f*h + b*(4*A*d*f*h - 3*B*(d*f*g + d*e*h + c*f*h))))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(4*b*d^2*Sqrt[b*c - a*d]*f^2*h^3*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(a + b*x)^(1/2)*(A + B*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (B*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(f*h*Sqrt[c + d*x]) - (B*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(d*f*h*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (B*(b*e - a*f)*Sqrt[b*g - a*h]*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(b*f*h*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (Sqrt[(-d)*g + c*h]*(2*A*b*d*f*h + B*(a*d*f*h - b*(d*f*g + d*e*h + c*f*h)))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(b*d*Sqrt[b*c - a*d]*f*h^2*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x)/((a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 5, (2*(A*b - a*B)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(b*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (2*B*Sqrt[(-d)*g + c*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(b*Sqrt[b*c - a*d]*h*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + B*x)/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*(A*b - a*B)*d*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[c + d*x]) - (2*b*(A*b - a*B)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[a + b*x]) - (2*(A*b - a*B)*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + (2*(B*c - A*d)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/((b*c - a*d)*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}
{(A + B*x)/((a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (2*d*(3*a^3*B*d*f*h + b^3*(3*B*c*e*g - 2*A*(d*e*g + c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 4*A*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*A*d*f*h + B*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[c + d*x]) - (2*b*(A*b - a*B)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^(3/2)) - (2*b*(3*a^3*B*d*f*h + b^3*(3*B*c*e*g - 2*A*(d*e*g + c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 4*A*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*A*d*f*h + B*(d*f*g + d*e*h + c*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[a + b*x]) - (2*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(3*a^3*B*d*f*h + b^3*(3*B*c*e*g - 2*A*(d*e*g + c*f*g + c*e*h)) - a*b^2*(B*(d*e*g + c*f*g + c*e*h) - 4*A*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*A*d*f*h + B*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (2*(3*a^2*d*(B*c - A*d)*f*h + b^2*(3*B*c*d*e*g - A*(2*d^2*e*g - c^2*f*h + c*d*(f*g + e*h))) + a*b*(3*A*d^2*(f*g + e*h) - B*(d^2*e*g + c^2*f*h + 2*c*d*(f*g + e*h))))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(3*(b*c - a*d)^2*(b*e - a*f)*(b*g - a*h)^(3/2)*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}


{(a + b*x)^(3/2)*(d*e + c*f + 2*d*f*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 10, ((5*a*d*f*h - b*(3*d*f*g + d*e*h + c*f*h))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(2*f*h^2*Sqrt[c + d*x]) + (b*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/h - (Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(5*a*d*f*h - b*(3*d*f*g + d*e*h + c*f*h))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(2*d*f*h^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - ((b*e - a*f)*Sqrt[b*g - a*h]*(3*a*d*f*h + b*(c*f*h - d*(3*f*g + e*h)))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(2*b*f*h^2*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (1/(2*b*d*Sqrt[b*c - a*d]*f*h^3*Sqrt[c + d*x]*Sqrt[e + f*x]))*(Sqrt[(-d)*g + c*h]*(6*a*b*d^2*f^2*g*h - 3*a^2*d^2*f^2*h^2 + b^2*(2*c*d*e*f*h^2 - c^2*f^2*h^2 - d^2*(3*f^2*g^2 + e^2*h^2)))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])}
{(a + b*x)^(1/2)*(d*e + c*f + 2*d*f*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 5, (2*b*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(h*Sqrt[a + b*x]) - (2*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*EllipticE[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(h*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]) - (2*d*(b*g - a*h)^(3/2)*Sqrt[((f*g - e*h)*(a + b*x))/((b*g - a*h)*(e + f*x))]*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*(e + f*x)*EllipticPi[(f*(b*g - a*h))/((b*e - a*f)*h), ArcSin[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[b*g - a*h]*Sqrt[e + f*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(Sqrt[b*e - a*f]*h^2*Sqrt[a + b*x]*Sqrt[c + d*x])}
{(d*e + c*f + 2*d*f*x)/((a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 5, (2*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(b*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (4*d*f*Sqrt[(-d)*g + c*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(b*Sqrt[b*c - a*d]*h*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(d*e + c*f + 2*d*f*x)/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*d*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[c + d*x]) - (2*b*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[a + b*x]) - (2*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (2*d*(d*e - c*f)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/((b*c - a*d)*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}
{(d*e + c*f + 2*d*f*x)/((a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (4*d*(3*a^3*d^2*f^2*h - a^2*b*d*f*(d*f*g + 4*d*e*h + 4*c*f*h) - b^3*(d^2*e^2*g - c*d*e*(f*g - e*h) + c^2*f*(f*g + e*h)) + a*b^2*(2*c^2*f^2*h + d^2*e*(f*g + 2*e*h) + c*d*f*(f*g + 3*e*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[c + d*x]) - (2*b*(b*d*e + b*c*f - 2*a*d*f)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^(3/2)) - (4*b*(3*a^3*d^2*f^2*h - a^2*b*d*f*(d*f*g + 4*d*e*h + 4*c*f*h) - b^3*(d^2*e^2*g - c*d*e*(f*g - e*h) + c^2*f*(f*g + e*h)) + a*b^2*(2*c^2*f^2*h + d^2*e*(f*g + 2*e*h) + c*d*f*(f*g + 3*e*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[a + b*x]) - (4*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(3*a^3*d^2*f^2*h - a^2*b*d*f*(d*f*g + 4*d*e*h + 4*c*f*h) - b^3*(d^2*e^2*g - c*d*e*(f*g - e*h) + c^2*f*(f*g + e*h)) + a*b^2*(2*c^2*f^2*h + d^2*e*(f*g + 2*e*h) + c*d*f*(f*g + 3*e*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + (2*(d*e - c*f)*(3*a^2*d^2*f*h - a*b*d*(d*f*g + 3*d*e*h + 2*c*f*h) + b^2*(2*d^2*e*g - c*d*f*g + c*d*e*h + c^2*f*h))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(3*(b*c - a*d)^2*(b*e - a*f)*(b*g - a*h)^(3/2)*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}


(* ::Title:: *)
(*Integrands of the form P3[x] (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (e+f x)^(p/2) (g+h x)^(q/2) (A+B x+C x^2) with A b^2-a b B+a^2 C=0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (A+B x+C x^2) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(a + b*x)^1*(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (2*b^2*(5*b*B*d*f*h + 2*C*(a*d*f*h - 2*b*(d*f*g + d*e*h + c*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(15*d^2*f^2*h^2) + (2*b^2*C*(a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(5*d*f*h) - (1/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]))*(2*b*Sqrt[(-d)*e + c*f]*(15*a^2*C*d^2*f^2*h^2 - 10*a*b*d*f*h*(3*B*d*f*h - C*(d*f*g + d*e*h + c*f*h)) + b^2*(10*B*d*f*h*(d*f*g + d*e*h + c*f*h) - C*(8*c^2*f^2*h^2 + 7*c*d*f*h*(f*g + e*h) + d^2*(8*f^2*g^2 + 7*e*f*g*h + 8*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))]) - (1/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[g + h*x]))*(2*Sqrt[(-d)*e + c*f]*(15*a^3*C*d^2*f^2*h^3 - 15*a^2*b*d^2*f^2*h^2*(C*g + B*h) + 5*a*b^2*d*f*h*(6*B*d*f*g*h - C*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))) - b^3*(5*B*d*f*h*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h)) - C*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])}
{(a + b*x)^0*(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*b^2*C*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*d*f*h) + (2*b^2*Sqrt[(-d)*e + c*f]*(3*B*d*f*h - 2*C*(d*f*g + d*e*h + c*f*h))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) + (2*Sqrt[(-d)*e + c*f]*(3*a*b*B*d*f*h^2 - 3*a^2*C*d*f*h^2 - b^2*(3*B*d*f*g*h - C*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^1*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*b*C*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*Sqrt[(-d)*e + c*f]*(b*C*g - b*B*h + a*C*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 10, (2*C*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(d*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*(b*B - 2*a*C)*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^3*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 13, -((b^2*(b*B - 2*a*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x))) + (b*(b*B - 2*a*C)*Sqrt[f]*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - ((b*B - 2*a*C)*Sqrt[f]*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*Sqrt[e + f*x]*Sqrt[g + h*x]) - (Sqrt[(-d)*e + c*f]*(4*a^3*C*d*f*h + 2*a*b^2*B*(d*f*g + d*e*h + c*f*h) - b^3*(B*d*e*g - c*(2*C*e*g - B*f*g - B*e*h)) - a^2*b*(3*B*d*f*h + 2*C*(d*f*g + d*e*h + c*f*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)^2*Sqrt[f]*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[g + h*x])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (A+B x+C x^2) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(a + b*x)^(1/2)*(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (b*(4*b*B*d*f*h + C*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(4*d*f^2*h^2*Sqrt[c + d*x]) + (b^2*C*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(2*d*f*h) - (b*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(4*b*B*d*f*h + C*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(4*d^2*f^2*h^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + ((b*e - a*f)*Sqrt[b*g - a*h]*(a*C*d*f*h - b*(4*B*d*f*h - C*(3*d*f*g + 3*d*e*h + c*f*h)))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(4*d*f^2*h^2*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (1/(4*d^2*Sqrt[b*c - a*d]*f^2*h^3*Sqrt[c + d*x]*Sqrt[e + f*x]))*(Sqrt[(-d)*g + c*h]*((a*d*f*h + b*(d*f*g + d*e*h + c*f*h))*(4*b*B*d*f*h + C*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))) + 4*d*f*h*(2*a^2*C*d*f*h + b^2*C*(d*e*g + c*f*g + c*e*h) - a*b*(4*B*d*f*h - C*(d*f*g + d*e*h + c*f*h))))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (b*C*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(f*h*Sqrt[c + d*x]) - (b*C*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(d*f*h*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (C*(b*e - a*f)*Sqrt[b*g - a*h]*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(f*h*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (Sqrt[(-d)*g + c*h]*(a*C*d*f*h - b*(2*B*d*f*h - C*(d*f*g + d*e*h + c*f*h)))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(d*Sqrt[b*c - a*d]*f*h^2*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 6, (2*(b*B - 2*a*C)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (2*C*Sqrt[(-d)*g + c*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(Sqrt[b*c - a*d]*h*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (2*b*(b*B - 2*a*C)*d*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[c + d*x]) - (2*b^2*(b*B - 2*a*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[a + b*x]) - (2*b*(b*B - 2*a*C)*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + (2*(b*c*C - b*B*d + a*C*d)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/((b*c - a*d)*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}
{(a*b*B - a^2*C + b^2*B*x + b^2*C*x^2)/((a + b*x)^(7/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (2*b*d*(9*a^3*C*d*f*h - b^3*(2*B*d*e*g - c*(3*C*e*g - 2*B*f*g - 2*B*e*h)) + a*b^2*(C*(d*e*g + c*f*g + c*e*h) + 4*B*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*B*d*f*h + 5*C*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[c + d*x]) - (2*b^2*(b*B - 2*a*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^(3/2)) - (2*b^2*(9*a^3*C*d*f*h - b^3*(2*B*d*e*g - c*(3*C*e*g - 2*B*f*g - 2*B*e*h)) + a*b^2*(C*(d*e*g + c*f*g + c*e*h) + 4*B*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*B*d*f*h + 5*C*(d*f*g + d*e*h + c*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[a + b*x]) - (2*b*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(9*a^3*C*d*f*h - b^3*(2*B*d*e*g - c*(3*C*e*g - 2*B*f*g - 2*B*e*h)) + a*b^2*(C*(d*e*g + c*f*g + c*e*h) + 4*B*(d*f*g + d*e*h + c*f*h)) - a^2*b*(6*B*d*f*h + 5*C*(d*f*g + d*e*h + c*f*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (2*(3*a^3*C*d^2*f*h - b^3*(2*B*d^2*e*g - B*c^2*f*h - c*d*(3*C*e*g - B*f*g - B*e*h)) - 3*a^2*b*d*(B*d*f*h + C*(d*f*g + d*e*h - c*f*h)) + a*b^2*(3*B*d^2*(f*g + e*h) + C*(d^2*e*g - c*d*f*g - c*d*e*h - 2*c^2*f*h)))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(3*(b*c - a*d)^2*(b*e - a*f)*(b*g - a*h)^(3/2)*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (e+f x)^(p/2) (g+h x)^(q/2) (A+B x+C x^2) with B=0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (A+B x+C x^2) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(a + b*x)^2*(A + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (2*(4*C*(2*a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))*(a*d*f*h - 2*b*(d*f*g + d*e*h + c*f*h)) + 5*b*d*f*h*(7*A*b*d*f*h - C*(5*b*(d*e*g + c*f*g + c*e*h) + 2*a*(d*f*g + d*e*h + c*f*h))))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(105*d^3*f^3*h^3) + (4*C*(2*a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))*(a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(35*d^2*f^2*h^2) + (2*C*(a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(7*d*f*h) - (1/(105*d^4*f^(7/2)*h^4*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]))*(4*Sqrt[(-d)*e + c*f]*(35*a^2*C*d^2*f^2*h^2*(d*f*g + d*e*h + c*f*h) - 7*a*b*d*f*h*(15*A*d^2*f^2*h^2 + C*(8*c^2*f^2*h^2 + 7*c*d*f*h*(f*g + e*h) + d^2*(8*f^2*g^2 + 7*e*f*g*h + 8*e^2*h^2))) + b^2*(35*A*d^2*f^2*h^2*(d*f*g + d*e*h + c*f*h) + 2*C*(12*c^3*f^3*h^3 + 10*c^2*d*f^2*h^2*(f*g + e*h) + c*d^2*f*h*(10*f^2*g^2 + 9*e*f*g*h + 10*e^2*h^2) + 2*d^3*(6*f^3*g^3 + 5*e*f^2*g^2*h + 5*e^2*f*g*h^2 + 6*e^3*h^3))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))]) + (1/(105*d^4*f^(7/2)*h^4*Sqrt[e + f*x]*Sqrt[g + h*x]))*(2*Sqrt[(-d)*e + c*f]*(35*a^2*d^2*f^2*h^2*(3*A*d*f*h^2 + C*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))) - 14*a*b*d*f*h*(15*A*d^2*f^2*g*h^2 + C*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2))) + b^2*(35*A*d^2*f^2*h^2*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h)) + C*(24*c^3*f^2*h^3*(f*g - e*h) + c^2*d*f*h^2*(17*f^2*g^2 + 6*e*f*g*h - 23*e^2*h^2) + 2*c*d^2*h*(8*f^3*g^3 + e*f^2*g^2*h + 3*e^2*f*g*h^2 - 12*e^3*h^3) + d^3*g*(48*f^3*g^3 + 16*e*f^2*g^2*h + 17*e^2*f*g*h^2 + 24*e^3*h^3))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])}
{(a + b*x)^1*(A + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (4*C*(a*d*f*h - 2*b*(d*f*g + d*e*h + c*f*h))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(15*d^2*f^2*h^2) + (2*C*(a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(5*d*f*h) - (2*Sqrt[(-d)*e + c*f]*(10*a*C*d*f*h*(d*f*g + d*e*h + c*f*h) - b*(15*A*d^2*f^2*h^2 + C*(8*c^2*f^2*h^2 + 7*c*d*f*h*(f*g + e*h) + d^2*(8*f^2*g^2 + 7*e*f*g*h + 8*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) + (1/(15*d^3*f^(5/2)*h^3*Sqrt[e + f*x]*Sqrt[g + h*x]))*(2*Sqrt[(-d)*e + c*f]*(5*a*d*f*h*(3*A*d*f*h^2 + C*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h))) - b*(15*A*d^2*f^2*g*h^2 + C*(4*c^2*f*h^2*(f*g - e*h) + c*d*h*(3*f^2*g^2 + e*f*g*h - 4*e^2*h^2) + d^2*g*(8*f^2*g^2 + 3*e*f*g*h + 4*e^2*h^2))))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])}
{(a + b*x)^0*(A + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*C*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*d*f*h) - (4*C*Sqrt[(-d)*e + c*f]*(d*f*g + d*e*h + c*f*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) + (2*Sqrt[(-d)*e + c*f]*(3*A*d*f*h^2 + C*(c*h*(f*g - e*h) + d*g*(2*f*g + e*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*d^2*f^(3/2)*h^2*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(A + C*x^2)/((a + b*x)^1*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 11, (2*C*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*C*Sqrt[(-d)*e + c*f]*(b*g + a*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b^2*d*Sqrt[f]*h*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*(A + (a^2*C)/b^2)*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(A + C*x^2)/((a + b*x)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 12, -(((A*b^2 + a^2*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x))) + ((A*b + (a^2*C)/b)*Sqrt[f]*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) + (Sqrt[(-d)*e + c*f]*(a^2*C*d*f - 2*a*b*C*(d*e + c*f) + b^2*(2*c*C*e - A*d*f))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b^2*d*(b*c - a*d)*Sqrt[f]*(b*e - a*f)*Sqrt[e + f*x]*Sqrt[g + h*x]) - (1/(b^2*(b*c - a*d)^2*Sqrt[f]*(b*e - a*f)*(b*g - a*h)*Sqrt[e + f*x]*Sqrt[g + h*x]))*(Sqrt[(-d)*e + c*f]*(a^4*C*d*f*h - A*b^4*(d*e*g + c*f*g + c*e*h) - 2*a^3*b*C*(d*f*g + d*e*h + c*f*h) - 2*a*b^3*(2*c*C*e*g - A*d*f*g - A*d*e*h - A*c*f*h) - 3*a^2*b^2*(A*d*f*h - C*(d*e*g + c*f*g + c*e*h)))*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (A+B x+C x^2) / (Sqrte+f x] Sqrt[g+h x])*)


(* ::Subsubsection:: *)
(*n>0*)


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(a + b*x)^(3/2)*(A + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 10, ((C*(3*a*d*f*h - 5*b*(d*f*g + d*e*h + c*f*h))*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h)) + 8*b*d*f*h*(3*A*b*d*f*h - C*(2*b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(24*b*d^2*f^3*h^3*Sqrt[c + d*x]) + (C*(3*a*d*f*h - 5*b*(d*f*g + d*e*h + c*f*h))*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(12*d^2*f^2*h^2) + (C*(a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*d*f*h) - (Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(C*(3*a*d*f*h - 5*b*(d*f*g + d*e*h + c*f*h))*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h)) + 8*b*d*f*h*(3*A*b*d*f*h - C*(2*b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(24*b*d^3*f^3*h^3*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + ((b*e - a*f)*Sqrt[b*g - a*h]*(3*a^2*C*d^2*f^2*h^2 + 6*a*b*C*d*f*h*(c*f*h + 2*d*(f*g + e*h)) - b^2*(24*A*d^2*f^2*h^2 + C*(5*c^2*f^2*h^2 + 4*c*d*f*h*(f*g + e*h) + d^2*(15*f^2*g^2 + 14*e*f*g*h + 15*e^2*h^2))))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(24*b^2*d^2*f^3*h^3*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (1/(24*b^2*d^3*Sqrt[b*c - a*d]*f^3*h^4*Sqrt[c + d*x]*Sqrt[e + f*x]))*(Sqrt[(-d)*g + c*h]*(4*b*d*f*h*(C*(b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))*(3*a*d*f*h - 5*b*(d*f*g + d*e*h + c*f*h)) + 2*d*f*h*(3*b^2*c*C*e*g + 2*a^2*C*(d*f*g + d*e*h + c*f*h) - a*b*(12*A*d*f*h - 5*C*(d*e*g + c*f*g + c*e*h)))) + (a*d*f*h + b*(d*f*g + d*e*h + c*f*h))*(C*(3*a*d*f*h - 5*b*(d*f*g + d*e*h + c*f*h))*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h)) + 8*b*d*f*h*(3*A*b*d*f*h - C*(2*b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h)))))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])}
{(a + b*x)^(1/2)*(A + C*x^2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (C*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(4*b*d*f^2*h^2*Sqrt[c + d*x]) + (C*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(2*d*f*h) - (C*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(4*b*d^2*f^2*h^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + (C*(b*e - a*f)*Sqrt[b*g - a*h]*(a*d*f*h + b*(c*f*h + 3*d*(f*g + e*h)))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(4*b^2*d*f^2*h^2*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (Sqrt[(-d)*g + c*h]*(C*(a*d*f*h - 3*b*(d*f*g + d*e*h + c*f*h))*(a*d*f*h + b*(d*f*g + d*e*h + c*f*h)) - 4*b*d*f*h*(2*A*b*d*f*h - C*(b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(4*b^2*d^2*Sqrt[b*c - a*d]*f^2*h^3*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + C*x^2)/((a + b*x)^(1/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, (C*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(b*f*h*Sqrt[c + d*x]) - (C*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(b*d*f*h*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) + ((a^2*C*f*h + a*b*C*(f*g + e*h) - b^2*(C*e*g - 2*A*f*h))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(b^2*f*h*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) - (C*Sqrt[(-d)*g + c*h]*(a*d*f*h + b*(d*f*g + d*e*h + c*f*h))*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(b^2*d*Sqrt[b*c - a*d]*f*h^2*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + C*x^2)/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 9, (2*(A*b^2 + a^2*C)*d*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(b*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[c + d*x]) - (2*(A*b^2 + a^2*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[a + b*x]) - (2*(A*b^2 + a^2*C)*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(b*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (2*(2*a*b*c*C + A*b^2*d - a^2*C*d)*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(b^2*(b*c - a*d)*Sqrt[b*g - a*h]*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]) + (2*C*Sqrt[(-d)*g + c*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*EllipticPi[-((b*(d*g - c*h))/((b*c - a*d)*h)), ArcSin[(Sqrt[b*c - a*d]*Sqrt[g + h*x])/(Sqrt[(-d)*g + c*h]*Sqrt[a + b*x])], ((b*e - a*f)*(d*g - c*h))/((b*c - a*d)*(f*g - e*h))])/(b^2*Sqrt[b*c - a*d]*h*Sqrt[c + d*x]*Sqrt[e + f*x])}
{(A + C*x^2)/((a + b*x)^(5/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, -((4*d*(A*b^3*(d*e*g + c*f*g + c*e*h) + a^3*C*(d*f*g + d*e*h + c*f*h) + a^2*b*(3*A*d*f*h - 2*C*(d*e*g + c*f*g + c*e*h)) - a*b^2*(2*A*d*(f*g + e*h) - c*(3*C*e*g - 2*A*f*h)))*Sqrt[a + b*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[c + d*x])) - (2*(A*b^2 + a^2*C)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^(3/2)) + (4*b*(A*b^3*(d*e*g + c*f*g + c*e*h) + a^3*C*(d*f*g + d*e*h + c*f*h) + a^2*b*(3*A*d*f*h - 2*C*(d*e*g + c*f*g + c*e*h)) - a*b^2*(2*A*d*(f*g + e*h) - c*(3*C*e*g - 2*A*f*h)))*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[a + b*x]) + (4*Sqrt[d*g - c*h]*Sqrt[f*g - e*h]*(A*b^3*(d*e*g + c*f*g + c*e*h) + a^3*C*(d*f*g + d*e*h + c*f*h) + a^2*b*(3*A*d*f*h - 2*C*(d*e*g + c*f*g + c*e*h)) - a*b^2*(2*A*d*(f*g + e*h) - c*(3*C*e*g - 2*A*f*h)))*Sqrt[a + b*x]*Sqrt[-(((d*e - c*f)*(g + h*x))/((f*g - e*h)*(c + d*x)))]*EllipticE[ArcSin[(Sqrt[d*g - c*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[c + d*x])], ((b*c - a*d)*(f*g - e*h))/((b*e - a*f)*(d*g - c*h))])/(3*(b*c - a*d)^2*(b*e - a*f)^2*(b*g - a*h)^2*Sqrt[((d*e - c*f)*(a + b*x))/((b*e - a*f)*(c + d*x))]*Sqrt[g + h*x]) - (2*(3*a*b*(c^2*C + A*d^2)*(f*g + e*h) - b^2*(2*A*d^2*e*g + A*c*d*(f*g + e*h) + c^2*(3*C*e*g - A*f*h)) - a^2*(3*A*d^2*f*h - C*(d^2*e*g - c*d*f*g - c*d*e*h - 2*c^2*f*h)))*Sqrt[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Sqrt[g + h*x]*EllipticF[ArcSin[(Sqrt[b*g - a*h]*Sqrt[e + f*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], -(((b*c - a*d)*(f*g - e*h))/((d*e - c*f)*(b*g - a*h)))])/(3*(b*c - a*d)^2*(b*e - a*f)*(b*g - a*h)^(3/2)*Sqrt[f*g - e*h]*Sqrt[c + d*x]*Sqrt[-(((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))])}
