(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (e x)^m (a+b x^n)^p Cosh[c+d x]*)


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^1)^p Cosh[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x)*Cosh[c + d*x], x, 11, (-6*a*Cosh[c + d*x])/d^4 - (24*b*x*Cosh[c + d*x])/d^4 - (3*a*x^2*Cosh[c + d*x])/d^2 - (4*b*x^3*Cosh[c + d*x])/d^2 + (24*b*Sinh[c + d*x])/d^5 + (6*a*x*Sinh[c + d*x])/d^3 + (12*b*x^2*Sinh[c + d*x])/d^3 + (a*x^3*Sinh[c + d*x])/d + (b*x^4*Sinh[c + d*x])/d}
{x^2*(a + b*x)*Cosh[c + d*x], x, 9, (-6*b*Cosh[c + d*x])/d^4 - (2*a*x*Cosh[c + d*x])/d^2 - (3*b*x^2*Cosh[c + d*x])/d^2 + (2*a*Sinh[c + d*x])/d^3 + (6*b*x*Sinh[c + d*x])/d^3 + (a*x^2*Sinh[c + d*x])/d + (b*x^3*Sinh[c + d*x])/d}
{x*(a + b*x)*Cosh[c + d*x], x, 7, -((a*Cosh[c + d*x])/d^2) - (2*b*x*Cosh[c + d*x])/d^2 + (2*b*Sinh[c + d*x])/d^3 + (a*x*Sinh[c + d*x])/d + (b*x^2*Sinh[c + d*x])/d}
{(a + b*x)*Cosh[c + d*x], x, 2, -((b*Cosh[c + d*x])/d^2) + ((a + b*x)*Sinh[c + d*x])/d}
{((a + b*x)*Cosh[c + d*x])/x, x, 6, a*Cosh[c]*CoshIntegral[d*x] + (b*Sinh[c + d*x])/d + a*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x)*Cosh[c + d*x])/x^2, x, 9, -((a*Cosh[c + d*x])/x) + b*Cosh[c]*CoshIntegral[d*x] + a*d*CoshIntegral[d*x]*Sinh[c] + a*d*Cosh[c]*SinhIntegral[d*x] + b*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x)*Cosh[c + d*x])/x^3, x, 11, -(a*Cosh[c + d*x])/(2*x^2) - (b*Cosh[c + d*x])/x + (a*d^2*Cosh[c]*CoshIntegral[d*x])/2 + b*d*CoshIntegral[d*x]*Sinh[c] - (a*d*Sinh[c + d*x])/(2*x) + b*d*Cosh[c]*SinhIntegral[d*x] + (a*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x)*Cosh[c + d*x])/x^4, x, 13, -(a*Cosh[c + d*x])/(3*x^3) - (b*Cosh[c + d*x])/(2*x^2) - (a*d^2*Cosh[c + d*x])/(6*x) + (b*d^2*Cosh[c]*CoshIntegral[d*x])/2 + (a*d^3*CoshIntegral[d*x]*Sinh[c])/6 - (a*d*Sinh[c + d*x])/(6*x^2) - (b*d*Sinh[c + d*x])/(2*x) + (a*d^3*Cosh[c]*SinhIntegral[d*x])/6 + (b*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x)*Cosh[c + d*x])/x^5, x, 15, -(a*Cosh[c + d*x])/(4*x^4) - (b*Cosh[c + d*x])/(3*x^3) - (a*d^2*Cosh[c + d*x])/(24*x^2) - (b*d^2*Cosh[c + d*x])/(6*x) + (a*d^4*Cosh[c]*CoshIntegral[d*x])/24 + (b*d^3*CoshIntegral[d*x]*Sinh[c])/6 - (a*d*Sinh[c + d*x])/(12*x^3) - (b*d*Sinh[c + d*x])/(6*x^2) - (a*d^3*Sinh[c + d*x])/(24*x) + (b*d^3*Cosh[c]*SinhIntegral[d*x])/6 + (a*d^4*Sinh[c]*SinhIntegral[d*x])/24}


{x^2*(a + b*x)^2*Cosh[c + d*x], x, 14, (-12*a*b*Cosh[c + d*x])/d^4 - (24*b^2*x*Cosh[c + d*x])/d^4 - (2*a^2*x*Cosh[c + d*x])/d^2 - (6*a*b*x^2*Cosh[c + d*x])/d^2 - (4*b^2*x^3*Cosh[c + d*x])/d^2 + (24*b^2*Sinh[c + d*x])/d^5 + (2*a^2*Sinh[c + d*x])/d^3 + (12*a*b*x*Sinh[c + d*x])/d^3 + (12*b^2*x^2*Sinh[c + d*x])/d^3 + (a^2*x^2*Sinh[c + d*x])/d + (2*a*b*x^3*Sinh[c + d*x])/d + (b^2*x^4*Sinh[c + d*x])/d}
{x*(a + b*x)^2*Cosh[c + d*x], x, 11, (-6*b^2*Cosh[c + d*x])/d^4 - (a^2*Cosh[c + d*x])/d^2 - (4*a*b*x*Cosh[c + d*x])/d^2 - (3*b^2*x^2*Cosh[c + d*x])/d^2 + (4*a*b*Sinh[c + d*x])/d^3 + (6*b^2*x*Sinh[c + d*x])/d^3 + (a^2*x*Sinh[c + d*x])/d + (2*a*b*x^2*Sinh[c + d*x])/d + (b^2*x^3*Sinh[c + d*x])/d}
{(a + b*x)^2*Cosh[c + d*x], x, 3, (-2*b*(a + b*x)*Cosh[c + d*x])/d^2 + (2*b^2*Sinh[c + d*x])/d^3 + ((a + b*x)^2*Sinh[c + d*x])/d}
{((a + b*x)^2*Cosh[c + d*x])/x, x, 8, -((b^2*Cosh[c + d*x])/d^2) + a^2*Cosh[c]*CoshIntegral[d*x] + (2*a*b*Sinh[c + d*x])/d + (b^2*x*Sinh[c + d*x])/d + a^2*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x)^2*Cosh[c + d*x])/x^2, x, 10, -((a^2*Cosh[c + d*x])/x) + 2*a*b*Cosh[c]*CoshIntegral[d*x] + a^2*d*CoshIntegral[d*x]*Sinh[c] + (b^2*Sinh[c + d*x])/d + a^2*d*Cosh[c]*SinhIntegral[d*x] + 2*a*b*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x)^2*Cosh[c + d*x])/x^3, x, 14, -(a^2*Cosh[c + d*x])/(2*x^2) - (2*a*b*Cosh[c + d*x])/x + b^2*Cosh[c]*CoshIntegral[d*x] + (a^2*d^2*Cosh[c]*CoshIntegral[d*x])/2 + 2*a*b*d*CoshIntegral[d*x]*Sinh[c] - (a^2*d*Sinh[c + d*x])/(2*x) + 2*a*b*d*Cosh[c]*SinhIntegral[d*x] + b^2*Sinh[c]*SinhIntegral[d*x] + (a^2*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x)^2*Cosh[c + d*x])/x^4, x, 17, -(a^2*Cosh[c + d*x])/(3*x^3) - (a*b*Cosh[c + d*x])/x^2 - (b^2*Cosh[c + d*x])/x - (a^2*d^2*Cosh[c + d*x])/(6*x) + a*b*d^2*Cosh[c]*CoshIntegral[d*x] + b^2*d*CoshIntegral[d*x]*Sinh[c] + (a^2*d^3*CoshIntegral[d*x]*Sinh[c])/6 - (a^2*d*Sinh[c + d*x])/(6*x^2) - (a*b*d*Sinh[c + d*x])/x + b^2*d*Cosh[c]*SinhIntegral[d*x] + (a^2*d^3*Cosh[c]*SinhIntegral[d*x])/6 + a*b*d^2*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x)^2*Cosh[c + d*x])/x^5, x, 20, -(a^2*Cosh[c + d*x])/(4*x^4) - (2*a*b*Cosh[c + d*x])/(3*x^3) - (b^2*Cosh[c + d*x])/(2*x^2) - (a^2*d^2*Cosh[c + d*x])/(24*x^2) - (a*b*d^2*Cosh[c + d*x])/(3*x) + (b^2*d^2*Cosh[c]*CoshIntegral[d*x])/2 + (a^2*d^4*Cosh[c]*CoshIntegral[d*x])/24 + (a*b*d^3*CoshIntegral[d*x]*Sinh[c])/3 - (a^2*d*Sinh[c + d*x])/(12*x^3) - (a*b*d*Sinh[c + d*x])/(3*x^2) - (b^2*d*Sinh[c + d*x])/(2*x) - (a^2*d^3*Sinh[c + d*x])/(24*x) + (a*b*d^3*Cosh[c]*SinhIntegral[d*x])/3 + (b^2*d^2*Sinh[c]*SinhIntegral[d*x])/2 + (a^2*d^4*Sinh[c]*SinhIntegral[d*x])/24}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Cosh[c + d*x])/(a + b*x), x, 15, (-6*Cosh[c + d*x])/(b*d^4) - (a^2*Cosh[c + d*x])/(b^3*d^2) + (2*a*x*Cosh[c + d*x])/(b^2*d^2) - (3*x^2*Cosh[c + d*x])/(b*d^2) + (a^4*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^5 - (2*a*Sinh[c + d*x])/(b^2*d^3) - (a^3*Sinh[c + d*x])/(b^4*d) + (6*x*Sinh[c + d*x])/(b*d^3) + (a^2*x*Sinh[c + d*x])/(b^3*d) - (a*x^2*Sinh[c + d*x])/(b^2*d) + (x^3*Sinh[c + d*x])/(b*d) + (a^4*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^5}
{(x^3*Cosh[c + d*x])/(a + b*x), x, 11, (a*Cosh[c + d*x])/(b^2*d^2) - (2*x*Cosh[c + d*x])/(b*d^2) - (a^3*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^4 + (2*Sinh[c + d*x])/(b*d^3) + (a^2*Sinh[c + d*x])/(b^3*d) - (a*x*Sinh[c + d*x])/(b^2*d) + (x^2*Sinh[c + d*x])/(b*d) - (a^3*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^4}
{(x^2*Cosh[c + d*x])/(a + b*x), x, 8, -(Cosh[c + d*x]/(b*d^2)) + (a^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^3 - (a*Sinh[c + d*x])/(b^2*d) + (x*Sinh[c + d*x])/(b*d) + (a^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^3}
{(x*Cosh[c + d*x])/(a + b*x), x, 6, -((a*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^2) + Sinh[c + d*x]/(b*d) - (a*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^2}
{Cosh[c + d*x]/(a + b*x), x, 3, (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b + (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b}
{Cosh[c + d*x]/(x*(a + b*x)), x, 8, (Cosh[c]*CoshIntegral[d*x])/a - (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a + (Sinh[c]*SinhIntegral[d*x])/a - (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a}
{Cosh[c + d*x]/(x^2*(a + b*x)), x, 12, -(Cosh[c + d*x]/(a*x)) - (b*Cosh[c]*CoshIntegral[d*x])/a^2 + (b*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^2 + (d*CoshIntegral[d*x]*Sinh[c])/a + (d*Cosh[c]*SinhIntegral[d*x])/a - (b*Sinh[c]*SinhIntegral[d*x])/a^2 + (b*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^2}
{Cosh[c + d*x]/(x^3*(a + b*x)), x, 17, -Cosh[c + d*x]/(2*a*x^2) + (b*Cosh[c + d*x])/(a^2*x) + (b^2*Cosh[c]*CoshIntegral[d*x])/a^3 + (d^2*Cosh[c]*CoshIntegral[d*x])/(2*a) - (b^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^3 - (b*d*CoshIntegral[d*x]*Sinh[c])/a^2 - (d*Sinh[c + d*x])/(2*a*x) - (b*d*Cosh[c]*SinhIntegral[d*x])/a^2 + (b^2*Sinh[c]*SinhIntegral[d*x])/a^3 + (d^2*Sinh[c]*SinhIntegral[d*x])/(2*a) - (b^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^3}


{(x^4*Cosh[c + d*x])/(a + b*x)^2, x, 15, (2*a*Cosh[c + d*x])/(b^3*d^2) - (2*x*Cosh[c + d*x])/(b^2*d^2) - (a^4*Cosh[c + d*x])/(b^5*(a + b*x)) - (4*a^3*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^5 + (a^4*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^6 + (2*Sinh[c + d*x])/(b^2*d^3) + (3*a^2*Sinh[c + d*x])/(b^4*d) - (2*a*x*Sinh[c + d*x])/(b^3*d) + (x^2*Sinh[c + d*x])/(b^2*d) + (a^4*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^6 - (4*a^3*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^5}
{(x^3*Cosh[c + d*x])/(a + b*x)^2, x, 12, -(Cosh[c + d*x]/(b^2*d^2)) + (a^3*Cosh[c + d*x])/(b^4*(a + b*x)) + (3*a^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^4 - (a^3*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^5 - (2*a*Sinh[c + d*x])/(b^3*d) + (x*Sinh[c + d*x])/(b^2*d) - (a^3*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^5 + (3*a^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^4}
{(x^2*Cosh[c + d*x])/(a + b*x)^2, x, 10, -((a^2*Cosh[c + d*x])/(b^3*(a + b*x))) - (2*a*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^3 + (a^2*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^4 + Sinh[c + d*x]/(b^2*d) + (a^2*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^4 - (2*a*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^3}
{(x*Cosh[c + d*x])/(a + b*x)^2, x, 9, (a*Cosh[c + d*x])/(b^2*(a + b*x)) + (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^2 - (a*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^3 - (a*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^3 + (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^2}
{Cosh[c + d*x]/(a + b*x)^2, x, 4, -(Cosh[c + d*x]/(b*(a + b*x))) + (d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^2 + (d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^2}
{Cosh[c + d*x]/(x*(a + b*x)^2), x, 12, Cosh[c + d*x]/(a*(a + b*x)) + (Cosh[c]*CoshIntegral[d*x])/a^2 - (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^2 - (d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/(a*b) + (Sinh[c]*SinhIntegral[d*x])/a^2 - (d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(a*b) - (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^2}
{Cosh[c + d*x]/(x^2*(a + b*x)^2), x, 16, -(Cosh[c + d*x]/(a^2*x)) - (b*Cosh[c + d*x])/(a^2*(a + b*x)) - (2*b*Cosh[c]*CoshIntegral[d*x])/a^3 + (2*b*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^3 + (d*CoshIntegral[d*x]*Sinh[c])/a^2 + (d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/a^2 + (d*Cosh[c]*SinhIntegral[d*x])/a^2 - (2*b*Sinh[c]*SinhIntegral[d*x])/a^3 + (d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^2 + (2*b*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^3}


{(x^3*Cosh[c + d*x])/(a + b*x)^3, x, 15, (a^3*Cosh[c + d*x])/(2*b^4*(a + b*x)^2) - (3*a^2*Cosh[c + d*x])/(b^4*(a + b*x)) - (3*a*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^4 - (a^3*d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*b^6) + (3*a^2*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^5 + Sinh[c + d*x]/(b^3*d) + (a^3*d*Sinh[c + d*x])/(2*b^5*(a + b*x)) + (3*a^2*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^5 - (3*a*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^4 - (a^3*d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*b^6)}
{(x^2*Cosh[c + d*x])/(a + b*x)^3, x, 14, -(a^2*Cosh[c + d*x])/(2*b^3*(a + b*x)^2) + (2*a*Cosh[c + d*x])/(b^3*(a + b*x)) + (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/b^3 + (a^2*d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*b^5) - (2*a*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^4 - (a^2*d*Sinh[c + d*x])/(2*b^4*(a + b*x)) - (2*a*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^4 + (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^3 + (a^2*d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*b^5)}
{(x*Cosh[c + d*x])/(a + b*x)^3, x, 11, (a*Cosh[c + d*x])/(2*b^2*(a + b*x)^2) - Cosh[c + d*x]/(b^2*(a + b*x)) - (a*d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*b^4) + (d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/b^3 + (a*d*Sinh[c + d*x])/(2*b^3*(a + b*x)) + (d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/b^3 - (a*d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*b^4)}
{Cosh[c + d*x]/(a + b*x)^3, x, 5, -Cosh[c + d*x]/(2*b*(a + b*x)^2) + (d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*b^3) - (d*Sinh[c + d*x])/(2*b^2*(a + b*x)) + (d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*b^3)}
{Cosh[c + d*x]/(x*(a + b*x)^3), x, 17, Cosh[c + d*x]/(2*a*(a + b*x)^2) + Cosh[c + d*x]/(a^2*(a + b*x)) + (Cosh[c]*CoshIntegral[d*x])/a^3 - (Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^3 - (d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*a*b^2) - (d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/(a^2*b) + (d*Sinh[c + d*x])/(2*a*b*(a + b*x)) + (Sinh[c]*SinhIntegral[d*x])/a^3 - (d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(a^2*b) - (Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^3 - (d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*a*b^2)}
{Cosh[c + d*x]/(x^2*(a + b*x)^3), x, 21, -(Cosh[c + d*x]/(a^3*x)) - (b*Cosh[c + d*x])/(2*a^2*(a + b*x)^2) - (2*b*Cosh[c + d*x])/(a^3*(a + b*x)) - (3*b*Cosh[c]*CoshIntegral[d*x])/a^4 + (3*b*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^4 + (d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*a^2*b) + (d*CoshIntegral[d*x]*Sinh[c])/a^3 + (2*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/a^3 - (d*Sinh[c + d*x])/(2*a^2*(a + b*x)) + (d*Cosh[c]*SinhIntegral[d*x])/a^3 - (3*b*Sinh[c]*SinhIntegral[d*x])/a^4 + (2*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^3 + (3*b*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^4 + (d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*a^2*b)}
{Cosh[c + d*x]/(x^3*(a + b*x)^3), x, 26, -Cosh[c + d*x]/(2*a^3*x^2) + (3*b*Cosh[c + d*x])/(a^4*x) + (b^2*Cosh[c + d*x])/(2*a^3*(a + b*x)^2) + (3*b^2*Cosh[c + d*x])/(a^4*(a + b*x)) + (6*b^2*Cosh[c]*CoshIntegral[d*x])/a^5 + (d^2*Cosh[c]*CoshIntegral[d*x])/(2*a^3) - (6*b^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/a^5 - (d^2*Cosh[c - (a*d)/b]*CoshIntegral[(a*d)/b + d*x])/(2*a^3) - (3*b*d*CoshIntegral[d*x]*Sinh[c])/a^4 - (3*b*d*CoshIntegral[(a*d)/b + d*x]*Sinh[c - (a*d)/b])/a^4 - (d*Sinh[c + d*x])/(2*a^3*x) + (b*d*Sinh[c + d*x])/(2*a^3*(a + b*x)) - (3*b*d*Cosh[c]*SinhIntegral[d*x])/a^4 + (6*b^2*Sinh[c]*SinhIntegral[d*x])/a^5 + (d^2*Sinh[c]*SinhIntegral[d*x])/(2*a^3) - (3*b*d*Cosh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^4 - (6*b^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/a^5 - (d^2*Sinh[c - (a*d)/b]*SinhIntegral[(a*d)/b + d*x])/(2*a^3)}


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^2)^p Cosh[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x^2)*Cosh[c + d*x], x, 12, (-120*b*Cosh[c + d*x])/d^6 - (6*a*Cosh[c + d*x])/d^4 - (60*b*x^2*Cosh[c + d*x])/d^4 - (3*a*x^2*Cosh[c + d*x])/d^2 - (5*b*x^4*Cosh[c + d*x])/d^2 + (120*b*x*Sinh[c + d*x])/d^5 + (6*a*x*Sinh[c + d*x])/d^3 + (20*b*x^3*Sinh[c + d*x])/d^3 + (a*x^3*Sinh[c + d*x])/d + (b*x^5*Sinh[c + d*x])/d}
{x^2*(a + b*x^2)*Cosh[c + d*x], x, 10, (-24*b*x*Cosh[c + d*x])/d^4 - (2*a*x*Cosh[c + d*x])/d^2 - (4*b*x^3*Cosh[c + d*x])/d^2 + (24*b*Sinh[c + d*x])/d^5 + (2*a*Sinh[c + d*x])/d^3 + (12*b*x^2*Sinh[c + d*x])/d^3 + (a*x^2*Sinh[c + d*x])/d + (b*x^4*Sinh[c + d*x])/d}
{x*(a + b*x^2)*Cosh[c + d*x], x, 8, (-6*b*Cosh[c + d*x])/d^4 - (a*Cosh[c + d*x])/d^2 - (3*b*x^2*Cosh[c + d*x])/d^2 + (6*b*x*Sinh[c + d*x])/d^3 + (a*x*Sinh[c + d*x])/d + (b*x^3*Sinh[c + d*x])/d}
{(a + b*x^2)*Cosh[c + d*x], x, 6, (-2*b*x*Cosh[c + d*x])/d^2 + (2*b*Sinh[c + d*x])/d^3 + (a*Sinh[c + d*x])/d + (b*x^2*Sinh[c + d*x])/d}
{((a + b*x^2)*Cosh[c + d*x])/x, x, 7, -((b*Cosh[c + d*x])/d^2) + a*Cosh[c]*CoshIntegral[d*x] + (b*x*Sinh[c + d*x])/d + a*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x^2)*Cosh[c + d*x])/x^2, x, 7, -((a*Cosh[c + d*x])/x) + a*d*CoshIntegral[d*x]*Sinh[c] + (b*Sinh[c + d*x])/d + a*d*Cosh[c]*SinhIntegral[d*x]}
{((a + b*x^2)*Cosh[c + d*x])/x^3, x, 10, -(a*Cosh[c + d*x])/(2*x^2) + b*Cosh[c]*CoshIntegral[d*x] + (a*d^2*Cosh[c]*CoshIntegral[d*x])/2 - (a*d*Sinh[c + d*x])/(2*x) + b*Sinh[c]*SinhIntegral[d*x] + (a*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x^2)*Cosh[c + d*x])/x^4, x, 12, -(a*Cosh[c + d*x])/(3*x^3) - (b*Cosh[c + d*x])/x - (a*d^2*Cosh[c + d*x])/(6*x) + b*d*CoshIntegral[d*x]*Sinh[c] + (a*d^3*CoshIntegral[d*x]*Sinh[c])/6 - (a*d*Sinh[c + d*x])/(6*x^2) + b*d*Cosh[c]*SinhIntegral[d*x] + (a*d^3*Cosh[c]*SinhIntegral[d*x])/6}
{((a + b*x^2)*Cosh[c + d*x])/x^5, x, 14, -(a*Cosh[c + d*x])/(4*x^4) - (b*Cosh[c + d*x])/(2*x^2) - (a*d^2*Cosh[c + d*x])/(24*x^2) + (b*d^2*Cosh[c]*CoshIntegral[d*x])/2 + (a*d^4*Cosh[c]*CoshIntegral[d*x])/24 - (a*d*Sinh[c + d*x])/(12*x^3) - (b*d*Sinh[c + d*x])/(2*x) - (a*d^3*Sinh[c + d*x])/(24*x) + (b*d^2*Sinh[c]*SinhIntegral[d*x])/2 + (a*d^4*Sinh[c]*SinhIntegral[d*x])/24}


{x^2*(a + b*x^2)^2*Cosh[c + d*x], x, 17, (-720*b^2*x*Cosh[c + d*x])/d^6 - (48*a*b*x*Cosh[c + d*x])/d^4 - (2*a^2*x*Cosh[c + d*x])/d^2 - (120*b^2*x^3*Cosh[c + d*x])/d^4 - (8*a*b*x^3*Cosh[c + d*x])/d^2 - (6*b^2*x^5*Cosh[c + d*x])/d^2 + (720*b^2*Sinh[c + d*x])/d^7 + (48*a*b*Sinh[c + d*x])/d^5 + (2*a^2*Sinh[c + d*x])/d^3 + (360*b^2*x^2*Sinh[c + d*x])/d^5 + (24*a*b*x^2*Sinh[c + d*x])/d^3 + (a^2*x^2*Sinh[c + d*x])/d + (30*b^2*x^4*Sinh[c + d*x])/d^3 + (2*a*b*x^4*Sinh[c + d*x])/d + (b^2*x^6*Sinh[c + d*x])/d}
{x*(a + b*x^2)^2*Cosh[c + d*x], x, 14, (-120*b^2*Cosh[c + d*x])/d^6 - (12*a*b*Cosh[c + d*x])/d^4 - (a^2*Cosh[c + d*x])/d^2 - (60*b^2*x^2*Cosh[c + d*x])/d^4 - (6*a*b*x^2*Cosh[c + d*x])/d^2 - (5*b^2*x^4*Cosh[c + d*x])/d^2 + (120*b^2*x*Sinh[c + d*x])/d^5 + (12*a*b*x*Sinh[c + d*x])/d^3 + (a^2*x*Sinh[c + d*x])/d + (20*b^2*x^3*Sinh[c + d*x])/d^3 + (2*a*b*x^3*Sinh[c + d*x])/d + (b^2*x^5*Sinh[c + d*x])/d}
{(a + b*x^2)^2*Cosh[c + d*x], x, 11, (-24*b^2*x*Cosh[c + d*x])/d^4 - (4*a*b*x*Cosh[c + d*x])/d^2 - (4*b^2*x^3*Cosh[c + d*x])/d^2 + (24*b^2*Sinh[c + d*x])/d^5 + (4*a*b*Sinh[c + d*x])/d^3 + (a^2*Sinh[c + d*x])/d + (12*b^2*x^2*Sinh[c + d*x])/d^3 + (2*a*b*x^2*Sinh[c + d*x])/d + (b^2*x^4*Sinh[c + d*x])/d}
{((a + b*x^2)^2*Cosh[c + d*x])/x, x, 11, (-6*b^2*Cosh[c + d*x])/d^4 - (2*a*b*Cosh[c + d*x])/d^2 - (3*b^2*x^2*Cosh[c + d*x])/d^2 + a^2*Cosh[c]*CoshIntegral[d*x] + (6*b^2*x*Sinh[c + d*x])/d^3 + (2*a*b*x*Sinh[c + d*x])/d + (b^2*x^3*Sinh[c + d*x])/d + a^2*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x^2)^2*Cosh[c + d*x])/x^2, x, 10, -((a^2*Cosh[c + d*x])/x) - (2*b^2*x*Cosh[c + d*x])/d^2 + a^2*d*CoshIntegral[d*x]*Sinh[c] + (2*b^2*Sinh[c + d*x])/d^3 + (2*a*b*Sinh[c + d*x])/d + (b^2*x^2*Sinh[c + d*x])/d + a^2*d*Cosh[c]*SinhIntegral[d*x]}
{((a + b*x^2)^2*Cosh[c + d*x])/x^3, x, 12, -((b^2*Cosh[c + d*x])/d^2) - (a^2*Cosh[c + d*x])/(2*x^2) + 2*a*b*Cosh[c]*CoshIntegral[d*x] + (a^2*d^2*Cosh[c]*CoshIntegral[d*x])/2 - (a^2*d*Sinh[c + d*x])/(2*x) + (b^2*x*Sinh[c + d*x])/d + 2*a*b*Sinh[c]*SinhIntegral[d*x] + (a^2*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x^2)^2*Cosh[c + d*x])/x^4, x, 13, -(a^2*Cosh[c + d*x])/(3*x^3) - (2*a*b*Cosh[c + d*x])/x - (a^2*d^2*Cosh[c + d*x])/(6*x) + 2*a*b*d*CoshIntegral[d*x]*Sinh[c] + (a^2*d^3*CoshIntegral[d*x]*Sinh[c])/6 + (b^2*Sinh[c + d*x])/d - (a^2*d*Sinh[c + d*x])/(6*x^2) + 2*a*b*d*Cosh[c]*SinhIntegral[d*x] + (a^2*d^3*Cosh[c]*SinhIntegral[d*x])/6}
{((a + b*x^2)^2*Cosh[c + d*x])/x^5, x, 17, -(a^2*Cosh[c + d*x])/(4*x^4) - (a*b*Cosh[c + d*x])/x^2 - (a^2*d^2*Cosh[c + d*x])/(24*x^2) + b^2*Cosh[c]*CoshIntegral[d*x] + a*b*d^2*Cosh[c]*CoshIntegral[d*x] + (a^2*d^4*Cosh[c]*CoshIntegral[d*x])/24 - (a^2*d*Sinh[c + d*x])/(12*x^3) - (a*b*d*Sinh[c + d*x])/x - (a^2*d^3*Sinh[c + d*x])/(24*x) + b^2*Sinh[c]*SinhIntegral[d*x] + a*b*d^2*Sinh[c]*SinhIntegral[d*x] + (a^2*d^4*Sinh[c]*SinhIntegral[d*x])/24}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Cosh[c + d*x])/(a + b*x^2), x, 14, (-2*x*Cosh[c + d*x])/(b*d^2) + ((-a)^(3/2)*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(5/2)) - ((-a)^(3/2)*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(5/2)) + (2*Sinh[c + d*x])/(b*d^3) - (a*Sinh[c + d*x])/(b^2*d) + (x^2*Sinh[c + d*x])/(b*d) - ((-a)^(3/2)*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(5/2)) - ((-a)^(3/2)*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(5/2))}
{(x^3*Cosh[c + d*x])/(a + b*x^2), x, 12, -(Cosh[c + d*x]/(b*d^2)) - (a*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) - (a*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2) + (x*Sinh[c + d*x])/(b*d) + (a*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) - (a*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2)}
{(x^2*Cosh[c + d*x])/(a + b*x^2), x, 11, (Sqrt[-a]*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(3/2)) - (Sqrt[-a]*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(3/2)) + Sinh[c + d*x]/(b*d) - (Sqrt[-a]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(3/2)) - (Sqrt[-a]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(3/2))}
{(x*Cosh[c + d*x])/(a + b*x^2), x, 8, (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b) + (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b) - (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b) + (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b)}
{Cosh[c + d*x]/(a + b*x^2), x, 8, (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*Sqrt[-a]*Sqrt[b]) - (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*Sqrt[-a]*Sqrt[b]) - (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*Sqrt[-a]*Sqrt[b]) - (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*Sqrt[-a]*Sqrt[b])}
{Cosh[c + d*x]/(x*(a + b*x^2)), x, 13, (Cosh[c]*CoshIntegral[d*x])/a - (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a) - (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a) + (Sinh[c]*SinhIntegral[d*x])/a + (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a) - (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a)}
{Cosh[c + d*x]/(x^2*(a + b*x^2)), x, 14, -(Cosh[c + d*x]/(a*x)) + (Sqrt[b]*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*(-a)^(3/2)) - (Sqrt[b]*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*(-a)^(3/2)) + (d*CoshIntegral[d*x]*Sinh[c])/a + (d*Cosh[c]*SinhIntegral[d*x])/a - (Sqrt[b]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*(-a)^(3/2)) - (Sqrt[b]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*(-a)^(3/2))}
{Cosh[c + d*x]/(x^3*(a + b*x^2)), x, 18, -Cosh[c + d*x]/(2*a*x^2) - (b*Cosh[c]*CoshIntegral[d*x])/a^2 + (d^2*Cosh[c]*CoshIntegral[d*x])/(2*a) + (b*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) + (b*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2) - (d*Sinh[c + d*x])/(2*a*x) - (b*Sinh[c]*SinhIntegral[d*x])/a^2 + (d^2*Sinh[c]*SinhIntegral[d*x])/(2*a) - (b*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) + (b*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2)}


{(x^4*Cosh[c + d*x])/(a + b*x^2)^2, x, 24, (x*Cosh[c + d*x])/(2*b^2) - (x^3*Cosh[c + d*x])/(2*b*(a + b*x^2)) + (3*Sqrt[-a]*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) - (3*Sqrt[-a]*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2)) - (a*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*b^3) - (a*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*b^3) + Sinh[c + d*x]/(b^2*d) + (a*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^3) - (3*Sqrt[-a]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) - (a*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^3) - (3*Sqrt[-a]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2))}
{(x^3*Cosh[c + d*x])/(a + b*x^2)^2, x, 20, Cosh[c + d*x]/(2*b^2) - (x^2*Cosh[c + d*x])/(2*b*(a + b*x^2)) + (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) + (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2) - (Sqrt[-a]*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*b^(5/2)) + (Sqrt[-a]*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*b^(5/2)) - (Sqrt[-a]*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) - (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) - (Sqrt[-a]*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2)) + (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2)}
{(x^2*Cosh[c + d*x])/(a + b*x^2)^2, x, 17, -(x*Cosh[c + d*x])/(2*b*(a + b*x^2)) + (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) - (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2)) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*b^2) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*b^2) - (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^2) - (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) + (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^2) - (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2))}
{(x*Cosh[c + d*x])/(a + b*x^2)^2, x, 9, -Cosh[c + d*x]/(2*b*(a + b*x^2)) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*Sqrt[-a]*b^(3/2)) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*Sqrt[-a]*b^(3/2)) - (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) - (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2))}
{Cosh[c + d*x]/(a + b*x^2)^2, x, 18, -Cosh[c + d*x]/(4*a*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) + Cosh[c + d*x]/(4*a*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) - (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) + (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*a*b) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*a*b) + (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a*b) + (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a*b) + (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b])}
{Cosh[c + d*x]/(x*(a + b*x^2)^2), x, 22, Cosh[c + d*x]/(2*a*(a + b*x^2)) + (Cosh[c]*CoshIntegral[d*x])/a^2 - (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) - (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(3/2)*Sqrt[b]) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(3/2)*Sqrt[b]) + (Sinh[c]*SinhIntegral[d*x])/a^2 - (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) + (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) - (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2)}
{Cosh[c + d*x]/(x^2*(a + b*x^2)^2), x, 32, -(Cosh[c + d*x]/(a^2*x)) + (Sqrt[b]*Cosh[c + d*x])/(4*a^2*(Sqrt[-a] - Sqrt[b]*x)) - (Sqrt[b]*Cosh[c + d*x])/(4*a^2*(Sqrt[-a] + Sqrt[b]*x)) - (3*Sqrt[b]*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(5/2)) + (3*Sqrt[b]*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(5/2)) + (d*CoshIntegral[d*x]*Sinh[c])/a^2 + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*a^2) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*a^2) + (d*Cosh[c]*SinhIntegral[d*x])/a^2 - (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a^2) + (3*Sqrt[b]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(5/2)) + (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a^2) + (3*Sqrt[b]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(5/2))}


{(x^3*Cosh[c + d*x])/(a + b*x^2)^3, x, 27, -(x^2*Cosh[c + d*x])/(4*b*(a + b*x^2)^2) - Cosh[c + d*x]/(4*b^2*(a + b*x^2)) + (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*b^3) + (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*b^3) - (3*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*Sqrt[-a]*b^(5/2)) + (3*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*Sqrt[-a]*b^(5/2)) - (d*x*Sinh[c + d*x])/(8*b^2*(a + b*x^2)) - (3*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) - (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*b^3) - (3*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2)) + (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*b^3)}
{(x^2*Cosh[c + d*x])/(a + b*x^2)^3, x, 28, -Cosh[c + d*x]/(16*a*b^(3/2)*(Sqrt[-a] - Sqrt[b]*x)) + Cosh[c + d*x]/(16*a*b^(3/2)*(Sqrt[-a] + Sqrt[b]*x)) - (x*Cosh[c + d*x])/(4*b*(a + b*x^2)^2) - (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) + (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) - (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2)) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a*b^2) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a*b^2) - (d*Sinh[c + d*x])/(8*b^2*(a + b*x^2)) + (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) + (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) - (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) - (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2) + (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) - (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2))}
{(x*Cosh[c + d*x])/(a + b*x^2)^3, x, 19, -Cosh[c + d*x]/(4*b*(a + b*x^2)^2) - (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) - (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2) + (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) - (d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) - (d*Sinh[c + d*x])/(16*a*b^(3/2)*(Sqrt[-a] - Sqrt[b]*x)) + (d*Sinh[c + d*x])/(16*a*b^(3/2)*(Sqrt[-a] + Sqrt[b]*x)) + (d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) + (d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) - (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2)}
{Cosh[c + d*x]/(a + b*x^2)^3, x, 28, -Cosh[c + d*x]/(16*(-a)^(3/2)*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)^2) - (3*Cosh[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) + Cosh[c + d*x]/(16*(-a)^(3/2)*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)^2) + (3*Cosh[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) + (3*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) - (3*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) - (3*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a^2*b) - (3*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a^2*b) + (d*Sinh[c + d*x])/(16*(-a)^(3/2)*b*(Sqrt[-a] - Sqrt[b]*x)) + (d*Sinh[c + d*x])/(16*(-a)^(3/2)*b*(Sqrt[-a] + Sqrt[b]*x)) + (3*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) - (3*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) - (3*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b) - (3*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2))}
{Cosh[c + d*x]/(x*(a + b*x^2)^3), x, 41, Cosh[c + d*x]/(4*a*(a + b*x^2)^2) + Cosh[c + d*x]/(2*a^2*(a + b*x^2)) + (Cosh[c]*CoshIntegral[d*x])/a^3 - (Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^3) + (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) - (Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^3) + (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b) + (5*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) - (5*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) + (d*Sinh[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) - (d*Sinh[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) + (Sinh[c]*SinhIntegral[d*x])/a^3 + (5*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^3) - (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) + (5*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^3) + (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b)}
{Cosh[c + d*x]/(x^2*(a + b*x^2)^3), x, 60, -(Cosh[c + d*x]/(a^3*x)) - (Sqrt[b]*Cosh[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] - Sqrt[b]*x)^2) + (7*Sqrt[b]*Cosh[c + d*x])/(16*a^3*(Sqrt[-a] - Sqrt[b]*x)) + (Sqrt[b]*Cosh[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] + Sqrt[b]*x)^2) - (7*Sqrt[b]*Cosh[c + d*x])/(16*a^3*(Sqrt[-a] + Sqrt[b]*x)) + (15*Sqrt[b]*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) + (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (15*Sqrt[b]*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2)) - (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (d*CoshIntegral[d*x]*Sinh[c])/a^3 + (7*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a^3) + (7*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a^3) + (d*Sinh[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] - Sqrt[b]*x)) + (d*Sinh[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] + Sqrt[b]*x)) + (d*Cosh[c]*SinhIntegral[d*x])/a^3 - (7*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) - (15*Sqrt[b]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) - (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (7*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3) - (15*Sqrt[b]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2)) - (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b])}
{Cosh[c + d*x]/(x^3*(a + b*x^2)^3), x, 46, -Cosh[c + d*x]/(2*a^3*x^2) - (b*Cosh[c + d*x])/(4*a^2*(a + b*x^2)^2) - (b*Cosh[c + d*x])/(a^3*(a + b*x^2)) - (3*b*Cosh[c]*CoshIntegral[d*x])/a^4 + (d^2*Cosh[c]*CoshIntegral[d*x])/(2*a^3) + (3*b*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^4) - (d^2*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) + (3*b*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^4) - (d^2*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3) + (9*Sqrt[b]*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(7/2)) - (9*Sqrt[b]*d*CoshIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(7/2)) - (d*Sinh[c + d*x])/(2*a^3*x) - (Sqrt[b]*d*Sinh[c + d*x])/(16*a^3*(Sqrt[-a] - Sqrt[b]*x)) + (Sqrt[b]*d*Sinh[c + d*x])/(16*a^3*(Sqrt[-a] + Sqrt[b]*x)) - (3*b*Sinh[c]*SinhIntegral[d*x])/a^4 + (d^2*Sinh[c]*SinhIntegral[d*x])/(2*a^3) + (9*Sqrt[b]*d*Cosh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) - (3*b*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^4) + (d^2*Sinh[c + (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) + (9*Sqrt[b]*d*Cosh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2)) + (3*b*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^4) - (d^2*Sinh[c - (Sqrt[-a]*d)/Sqrt[b]]*SinhIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3)}


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^3)^p Cosh[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x^3)*Cosh[c + d*x], x, 13, (-6*a*Cosh[c + d*x])/d^4 - (720*b*x*Cosh[c + d*x])/d^6 - (3*a*x^2*Cosh[c + d*x])/d^2 - (120*b*x^3*Cosh[c + d*x])/d^4 - (6*b*x^5*Cosh[c + d*x])/d^2 + (720*b*Sinh[c + d*x])/d^7 + (6*a*x*Sinh[c + d*x])/d^3 + (360*b*x^2*Sinh[c + d*x])/d^5 + (a*x^3*Sinh[c + d*x])/d + (30*b*x^4*Sinh[c + d*x])/d^3 + (b*x^6*Sinh[c + d*x])/d}
{x^2*(a + b*x^3)*Cosh[c + d*x], x, 11, (-120*b*Cosh[c + d*x])/d^6 - (2*a*x*Cosh[c + d*x])/d^2 - (60*b*x^2*Cosh[c + d*x])/d^4 - (5*b*x^4*Cosh[c + d*x])/d^2 + (2*a*Sinh[c + d*x])/d^3 + (120*b*x*Sinh[c + d*x])/d^5 + (a*x^2*Sinh[c + d*x])/d + (20*b*x^3*Sinh[c + d*x])/d^3 + (b*x^5*Sinh[c + d*x])/d}
{x^1*(a + b*x^3)*Cosh[c + d*x], x, 9, -((a*Cosh[c + d*x])/d^2) - (24*b*x*Cosh[c + d*x])/d^4 - (4*b*x^3*Cosh[c + d*x])/d^2 + (24*b*Sinh[c + d*x])/d^5 + (a*x*Sinh[c + d*x])/d + (12*b*x^2*Sinh[c + d*x])/d^3 + (b*x^4*Sinh[c + d*x])/d}
{(a + b*x^3)*Cosh[c + d*x], x, 7, (-6*b*Cosh[c + d*x])/d^4 - (3*b*x^2*Cosh[c + d*x])/d^2 + (a*Sinh[c + d*x])/d + (6*b*x*Sinh[c + d*x])/d^3 + (b*x^3*Sinh[c + d*x])/d}
{((a + b*x^3)*Cosh[c + d*x])/x^1, x, 8, (-2*b*x*Cosh[c + d*x])/d^2 + a*Cosh[c]*CoshIntegral[d*x] + (2*b*Sinh[c + d*x])/d^3 + (b*x^2*Sinh[c + d*x])/d + a*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x^3)*Cosh[c + d*x])/x^2, x, 8, -((b*Cosh[c + d*x])/d^2) - (a*Cosh[c + d*x])/x + a*d*CoshIntegral[d*x]*Sinh[c] + (b*x*Sinh[c + d*x])/d + a*d*Cosh[c]*SinhIntegral[d*x]}
{((a + b*x^3)*Cosh[c + d*x])/x^3, x, 8, -(a*Cosh[c + d*x])/(2*x^2) + (a*d^2*Cosh[c]*CoshIntegral[d*x])/2 + (b*Sinh[c + d*x])/d - (a*d*Sinh[c + d*x])/(2*x) + (a*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x^3)*Cosh[c + d*x])/x^4, x, 11, -(a*Cosh[c + d*x])/(3*x^3) - (a*d^2*Cosh[c + d*x])/(6*x) + b*Cosh[c]*CoshIntegral[d*x] + (a*d^3*CoshIntegral[d*x]*Sinh[c])/6 - (a*d*Sinh[c + d*x])/(6*x^2) + (a*d^3*Cosh[c]*SinhIntegral[d*x])/6 + b*Sinh[c]*SinhIntegral[d*x]}


{x^1*(a + b*x^3)^2*Cosh[c + d*x], x, 17, (-5040*b^2*Cosh[c + d*x])/d^8 - (a^2*Cosh[c + d*x])/d^2 - (48*a*b*x*Cosh[c + d*x])/d^4 - (2520*b^2*x^2*Cosh[c + d*x])/d^6 - (8*a*b*x^3*Cosh[c + d*x])/d^2 - (210*b^2*x^4*Cosh[c + d*x])/d^4 - (7*b^2*x^6*Cosh[c + d*x])/d^2 + (48*a*b*Sinh[c + d*x])/d^5 + (5040*b^2*x*Sinh[c + d*x])/d^7 + (a^2*x*Sinh[c + d*x])/d + (24*a*b*x^2*Sinh[c + d*x])/d^3 + (840*b^2*x^3*Sinh[c + d*x])/d^5 + (2*a*b*x^4*Sinh[c + d*x])/d + (42*b^2*x^5*Sinh[c + d*x])/d^3 + (b^2*x^7*Sinh[c + d*x])/d}
{(a + b*x^3)^2*Cosh[c + d*x], x, 14, (-12*a*b*Cosh[c + d*x])/d^4 - (720*b^2*x*Cosh[c + d*x])/d^6 - (6*a*b*x^2*Cosh[c + d*x])/d^2 - (120*b^2*x^3*Cosh[c + d*x])/d^4 - (6*b^2*x^5*Cosh[c + d*x])/d^2 + (720*b^2*Sinh[c + d*x])/d^7 + (a^2*Sinh[c + d*x])/d + (12*a*b*x*Sinh[c + d*x])/d^3 + (360*b^2*x^2*Sinh[c + d*x])/d^5 + (2*a*b*x^3*Sinh[c + d*x])/d + (30*b^2*x^4*Sinh[c + d*x])/d^3 + (b^2*x^6*Sinh[c + d*x])/d}
{((a + b*x^3)^2*Cosh[c + d*x])/x^1, x, 14, (-120*b^2*Cosh[c + d*x])/d^6 - (4*a*b*x*Cosh[c + d*x])/d^2 - (60*b^2*x^2*Cosh[c + d*x])/d^4 - (5*b^2*x^4*Cosh[c + d*x])/d^2 + a^2*Cosh[c]*CoshIntegral[d*x] + (4*a*b*Sinh[c + d*x])/d^3 + (120*b^2*x*Sinh[c + d*x])/d^5 + (2*a*b*x^2*Sinh[c + d*x])/d + (20*b^2*x^3*Sinh[c + d*x])/d^3 + (b^2*x^5*Sinh[c + d*x])/d + a^2*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x^3)^2*Cosh[c + d*x])/x^2, x, 13, (-2*a*b*Cosh[c + d*x])/d^2 - (a^2*Cosh[c + d*x])/x - (24*b^2*x*Cosh[c + d*x])/d^4 - (4*b^2*x^3*Cosh[c + d*x])/d^2 + a^2*d*CoshIntegral[d*x]*Sinh[c] + (24*b^2*Sinh[c + d*x])/d^5 + (2*a*b*x*Sinh[c + d*x])/d + (12*b^2*x^2*Sinh[c + d*x])/d^3 + (b^2*x^4*Sinh[c + d*x])/d + a^2*d*Cosh[c]*SinhIntegral[d*x]}
{((a + b*x^3)^2*Cosh[c + d*x])/x^3, x, 12, (-6*b^2*Cosh[c + d*x])/d^4 - (a^2*Cosh[c + d*x])/(2*x^2) - (3*b^2*x^2*Cosh[c + d*x])/d^2 + (a^2*d^2*Cosh[c]*CoshIntegral[d*x])/2 + (2*a*b*Sinh[c + d*x])/d - (a^2*d*Sinh[c + d*x])/(2*x) + (6*b^2*x*Sinh[c + d*x])/d^3 + (b^2*x^3*Sinh[c + d*x])/d + (a^2*d^2*Sinh[c]*SinhIntegral[d*x])/2}
{((a + b*x^3)^2*Cosh[c + d*x])/x^4, x, 14, -(a^2*Cosh[c + d*x])/(3*x^3) - (a^2*d^2*Cosh[c + d*x])/(6*x) - (2*b^2*x*Cosh[c + d*x])/d^2 + 2*a*b*Cosh[c]*CoshIntegral[d*x] + (a^2*d^3*CoshIntegral[d*x]*Sinh[c])/6 + (2*b^2*Sinh[c + d*x])/d^3 - (a^2*d*Sinh[c + d*x])/(6*x^2) + (b^2*x^2*Sinh[c + d*x])/d + (a^2*d^3*Cosh[c]*SinhIntegral[d*x])/6 + 2*a*b*Sinh[c]*SinhIntegral[d*x]}
{((a + b*x^3)^2*Cosh[c + d*x])/x^5, x, 15, -((b^2*Cosh[c + d*x])/d^2) - (a^2*Cosh[c + d*x])/(4*x^4) - (a^2*d^2*Cosh[c + d*x])/(24*x^2) - (2*a*b*Cosh[c + d*x])/x + (a^2*d^4*Cosh[c]*CoshIntegral[d*x])/24 + 2*a*b*d*CoshIntegral[d*x]*Sinh[c] - (a^2*d*Sinh[c + d*x])/(12*x^3) - (a^2*d^3*Sinh[c + d*x])/(24*x) + (b^2*x*Sinh[c + d*x])/d + 2*a*b*d*Cosh[c]*SinhIntegral[d*x] + (a^2*d^4*Sinh[c]*SinhIntegral[d*x])/24}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Cosh[c + d*x])/(a + b*x^3), x, 15, -(Cosh[c + d*x]/(b*d^2)) + ((-1)^(2/3)*a^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*b^(5/3)) + (a^(2/3)*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(5/3)) + (x*Sinh[c + d*x])/(b*d) - ((-1)^(2/3)*a^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(5/3)) + (a^(2/3)*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(5/3))}
{(x^3*Cosh[c + d*x])/(a + b*x^3), x, 14, ((-1)^(1/3)*a^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*b^(4/3)) - (a^(1/3)*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(4/3)) + Sinh[c + d*x]/(b*d) - ((-1)^(1/3)*a^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(4/3)) - (a^(1/3)*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(4/3))}
{(x^2*Cosh[c + d*x])/(a + b*x^3), x, 11, (Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b) + (Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*b) + (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b) - (Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b) + (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b) + (Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b)}
{(x^1*Cosh[c + d*x])/(a + b*x^3), x, 11, -(((-1)^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(1/3)*b^(2/3))) + ((-1)^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a^(1/3)*b^(2/3)) - (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(1/3)*b^(2/3)) + ((-1)^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(1/3)*b^(2/3)) - (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(1/3)*b^(2/3))}
{Cosh[c + d*x]/(a + b*x^3), x, 11, -(((-1)^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(2/3)*b^(1/3))) + ((-1)^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a^(2/3)*b^(1/3)) + (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(2/3)*b^(1/3)) + ((-1)^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(2/3)*b^(1/3)) + (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(2/3)*b^(1/3))}
{Cosh[c + d*x]/(x^1*(a + b*x^3)), x, 16, (Cosh[c]*CoshIntegral[d*x])/a - (Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a) - (Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a) - (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a) + (Sinh[c]*SinhIntegral[d*x])/a + (Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a) - (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a) - (Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a)}
{Cosh[c + d*x]/(x^2*(a + b*x^3)), x, 17, -(Cosh[c + d*x]/(a*x)) + ((-1)^(2/3)*b^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a^(4/3)) + (b^(1/3)*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(4/3)) + (d*CoshIntegral[d*x]*Sinh[c])/a + (d*Cosh[c]*SinhIntegral[d*x])/a - ((-1)^(2/3)*b^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(4/3)) + (b^(1/3)*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(4/3))}
{Cosh[c + d*x]/(x^3*(a + b*x^3)), x, 18, -(Cosh[c + d*x]/(2*a*x^2)) + (d^2*Cosh[c]*CoshIntegral[d*x])/(2*a) + ((-1)^(1/3)*b^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a^(5/3)) - (b^(2/3)*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(5/3)) - (d*Sinh[c + d*x])/(2*a*x) + (d^2*Sinh[c]*SinhIntegral[d*x])/(2*a) - ((-1)^(1/3)*b^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(5/3)) - (b^(2/3)*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(5/3))}


{(x^3*Cosh[c + d*x])/(a + b*x^3)^2, x, 23, -((x*Cosh[c + d*x])/(3*b*(a + b*x^3))) - ((-1)^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(9*a^(2/3)*b^(4/3)) + (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) - (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(1/3)*b^(5/3)) - ((-1)^(2/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3)) - (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3)) + (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) + ((-1)^(1/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3))}
{(x^2*Cosh[c + d*x])/(a + b*x^3)^2, x, 12, -(Cosh[c + d*x]/(3*b*(a + b*x^3))) + (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) + ((-1)^(1/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3)) + (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3))}
{(x^1*Cosh[c + d*x])/(a + b*x^3)^2, x, 34, Cosh[c + d*x]/(3*a*b*x) - Cosh[c + d*x]/(3*b*x*(a + b*x^3)) - ((-1)^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) + ((-1)^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(9*a^(4/3)*b^(2/3)) - (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) - (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(9*a*b) - (d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a*b) - (d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a*b) + (d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a*b) + ((-1)^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) - (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b) - (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) - (d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b) + ((-1)^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3))}
{Cosh[c + d*x]/(a + b*x^3)^2, x, 36, Cosh[c + d*x]/(3*a*b*x^2) - Cosh[c + d*x]/(3*b*x^2*(a + b*x^3)) - (2*(-1)^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) + (2*(-1)^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(9*a^(5/3)*b^(1/3)) + (2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) + (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) + ((-1)^(2/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) - ((-1)^(1/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) - ((-1)^(2/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) + (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - ((-1)^(1/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3))}
{Cosh[c + d*x]/(x^1*(a + b*x^3)^2), x, 41, Cosh[c + d*x]/(3*a*b*x^3) - Cosh[c + d*x]/(3*b*x^3*(a + b*x^3)) + (Cosh[c]*CoshIntegral[d*x])/a^2 - (Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^2) - (Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(3*a^2) - (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^2) - (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) + ((-1)^(1/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) - ((-1)^(2/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) + (Sinh[c]*SinhIntegral[d*x])/a^2 - ((-1)^(1/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) + (Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^2) - (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^2) - ((-1)^(2/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - (Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^2)}


{(x^5*Cosh[c + d*x])/(a + b*x^3)^3, x, 36, -((x^3*Cosh[c + d*x])/(6*b*(a + b*x^3)^2)) - Cosh[c + d*x]/(6*b^2*(a + b*x^3)) - ((-1)^(2/3)*d^2*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(1/3)*b^(8/3)) + ((-1)^(1/3)*d^2*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(54*a^(1/3)*b^(8/3)) - (d^2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(1/3)*b^(8/3)) + (2*d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(27*a^(2/3)*b^(7/3)) - (2*(-1)^(1/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(2/3)*b^(7/3)) + (2*(-1)^(2/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(2/3)*b^(7/3)) - (d*x*Sinh[c + d*x])/(18*b^2*(a + b*x^3)) + (2*(-1)^(1/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(2/3)*b^(7/3)) + ((-1)^(2/3)*d^2*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(1/3)*b^(8/3)) + (2*d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(2/3)*b^(7/3)) - (d^2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(1/3)*b^(8/3)) + (2*(-1)^(2/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(2/3)*b^(7/3)) + ((-1)^(1/3)*d^2*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(1/3)*b^(8/3))}
{(x^4*Cosh[c + d*x])/(a + b*x^3)^3, x, 47, Cosh[c + d*x]/(9*a*b^2*x) - (x^2*Cosh[c + d*x])/(6*b*(a + b*x^3)^2) - Cosh[c + d*x]/(9*b^2*x*(a + b*x^3)) - ((-1)^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d^2*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(2/3)*b^(7/3)) + ((-1)^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(27*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d^2*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(54*a^(2/3)*b^(7/3)) - (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(4/3)*b^(5/3)) + (d^2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(2/3)*b^(7/3)) - (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(27*a*b^2) - (d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a*b^2) - (d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a*b^2) - (d*Sinh[c + d*x])/(18*b^2*(a + b*x^3)) + (d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a*b^2) + ((-1)^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(4/3)*b^(5/3)) + ((-1)^(1/3)*d^2*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(2/3)*b^(7/3)) - (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a*b^2) - (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(4/3)*b^(5/3)) + (d^2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(2/3)*b^(7/3)) - (d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a*b^2) + ((-1)^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d^2*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(2/3)*b^(7/3))}
{(x^3*Cosh[c + d*x])/(a + b*x^3)^3, x, 71, Cosh[c + d*x]/(18*a*b^2*x^2) - (x*Cosh[c + d*x])/(6*b*(a + b*x^3)^2) - Cosh[c + d*x]/(18*b^2*x^2*(a + b*x^3)) - ((-1)^(1/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a*b^2) + ((-1)^(2/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(54*a*b^2) + (Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a*b^2) + (d*Sinh[c + d*x])/(18*a*b^2*x) - (d*Sinh[c + d*x])/(18*b^2*x*(a + b*x^3)) + ((-1)^(1/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) + (d^2*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a*b^2) + (Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a*b^2) + ((-1)^(2/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a*b^2)}
{(x^2*Cosh[c + d*x])/(a + b*x^3)^3, x, 37, -(Cosh[c + d*x]/(6*b*(a + b*x^3)^2)) + ((-1)^(2/3)*d^2*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d^2*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(54*a^(4/3)*b^(5/3)) + (d^2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(4/3)*b^(5/3)) + (d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) - ((-1)^(1/3)*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) + ((-1)^(2/3)*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) + (d*Sinh[c + d*x])/(18*a*b^2*x^2) - (d*Sinh[c + d*x])/(18*b^2*x^2*(a + b*x^3)) + ((-1)^(1/3)*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) - ((-1)^(2/3)*d^2*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(4/3)*b^(5/3)) + (d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) + (d^2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) - ((-1)^(1/3)*d^2*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(4/3)*b^(5/3))}
{(x^1*Cosh[c + d*x])/(a + b*x^3)^3, x, 89, -(Cosh[c + d*x]/(18*a*b^2*x^4)) + (2*Cosh[c + d*x])/(9*a^2*b*x) - Cosh[c + d*x]/(6*b*x*(a + b*x^3)^2) + Cosh[c + d*x]/(18*b^2*x^4*(a + b*x^3)) - (2*(-1)^(2/3)*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(7/3)*b^(2/3)) + ((-1)^(1/3)*d^2*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(5/3)*b^(4/3)) + (2*(-1)^(1/3)*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(27*a^(7/3)*b^(2/3)) - ((-1)^(2/3)*d^2*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x])/(54*a^(5/3)*b^(4/3)) - (2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(7/3)*b^(2/3)) - (d^2*Cosh[c - (a^(1/3)*d)/b^(1/3)]*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(5/3)*b^(4/3)) - (2*d*CoshIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sinh[c - (a^(1/3)*d)/b^(1/3)])/(27*a^2*b) - (2*d*CoshIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^2*b) - (2*d*CoshIntegral[-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x]*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^2*b) + (d*Sinh[c + d*x])/(18*a*b^2*x^3) - (d*Sinh[c + d*x])/(18*b^2*x^3*(a + b*x^3)) + (2*d*Cosh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^2*b) + (2*(-1)^(2/3)*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d^2*Sinh[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(5/3)*b^(4/3)) - (2*d*Cosh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b) - (2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(7/3)*b^(2/3)) - (d^2*Sinh[c - (a^(1/3)*d)/b^(1/3)]*SinhIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(5/3)*b^(4/3)) - (2*d*Cosh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b) + (2*(-1)^(1/3)*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(7/3)*b^(2/3)) - ((-1)^(2/3)*d^2*Sinh[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinhIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(5/3)*b^(4/3))}
