(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^n*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^1*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcSin[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^4*(d + e*x^2)*(a + b*ArcSin[c*x]), x, 5, (b*(7*c^2*d + 5*e)*Sqrt[1 - c^2*x^2])/(35*c^7) - (b*(14*c^2*d + 15*e)*(1 - c^2*x^2)^(3/2))/(105*c^7) + (b*(7*c^2*d + 15*e)*(1 - c^2*x^2)^(5/2))/(175*c^7) - (b*e*(1 - c^2*x^2)^(7/2))/(49*c^7) + (1/5)*d*x^5*(a + b*ArcSin[c*x]) + (1/7)*e*x^7*(a + b*ArcSin[c*x])}
{x^3*(d + e*x^2)*(a + b*ArcSin[c*x]), x, 6, (b*(9*c^2*d + 5*e)*x*Sqrt[1 - c^2*x^2])/(96*c^5) + (b*(9*c^2*d + 5*e)*x^3*Sqrt[1 - c^2*x^2])/(144*c^3) + (b*e*x^5*Sqrt[1 - c^2*x^2])/(36*c) - (b*(9*c^2*d + 5*e)*ArcSin[c*x])/(96*c^6) + (1/4)*d*x^4*(a + b*ArcSin[c*x]) + (1/6)*e*x^6*(a + b*ArcSin[c*x])}
{x^2*(d + e*x^2)*(a + b*ArcSin[c*x]), x, 5, (b*(5*c^2*d + 3*e)*Sqrt[1 - c^2*x^2])/(15*c^5) - (b*(5*c^2*d + 6*e)*(1 - c^2*x^2)^(3/2))/(45*c^5) + (b*e*(1 - c^2*x^2)^(5/2))/(25*c^5) + (1/3)*d*x^3*(a + b*ArcSin[c*x]) + (1/5)*e*x^5*(a + b*ArcSin[c*x])}
{x^1*(d + e*x^2)*(a + b*ArcSin[c*x]), x, 4, (3*b*(2*c^2*d + e)*x*Sqrt[1 - c^2*x^2])/(32*c^3) + (b*x*Sqrt[1 - c^2*x^2]*(d + e*x^2))/(16*c) - (b*(8*c^4*d^2 + 8*c^2*d*e + 3*e^2)*ArcSin[c*x])/(32*c^4*e) + ((d + e*x^2)^2*(a + b*ArcSin[c*x]))/(4*e)}
{x^0*(d + e*x^2)*(a + b*ArcSin[c*x]), x, 4, (b*(3*c^2*d + e)*Sqrt[1 - c^2*x^2])/(3*c^3) - (b*e*(1 - c^2*x^2)^(3/2))/(9*c^3) + d*x*(a + b*ArcSin[c*x]) + (1/3)*e*x^3*(a + b*ArcSin[c*x])}
{(d + e*x^2)*(a + b*ArcSin[c*x])/x^1, x, 12, (b*e*x*Sqrt[1 - c^2*x^2])/(4*c) - (b*e*ArcSin[c*x])/(4*c^2) - (1/2)*I*b*d*ArcSin[c*x]^2 + (1/2)*e*x^2*(a + b*ArcSin[c*x]) + b*d*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - b*d*ArcSin[c*x]*Log[x] + d*(a + b*ArcSin[c*x])*Log[x] - (1/2)*I*b*d*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)*(a + b*ArcSin[c*x])/x^2, x, 5, (b*e*Sqrt[1 - c^2*x^2])/c - (d*(a + b*ArcSin[c*x]))/x + e*x*(a + b*ArcSin[c*x]) - b*c*d*ArcTanh[Sqrt[1 - c^2*x^2]]}
{(d + e*x^2)*(a + b*ArcSin[c*x])/x^3, x, 10, -((b*c*d*Sqrt[1 - c^2*x^2])/(2*x)) - (1/2)*I*b*e*ArcSin[c*x]^2 - (d*(a + b*ArcSin[c*x]))/(2*x^2) + b*e*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - b*e*ArcSin[c*x]*Log[x] + e*(a + b*ArcSin[c*x])*Log[x] - (1/2)*I*b*e*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)*(a + b*ArcSin[c*x])/x^4, x, 6, -((b*c*d*Sqrt[1 - c^2*x^2])/(6*x^2)) - (d*(a + b*ArcSin[c*x]))/(3*x^3) - (e*(a + b*ArcSin[c*x]))/x - (1/6)*b*c*(c^2*d + 6*e)*ArcTanh[Sqrt[1 - c^2*x^2]]}


{x^4*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 6, (b*(63*c^4*d^2 + 90*c^2*d*e + 35*e^2)*Sqrt[1 - c^2*x^2])/(315*c^9) - (2*b*(63*c^4*d^2 + 135*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^(3/2))/(945*c^9) + (b*(21*c^4*d^2 + 90*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^(5/2))/(525*c^9) - (2*b*e*(9*c^2*d + 14*e)*(1 - c^2*x^2)^(7/2))/(441*c^9) + (b*e^2*(1 - c^2*x^2)^(9/2))/(81*c^9) + (1/5)*d^2*x^5*(a + b*ArcSin[c*x]) + (2/7)*d*e*x^7*(a + b*ArcSin[c*x]) + (1/9)*e^2*x^9*(a + b*ArcSin[c*x])}
{x^3*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 7, (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*x*Sqrt[1 - c^2*x^2])/(3072*c^7) + (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*x^3*Sqrt[1 - c^2*x^2])/(4608*c^5) + (b*e*(64*c^2*d + 21*e)*x^5*Sqrt[1 - c^2*x^2])/(1152*c^3) + (b*e^2*x^7*Sqrt[1 - c^2*x^2])/(64*c) - (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*ArcSin[c*x])/(3072*c^8) + (1/4)*d^2*x^4*(a + b*ArcSin[c*x]) + (1/3)*d*e*x^6*(a + b*ArcSin[c*x]) + (1/8)*e^2*x^8*(a + b*ArcSin[c*x])}
{x^2*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 5, (b*(35*c^4*d^2 + 42*c^2*d*e + 15*e^2)*Sqrt[1 - c^2*x^2])/(105*c^7) - (b*(35*c^4*d^2 + 84*c^2*d*e + 45*e^2)*(1 - c^2*x^2)^(3/2))/(315*c^7) + (b*e*(14*c^2*d + 15*e)*(1 - c^2*x^2)^(5/2))/(175*c^7) - (b*e^2*(1 - c^2*x^2)^(7/2))/(49*c^7) + (1/3)*d^2*x^3*(a + b*ArcSin[c*x]) + (2/5)*d*e*x^5*(a + b*ArcSin[c*x]) + (1/7)*e^2*x^7*(a + b*ArcSin[c*x])}
{x^1*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 5, (b*(44*c^4*d^2 + 44*c^2*d*e + 15*e^2)*x*Sqrt[1 - c^2*x^2])/(288*c^5) + (5*b*(2*c^2*d + e)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2))/(144*c^3) + (b*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^2)/(36*c) - (b*(2*c^2*d + e)*(8*c^4*d^2 + 8*c^2*d*e + 5*e^2)*ArcSin[c*x])/(96*c^6*e) + ((d + e*x^2)^3*(a + b*ArcSin[c*x]))/(6*e)}
{x^0*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 5, (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*Sqrt[1 - c^2*x^2])/(15*c^5) - (2*b*e*(5*c^2*d + 3*e)*(1 - c^2*x^2)^(3/2))/(45*c^5) + (b*e^2*(1 - c^2*x^2)^(5/2))/(25*c^5) + d^2*x*(a + b*ArcSin[c*x]) + (2/3)*d*e*x^3*(a + b*ArcSin[c*x]) + (1/5)*e^2*x^5*(a + b*ArcSin[c*x])}
{(d + e*x^2)^2*(a + b*ArcSin[c*x])/x^1, x, 14, (b*d*e*x*Sqrt[1 - c^2*x^2])/(2*c) + (3*b*e^2*x*Sqrt[1 - c^2*x^2])/(32*c^3) + (b*e^2*x^3*Sqrt[1 - c^2*x^2])/(16*c) - (b*d*e*ArcSin[c*x])/(2*c^2) - (3*b*e^2*ArcSin[c*x])/(32*c^4) - (1/2)*I*b*d^2*ArcSin[c*x]^2 + d*e*x^2*(a + b*ArcSin[c*x]) + (1/4)*e^2*x^4*(a + b*ArcSin[c*x]) + b*d^2*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - b*d^2*ArcSin[c*x]*Log[x] + d^2*(a + b*ArcSin[c*x])*Log[x] - (1/2)*I*b*d^2*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)^2*(a + b*ArcSin[c*x])/x^2, x, 6, (b*e*(6*c^2*d + e)*Sqrt[1 - c^2*x^2])/(3*c^3) - (b*e^2*(1 - c^2*x^2)^(3/2))/(9*c^3) - (d^2*(a + b*ArcSin[c*x]))/x + 2*d*e*x*(a + b*ArcSin[c*x]) + (1/3)*e^2*x^3*(a + b*ArcSin[c*x]) - b*c*d^2*ArcTanh[Sqrt[1 - c^2*x^2]]}
{(d + e*x^2)^2*(a + b*ArcSin[c*x])/x^3, x, 13, -((b*c*d^2*Sqrt[1 - c^2*x^2])/(2*x)) + (b*e^2*x*Sqrt[1 - c^2*x^2])/(4*c) - (b*e^2*ArcSin[c*x])/(4*c^2) - I*b*d*e*ArcSin[c*x]^2 - (d^2*(a + b*ArcSin[c*x]))/(2*x^2) + (1/2)*e^2*x^2*(a + b*ArcSin[c*x]) + 2*b*d*e*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - 2*b*d*e*ArcSin[c*x]*Log[x] + 2*d*e*(a + b*ArcSin[c*x])*Log[x] - I*b*d*e*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)^2*(a + b*ArcSin[c*x])/x^4, x, 6, (b*e^2*Sqrt[1 - c^2*x^2])/c - (b*c*d^2*Sqrt[1 - c^2*x^2])/(6*x^2) - (d^2*(a + b*ArcSin[c*x]))/(3*x^3) - (2*d*e*(a + b*ArcSin[c*x]))/x + e^2*x*(a + b*ArcSin[c*x]) - (1/6)*b*c*d*(c^2*d + 12*e)*ArcTanh[Sqrt[1 - c^2*x^2]]}


{x^4*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 5, (b*(231*c^6*d^3 + 495*c^4*d^2*e + 385*c^2*d*e^2 + 105*e^3)*Sqrt[1 - c^2*x^2])/(1155*c^11) - (b*(462*c^6*d^3 + 1485*c^4*d^2*e + 1540*c^2*d*e^2 + 525*e^3)*(1 - c^2*x^2)^(3/2))/(3465*c^11) + (b*(77*c^6*d^3 + 495*c^4*d^2*e + 770*c^2*d*e^2 + 350*e^3)*(1 - c^2*x^2)^(5/2))/(1925*c^11) - (b*e*(99*c^4*d^2 + 308*c^2*d*e + 210*e^2)*(1 - c^2*x^2)^(7/2))/(1617*c^11) + (b*e^2*(11*c^2*d + 15*e)*(1 - c^2*x^2)^(9/2))/(297*c^11) - (b*e^3*(1 - c^2*x^2)^(11/2))/(121*c^11) + (1/5)*d^3*x^5*(a + b*ArcSin[c*x]) + (3/7)*d^2*e*x^7*(a + b*ArcSin[c*x]) + (1/3)*d*e^2*x^9*(a + b*ArcSin[c*x]) + (1/11)*e^3*x^11*(a + b*ArcSin[c*x])}
{x^3*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 8, -((b*(1232*c^8*d^4 - 2536*c^6*d^3*e - 7758*c^4*d^2*e^2 - 6615*c^2*d*e^3 - 1890*e^4)*x*Sqrt[1 - c^2*x^2])/(76800*c^9*e)) - (b*(136*c^6*d^3 - 1096*c^4*d^2*e - 1617*c^2*d*e^2 - 630*e^3)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2))/(38400*c^7*e) + (b*(26*c^4*d^2 + 201*c^2*d*e + 126*e^2)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^2)/(9600*c^5*e) + (b*(11*c^2*d + 18*e)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^3)/(1600*c^3*e) + (b*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^4)/(100*c*e) + (b*(128*c^10*d^5 - 480*c^6*d^3*e^2 - 800*c^4*d^2*e^3 - 525*c^2*d*e^4 - 126*e^5)*ArcSin[c*x])/(5120*c^10*e^2) - (d*(d + e*x^2)^4*(a + b*ArcSin[c*x]))/(8*e^2) + ((d + e*x^2)^5*(a + b*ArcSin[c*x]))/(10*e^2)}
{x^2*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 5, (b*(105*c^6*d^3 + 189*c^4*d^2*e + 135*c^2*d*e^2 + 35*e^3)*Sqrt[1 - c^2*x^2])/(315*c^9) - (b*(105*c^6*d^3 + 378*c^4*d^2*e + 405*c^2*d*e^2 + 140*e^3)*(1 - c^2*x^2)^(3/2))/(945*c^9) + (b*e*(63*c^4*d^2 + 135*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^(5/2))/(525*c^9) - (b*e^2*(27*c^2*d + 28*e)*(1 - c^2*x^2)^(7/2))/(441*c^9) + (b*e^3*(1 - c^2*x^2)^(9/2))/(81*c^9) + (1/3)*d^3*x^3*(a + b*ArcSin[c*x]) + (3/5)*d^2*e*x^5*(a + b*ArcSin[c*x]) + (3/7)*d*e^2*x^7*(a + b*ArcSin[c*x]) + (1/9)*e^3*x^9*(a + b*ArcSin[c*x])}
{x^1*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 6, (5*b*(2*c^2*d + e)*(40*c^4*d^2 + 40*c^2*d*e + 21*e^2)*x*Sqrt[1 - c^2*x^2])/(3072*c^7) + (b*(104*c^4*d^2 + 104*c^2*d*e + 35*e^2)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2))/(1536*c^5) + (7*b*(2*c^2*d + e)*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^2)/(384*c^3) + (b*x*Sqrt[1 - c^2*x^2]*(d + e*x^2)^3)/(64*c) - (b*(128*c^8*d^4 + 256*c^6*d^3*e + 288*c^4*d^2*e^2 + 160*c^2*d*e^3 + 35*e^4)*ArcSin[c*x])/(1024*c^8*e) + ((d + e*x^2)^4*(a + b*ArcSin[c*x]))/(8*e)}
{x^0*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 5, (b*(35*c^6*d^3 + 35*c^4*d^2*e + 21*c^2*d*e^2 + 5*e^3)*Sqrt[1 - c^2*x^2])/(35*c^7) - (b*e*(35*c^4*d^2 + 42*c^2*d*e + 15*e^2)*(1 - c^2*x^2)^(3/2))/(105*c^7) + (3*b*e^2*(7*c^2*d + 5*e)*(1 - c^2*x^2)^(5/2))/(175*c^7) - (b*e^3*(1 - c^2*x^2)^(7/2))/(49*c^7) + d^3*x*(a + b*ArcSin[c*x]) + d^2*e*x^3*(a + b*ArcSin[c*x]) + (3/5)*d*e^2*x^5*(a + b*ArcSin[c*x]) + (1/7)*e^3*x^7*(a + b*ArcSin[c*x])}
{(d + e*x^2)^3*(a + b*ArcSin[c*x])/x^1, x, 19, (3*b*d^2*e*x*Sqrt[1 - c^2*x^2])/(4*c) + (9*b*d*e^2*x*Sqrt[1 - c^2*x^2])/(32*c^3) + (5*b*e^3*x*Sqrt[1 - c^2*x^2])/(96*c^5) + (3*b*d*e^2*x^3*Sqrt[1 - c^2*x^2])/(16*c) + (5*b*e^3*x^3*Sqrt[1 - c^2*x^2])/(144*c^3) + (b*e^3*x^5*Sqrt[1 - c^2*x^2])/(36*c) - (3*b*d^2*e*ArcSin[c*x])/(4*c^2) - (9*b*d*e^2*ArcSin[c*x])/(32*c^4) - (5*b*e^3*ArcSin[c*x])/(96*c^6) - (1/2)*I*b*d^3*ArcSin[c*x]^2 + (3/2)*d^2*e*x^2*(a + b*ArcSin[c*x]) + (3/4)*d*e^2*x^4*(a + b*ArcSin[c*x]) + (1/6)*e^3*x^6*(a + b*ArcSin[c*x]) + b*d^3*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - b*d^3*ArcSin[c*x]*Log[x] + d^3*(a + b*ArcSin[c*x])*Log[x] - (1/2)*I*b*d^3*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)^3*(a + b*ArcSin[c*x])/x^2, x, 6, (b*e*(15*c^4*d^2 + 5*c^2*d*e + e^2)*Sqrt[1 - c^2*x^2])/(5*c^5) - (b*e^2*(5*c^2*d + 2*e)*(1 - c^2*x^2)^(3/2))/(15*c^5) + (b*e^3*(1 - c^2*x^2)^(5/2))/(25*c^5) - (d^3*(a + b*ArcSin[c*x]))/x + 3*d^2*e*x*(a + b*ArcSin[c*x]) + d*e^2*x^3*(a + b*ArcSin[c*x]) + (1/5)*e^3*x^5*(a + b*ArcSin[c*x]) - b*c*d^3*ArcTanh[Sqrt[1 - c^2*x^2]]}
{(d + e*x^2)^3*(a + b*ArcSin[c*x])/x^3, x, 15, -((b*c*d^3*Sqrt[1 - c^2*x^2])/(2*x)) + (3*b*e^2*(8*c^2*d + e)*x*Sqrt[1 - c^2*x^2])/(32*c^3) + (b*e^3*x^3*Sqrt[1 - c^2*x^2])/(16*c) - (3*b*e^2*(8*c^2*d + e)*ArcSin[c*x])/(32*c^4) - (3/2)*I*b*d^2*e*ArcSin[c*x]^2 - (d^3*(a + b*ArcSin[c*x]))/(2*x^2) + (3/2)*d*e^2*x^2*(a + b*ArcSin[c*x]) + (1/4)*e^3*x^4*(a + b*ArcSin[c*x]) + 3*b*d^2*e*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])] - 3*b*d^2*e*ArcSin[c*x]*Log[x] + 3*d^2*e*(a + b*ArcSin[c*x])*Log[x] - (3/2)*I*b*d^2*e*PolyLog[2, E^(2*I*ArcSin[c*x])]}
{(d + e*x^2)^3*(a + b*ArcSin[c*x])/x^4, x, 8, (b*e^2*(9*c^2*d + e)*Sqrt[1 - c^2*x^2])/(3*c^3) - (b*c*d^3*Sqrt[1 - c^2*x^2])/(6*x^2) - (b*e^3*(1 - c^2*x^2)^(3/2))/(9*c^3) - (d^3*(a + b*ArcSin[c*x]))/(3*x^3) - (3*d^2*e*(a + b*ArcSin[c*x]))/x + 3*d*e^2*x*(a + b*ArcSin[c*x]) + (1/3)*e^3*x^3*(a + b*ArcSin[c*x]) - (1/6)*b*c*d^2*(c^2*d + 18*e)*ArcTanh[Sqrt[1 - c^2*x^2]]}


{(d + e*x^2)^4*(a + b*ArcSin[c*x]), x, 5, (b*(315*c^8*d^4 + 420*c^6*d^3*e + 378*c^4*d^2*e^2 + 180*c^2*d*e^3 + 35*e^4)*Sqrt[1 - c^2*x^2])/(315*c^9) - (4*b*e*(105*c^6*d^3 + 189*c^4*d^2*e + 135*c^2*d*e^2 + 35*e^3)*(1 - c^2*x^2)^(3/2))/(945*c^9) + (2*b*e^2*(63*c^4*d^2 + 90*c^2*d*e + 35*e^2)*(1 - c^2*x^2)^(5/2))/(525*c^9) - (4*b*e^3*(9*c^2*d + 7*e)*(1 - c^2*x^2)^(7/2))/(441*c^9) + (b*e^4*(1 - c^2*x^2)^(9/2))/(81*c^9) + d^4*x*(a + b*ArcSin[c*x]) + (4/3)*d^3*e*x^3*(a + b*ArcSin[c*x]) + (6/5)*d^2*e^2*x^5*(a + b*ArcSin[c*x]) + (4/7)*d*e^3*x^7*(a + b*ArcSin[c*x]) + (1/9)*e^4*x^9*(a + b*ArcSin[c*x])}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*(a + b*ArcSin[c*x]))/(d + e*x^2), x, 27, -((a*d*x)/e^2) - (b*d*Sqrt[1 - c^2*x^2])/(c*e^2) + (b*Sqrt[1 - c^2*x^2])/(3*c^3*e) - (b*(1 - c^2*x^2)^(3/2))/(9*c^3*e) - (b*d*x*ArcSin[c*x])/e^2 + (x^3*(a + b*ArcSin[c*x]))/(3*e) + ((-d)^(3/2)*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(5/2)) - ((-d)^(3/2)*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(5/2)) + ((-d)^(3/2)*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(5/2)) - ((-d)^(3/2)*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(5/2)) + (I*b*(-d)^(3/2)*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e^(5/2)) - (I*b*(-d)^(3/2)*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(5/2)) + (I*b*(-d)^(3/2)*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e^(5/2)) - (I*b*(-d)^(3/2)*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(5/2))}
{(x^3*(a + b*ArcSin[c*x]))/(d + e*x^2), x, 23, (b*x*Sqrt[1 - c^2*x^2])/(4*c*e) - (b*ArcSin[c*x])/(4*c^2*e) + (x^2*(a + b*ArcSin[c*x]))/(2*e) + (I*d*(a + b*ArcSin[c*x])^2)/(2*b*e^2) - (d*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) - (d*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) - (d*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2) - (d*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2) + (I*b*d*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) + (I*b*d*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2)}
{(x^2*(a + b*ArcSin[c*x]))/(d + e*x^2), x, 23, (a*x)/e + (b*Sqrt[1 - c^2*x^2])/(c*e) + (b*x*ArcSin[c*x])/e + (Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^(3/2))}
{(x^1*(a + b*ArcSin[c*x]))/(d + e*x^2), x, 18, -((I*(a + b*ArcSin[c*x])^2)/(2*b*e)) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e)}
{(a + b*ArcSin[c*x])/(d + e*x^2), x, 18, ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcSin[c*x])/(x^1*(d + e*x^2)), x, 25, -(((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d)) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d) + ((a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d) - (I*b*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*d)}
{(a + b*ArcSin[c*x])/(x^2*(d + e*x^2)), x, 24, -((a + b*ArcSin[c*x])/(d*x)) - (b*c*ArcTanh[Sqrt[1 - c^2*x^2]])/d + (Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2))}
{(a + b*ArcSin[c*x])/(x^3*(d + e*x^2)), x, 27, -((b*c*Sqrt[1 - c^2*x^2])/(2*d*x)) - (a + b*ArcSin[c*x])/(2*d*x^2) + (e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) + (e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) + (e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) + (e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) - (e*(a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d^2 - (I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*d^2) - (I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) - (I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*d^2) - (I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) + (I*b*e*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*d^2)}
{(a + b*ArcSin[c*x])/(x^4*(d + e*x^2)), x, 29, -((b*c*Sqrt[1 - c^2*x^2])/(6*d*x^2)) - (a + b*ArcSin[c*x])/(3*d*x^3) + (e*(a + b*ArcSin[c*x]))/(d^2*x) - (b*c^3*ArcTanh[Sqrt[1 - c^2*x^2]])/(6*d) + (b*c*e*ArcTanh[Sqrt[1 - c^2*x^2]])/d^2 + (e^(3/2)*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(5/2)) - (e^(3/2)*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(5/2)) + (e^(3/2)*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(5/2)) - (e^(3/2)*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(5/2)) + (I*b*e^(3/2)*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*(-d)^(5/2)) - (I*b*e^(3/2)*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*(-d)^(5/2)) + (I*b*e^(3/2)*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*(-d)^(5/2)) - (I*b*e^(3/2)*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*(-d)^(5/2))}


{(x^3*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x, 23, (d*(a + b*ArcSin[c*x]))/(2*e^2*(d + e*x^2)) - (I*(a + b*ArcSin[c*x])^2)/(2*b*e^2) - (b*c*Sqrt[d]*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(2*e^2*Sqrt[c^2*d + e]) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^2) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^2)}
{(x^1*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x, 3, -(a + b*ArcSin[c*x])/(2*e*(d + e*x^2)) + (b*c*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(2*Sqrt[d]*e*Sqrt[c^2*d + e])}
{(a + b*ArcSin[c*x])/(x^1*(d + e*x^2)^2), x, 28, (a + b*ArcSin[c*x])/(2*d*(d + e*x^2)) - (b*c*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(2*d^(3/2)*Sqrt[c^2*d + e]) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) + ((a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d^2 + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^2) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^2) - (I*b*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*d^2)}
{(a + b*ArcSin[c*x])/(x^3*(d + e*x^2)^2), x, 30, -((b*c*Sqrt[1 - c^2*x^2])/(2*d^2*x)) - (a + b*ArcSin[c*x])/(2*d^2*x^2) - (e*(a + b*ArcSin[c*x]))/(2*d^2*(d + e*x^2)) + (b*c*e*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(2*d^(5/2)*Sqrt[c^2*d + e]) + (e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/d^3 + (e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/d^3 + (e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/d^3 + (e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/d^3 - (2*e*(a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d^3 - (I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/d^3 - (I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/d^3 - (I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/d^3 - (I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/d^3 + (I*b*e*PolyLog[2, E^(2*I*ArcSin[c*x])])/d^3}

{(x^4*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x, 49, (a*x)/e^2 + (b*Sqrt[1 - c^2*x^2])/(c*e^2) + (b*x*ArcSin[c*x])/e^2 - (d*(a + b*ArcSin[c*x]))/(4*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)) + (d*(a + b*ArcSin[c*x]))/(4*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)) + (b*c*d*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*e^(5/2)*Sqrt[c^2*d + e]) + (b*c*d*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*e^(5/2)*Sqrt[c^2*d + e]) + (3*Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*e^(5/2))}
{(x^2*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x, 46, (a + b*ArcSin[c*x])/(4*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)) - (a + b*ArcSin[c*x])/(4*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)) - (b*c*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*e^(3/2)*Sqrt[c^2*d + e]) - (b*c*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*e^(3/2)*Sqrt[c^2*d + e]) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2))}
{(x^0*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x, 26, -((a + b*ArcSin[c*x])/(4*d*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x))) + (a + b*ArcSin[c*x])/(4*d*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)) + (b*c*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*d*Sqrt[e]*Sqrt[c^2*d + e]) + (b*c*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*d*Sqrt[e]*Sqrt[c^2*d + e]) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e])}
{(a + b*ArcSin[c*x])/(x^2*(d + e*x^2)^2), x, 50, -((a + b*ArcSin[c*x])/(d^2*x)) + (Sqrt[e]*(a + b*ArcSin[c*x]))/(4*d^2*(Sqrt[-d] - Sqrt[e]*x)) - (Sqrt[e]*(a + b*ArcSin[c*x]))/(4*d^2*(Sqrt[-d] + Sqrt[e]*x)) - (b*c*Sqrt[e]*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*d^2*Sqrt[c^2*d + e]) - (b*c*Sqrt[e]*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(4*d^2*Sqrt[c^2*d + e]) - (b*c*ArcTanh[Sqrt[1 - c^2*x^2]])/d^2 - (3*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2))}


{(x^5*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 27, (b*c*d*x*Sqrt[1 - c^2*x^2])/(8*e^2*(c^2*d + e)*(d + e*x^2)) - (d^2*(a + b*ArcSin[c*x]))/(4*e^3*(d + e*x^2)^2) + (d*(a + b*ArcSin[c*x]))/(e^3*(d + e*x^2)) - (I*(a + b*ArcSin[c*x])^2)/(2*b*e^3) - (b*c*Sqrt[d]*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(e^3*Sqrt[c^2*d + e]) + (b*c*Sqrt[d]*(2*c^2*d + e)*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*e^3*(c^2*d + e)^(3/2)) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^3) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*e^3) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*e^3)}
{(x^3*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 7, -(b*c*x*Sqrt[1 - c^2*x^2])/(8*e*(c^2*d + e)*(d + e*x^2)) - (b*ArcSin[c*x])/(4*d*e^2) + (x^4*(a + b*ArcSin[c*x]))/(4*d*(d + e*x^2)^2) + (b*c*(2*c^2*d + 3*e)*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*Sqrt[d]*e^2*(c^2*d + e)^(3/2))}
{(x^1*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 4, (b*c*x*Sqrt[1 - c^2*x^2])/(8*d*(c^2*d + e)*(d + e*x^2)) - (a + b*ArcSin[c*x])/(4*e*(d + e*x^2)^2) + (b*c*(2*c^2*d + e)*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*d^(3/2)*e*(c^2*d + e)^(3/2))}
{(a + b*ArcSin[c*x])/(x^1*(d + e*x^2)^3), x, 32, -((b*c*e*x*Sqrt[1 - c^2*x^2])/(8*d^2*(c^2*d + e)*(d + e*x^2))) + (a + b*ArcSin[c*x])/(4*d*(d + e*x^2)^2) + (a + b*ArcSin[c*x])/(2*d^2*(d + e*x^2)) - (b*c*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(2*d^(5/2)*Sqrt[c^2*d + e]) - (b*c*(2*c^2*d + e)*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*d^(5/2)*(c^2*d + e)^(3/2)) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^3) + ((a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d^3 + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^3) + (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^3) - (I*b*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*d^3)}
{(a + b*ArcSin[c*x])/(x^3*(d + e*x^2)^3), x, 34, -((b*c*Sqrt[1 - c^2*x^2])/(2*d^3*x)) + (b*c*e^2*x*Sqrt[1 - c^2*x^2])/(8*d^3*(c^2*d + e)*(d + e*x^2)) - (a + b*ArcSin[c*x])/(2*d^3*x^2) - (e*(a + b*ArcSin[c*x]))/(4*d^2*(d + e*x^2)^2) - (e*(a + b*ArcSin[c*x]))/(d^3*(d + e*x^2)) + (b*c*e*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(d^(7/2)*Sqrt[c^2*d + e]) + (b*c*e*(2*c^2*d + e)*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*d^(7/2)*(c^2*d + e)^(3/2)) + (3*e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^4) + (3*e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^4) + (3*e*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^4) + (3*e*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^4) - (3*e*(a + b*ArcSin[c*x])*Log[1 - E^(2*I*ArcSin[c*x])])/d^4 - (3*I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(2*d^4) - (3*I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*d^4) - (3*I*b*e*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(2*d^4) - (3*I*b*e*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*d^4) + (3*I*b*e*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*d^4)}

{(x^4*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 80, (b*c*Sqrt[-d]*Sqrt[1 - c^2*x^2])/(16*e^2*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x)) + (b*c*Sqrt[-d]*Sqrt[1 - c^2*x^2])/(16*e^2*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (Sqrt[-d]*(a + b*ArcSin[c*x]))/(16*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)^2) + (5*(a + b*ArcSin[c*x]))/(16*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)) + (Sqrt[-d]*(a + b*ArcSin[c*x]))/(16*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)^2) - (5*(a + b*ArcSin[c*x]))/(16*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)) + (b*c^3*d*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(5/2)*(c^2*d + e)^(3/2)) - (5*b*c*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(5/2)*Sqrt[c^2*d + e]) + (b*c^3*d*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(5/2)*(c^2*d + e)^(3/2)) - (5*b*c*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(5/2)*Sqrt[c^2*d + e]) + (3*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2))}
{(x^2*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 62, (b*c*Sqrt[1 - c^2*x^2])/(16*Sqrt[-d]*e*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x)) + (b*c*Sqrt[1 - c^2*x^2])/(16*Sqrt[-d]*e*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcSin[c*x])/(16*Sqrt[-d]*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)^2) - (a + b*ArcSin[c*x])/(16*d*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)) + (a + b*ArcSin[c*x])/(16*Sqrt[-d]*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)^2) + (a + b*ArcSin[c*x])/(16*d*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)) - (b*c^3*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(3/2)*(c^2*d + e)^(3/2)) + (b*c*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d*e^(3/2)*Sqrt[c^2*d + e]) - (b*c^3*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*e^(3/2)*(c^2*d + e)^(3/2)) + (b*c*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d*e^(3/2)*Sqrt[c^2*d + e]) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2))}
{(x^0*(a + b*ArcSin[c*x]))/(d + e*x^2)^3, x, 34, (b*c*Sqrt[1 - c^2*x^2])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x)) + (b*c*Sqrt[1 - c^2*x^2])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcSin[c*x])/(16*(-d)^(3/2)*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x)^2) - (3*(a + b*ArcSin[c*x]))/(16*d^2*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x)) + (a + b*ArcSin[c*x])/(16*(-d)^(3/2)*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)^2) + (3*(a + b*ArcSin[c*x]))/(16*d^2*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)) + (b*c^3*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d*Sqrt[e]*(c^2*d + e)^(3/2)) + (3*b*c*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*Sqrt[e]*Sqrt[c^2*d + e]) + (b*c^3*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d*Sqrt[e]*(c^2*d + e)^(3/2)) + (3*b*c*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*Sqrt[e]*Sqrt[c^2*d + e]) + (3*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e])}
(* {(a + b*ArcSin[c*x])/(x^2*(d + e*x^2)^3), x, 84, (b*c*e*Sqrt[1 - c^2*x^2])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x)) + (b*c*e*Sqrt[1 - c^2*x^2])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcSin[c*x])/(d^3*x) - (Sqrt[e]*(a + b*ArcSin[c*x]))/(16*(-d)^(5/2)*(Sqrt[-d] - Sqrt[e]*x)^2) + (7*Sqrt[e]*(a + b*ArcSin[c*x]))/(16*d^3*(Sqrt[-d] - Sqrt[e]*x)) + (Sqrt[e]*(a + b*ArcSin[c*x]))/(16*(-d)^(5/2)*(Sqrt[-d] + Sqrt[e]*x)^2) - (7*Sqrt[e]*(a + b*ArcSin[c*x]))/(16*d^3*(Sqrt[-d] + Sqrt[e]*x)) - (b*c^3*Sqrt[e]*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*(c^2*d + e)^(3/2)) - (7*b*c*Sqrt[e]*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^3*Sqrt[c^2*d + e]) - (b*c^3*Sqrt[e]*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*(c^2*d + e)^(3/2)) - (7*b*c*Sqrt[e]*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^3*Sqrt[c^2*d + e]) - (b*c*ArcTanh[Sqrt[1 - c^2*x^2]])/d^3 + (15*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) - (15*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) - (15*Sqrt[e]*(a + b*ArcSin[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2))} *)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^(p/2) (a+b ArcSin[c x])*)


{(d + e*x^2)^(1/2)*(a + b*ArcSin[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcSin[c*x]), x]}
{(a + b*ArcSin[c*x])/(d + e*x^2)^(1/2), x, 0, Unintegrable[(a + b*ArcSin[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcSin[c*x])/(d + e*x^2)^(3/2), x, 6, (x*(a + b*ArcSin[c*x]))/(d*Sqrt[d + e*x^2]) + (b*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(d*Sqrt[e])}
{(a + b*ArcSin[c*x])/(d + e*x^2)^(5/2), x, 7, (b*c*Sqrt[1 - c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[d + e*x^2]) + (x*(a + b*ArcSin[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcSin[c*x]))/(3*d^2*Sqrt[d + e*x^2]) + (2*b*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(3*d^2*Sqrt[e])}
{(a + b*ArcSin[c*x])/(d + e*x^2)^(7/2), x, 8, (b*c*Sqrt[1 - c^2*x^2])/(15*d*(c^2*d + e)*(d + e*x^2)^(3/2)) + (2*b*c*(3*c^2*d + 2*e)*Sqrt[1 - c^2*x^2])/(15*d^2*(c^2*d + e)^2*Sqrt[d + e*x^2]) + (x*(a + b*ArcSin[c*x]))/(5*d*(d + e*x^2)^(5/2)) + (4*x*(a + b*ArcSin[c*x]))/(15*d^2*(d + e*x^2)^(3/2)) + (8*x*(a + b*ArcSin[c*x]))/(15*d^3*Sqrt[d + e*x^2]) + (8*b*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(15*d^3*Sqrt[e])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x]) when m symbolic*)


{(f*x)^m*(d + e*x^2)^3*(a + b*ArcSin[c*x]), x, 6, If[$VersionNumber>=8, (b*e*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4))*(f*x)^(2 + m)*Sqrt[1 - c^2*x^2])/(c^5*f^2*(3 + m)^2*(5 + m)^2*(7 + m)^2) + (b*e^2*(3*c^2*d*(7 + m)^2 + e*(30 + 11*m + m^2))*(f*x)^(4 + m)*Sqrt[1 - c^2*x^2])/(c^3*f^4*(5 + m)^2*(7 + m)^2) + (b*e^3*(f*x)^(6 + m)*Sqrt[1 - c^2*x^2])/(c*f^6*(7 + m)^2) + (d^3*(f*x)^(1 + m)*(a + b*ArcSin[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSin[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSin[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSin[c*x]))/(f^7*(7 + m)) - (b*((c^6*d^3*(3 + m)*(5 + m)*(7 + m))/(1 + m) + (e*(2 + m)*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4)))/((3 + m)*(5 + m)*(7 + m)))*(f*x)^(2 + m)*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^5*f^2*(2 + m)*(3 + m)*(5 + m)*(7 + m)), (b*e*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4))*(f*x)^(2 + m)*Sqrt[1 - c^2*x^2])/(c^5*f^2*(3 + m)^2*(5 + m)^2*(7 + m)^2) + (b*e^2*(3*c^2*d*(7 + m)^2 + e*(30 + 11*m + m^2))*(f*x)^(4 + m)*Sqrt[1 - c^2*x^2])/(c^3*f^4*(5 + m)^2*(7 + m)^2) + (b*e^3*(f*x)^(6 + m)*Sqrt[1 - c^2*x^2])/(c*f^6*(7 + m)^2) + (d^3*(f*x)^(1 + m)*(a + b*ArcSin[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSin[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSin[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSin[c*x]))/(f^7*(7 + m)) - (b*((c^6*d^3*(3 + m)*(5 + m)*(7 + m))/(1 + m) + (e*(2 + m)*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4)))/(105 + 71*m + 15*m^2 + m^3))*(f*x)^(2 + m)*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^5*f^2*(2 + m)*(3 + m)*(5 + m)*(7 + m))]}
{(f*x)^m*(d + e*x^2)^2*(a + b*ArcSin[c*x]), x, 5, (b*e*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2))*(f*x)^(2 + m)*Sqrt[1 - c^2*x^2])/(c^3*f^2*(3 + m)^2*(5 + m)^2) + (b*e^2*(f*x)^(4 + m)*Sqrt[1 - c^2*x^2])/(c*f^4*(5 + m)^2) + (d^2*(f*x)^(1 + m)*(a + b*ArcSin[c*x]))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*ArcSin[c*x]))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*ArcSin[c*x]))/(f^5*(5 + m)) - (b*((c^4*d^2*(3 + m)*(5 + m))/(1 + m) + (e*(2 + m)*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2)))/((3 + m)*(5 + m)))*(f*x)^(2 + m)*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^3*f^2*(2 + m)*(3 + m)*(5 + m))}
{(f*x)^m*(d + e*x^2)^1*(a + b*ArcSin[c*x]), x, 4, (b*e*(f*x)^(2 + m)*Sqrt[1 - c^2*x^2])/(c*f^2*(3 + m)^2) + (d*(f*x)^(1 + m)*(a + b*ArcSin[c*x]))/(f*(1 + m)) + (e*(f*x)^(3 + m)*(a + b*ArcSin[c*x]))/(f^3*(3 + m)) - (b*(e*(1 + m)*(2 + m) + c^2*d*(3 + m)^2)*(f*x)^(2 + m)*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c*f^2*(1 + m)*(2 + m)*(3 + m)^2)}
{(f*x)^m*(a + b*ArcSin[c*x])/(d + e*x^2)^1, x, 0, Unintegrable[((f*x)^m*(a + b*ArcSin[c*x]))/(d + e*x^2), x]}
{(f*x)^m*(a + b*ArcSin[c*x])/(d + e*x^2)^2, x, 0, Unintegrable[((f*x)^m*(a + b*ArcSin[c*x]))/(d + e*x^2)^2, x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^2*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^2*)


{(d + e*x^2)^3*(a + b*ArcSin[c*x])^2, x, 26, -2*b^2*d^3*x - (4*b^2*d^2*e*x)/(3*c^2) - (16*b^2*d*e^2*x)/(25*c^4) - (32*b^2*e^3*x)/(245*c^6) - (2/9)*b^2*d^2*e*x^3 - (8*b^2*d*e^2*x^3)/(75*c^2) - (16*b^2*e^3*x^3)/(735*c^4) - (6/125)*b^2*d*e^2*x^5 - (12*b^2*e^3*x^5)/(1225*c^2) - (2/343)*b^2*e^3*x^7 + (2*b*d^3*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/c + (4*b*d^2*e*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(3*c^3) + (16*b*d*e^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(25*c^5) + (32*b*e^3*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(245*c^7) + (2*b*d^2*e*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(3*c) + (8*b*d*e^2*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(25*c^3) + (16*b*e^3*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(245*c^5) + (6*b*d*e^2*x^4*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(25*c) + (12*b*e^3*x^4*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(245*c^3) + (2*b*e^3*x^6*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(49*c) + d^3*x*(a + b*ArcSin[c*x])^2 + d^2*e*x^3*(a + b*ArcSin[c*x])^2 + (3/5)*d*e^2*x^5*(a + b*ArcSin[c*x])^2 + (1/7)*e^3*x^7*(a + b*ArcSin[c*x])^2}
{(d + e*x^2)^2*(a + b*ArcSin[c*x])^2, x, 17, -2*b^2*d^2*x - (8*b^2*d*e*x)/(9*c^2) - (16*b^2*e^2*x)/(75*c^4) - (4/27)*b^2*d*e*x^3 - (8*b^2*e^2*x^3)/(225*c^2) - (2/125)*b^2*e^2*x^5 + (2*b*d^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/c + (8*b*d*e*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(9*c^3) + (16*b*e^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(75*c^5) + (4*b*d*e*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(9*c) + (8*b*e^2*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(75*c^3) + (2*b*e^2*x^4*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(25*c) + d^2*x*(a + b*ArcSin[c*x])^2 + (2/3)*d*e*x^3*(a + b*ArcSin[c*x])^2 + (1/5)*e^2*x^5*(a + b*ArcSin[c*x])^2}
{(d + e*x^2)^1*(a + b*ArcSin[c*x])^2, x, 10, -2*b^2*d*x - (4*b^2*e*x)/(9*c^2) - (2/27)*b^2*e*x^3 + (2*b*d*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/c + (4*b*e*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(9*c^3) + (2*b*e*x^2*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/(9*c) + d*x*(a + b*ArcSin[c*x])^2 + (1/3)*e*x^3*(a + b*ArcSin[c*x])^2}
{(d + e*x^2)^0*(a + b*ArcSin[c*x])^2, x, 3, -2*b^2*x + (2*b*Sqrt[1 - c^2*x^2]*(a + b*ArcSin[c*x]))/c + x*(a + b*ArcSin[c*x])^2}
{(a + b*ArcSin[c*x])^2/(d + e*x^2)^1, x, 22, ((a + b*ArcSin[c*x])^2*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSin[c*x])^2*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcSin[c*x])^2*Log[1 - (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSin[c*x])^2*Log[1 + (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*(a + b*ArcSin[c*x])*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(Sqrt[-d]*Sqrt[e]) - (I*b*(a + b*ArcSin[c*x])*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(Sqrt[-d]*Sqrt[e]) + (I*b*(a + b*ArcSin[c*x])*PolyLog[2, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(Sqrt[-d]*Sqrt[e]) - (I*b*(a + b*ArcSin[c*x])*PolyLog[2, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(Sqrt[-d]*Sqrt[e]) - (b^2*PolyLog[3, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(Sqrt[-d]*Sqrt[e]) + (b^2*PolyLog[3, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(Sqrt[-d]*Sqrt[e]) - (b^2*PolyLog[3, -((Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(Sqrt[-d]*Sqrt[e]) + (b^2*PolyLog[3, (Sqrt[e]*E^(I*ArcSin[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(Sqrt[-d]*Sqrt[e])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^(p/2) (a+b ArcSin[c x])^2*)


{(d + e*x^2)^(1/2)*(a + b*ArcSin[c*x])^2, x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^2, x]}
{(a + b*ArcSin[c*x])^2/(d + e*x^2)^(1/2), x, 0, Unintegrable[(a + b*ArcSin[c*x])^2/Sqrt[d + e*x^2], x]}
{(a + b*ArcSin[c*x])^2/(d + e*x^2)^(3/2), x, 0, Unintegrable[(a + b*ArcSin[c*x])^2/(d + e*x^2)^(3/2), x]}
{(a + b*ArcSin[c*x])^2/(d + e*x^2)^(5/2), x, 0, Unintegrable[(a + b*ArcSin[c*x])^2/(d + e*x^2)^(5/2), x]}


(* ::Section:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^3*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcSin[c x])^1*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcSin[c x])*)


{(d + e*x^2)^2/(a + b*ArcSin[c*x]), x, 27, (d*e*Cos[a/b]*CosIntegral[a/b + ArcSin[c*x]])/(2*b*c^3) + (e^2*Cos[a/b]*CosIntegral[a/b + ArcSin[c*x]])/(8*b*c^5) - (d*e*Cos[(3*a)/b]*CosIntegral[(3*a)/b + 3*ArcSin[c*x]])/(2*b*c^3) - (3*e^2*Cos[(3*a)/b]*CosIntegral[(3*a)/b + 3*ArcSin[c*x]])/(16*b*c^5) + (e^2*Cos[(5*a)/b]*CosIntegral[(5*a)/b + 5*ArcSin[c*x]])/(16*b*c^5) + (d^2*Cos[a/b]*CosIntegral[(a + b*ArcSin[c*x])/b])/(b*c) + (d*e*Sin[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(2*b*c^3) + (e^2*Sin[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(8*b*c^5) - (d*e*Sin[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(2*b*c^3) - (3*e^2*Sin[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(16*b*c^5) + (e^2*Sin[(5*a)/b]*SinIntegral[(5*a)/b + 5*ArcSin[c*x]])/(16*b*c^5) + (d^2*Sin[a/b]*SinIntegral[(a + b*ArcSin[c*x])/b])/(b*c)}
{(d + e*x^2)^1/(a + b*ArcSin[c*x]), x, 15, (e*Cos[a/b]*CosIntegral[a/b + ArcSin[c*x]])/(4*b*c^3) - (e*Cos[(3*a)/b]*CosIntegral[(3*a)/b + 3*ArcSin[c*x]])/(4*b*c^3) + (d*Cos[a/b]*CosIntegral[(a + b*ArcSin[c*x])/b])/(b*c) + (e*Sin[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(4*b*c^3) - (e*Sin[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(4*b*c^3) + (d*Sin[a/b]*SinIntegral[(a + b*ArcSin[c*x])/b])/(b*c)}
{(d + e*x^2)^0/(a + b*ArcSin[c*x]), x, 4, (Cos[a/b]*CosIntegral[(a + b*ArcSin[c*x])/b])/(b*c) + (Sin[a/b]*SinIntegral[(a + b*ArcSin[c*x])/b])/(b*c)}
{1/((d + e*x^2)^1*(a + b*ArcSin[c*x])), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcSin[c*x])), x]}
{1/((d + e*x^2)^2*(a + b*ArcSin[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcSin[c*x])), x]}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^(p/2) / (a+b ArcSin[c x])*)


{(d + e*x^2)^(1/2)/(a + b*ArcSin[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]/(a + b*ArcSin[c*x]), x]}
{1/((d + e*x^2)^(1/2)*(a + b*ArcSin[c*x])), x, 0, Unintegrable[1/(Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])), x]}
{1/((d + e*x^2)^(3/2)*(a + b*ArcSin[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^(3/2)*(a + b*ArcSin[c*x])), x]}
{1/((d + e*x^2)^(5/2)*(a + b*ArcSin[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^(5/2)*(a + b*ArcSin[c*x])), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcSin[c x])^2*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcSin[c x])^2*)


{(d + e*x^2)^2/(a + b*ArcSin[c*x])^2, x, 26, -((d^2*Sqrt[1 - c^2*x^2])/(b*c*(a + b*ArcSin[c*x]))) - (2*d*e*x^2*Sqrt[1 - c^2*x^2])/(b*c*(a + b*ArcSin[c*x])) - (e^2*x^4*Sqrt[1 - c^2*x^2])/(b*c*(a + b*ArcSin[c*x])) + (d^2*CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(b^2*c) + (d*e*CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(2*b^2*c^3) + (e^2*CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(8*b^2*c^5) - (3*d*e*CosIntegral[(3*a)/b + 3*ArcSin[c*x]]*Sin[(3*a)/b])/(2*b^2*c^3) - (9*e^2*CosIntegral[(3*a)/b + 3*ArcSin[c*x]]*Sin[(3*a)/b])/(16*b^2*c^5) + (5*e^2*CosIntegral[(5*a)/b + 5*ArcSin[c*x]]*Sin[(5*a)/b])/(16*b^2*c^5) - (d^2*Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(b^2*c) - (d*e*Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(2*b^2*c^3) - (e^2*Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(8*b^2*c^5) + (3*d*e*Cos[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(2*b^2*c^3) + (9*e^2*Cos[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(16*b^2*c^5) - (5*e^2*Cos[(5*a)/b]*SinIntegral[(5*a)/b + 5*ArcSin[c*x]])/(16*b^2*c^5)}
{(d + e*x^2)^1/(a + b*ArcSin[c*x])^2, x, 15, -((d*Sqrt[1 - c^2*x^2])/(b*c*(a + b*ArcSin[c*x]))) - (e*x^2*Sqrt[1 - c^2*x^2])/(b*c*(a + b*ArcSin[c*x])) + (d*CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(b^2*c) + (e*CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(4*b^2*c^3) - (3*e*CosIntegral[(3*a)/b + 3*ArcSin[c*x]]*Sin[(3*a)/b])/(4*b^2*c^3) - (d*Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(b^2*c) - (e*Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(4*b^2*c^3) + (3*e*Cos[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSin[c*x]])/(4*b^2*c^3)}
{(d + e*x^2)^0/(a + b*ArcSin[c*x])^2, x, 5, -(Sqrt[1 - c^2*x^2]/(b*c*(a + b*ArcSin[c*x]))) + (CosIntegral[a/b + ArcSin[c*x]]*Sin[a/b])/(b^2*c) - (Cos[a/b]*SinIntegral[a/b + ArcSin[c*x]])/(b^2*c)}
{1/((d + e*x^2)^1*(a + b*ArcSin[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcSin[c*x])^2), x]}
{1/((d + e*x^2)^2*(a + b*ArcSin[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcSin[c*x])^2), x]}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^(p/2) / (a+b ArcSin[c x])^2*)


{(d + e*x^2)^(1/2)/(a + b*ArcSin[c*x])^2, x, 0, Unintegrable[Sqrt[d + e*x^2]/(a + b*ArcSin[c*x])^2, x]}
{1/((d + e*x^2)^(1/2)*(a + b*ArcSin[c*x])^2), x, 0, Unintegrable[1/(Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^2), x]}
{1/((d + e*x^2)^(3/2)*(a + b*ArcSin[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^(3/2)*(a + b*ArcSin[c*x])^2), x]}
{1/((d + e*x^2)^(5/2)*(a + b*ArcSin[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^(5/2)*(a + b*ArcSin[c*x])^2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSin[c x])^(n/2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x^2)^p (a+b ArcSin[c x])^(n/2)*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x^2)^2*(a + b*ArcSin[c*x])^(1/2), x, 42, d^2*x*Sqrt[a + b*ArcSin[c*x]] + (2/3)*d*e*x^3*Sqrt[a + b*ArcSin[c*x]] + (1/5)*e^2*x^5*Sqrt[a + b*ArcSin[c*x]] - (Sqrt[b]*d^2*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/c - (Sqrt[b]*d*e*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(2*c^3) - (Sqrt[b]*e^2*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(8*c^5) + (Sqrt[b]*d*e*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(6*c^3) + (Sqrt[b]*e^2*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(16*c^5) - (Sqrt[b]*e^2*Sqrt[Pi/10]*Cos[(5*a)/b]*FresnelS[(Sqrt[10/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(80*c^5) + (Sqrt[b]*d^2*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/c + (Sqrt[b]*d*e*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(2*c^3) + (Sqrt[b]*e^2*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(8*c^5) - (Sqrt[b]*d*e*Sqrt[Pi/6]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(6*c^3) - (Sqrt[b]*e^2*Sqrt[Pi/6]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(16*c^5) + (Sqrt[b]*e^2*Sqrt[Pi/10]*FresnelC[(Sqrt[10/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(5*a)/b])/(80*c^5)}
{(d + e*x^2)^1*(a + b*ArcSin[c*x])^(1/2), x, 23, d*x*Sqrt[a + b*ArcSin[c*x]] + (1/3)*e*x^3*Sqrt[a + b*ArcSin[c*x]] - (Sqrt[b]*d*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/c - (Sqrt[b]*e*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(4*c^3) + (Sqrt[b]*e*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(12*c^3) + (Sqrt[b]*d*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/c + (Sqrt[b]*e*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(4*c^3) - (Sqrt[b]*e*Sqrt[Pi/6]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(12*c^3)}
{(d + e*x^2)^0*(a + b*ArcSin[c*x])^(1/2), x, 7, x*Sqrt[a + b*ArcSin[c*x]] - (Sqrt[b]*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/c + (Sqrt[b]*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/c}
{(a + b*ArcSin[c*x])^(1/2)/(d + e*x^2)^1, x, 0, Unintegrable[Sqrt[a + b*ArcSin[c*x]]/(d + e*x^2), x]}
{(a + b*ArcSin[c*x])^(1/2)/(d + e*x^2)^2, x, 0, Unintegrable[Sqrt[a + b*ArcSin[c*x]]/(d + e*x^2)^2, x]}


{(d + e*x^2)^1*(a + b*ArcSin[c*x])^(3/2), x, 32, (3*b*d*Sqrt[1 - c^2*x^2]*Sqrt[a + b*ArcSin[c*x]])/(2*c) + (b*e*Sqrt[1 - c^2*x^2]*Sqrt[a + b*ArcSin[c*x]])/(3*c^3) + (b*e*x^2*Sqrt[1 - c^2*x^2]*Sqrt[a + b*ArcSin[c*x]])/(6*c) + d*x*(a + b*ArcSin[c*x])^(3/2) + (1/3)*e*x^3*(a + b*ArcSin[c*x])^(3/2) - (3*b^(3/2)*d*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(2*c) - (3*b^(3/2)*e*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(8*c^3) + (b^(3/2)*e*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(24*c^3) - (3*b^(3/2)*d*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(2*c) - (3*b^(3/2)*e*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(8*c^3) + (b^(3/2)*e*Sqrt[Pi/6]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(24*c^3)}
{(d + e*x^2)^0*(a + b*ArcSin[c*x])^(3/2), x, 8, (3*b*Sqrt[1 - c^2*x^2]*Sqrt[a + b*ArcSin[c*x]])/(2*c) + x*(a + b*ArcSin[c*x])^(3/2) - (3*b^(3/2)*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(2*c) - (3*b^(3/2)*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(2*c)}
{(a + b*ArcSin[c*x])^(3/2)/(d + e*x^2)^1, x, 0, Unintegrable[(a + b*ArcSin[c*x])^(3/2)/(d + e*x^2), x]}
{(a + b*ArcSin[c*x])^(3/2)/(d + e*x^2)^2, x, 0, Unintegrable[(a + b*ArcSin[c*x])^(3/2)/(d + e*x^2)^2, x]}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(d + e*x^2)^2/(a + b*ArcSin[c*x])^(1/2), x, 39, (d*e*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(Sqrt[b]*c^3) + (e^2*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(4*Sqrt[b]*c^5) + (d^2*Sqrt[2*Pi]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(Sqrt[b]*c) - (d*e*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(Sqrt[b]*c^3) - (e^2*Sqrt[(3*Pi)/2]*Cos[(3*a)/b]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(8*Sqrt[b]*c^5) + (e^2*Sqrt[Pi/10]*Cos[(5*a)/b]*FresnelC[(Sqrt[10/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(8*Sqrt[b]*c^5) + (d*e*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(Sqrt[b]*c^3) + (e^2*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(4*Sqrt[b]*c^5) + (d^2*Sqrt[2*Pi]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(Sqrt[b]*c) - (d*e*Sqrt[Pi/6]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(Sqrt[b]*c^3) - (e^2*Sqrt[(3*Pi)/2]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(8*Sqrt[b]*c^5) + (e^2*Sqrt[Pi/10]*FresnelS[(Sqrt[10/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(5*a)/b])/(8*Sqrt[b]*c^5)}
{(d + e*x^2)^1/(a + b*ArcSin[c*x])^(1/2), x, 21, (e*Sqrt[Pi/2]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(2*Sqrt[b]*c^3) + (d*Sqrt[2*Pi]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(Sqrt[b]*c) - (e*Sqrt[Pi/6]*Cos[(3*a)/b]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(2*Sqrt[b]*c^3) + (e*Sqrt[Pi/2]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(2*Sqrt[b]*c^3) + (d*Sqrt[2*Pi]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(Sqrt[b]*c) - (e*Sqrt[Pi/6]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(2*Sqrt[b]*c^3)}
{(d + e*x^2)^0/(a + b*ArcSin[c*x])^(1/2), x, 6, (Sqrt[2*Pi]*Cos[a/b]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(Sqrt[b]*c) + (Sqrt[2*Pi]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(Sqrt[b]*c)}
{1/((d + e*x^2)^1*(a + b*ArcSin[c*x])^(1/2)), x, 0, Unintegrable[1/((d + e*x^2)*Sqrt[a + b*ArcSin[c*x]]), x]}
{1/((d + e*x^2)^2*(a + b*ArcSin[c*x])^(1/2)), x, 0, Unintegrable[1/((d + e*x^2)^2*Sqrt[a + b*ArcSin[c*x]]), x]}


{(d + e*x^2)^1/(a + b*ArcSin[c*x])^(3/2), x, 21, -((2*d*Sqrt[1 - c^2*x^2])/(b*c*Sqrt[a + b*ArcSin[c*x]])) - (2*e*x^2*Sqrt[1 - c^2*x^2])/(b*c*Sqrt[a + b*ArcSin[c*x]]) - (e*Sqrt[Pi/2]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(b^(3/2)*c^3) - (2*d*Sqrt[2*Pi]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(b^(3/2)*c) + (e*Sqrt[(3*Pi)/2]*Cos[(3*a)/b]*FresnelS[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(b^(3/2)*c^3) + (e*Sqrt[Pi/2]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(b^(3/2)*c^3) + (2*d*Sqrt[2*Pi]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(b^(3/2)*c) - (e*Sqrt[(3*Pi)/2]*FresnelC[(Sqrt[6/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[(3*a)/b])/(b^(3/2)*c^3)}
{(d + e*x^2)^0/(a + b*ArcSin[c*x])^(3/2), x, 7, -((2*Sqrt[1 - c^2*x^2])/(b*c*Sqrt[a + b*ArcSin[c*x]])) - (2*Sqrt[2*Pi]*Cos[a/b]*FresnelS[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]])/(b^(3/2)*c) + (2*Sqrt[2*Pi]*FresnelC[(Sqrt[2/Pi]*Sqrt[a + b*ArcSin[c*x]])/Sqrt[b]]*Sin[a/b])/(b^(3/2)*c)}
{1/((d + e*x^2)^1*(a + b*ArcSin[c*x])^(3/2)), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcSin[c*x])^(3/2)), x]}
{1/((d + e*x^2)^2*(a + b*ArcSin[c*x])^(3/2)), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcSin[c*x])^(3/2)), x]}
