(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form Trig[d+e x]^m (a+b Cot[d+e x]^n+c Cot[d+e x]^(2 n))^p*)


(* ::Section:: *)
(*Integrands of the form Sin[d+e x]^m (a+b Cot[d+e x]^n+c Cot[d+e x]^(2 n))^p*)


(* ::Section:: *)
(*Integrands of the form Cos[d+e x]^m (a+b Cot[d+e x]^n+c Cot[d+e x]^(2 n))^p*)


(* ::Section::Closed:: *)
(*Integrands of the form Cot[d+e x]^m (a+b Cot[d+e x]^n+c Cot[d+e x]^(2 n))^p*)


(* ::Subsection::Closed:: *)
(*Integrands of the form Cot[d+e x]^m (a+b Cot[d+e x]+c Cot[d+e x]^2)^(p/2)*)


{Cot[d + e*x]^5/Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 15, -((Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e)) + (Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) - (b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*c^(3/2)*e) + (b*(5*b^2 - 12*a*c)*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(16*c^(7/2)*e) + Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]/(c*e) - (Cot[d + e*x]^2*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(3*c*e) - ((15*b^2 - 16*a*c - 10*b*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(24*c^3*e)}
{Cot[d + e*x]^3/Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 11, (Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) - (Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) + (b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*c^(3/2)*e) - Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]/(c*e)}
{Cot[d + e*x]^1/Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 6, -((Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e)) + (Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e)}
{Tan[d + e*x]^1/Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 10, ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]/(Sqrt[a]*e) + (Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) - (Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e)}
{Tan[d + e*x]^3/Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 14, -(ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]/(Sqrt[a]*e)) + ((3*b^2 - 4*a*c)*ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(8*a^(5/2)*e) - (Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) + (Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2] + b*Cot[d + e*x])/(Sqrt[2]*Sqrt[a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*Sqrt[a^2 + b^2 - 2*a*c + c^2]*e) - (3*b*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]*Tan[d + e*x])/(4*a^2*e) + (Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]*Tan[d + e*x]^2)/(2*a*e)}


{Cot[d + e*x]^5*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 21, -((Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTan[(b^2 + (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e)) - (b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*Sqrt[c]*e) + (b*(b^2 - 4*a*c)*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(16*c^(5/2)*e) - (b*(7*b^2 - 12*a*c)*(b^2 - 4*a*c)*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(256*c^(9/2)*e) + (Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTanh[(b^2 + (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) + b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) - Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]/e - (b*(b + 2*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(8*c^2*e) + (b*(7*b^2 - 12*a*c)*(b + 2*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(128*c^4*e) + (a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2)/(3*c*e) - (Cot[d + e*x]^2*(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2))/(5*c*e) - ((35*b^2 - 32*a*c - 42*b*c*Cot[d + e*x])*(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2))/(240*c^3*e)}
{Cot[d + e*x]^3*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 16, (Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTan[(b^2 + (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) + (b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*Sqrt[c]*e) - (b*(b^2 - 4*a*c)*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(16*c^(5/2)*e) - (Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTanh[(b^2 + (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) + b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) + Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]/e + (b*(b + 2*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(8*c^2*e) - (a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2)/(3*c*e)}
{Cot[d + e*x]^1*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 10, -((Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTan[(b^2 + (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e)) - (b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*Sqrt[c]*e) + (Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTanh[(b^2 + (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) + b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) - Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]/e}
{Tan[d + e*x]^1*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 18, (Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTan[(b^2 + (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) + (Sqrt[a]*ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/e - (Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTanh[(b^2 + (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) + b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e)}
{Tan[d + e*x]^3*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2], x, 21, -((Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTan[(b^2 + (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e)) - (Sqrt[a]*ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/e - ((b^2 - 4*a*c)*ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(8*a^(3/2)*e) + (Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*ArcTanh[(b^2 + (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) + b*Sqrt[a^2 + b^2 - 2*a*c + c^2]*Cot[d + e*x])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*Sqrt[a^2 + b^2 + c*(c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - a*(2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(1/4)*e) + ((2*a + b*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]*Tan[d + e*x]^2)/(4*a*e)}


{Cot[d + e*x]^7/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 20, -((3*b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*c^(5/2)*e)) + (5*b*(7*b^2 - 12*a*c)*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(16*c^(9/2)*e) + (Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (2*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) + (2*Cot[d + e*x]^2*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - (2*Cot[d + e*x]^4*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) + (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - ((7*b^2 - 16*a*c)*Cot[d + e*x]^2*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(3*c^2*(b^2 - 4*a*c)*e) + (2*b*Cot[d + e*x]^3*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(c*(b^2 - 4*a*c)*e) + ((3*b^2 - 8*a*c - 2*b*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(c^2*(b^2 - 4*a*c)*e) - ((105*b^4 - 460*a*b^2*c + 256*a^2*c^2 - 2*b*c*(35*b^2 - 116*a*c)*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(24*c^4*(b^2 - 4*a*c)*e)}
{Cot[d + e*x]^5/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 14, (3*b*ArcTanh[(b + 2*c*Cot[d + e*x])/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(2*c^(5/2)*e) - (Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) + (Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) + (2*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - (2*Cot[d + e*x]^2*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - ((3*b^2 - 8*a*c - 2*b*c*Cot[d + e*x])*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])/(c^2*(b^2 - 4*a*c)*e)}
{Cot[d + e*x]^3/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 10, (Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (2*(2*a + b*Cot[d + e*x]))/((b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) + (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])}
{Cot[d + e*x]^1/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 7, -((Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e)) + (Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])}
{Tan[d + e*x]^1/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 13, ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]/(a^(3/2)*e) + (Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e) - (2*(b^2 - 2*a*c + b*c*Cot[d + e*x]))/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) + (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])}
{Tan[d + e*x]^3/(a + b*Cot[d + e*x] + c*Cot[d + e*x]^2)^(3/2), x, 18, -(ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]/(a^(3/2)*e)) + (3*(5*b^2 - 4*a*c)*ArcTanh[(2*a + b*Cot[d + e*x])/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])])/(8*a^(7/2)*e) - (1/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e))*(Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c + Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c - Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 + (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]) + (1/(Sqrt[2]*(a^2 + b^2 - 2*a*c + c^2)^(3/2)*e))*(Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*ArcTanh[(b^2 - (a - c)*(a - c - Sqrt[a^2 + b^2 - 2*a*c + c^2]) - b*(2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2])*Cot[d + e*x])/(Sqrt[2]*Sqrt[2*a - 2*c + Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a^2 - b^2 - 2*a*c + c^2 - (a - c)*Sqrt[a^2 + b^2 - 2*a*c + c^2]]*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2])]) + (2*(b^2 - 2*a*c + b*c*Cot[d + e*x]))/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - (2*(a*(b^2 - 2*(a - c)*c) + b*c*(a + c)*Cot[d + e*x]))/((b^2 + (a - c)^2)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) - (b*(15*b^2 - 52*a*c)*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]*Tan[d + e*x])/(4*a^3*(b^2 - 4*a*c)*e) - (2*(b^2 - 2*a*c + b*c*Cot[d + e*x])*Tan[d + e*x]^2)/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]) + ((5*b^2 - 12*a*c)*Sqrt[a + b*Cot[d + e*x] + c*Cot[d + e*x]^2]*Tan[d + e*x]^2)/(2*a^2*(b^2 - 4*a*c)*e)}


(* ::Subsection::Closed:: *)
(*Integrands of the form Cot[d+e x]^m (a+b Cot[d+e x]^2+c Cot[d+e x]^4)^(p/2)*)


{Cot[d + e*x]^5/Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 8, ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a - b + c]*e) + ((b + 2*c)*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*c^(3/2)*e) - Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]/(2*c*e)}
{Cot[d + e*x]^3/Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 7, -(ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a - b + c]*e)) - ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[c]*e)}
{Cot[d + e*x]^1/Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 4, ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a - b + c]*e)}
{Tan[d + e*x]^1/Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 8, ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a]*e) - ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a - b + c]*e)}
{Tan[d + e*x]^3/Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 11, -(ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a]*e)) - (b*ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*a^(3/2)*e) + ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*Sqrt[a - b + c]*e) + (Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]*Tan[d + e*x]^2)/(2*a*e)}


{Cot[d + e*x]^5*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 9, (Sqrt[a - b + c]*ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) - ((b^3 + 2*b^2*c - 4*b*(a - 2*c)*c - 8*c^2*(a + 2*c))*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(32*c^(5/2)*e) + (((b - 2*c)*(b + 4*c) + 2*c*(b + 2*c)*Cot[d + e*x]^2)*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])/(16*c^2*e) - (a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2)/(6*c*e)}
{Cot[d + e*x]^3*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 8, -((Sqrt[a - b + c]*ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e)) + ((b^2 + 4*b*c - 4*c*(a + 2*c))*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(16*c^(3/2)*e) - ((b - 4*c + 2*c*Cot[d + e*x]^2)*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])/(8*c*e)}
{Cot[d + e*x]^1*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 8, (Sqrt[a - b + c]*ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) - ((b - 2*c)*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*Sqrt[c]*e) - Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]/(2*e)}
{Tan[d + e*x]^1*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 10, (Sqrt[a]*ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) - (Sqrt[a - b + c]*ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) - (Sqrt[c]*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e)}
{Tan[d + e*x]^3*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4], x, 22, -((Sqrt[a]*ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e)) + (b*ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*Sqrt[a]*e) + (Sqrt[a - b + c]*ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) + (b*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*Sqrt[c]*e) - ((b - 2*c)*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*Sqrt[c]*e) - (Sqrt[c]*ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(2*e) + (Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]*Tan[d + e*x]^2)/(2*e)}


{Cot[d + e*x]^7/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 8, -(ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e)) - ArcTanh[(b + 2*c*Cot[d + e*x]^2)/(2*Sqrt[c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*c^(3/2)*e) - (a*(b^2 - a*(b + 2*c)) + (b^3 + 2*a^2*c - a*b*(b + 3*c))*Cot[d + e*x]^2)/(c*(a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])}
{Cot[d + e*x]^5/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 6, ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e) - (a*(2*a - b) + ((a - b)*b + 2*a*c)*Cot[d + e*x]^2)/((a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])}
{Cot[d + e*x]^3/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 6, -(ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e)) + (a*(b - 2*c) + (2*a - b)*c*Cot[d + e*x]^2)/((a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])}
{Cot[d + e*x]^1/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 6, ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e) - (b^2 - 2*a*c - b*c + (b - 2*c)*c*Cot[d + e*x]^2)/((a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])}
{Tan[d + e*x]^1/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 12, ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*a^(3/2)*e) - ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e) - (b^2 - 2*a*c + b*c*Cot[d + e*x]^2)/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]) + (b^2 - 2*a*c - b*c + (b - 2*c)*c*Cot[d + e*x]^2)/((a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])}
{Tan[d + e*x]^3/(a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4)^(3/2), x, 16, -(ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*a^(3/2)*e)) - (3*b*ArcTanh[(2*a + b*Cot[d + e*x]^2)/(2*Sqrt[a]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])])/(4*a^(5/2)*e) + ArcTanh[(2*a - b + (b - 2*c)*Cot[d + e*x]^2)/(2*Sqrt[a - b + c]*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4])]/(2*(a - b + c)^(3/2)*e) + (b^2 - 2*a*c + b*c*Cot[d + e*x]^2)/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]) - (b^2 - 2*a*c - b*c + (b - 2*c)*c*Cot[d + e*x]^2)/((a - b + c)*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]) - ((b^2 - 2*a*c + b*c*Cot[d + e*x]^2)*Tan[d + e*x]^2)/(a*(b^2 - 4*a*c)*e*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]) + ((3*b^2 - 8*a*c)*Sqrt[a + b*Cot[d + e*x]^2 + c*Cot[d + e*x]^4]*Tan[d + e*x]^2)/(2*a^2*(b^2 - 4*a*c)*e)}
