(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (e x)^m (a+b x^n)^p Sin[c+d x]*)


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^1)^p Sin[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x)*Sin[c + d*x], x, 11, (-24*b*Cos[c + d*x])/d^5 + (6*a*x*Cos[c + d*x])/d^3 + (12*b*x^2*Cos[c + d*x])/d^3 - (a*x^3*Cos[c + d*x])/d - (b*x^4*Cos[c + d*x])/d - (6*a*Sin[c + d*x])/d^4 - (24*b*x*Sin[c + d*x])/d^4 + (3*a*x^2*Sin[c + d*x])/d^2 + (4*b*x^3*Sin[c + d*x])/d^2}
{x^2*(a + b*x)*Sin[c + d*x], x, 9, (2*a*Cos[c + d*x])/d^3 + (6*b*x*Cos[c + d*x])/d^3 - (a*x^2*Cos[c + d*x])/d - (b*x^3*Cos[c + d*x])/d - (6*b*Sin[c + d*x])/d^4 + (2*a*x*Sin[c + d*x])/d^2 + (3*b*x^2*Sin[c + d*x])/d^2}
{x*(a + b*x)*Sin[c + d*x], x, 7, (2*b*Cos[c + d*x])/d^3 - (a*x*Cos[c + d*x])/d - (b*x^2*Cos[c + d*x])/d + (a*Sin[c + d*x])/d^2 + (2*b*x*Sin[c + d*x])/d^2}
{(a + b*x)*Sin[c + d*x], x, 2, -(((a + b*x)*Cos[c + d*x])/d) + (b*Sin[c + d*x])/d^2}
{((a + b*x)*Sin[c + d*x])/x, x, 6, -((b*Cos[c + d*x])/d) + a*CosIntegral[d*x]*Sin[c] + a*Cos[c]*SinIntegral[d*x]}
{((a + b*x)*Sin[c + d*x])/x^2, x, 9, a*d*Cos[c]*CosIntegral[d*x] + b*CosIntegral[d*x]*Sin[c] - (a*Sin[c + d*x])/x + b*Cos[c]*SinIntegral[d*x] - a*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x)*Sin[c + d*x])/x^3, x, 11, -(a*d*Cos[c + d*x])/(2*x) + b*d*Cos[c]*CosIntegral[d*x] - (a*d^2*CosIntegral[d*x]*Sin[c])/2 - (a*Sin[c + d*x])/(2*x^2) - (b*Sin[c + d*x])/x - (a*d^2*Cos[c]*SinIntegral[d*x])/2 - b*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x)*Sin[c + d*x])/x^4, x, 13, -(a*d*Cos[c + d*x])/(6*x^2) - (b*d*Cos[c + d*x])/(2*x) - (a*d^3*Cos[c]*CosIntegral[d*x])/6 - (b*d^2*CosIntegral[d*x]*Sin[c])/2 - (a*Sin[c + d*x])/(3*x^3) - (b*Sin[c + d*x])/(2*x^2) + (a*d^2*Sin[c + d*x])/(6*x) - (b*d^2*Cos[c]*SinIntegral[d*x])/2 + (a*d^3*Sin[c]*SinIntegral[d*x])/6}
{((a + b*x)*Sin[c + d*x])/x^5, x, 15, -(a*d*Cos[c + d*x])/(12*x^3) - (b*d*Cos[c + d*x])/(6*x^2) + (a*d^3*Cos[c + d*x])/(24*x) - (b*d^3*Cos[c]*CosIntegral[d*x])/6 + (a*d^4*CosIntegral[d*x]*Sin[c])/24 - (a*Sin[c + d*x])/(4*x^4) - (b*Sin[c + d*x])/(3*x^3) + (a*d^2*Sin[c + d*x])/(24*x^2) + (b*d^2*Sin[c + d*x])/(6*x) + (a*d^4*Cos[c]*SinIntegral[d*x])/24 + (b*d^3*Sin[c]*SinIntegral[d*x])/6}


{x^2*(a + b*x)^2*Sin[c + d*x], x, 14, (-24*b^2*Cos[c + d*x])/d^5 + (2*a^2*Cos[c + d*x])/d^3 + (12*a*b*x*Cos[c + d*x])/d^3 + (12*b^2*x^2*Cos[c + d*x])/d^3 - (a^2*x^2*Cos[c + d*x])/d - (2*a*b*x^3*Cos[c + d*x])/d - (b^2*x^4*Cos[c + d*x])/d - (12*a*b*Sin[c + d*x])/d^4 - (24*b^2*x*Sin[c + d*x])/d^4 + (2*a^2*x*Sin[c + d*x])/d^2 + (6*a*b*x^2*Sin[c + d*x])/d^2 + (4*b^2*x^3*Sin[c + d*x])/d^2}
{x*(a + b*x)^2*Sin[c + d*x], x, 11, (4*a*b*Cos[c + d*x])/d^3 + (6*b^2*x*Cos[c + d*x])/d^3 - (a^2*x*Cos[c + d*x])/d - (2*a*b*x^2*Cos[c + d*x])/d - (b^2*x^3*Cos[c + d*x])/d - (6*b^2*Sin[c + d*x])/d^4 + (a^2*Sin[c + d*x])/d^2 + (4*a*b*x*Sin[c + d*x])/d^2 + (3*b^2*x^2*Sin[c + d*x])/d^2}
{(a + b*x)^2*Sin[c + d*x], x, 3, (2*b^2*Cos[c + d*x])/d^3 - ((a + b*x)^2*Cos[c + d*x])/d + (2*b*(a + b*x)*Sin[c + d*x])/d^2}
{((a + b*x)^2*Sin[c + d*x])/x, x, 8, (-2*a*b*Cos[c + d*x])/d - (b^2*x*Cos[c + d*x])/d + a^2*CosIntegral[d*x]*Sin[c] + (b^2*Sin[c + d*x])/d^2 + a^2*Cos[c]*SinIntegral[d*x]}
{((a + b*x)^2*Sin[c + d*x])/x^2, x, 10, -((b^2*Cos[c + d*x])/d) + a^2*d*Cos[c]*CosIntegral[d*x] + 2*a*b*CosIntegral[d*x]*Sin[c] - (a^2*Sin[c + d*x])/x + 2*a*b*Cos[c]*SinIntegral[d*x] - a^2*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x)^2*Sin[c + d*x])/x^3, x, 14, -(a^2*d*Cos[c + d*x])/(2*x) + 2*a*b*d*Cos[c]*CosIntegral[d*x] + b^2*CosIntegral[d*x]*Sin[c] - (a^2*d^2*CosIntegral[d*x]*Sin[c])/2 - (a^2*Sin[c + d*x])/(2*x^2) - (2*a*b*Sin[c + d*x])/x + b^2*Cos[c]*SinIntegral[d*x] - (a^2*d^2*Cos[c]*SinIntegral[d*x])/2 - 2*a*b*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x)^2*Sin[c + d*x])/x^4, x, 17, -(a^2*d*Cos[c + d*x])/(6*x^2) - (a*b*d*Cos[c + d*x])/x + b^2*d*Cos[c]*CosIntegral[d*x] - (a^2*d^3*Cos[c]*CosIntegral[d*x])/6 - a*b*d^2*CosIntegral[d*x]*Sin[c] - (a^2*Sin[c + d*x])/(3*x^3) - (a*b*Sin[c + d*x])/x^2 - (b^2*Sin[c + d*x])/x + (a^2*d^2*Sin[c + d*x])/(6*x) - a*b*d^2*Cos[c]*SinIntegral[d*x] - b^2*d*Sin[c]*SinIntegral[d*x] + (a^2*d^3*Sin[c]*SinIntegral[d*x])/6}
{((a + b*x)^2*Sin[c + d*x])/x^5, x, 20, -(a^2*d*Cos[c + d*x])/(12*x^3) - (a*b*d*Cos[c + d*x])/(3*x^2) - (b^2*d*Cos[c + d*x])/(2*x) + (a^2*d^3*Cos[c + d*x])/(24*x) - (a*b*d^3*Cos[c]*CosIntegral[d*x])/3 - (b^2*d^2*CosIntegral[d*x]*Sin[c])/2 + (a^2*d^4*CosIntegral[d*x]*Sin[c])/24 - (a^2*Sin[c + d*x])/(4*x^4) - (2*a*b*Sin[c + d*x])/(3*x^3) - (b^2*Sin[c + d*x])/(2*x^2) + (a^2*d^2*Sin[c + d*x])/(24*x^2) + (a*b*d^2*Sin[c + d*x])/(3*x) - (b^2*d^2*Cos[c]*SinIntegral[d*x])/2 + (a^2*d^4*Cos[c]*SinIntegral[d*x])/24 + (a*b*d^3*Sin[c]*SinIntegral[d*x])/3}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Sin[c + d*x])/(a + b*x), x, 15, (-2*a*Cos[c + d*x])/(b^2*d^3) + (a^3*Cos[c + d*x])/(b^4*d) + (6*x*Cos[c + d*x])/(b*d^3) - (a^2*x*Cos[c + d*x])/(b^3*d) + (a*x^2*Cos[c + d*x])/(b^2*d) - (x^3*Cos[c + d*x])/(b*d) + (a^4*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^5 - (6*Sin[c + d*x])/(b*d^4) + (a^2*Sin[c + d*x])/(b^3*d^2) - (2*a*x*Sin[c + d*x])/(b^2*d^2) + (3*x^2*Sin[c + d*x])/(b*d^2) + (a^4*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^5}
{(x^3*Sin[c + d*x])/(a + b*x), x, 11, (2*Cos[c + d*x])/(b*d^3) - (a^2*Cos[c + d*x])/(b^3*d) + (a*x*Cos[c + d*x])/(b^2*d) - (x^2*Cos[c + d*x])/(b*d) - (a^3*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^4 - (a*Sin[c + d*x])/(b^2*d^2) + (2*x*Sin[c + d*x])/(b*d^2) - (a^3*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^4}
{(x^2*Sin[c + d*x])/(a + b*x), x, 8, (a*Cos[c + d*x])/(b^2*d) - (x*Cos[c + d*x])/(b*d) + (a^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^3 + Sin[c + d*x]/(b*d^2) + (a^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^3}
{(x*Sin[c + d*x])/(a + b*x), x, 6, -(Cos[c + d*x]/(b*d)) - (a*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^2 - (a*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^2}
{Sin[c + d*x]/(a + b*x), x, 3, (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b + (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b}
{Sin[c + d*x]/(x*(a + b*x)), x, 8, (CosIntegral[d*x]*Sin[c])/a - (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a + (Cos[c]*SinIntegral[d*x])/a - (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a}
{Sin[c + d*x]/(x^2*(a + b*x)), x, 12, (d*Cos[c]*CosIntegral[d*x])/a - (b*CosIntegral[d*x]*Sin[c])/a^2 + (b*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^2 - Sin[c + d*x]/(a*x) - (b*Cos[c]*SinIntegral[d*x])/a^2 - (d*Sin[c]*SinIntegral[d*x])/a + (b*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^2}
{Sin[c + d*x]/(x^3*(a + b*x)), x, 17, -(d*Cos[c + d*x])/(2*a*x) - (b*d*Cos[c]*CosIntegral[d*x])/a^2 + (b^2*CosIntegral[d*x]*Sin[c])/a^3 - (d^2*CosIntegral[d*x]*Sin[c])/(2*a) - (b^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^3 - Sin[c + d*x]/(2*a*x^2) + (b*Sin[c + d*x])/(a^2*x) + (b^2*Cos[c]*SinIntegral[d*x])/a^3 - (d^2*Cos[c]*SinIntegral[d*x])/(2*a) + (b*d*Sin[c]*SinIntegral[d*x])/a^2 - (b^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^3}


{(x^4*Sin[c + d*x])/(a + b*x)^2, x, 15, (2*Cos[c + d*x])/(b^2*d^3) - (3*a^2*Cos[c + d*x])/(b^4*d) + (2*a*x*Cos[c + d*x])/(b^3*d) - (x^2*Cos[c + d*x])/(b^2*d) + (a^4*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^6 - (4*a^3*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^5 - (2*a*Sin[c + d*x])/(b^3*d^2) + (2*x*Sin[c + d*x])/(b^2*d^2) - (a^4*Sin[c + d*x])/(b^5*(a + b*x)) - (4*a^3*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^5 - (a^4*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^6}
{(x^3*Sin[c + d*x])/(a + b*x)^2, x, 12, (2*a*Cos[c + d*x])/(b^3*d) - (x*Cos[c + d*x])/(b^2*d) - (a^3*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^5 + (3*a^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^4 + Sin[c + d*x]/(b^2*d^2) + (a^3*Sin[c + d*x])/(b^4*(a + b*x)) + (3*a^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^4 + (a^3*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^5}
{(x^2*Sin[c + d*x])/(a + b*x)^2, x, 10, -(Cos[c + d*x]/(b^2*d)) + (a^2*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^4 - (2*a*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^3 - (a^2*Sin[c + d*x])/(b^3*(a + b*x)) - (2*a*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^3 - (a^2*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^4}
{(x*Sin[c + d*x])/(a + b*x)^2, x, 9, -((a*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^3) + (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^2 + (a*Sin[c + d*x])/(b^2*(a + b*x)) + (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^2 + (a*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^3}
{Sin[c + d*x]/(a + b*x)^2, x, 4, (d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^2 - Sin[c + d*x]/(b*(a + b*x)) - (d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^2}
{Sin[c + d*x]/(x*(a + b*x)^2), x, 12, -((d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/(a*b)) + (CosIntegral[d*x]*Sin[c])/a^2 - (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^2 + Sin[c + d*x]/(a*(a + b*x)) + (Cos[c]*SinIntegral[d*x])/a^2 - (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^2 + (d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(a*b)}
{Sin[c + d*x]/(x^2*(a + b*x)^2), x, 16, (d*Cos[c]*CosIntegral[d*x])/a^2 + (d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/a^2 - (2*b*CosIntegral[d*x]*Sin[c])/a^3 + (2*b*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^3 - Sin[c + d*x]/(a^2*x) - (b*Sin[c + d*x])/(a^2*(a + b*x)) - (2*b*Cos[c]*SinIntegral[d*x])/a^3 - (d*Sin[c]*SinIntegral[d*x])/a^2 + (2*b*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^3 - (d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^2}


{(x^3*Sin[c + d*x])/(a + b*x)^3, x, 15, -(Cos[c + d*x]/(b^3*d)) + (a^3*d*Cos[c + d*x])/(2*b^5*(a + b*x)) + (3*a^2*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^5 - (3*a*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^4 + (a^3*d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*b^6) + (a^3*Sin[c + d*x])/(2*b^4*(a + b*x)^2) - (3*a^2*Sin[c + d*x])/(b^4*(a + b*x)) - (3*a*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^4 + (a^3*d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*b^6) - (3*a^2*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^5}
{(x^2*Sin[c + d*x])/(a + b*x)^3, x, 14, -(a^2*d*Cos[c + d*x])/(2*b^4*(a + b*x)) - (2*a*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^4 + (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/b^3 - (a^2*d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*b^5) - (a^2*Sin[c + d*x])/(2*b^3*(a + b*x)^2) + (2*a*Sin[c + d*x])/(b^3*(a + b*x)) + (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^3 - (a^2*d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*b^5) + (2*a*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^4}
{(x*Sin[c + d*x])/(a + b*x)^3, x, 11, (a*d*Cos[c + d*x])/(2*b^3*(a + b*x)) + (d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/b^3 + (a*d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*b^4) + (a*Sin[c + d*x])/(2*b^2*(a + b*x)^2) - Sin[c + d*x]/(b^2*(a + b*x)) + (a*d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*b^4) - (d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/b^3}
{Sin[c + d*x]/(a + b*x)^3, x, 5, -(d*Cos[c + d*x])/(2*b^2*(a + b*x)) - (d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*b^3) - Sin[c + d*x]/(2*b*(a + b*x)^2) - (d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*b^3)}
{Sin[c + d*x]/(x*(a + b*x)^3), x, 17, (d*Cos[c + d*x])/(2*a*b*(a + b*x)) - (d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/(a^2*b) + (CosIntegral[d*x]*Sin[c])/a^3 - (CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^3 + (d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*a*b^2) + Sin[c + d*x]/(2*a*(a + b*x)^2) + Sin[c + d*x]/(a^2*(a + b*x)) + (Cos[c]*SinIntegral[d*x])/a^3 - (Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^3 + (d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*a*b^2) + (d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(a^2*b)}
{Sin[c + d*x]/(x^2*(a + b*x)^3), x, 21, -(d*Cos[c + d*x])/(2*a^2*(a + b*x)) + (d*Cos[c]*CosIntegral[d*x])/a^3 + (2*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/a^3 - (3*b*CosIntegral[d*x]*Sin[c])/a^4 + (3*b*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^4 - (d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*a^2*b) - Sin[c + d*x]/(a^3*x) - (b*Sin[c + d*x])/(2*a^2*(a + b*x)^2) - (2*b*Sin[c + d*x])/(a^3*(a + b*x)) - (3*b*Cos[c]*SinIntegral[d*x])/a^4 - (d*Sin[c]*SinIntegral[d*x])/a^3 + (3*b*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^4 - (d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*a^2*b) - (2*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^3}
{Sin[c + d*x]/(x^3*(a + b*x)^3), x, 26, -(d*Cos[c + d*x])/(2*a^3*x) + (b*d*Cos[c + d*x])/(2*a^3*(a + b*x)) - (3*b*d*Cos[c]*CosIntegral[d*x])/a^4 - (3*b*d*Cos[c - (a*d)/b]*CosIntegral[(a*d)/b + d*x])/a^4 + (6*b^2*CosIntegral[d*x]*Sin[c])/a^5 - (d^2*CosIntegral[d*x]*Sin[c])/(2*a^3) - (6*b^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/a^5 + (d^2*CosIntegral[(a*d)/b + d*x]*Sin[c - (a*d)/b])/(2*a^3) - Sin[c + d*x]/(2*a^3*x^2) + (3*b*Sin[c + d*x])/(a^4*x) + (b^2*Sin[c + d*x])/(2*a^3*(a + b*x)^2) + (3*b^2*Sin[c + d*x])/(a^4*(a + b*x)) + (6*b^2*Cos[c]*SinIntegral[d*x])/a^5 - (d^2*Cos[c]*SinIntegral[d*x])/(2*a^3) + (3*b*d*Sin[c]*SinIntegral[d*x])/a^4 - (6*b^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^5 + (d^2*Cos[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/(2*a^3) + (3*b*d*Sin[c - (a*d)/b]*SinIntegral[(a*d)/b + d*x])/a^4}


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^2)^p Sin[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x^2)*Sin[c + d*x], x, 12, (-120*b*x*Cos[c + d*x])/d^5 + (6*a*x*Cos[c + d*x])/d^3 + (20*b*x^3*Cos[c + d*x])/d^3 - (a*x^3*Cos[c + d*x])/d - (b*x^5*Cos[c + d*x])/d + (120*b*Sin[c + d*x])/d^6 - (6*a*Sin[c + d*x])/d^4 - (60*b*x^2*Sin[c + d*x])/d^4 + (3*a*x^2*Sin[c + d*x])/d^2 + (5*b*x^4*Sin[c + d*x])/d^2}
{x^2*(a + b*x^2)*Sin[c + d*x], x, 10, (-24*b*Cos[c + d*x])/d^5 + (2*a*Cos[c + d*x])/d^3 + (12*b*x^2*Cos[c + d*x])/d^3 - (a*x^2*Cos[c + d*x])/d - (b*x^4*Cos[c + d*x])/d - (24*b*x*Sin[c + d*x])/d^4 + (2*a*x*Sin[c + d*x])/d^2 + (4*b*x^3*Sin[c + d*x])/d^2}
{x*(a + b*x^2)*Sin[c + d*x], x, 8, (6*b*x*Cos[c + d*x])/d^3 - (a*x*Cos[c + d*x])/d - (b*x^3*Cos[c + d*x])/d - (6*b*Sin[c + d*x])/d^4 + (a*Sin[c + d*x])/d^2 + (3*b*x^2*Sin[c + d*x])/d^2}
{(a + b*x^2)*Sin[c + d*x], x, 6, (2*b*Cos[c + d*x])/d^3 - (a*Cos[c + d*x])/d - (b*x^2*Cos[c + d*x])/d + (2*b*x*Sin[c + d*x])/d^2}
{((a + b*x^2)*Sin[c + d*x])/x, x, 7, -((b*x*Cos[c + d*x])/d) + a*CosIntegral[d*x]*Sin[c] + (b*Sin[c + d*x])/d^2 + a*Cos[c]*SinIntegral[d*x]}
{((a + b*x^2)*Sin[c + d*x])/x^2, x, 7, -((b*Cos[c + d*x])/d) + a*d*Cos[c]*CosIntegral[d*x] - (a*Sin[c + d*x])/x - a*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x^2)*Sin[c + d*x])/x^3, x, 10, -(a*d*Cos[c + d*x])/(2*x) + b*CosIntegral[d*x]*Sin[c] - (a*d^2*CosIntegral[d*x]*Sin[c])/2 - (a*Sin[c + d*x])/(2*x^2) + b*Cos[c]*SinIntegral[d*x] - (a*d^2*Cos[c]*SinIntegral[d*x])/2}
{((a + b*x^2)*Sin[c + d*x])/x^4, x, 12, -(a*d*Cos[c + d*x])/(6*x^2) + b*d*Cos[c]*CosIntegral[d*x] - (a*d^3*Cos[c]*CosIntegral[d*x])/6 - (a*Sin[c + d*x])/(3*x^3) - (b*Sin[c + d*x])/x + (a*d^2*Sin[c + d*x])/(6*x) - b*d*Sin[c]*SinIntegral[d*x] + (a*d^3*Sin[c]*SinIntegral[d*x])/6}
{((a + b*x^2)*Sin[c + d*x])/x^5, x, 14, -(a*d*Cos[c + d*x])/(12*x^3) - (b*d*Cos[c + d*x])/(2*x) + (a*d^3*Cos[c + d*x])/(24*x) - (b*d^2*CosIntegral[d*x]*Sin[c])/2 + (a*d^4*CosIntegral[d*x]*Sin[c])/24 - (a*Sin[c + d*x])/(4*x^4) - (b*Sin[c + d*x])/(2*x^2) + (a*d^2*Sin[c + d*x])/(24*x^2) - (b*d^2*Cos[c]*SinIntegral[d*x])/2 + (a*d^4*Cos[c]*SinIntegral[d*x])/24}


{x^2*(a + b*x^2)^2*Sin[c + d*x], x, 17, (720*b^2*Cos[c + d*x])/d^7 - (48*a*b*Cos[c + d*x])/d^5 + (2*a^2*Cos[c + d*x])/d^3 - (360*b^2*x^2*Cos[c + d*x])/d^5 + (24*a*b*x^2*Cos[c + d*x])/d^3 - (a^2*x^2*Cos[c + d*x])/d + (30*b^2*x^4*Cos[c + d*x])/d^3 - (2*a*b*x^4*Cos[c + d*x])/d - (b^2*x^6*Cos[c + d*x])/d + (720*b^2*x*Sin[c + d*x])/d^6 - (48*a*b*x*Sin[c + d*x])/d^4 + (2*a^2*x*Sin[c + d*x])/d^2 - (120*b^2*x^3*Sin[c + d*x])/d^4 + (8*a*b*x^3*Sin[c + d*x])/d^2 + (6*b^2*x^5*Sin[c + d*x])/d^2}
{x*(a + b*x^2)^2*Sin[c + d*x], x, 14, (-120*b^2*x*Cos[c + d*x])/d^5 + (12*a*b*x*Cos[c + d*x])/d^3 - (a^2*x*Cos[c + d*x])/d + (20*b^2*x^3*Cos[c + d*x])/d^3 - (2*a*b*x^3*Cos[c + d*x])/d - (b^2*x^5*Cos[c + d*x])/d + (120*b^2*Sin[c + d*x])/d^6 - (12*a*b*Sin[c + d*x])/d^4 + (a^2*Sin[c + d*x])/d^2 - (60*b^2*x^2*Sin[c + d*x])/d^4 + (6*a*b*x^2*Sin[c + d*x])/d^2 + (5*b^2*x^4*Sin[c + d*x])/d^2}
{(a + b*x^2)^2*Sin[c + d*x], x, 11, (-24*b^2*Cos[c + d*x])/d^5 + (4*a*b*Cos[c + d*x])/d^3 - (a^2*Cos[c + d*x])/d + (12*b^2*x^2*Cos[c + d*x])/d^3 - (2*a*b*x^2*Cos[c + d*x])/d - (b^2*x^4*Cos[c + d*x])/d - (24*b^2*x*Sin[c + d*x])/d^4 + (4*a*b*x*Sin[c + d*x])/d^2 + (4*b^2*x^3*Sin[c + d*x])/d^2}
{((a + b*x^2)^2*Sin[c + d*x])/x, x, 11, (6*b^2*x*Cos[c + d*x])/d^3 - (2*a*b*x*Cos[c + d*x])/d - (b^2*x^3*Cos[c + d*x])/d + a^2*CosIntegral[d*x]*Sin[c] - (6*b^2*Sin[c + d*x])/d^4 + (2*a*b*Sin[c + d*x])/d^2 + (3*b^2*x^2*Sin[c + d*x])/d^2 + a^2*Cos[c]*SinIntegral[d*x]}
{((a + b*x^2)^2*Sin[c + d*x])/x^2, x, 10, (2*b^2*Cos[c + d*x])/d^3 - (2*a*b*Cos[c + d*x])/d - (b^2*x^2*Cos[c + d*x])/d + a^2*d*Cos[c]*CosIntegral[d*x] - (a^2*Sin[c + d*x])/x + (2*b^2*x*Sin[c + d*x])/d^2 - a^2*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x^2)^2*Sin[c + d*x])/x^3, x, 12, -(a^2*d*Cos[c + d*x])/(2*x) - (b^2*x*Cos[c + d*x])/d + 2*a*b*CosIntegral[d*x]*Sin[c] - (a^2*d^2*CosIntegral[d*x]*Sin[c])/2 + (b^2*Sin[c + d*x])/d^2 - (a^2*Sin[c + d*x])/(2*x^2) + 2*a*b*Cos[c]*SinIntegral[d*x] - (a^2*d^2*Cos[c]*SinIntegral[d*x])/2}
{((a + b*x^2)^2*Sin[c + d*x])/x^4, x, 13, -((b^2*Cos[c + d*x])/d) - (a^2*d*Cos[c + d*x])/(6*x^2) + 2*a*b*d*Cos[c]*CosIntegral[d*x] - (a^2*d^3*Cos[c]*CosIntegral[d*x])/6 - (a^2*Sin[c + d*x])/(3*x^3) - (2*a*b*Sin[c + d*x])/x + (a^2*d^2*Sin[c + d*x])/(6*x) - 2*a*b*d*Sin[c]*SinIntegral[d*x] + (a^2*d^3*Sin[c]*SinIntegral[d*x])/6}
{((a + b*x^2)^2*Sin[c + d*x])/x^5, x, 17, -(a^2*d*Cos[c + d*x])/(12*x^3) - (a*b*d*Cos[c + d*x])/x + (a^2*d^3*Cos[c + d*x])/(24*x) + b^2*CosIntegral[d*x]*Sin[c] - a*b*d^2*CosIntegral[d*x]*Sin[c] + (a^2*d^4*CosIntegral[d*x]*Sin[c])/24 - (a^2*Sin[c + d*x])/(4*x^4) - (a*b*Sin[c + d*x])/x^2 + (a^2*d^2*Sin[c + d*x])/(24*x^2) + b^2*Cos[c]*SinIntegral[d*x] - a*b*d^2*Cos[c]*SinIntegral[d*x] + (a^2*d^4*Cos[c]*SinIntegral[d*x])/24}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Sin[c + d*x])/(a + b*x^2), x, 14, (2*Cos[c + d*x])/(b*d^3) + (a*Cos[c + d*x])/(b^2*d) - (x^2*Cos[c + d*x])/(b*d) - ((-a)^(3/2)*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*b^(5/2)) + ((-a)^(3/2)*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*b^(5/2)) + (2*x*Sin[c + d*x])/(b*d^2) - ((-a)^(3/2)*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(5/2)) - ((-a)^(3/2)*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(5/2))}
{(x^3*Sin[c + d*x])/(a + b*x^2), x, 12, -((x*Cos[c + d*x])/(b*d)) - (a*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*b^2) - (a*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*b^2) + Sin[c + d*x]/(b*d^2) + (a*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) - (a*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2)}
{(x^2*Sin[c + d*x])/(a + b*x^2), x, 11, -(Cos[c + d*x]/(b*d)) - (Sqrt[-a]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*b^(3/2)) + (Sqrt[-a]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*b^(3/2)) - (Sqrt[-a]*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^(3/2)) - (Sqrt[-a]*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^(3/2))}
{(x*Sin[c + d*x])/(a + b*x^2), x, 8, (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*b) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*b) - (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b) + (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b)}
{Sin[c + d*x]/(a + b*x^2), x, 8, -(CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*Sqrt[-a]*Sqrt[b]) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*Sqrt[-a]*Sqrt[b]) - (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*Sqrt[-a]*Sqrt[b]) - (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*Sqrt[-a]*Sqrt[b])}
{Sin[c + d*x]/(x*(a + b*x^2)), x, 13, (CosIntegral[d*x]*Sin[c])/a - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*a) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*a) + (Cos[c]*SinIntegral[d*x])/a + (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a) - (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a)}
{Sin[c + d*x]/(x^2*(a + b*x^2)), x, 14, (d*Cos[c]*CosIntegral[d*x])/a - (Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*(-a)^(3/2)) + (Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*(-a)^(3/2)) - Sin[c + d*x]/(a*x) - (d*Sin[c]*SinIntegral[d*x])/a - (Sqrt[b]*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*(-a)^(3/2)) - (Sqrt[b]*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*(-a)^(3/2))}
{Sin[c + d*x]/(x^3*(a + b*x^2)), x, 18, -(d*Cos[c + d*x])/(2*a*x) - (b*CosIntegral[d*x]*Sin[c])/a^2 - (d^2*CosIntegral[d*x]*Sin[c])/(2*a) + (b*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*a^2) + (b*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*a^2) - Sin[c + d*x]/(2*a*x^2) - (b*Cos[c]*SinIntegral[d*x])/a^2 - (d^2*Cos[c]*SinIntegral[d*x])/(2*a) - (b*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) + (b*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2)}


{(x^4*Sin[c + d*x])/(a + b*x^2)^2, x, 24, -(Cos[c + d*x]/(b^2*d)) - (a*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^3) - (a*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^3) - (3*Sqrt[-a]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*b^(5/2)) + (3*Sqrt[-a]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*b^(5/2)) + (x*Sin[c + d*x])/(2*b^2) - (x^3*Sin[c + d*x])/(2*b*(a + b*x^2)) - (3*Sqrt[-a]*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) - (a*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^3) - (3*Sqrt[-a]*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2)) + (a*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^3)}
{(x^3*Sin[c + d*x])/(a + b*x^2)^2, x, 20, (Sqrt[-a]*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) - (Sqrt[-a]*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2)) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*b^2) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*b^2) + Sin[c + d*x]/(2*b^2) - (x^2*Sin[c + d*x])/(2*b*(a + b*x^2)) - (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*b^2) + (Sqrt[-a]*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^(5/2)) + (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*b^2) + (Sqrt[-a]*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^(5/2))}
{(x^2*Sin[c + d*x])/(a + b*x^2)^2, x, 17, (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^2) + (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^2) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*Sqrt[-a]*b^(3/2)) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*Sqrt[-a]*b^(3/2)) - (x*Sin[c + d*x])/(2*b*(a + b*x^2)) - (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) + (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*b^2) - (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2)) - (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*b^2)}
{(x*Sin[c + d*x])/(a + b*x^2)^2, x, 9, (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) - (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2)) - Sin[c + d*x]/(2*b*(a + b*x^2)) + (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*Sqrt[-a]*b^(3/2)) + (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*Sqrt[-a]*b^(3/2))}
{Sin[c + d*x]/(a + b*x^2)^2, x, 18, -(d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a*b) - (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a*b) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(3/2)*Sqrt[b]) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(3/2)*Sqrt[b]) - Sin[c + d*x]/(4*a*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) + Sin[c + d*x]/(4*a*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) + (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a*b) + (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b]) + (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a*b)}
{Sin[c + d*x]/(x*(a + b*x^2)^2), x, 22, (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b]) + (CosIntegral[d*x]*Sin[c])/a^2 - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*a^2) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*a^2) + Sin[c + d*x]/(2*a*(a + b*x^2)) + (Cos[c]*SinIntegral[d*x])/a^2 + (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^2) + (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(3/2)*Sqrt[b]) - (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^2) + (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(3/2)*Sqrt[b])}
{Sin[c + d*x]/(x^2*(a + b*x^2)^2), x, 32, (d*Cos[c]*CosIntegral[d*x])/a^2 + (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a^2) + (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a^2) + (3*Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(5/2)) - (3*Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(4*(-a)^(5/2)) - Sin[c + d*x]/(a^2*x) + (Sqrt[b]*Sin[c + d*x])/(4*a^2*(Sqrt[-a] - Sqrt[b]*x)) - (Sqrt[b]*Sin[c + d*x])/(4*a^2*(Sqrt[-a] + Sqrt[b]*x)) - (d*Sin[c]*SinIntegral[d*x])/a^2 + (3*Sqrt[b]*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*(-a)^(5/2)) + (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(4*a^2) + (3*Sqrt[b]*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*(-a)^(5/2)) - (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(4*a^2)}


{(x^3*Sin[c + d*x])/(a + b*x^2)^3, x, 27, -(d*x*Cos[c + d*x])/(8*b^2*(a + b*x^2)) + (3*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) - (3*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2)) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*b^3) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*b^3) - (x^2*Sin[c + d*x])/(4*b*(a + b*x^2)^2) - Sin[c + d*x]/(4*b^2*(a + b*x^2)) + (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*b^3) + (3*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) - (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*b^3) + (3*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2))}
{(x^2*Sin[c + d*x])/(a + b*x^2)^3, x, 28, -(d*Cos[c + d*x])/(8*b^2*(a + b*x^2)) - (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) - (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2) + (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*Sqrt[-a]*b^(5/2)) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*Sqrt[-a]*b^(5/2)) - Sin[c + d*x]/(16*a*b^(3/2)*(Sqrt[-a] - Sqrt[b]*x)) + Sin[c + d*x]/(16*a*b^(3/2)*(Sqrt[-a] + Sqrt[b]*x)) - (x*Sin[c + d*x])/(4*b*(a + b*x^2)^2) + (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*Sqrt[-a]*b^(5/2)) - (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) + (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*Sqrt[-a]*b^(5/2)) + (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2)}
{(x*Sin[c + d*x])/(a + b*x^2)^3, x, 19, -(d*Cos[c + d*x])/(16*a*b^(3/2)*(Sqrt[-a] - Sqrt[b]*x)) + (d*Cos[c + d*x])/(16*a*b^(3/2)*(Sqrt[-a] + Sqrt[b]*x)) - (d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a*b^2) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a*b^2) - Sin[c + d*x]/(4*b*(a + b*x^2)^2) - (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a*b^2) - (d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) + (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a*b^2) - (d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2))}
{Sin[c + d*x]/(a + b*x^2)^3, x, 28, (d*Cos[c + d*x])/(16*(-a)^(3/2)*b*(Sqrt[-a] - Sqrt[b]*x)) + (d*Cos[c + d*x])/(16*(-a)^(3/2)*b*(Sqrt[-a] + Sqrt[b]*x)) - (3*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) - (3*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b) - (3*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) + (3*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(3/2)*b^(3/2)) - Sin[c + d*x]/(16*(-a)^(3/2)*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)^2) - (3*Sin[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) + Sin[c + d*x]/(16*(-a)^(3/2)*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)^2) + (3*Sin[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) - (3*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(3/2)*b^(3/2)) - (3*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) - (3*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(3/2)*b^(3/2)) + (3*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b)}
{Sin[c + d*x]/(x*(a + b*x^2)^3), x, 41, (d*Cos[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] - Sqrt[b]*x)) - (d*Cos[c + d*x])/(16*a^2*Sqrt[b]*(Sqrt[-a] + Sqrt[b]*x)) - (5*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (5*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (CosIntegral[d*x]*Sin[c])/a^3 - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*a^3) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a^2*b) - (CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*a^3) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a^2*b) + Sin[c + d*x]/(4*a*(a + b*x^2)^2) + Sin[c + d*x]/(2*a^2*(a + b*x^2)) + (Cos[c]*SinIntegral[d*x])/a^3 + (Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^3) + (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^2*b) - (5*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^3) - (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^2*b) - (5*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b])}
{Sin[c + d*x]/(x^2*(a + b*x^2)^3), x, 60, (d*Cos[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] - Sqrt[b]*x)) + (d*Cos[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] + Sqrt[b]*x)) + (d*Cos[c]*CosIntegral[d*x])/a^3 + (7*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) + (7*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3) - (15*Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(7/2)) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) + (15*Sqrt[b]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(7/2)) - (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*(-a)^(5/2)*Sqrt[b]) - Sin[c + d*x]/(a^3*x) - (Sqrt[b]*Sin[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] - Sqrt[b]*x)^2) + (7*Sqrt[b]*Sin[c + d*x])/(16*a^3*(Sqrt[-a] - Sqrt[b]*x)) + (Sqrt[b]*Sin[c + d*x])/(16*(-a)^(5/2)*(Sqrt[-a] + Sqrt[b]*x)^2) - (7*Sqrt[b]*Sin[c + d*x])/(16*a^3*(Sqrt[-a] + Sqrt[b]*x)) - (d*Sin[c]*SinIntegral[d*x])/a^3 - (15*Sqrt[b]*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) + (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(5/2)*Sqrt[b]) + (7*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) - (15*Sqrt[b]*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2)) + (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(5/2)*Sqrt[b]) - (7*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3)}
{Sin[c + d*x]/(x^3*(a + b*x^2)^3), x, 46, -(d*Cos[c + d*x])/(2*a^3*x) - (Sqrt[b]*d*Cos[c + d*x])/(16*a^3*(Sqrt[-a] - Sqrt[b]*x)) + (Sqrt[b]*d*Cos[c + d*x])/(16*a^3*(Sqrt[-a] + Sqrt[b]*x)) - (9*Sqrt[b]*d*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) + (9*Sqrt[b]*d*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2)) - (3*b*CosIntegral[d*x]*Sin[c])/a^4 - (d^2*CosIntegral[d*x]*Sin[c])/(2*a^3) + (3*b*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(2*a^4) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x]*Sin[c - (Sqrt[-a]*d)/Sqrt[b]])/(16*a^3) + (3*b*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(2*a^4) + (d^2*CosIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x]*Sin[c + (Sqrt[-a]*d)/Sqrt[b]])/(16*a^3) - Sin[c + d*x]/(2*a^3*x^2) - (b*Sin[c + d*x])/(4*a^2*(a + b*x^2)^2) - (b*Sin[c + d*x])/(a^3*(a + b*x^2)) - (3*b*Cos[c]*SinIntegral[d*x])/a^4 - (d^2*Cos[c]*SinIntegral[d*x])/(2*a^3) - (3*b*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(2*a^4) - (d^2*Cos[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*a^3) - (9*Sqrt[b]*d*Sin[c + (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] - d*x])/(16*(-a)^(7/2)) + (3*b*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(2*a^4) + (d^2*Cos[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*a^3) - (9*Sqrt[b]*d*Sin[c - (Sqrt[-a]*d)/Sqrt[b]]*SinIntegral[(Sqrt[-a]*d)/Sqrt[b] + d*x])/(16*(-a)^(7/2))}


(* ::Section::Closed:: *)
(*Integrands of the form (e x)^m (a+b x^3)^p Sin[c+d x]*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*x^3)*Sin[c + d*x], x, 13, (720*b*Cos[c + d*x])/d^7 + (6*a*x*Cos[c + d*x])/d^3 - (360*b*x^2*Cos[c + d*x])/d^5 - (a*x^3*Cos[c + d*x])/d + (30*b*x^4*Cos[c + d*x])/d^3 - (b*x^6*Cos[c + d*x])/d - (6*a*Sin[c + d*x])/d^4 + (720*b*x*Sin[c + d*x])/d^6 + (3*a*x^2*Sin[c + d*x])/d^2 - (120*b*x^3*Sin[c + d*x])/d^4 + (6*b*x^5*Sin[c + d*x])/d^2}
{x^2*(a + b*x^3)*Sin[c + d*x], x, 11, (2*a*Cos[c + d*x])/d^3 - (120*b*x*Cos[c + d*x])/d^5 - (a*x^2*Cos[c + d*x])/d + (20*b*x^3*Cos[c + d*x])/d^3 - (b*x^5*Cos[c + d*x])/d + (120*b*Sin[c + d*x])/d^6 + (2*a*x*Sin[c + d*x])/d^2 - (60*b*x^2*Sin[c + d*x])/d^4 + (5*b*x^4*Sin[c + d*x])/d^2}
{x*(a + b*x^3)*Sin[c + d*x], x, 9, (-24*b*Cos[c + d*x])/d^5 - (a*x*Cos[c + d*x])/d + (12*b*x^2*Cos[c + d*x])/d^3 - (b*x^4*Cos[c + d*x])/d + (a*Sin[c + d*x])/d^2 - (24*b*x*Sin[c + d*x])/d^4 + (4*b*x^3*Sin[c + d*x])/d^2}
{(a + b*x^3)*Sin[c + d*x], x, 7, -((a*Cos[c + d*x])/d) + (6*b*x*Cos[c + d*x])/d^3 - (b*x^3*Cos[c + d*x])/d - (6*b*Sin[c + d*x])/d^4 + (3*b*x^2*Sin[c + d*x])/d^2}
{((a + b*x^3)*Sin[c + d*x])/x, x, 8, (2*b*Cos[c + d*x])/d^3 - (b*x^2*Cos[c + d*x])/d + a*CosIntegral[d*x]*Sin[c] + (2*b*x*Sin[c + d*x])/d^2 + a*Cos[c]*SinIntegral[d*x]}
{((a + b*x^3)*Sin[c + d*x])/x^2, x, 8, -((b*x*Cos[c + d*x])/d) + a*d*Cos[c]*CosIntegral[d*x] + (b*Sin[c + d*x])/d^2 - (a*Sin[c + d*x])/x - a*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x^3)*Sin[c + d*x])/x^3, x, 8, -((b*Cos[c + d*x])/d) - (a*d*Cos[c + d*x])/(2*x) - (a*d^2*CosIntegral[d*x]*Sin[c])/2 - (a*Sin[c + d*x])/(2*x^2) - (a*d^2*Cos[c]*SinIntegral[d*x])/2}
{((a + b*x^3)*Sin[c + d*x])/x^4, x, 11, -(a*d*Cos[c + d*x])/(6*x^2) - (a*d^3*Cos[c]*CosIntegral[d*x])/6 + b*CosIntegral[d*x]*Sin[c] - (a*Sin[c + d*x])/(3*x^3) + (a*d^2*Sin[c + d*x])/(6*x) + b*Cos[c]*SinIntegral[d*x] + (a*d^3*Sin[c]*SinIntegral[d*x])/6}


{x*(a + b*x^3)^2*Sin[c + d*x], x, 17, (-48*a*b*Cos[c + d*x])/d^5 + (5040*b^2*x*Cos[c + d*x])/d^7 - (a^2*x*Cos[c + d*x])/d + (24*a*b*x^2*Cos[c + d*x])/d^3 - (840*b^2*x^3*Cos[c + d*x])/d^5 - (2*a*b*x^4*Cos[c + d*x])/d + (42*b^2*x^5*Cos[c + d*x])/d^3 - (b^2*x^7*Cos[c + d*x])/d - (5040*b^2*Sin[c + d*x])/d^8 + (a^2*Sin[c + d*x])/d^2 - (48*a*b*x*Sin[c + d*x])/d^4 + (2520*b^2*x^2*Sin[c + d*x])/d^6 + (8*a*b*x^3*Sin[c + d*x])/d^2 - (210*b^2*x^4*Sin[c + d*x])/d^4 + (7*b^2*x^6*Sin[c + d*x])/d^2}
{(a + b*x^3)^2*Sin[c + d*x], x, 14, (720*b^2*Cos[c + d*x])/d^7 - (a^2*Cos[c + d*x])/d + (12*a*b*x*Cos[c + d*x])/d^3 - (360*b^2*x^2*Cos[c + d*x])/d^5 - (2*a*b*x^3*Cos[c + d*x])/d + (30*b^2*x^4*Cos[c + d*x])/d^3 - (b^2*x^6*Cos[c + d*x])/d - (12*a*b*Sin[c + d*x])/d^4 + (720*b^2*x*Sin[c + d*x])/d^6 + (6*a*b*x^2*Sin[c + d*x])/d^2 - (120*b^2*x^3*Sin[c + d*x])/d^4 + (6*b^2*x^5*Sin[c + d*x])/d^2}
{((a + b*x^3)^2*Sin[c + d*x])/x, x, 14, (4*a*b*Cos[c + d*x])/d^3 - (120*b^2*x*Cos[c + d*x])/d^5 - (2*a*b*x^2*Cos[c + d*x])/d + (20*b^2*x^3*Cos[c + d*x])/d^3 - (b^2*x^5*Cos[c + d*x])/d + a^2*CosIntegral[d*x]*Sin[c] + (120*b^2*Sin[c + d*x])/d^6 + (4*a*b*x*Sin[c + d*x])/d^2 - (60*b^2*x^2*Sin[c + d*x])/d^4 + (5*b^2*x^4*Sin[c + d*x])/d^2 + a^2*Cos[c]*SinIntegral[d*x]}
{((a + b*x^3)^2*Sin[c + d*x])/x^2, x, 13, (-24*b^2*Cos[c + d*x])/d^5 - (2*a*b*x*Cos[c + d*x])/d + (12*b^2*x^2*Cos[c + d*x])/d^3 - (b^2*x^4*Cos[c + d*x])/d + a^2*d*Cos[c]*CosIntegral[d*x] + (2*a*b*Sin[c + d*x])/d^2 - (a^2*Sin[c + d*x])/x - (24*b^2*x*Sin[c + d*x])/d^4 + (4*b^2*x^3*Sin[c + d*x])/d^2 - a^2*d*Sin[c]*SinIntegral[d*x]}
{((a + b*x^3)^2*Sin[c + d*x])/x^3, x, 12, (-2*a*b*Cos[c + d*x])/d - (a^2*d*Cos[c + d*x])/(2*x) + (6*b^2*x*Cos[c + d*x])/d^3 - (b^2*x^3*Cos[c + d*x])/d - (a^2*d^2*CosIntegral[d*x]*Sin[c])/2 - (6*b^2*Sin[c + d*x])/d^4 - (a^2*Sin[c + d*x])/(2*x^2) + (3*b^2*x^2*Sin[c + d*x])/d^2 - (a^2*d^2*Cos[c]*SinIntegral[d*x])/2}
{((a + b*x^3)^2*Sin[c + d*x])/x^4, x, 14, (2*b^2*Cos[c + d*x])/d^3 - (a^2*d*Cos[c + d*x])/(6*x^2) - (b^2*x^2*Cos[c + d*x])/d - (a^2*d^3*Cos[c]*CosIntegral[d*x])/6 + 2*a*b*CosIntegral[d*x]*Sin[c] - (a^2*Sin[c + d*x])/(3*x^3) + (a^2*d^2*Sin[c + d*x])/(6*x) + (2*b^2*x*Sin[c + d*x])/d^2 + 2*a*b*Cos[c]*SinIntegral[d*x] + (a^2*d^3*Sin[c]*SinIntegral[d*x])/6}
{((a + b*x^3)^2*Sin[c + d*x])/x^5, x, 15, -(a^2*d*Cos[c + d*x])/(12*x^3) + (a^2*d^3*Cos[c + d*x])/(24*x) - (b^2*x*Cos[c + d*x])/d + 2*a*b*d*Cos[c]*CosIntegral[d*x] + (a^2*d^4*CosIntegral[d*x]*Sin[c])/24 + (b^2*Sin[c + d*x])/d^2 - (a^2*Sin[c + d*x])/(4*x^4) + (a^2*d^2*Sin[c + d*x])/(24*x^2) - (2*a*b*Sin[c + d*x])/x + (a^2*d^4*Cos[c]*SinIntegral[d*x])/24 - 2*a*b*d*Sin[c]*SinIntegral[d*x]}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*Sin[c + d*x])/(a + b*x^3), x, 15, -((x*Cos[c + d*x])/(b*d)) + (a^(2/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*b^(5/3)) + ((-1)^(2/3)*a^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*b^(5/3)) + Sin[c + d*x]/(b*d^2) - ((-1)^(2/3)*a^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(5/3)) + (a^(2/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(5/3))}
{(x^3*Sin[c + d*x])/(a + b*x^3), x, 14, -(Cos[c + d*x]/(b*d)) - (a^(1/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*b^(4/3)) + ((-1)^(1/3)*a^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*b^(4/3)) - ((-1)^(1/3)*a^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b^(4/3)) - (a^(1/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b^(4/3))}
{(x^2*Sin[c + d*x])/(a + b*x^3), x, 11, (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*b) + (CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*b) + (CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*b) - (Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*b) + (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*b) + (Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*b)}
{(x*Sin[c + d*x])/(a + b*x^3), x, 11, -((CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^(1/3)*b^(2/3))) - ((-1)^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(1/3)*b^(2/3)) + ((-1)^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(1/3)*b^(2/3)) - (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(1/3)*b^(2/3))}
{Sin[c + d*x]/(a + b*x^3), x, 11, (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^(2/3)*b^(1/3)) - ((-1)^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(2/3)*b^(1/3)) + ((-1)^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(2/3)*b^(1/3)) + (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(2/3)*b^(1/3))}
{Sin[c + d*x]/(x*(a + b*x^3)), x, 16, (CosIntegral[d*x]*Sin[c])/a - (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a) - (CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a) - (CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a) + (Cos[c]*SinIntegral[d*x])/a + (Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a) - (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a) - (Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a)}
{Sin[c + d*x]/(x^2*(a + b*x^3)), x, 17, (d*Cos[c]*CosIntegral[d*x])/a + (b^(1/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^(4/3)) + ((-1)^(2/3)*b^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(4/3)) - Sin[c + d*x]/(a*x) - (d*Sin[c]*SinIntegral[d*x])/a - ((-1)^(2/3)*b^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(4/3)) + (b^(1/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(4/3))}
{Sin[c + d*x]/(x^3*(a + b*x^3)), x, 18, -((d*Cos[c + d*x])/(2*a*x)) - (d^2*CosIntegral[d*x]*Sin[c])/(2*a) - (b^(2/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^(5/3)) + ((-1)^(1/3)*b^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^(5/3)) - Sin[c + d*x]/(2*a*x^2) - (d^2*Cos[c]*SinIntegral[d*x])/(2*a) - ((-1)^(1/3)*b^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^(5/3)) - (b^(2/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^(5/3))}


{(x^3*Sin[c + d*x])/(a + b*x^3)^2, x, 23, -(((-1)^(2/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(1/3)*b^(5/3))) - (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3)) + (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(2/3)*b^(4/3)) - (x*Sin[c + d*x])/(3*b*(a + b*x^3)) + ((-1)^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3)) - ((-1)^(2/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(1/3)*b^(5/3)) + (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) + (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(1/3)*b^(5/3))}
{(x^2*Sin[c + d*x])/(a + b*x^3)^2, x, 12, -(((-1)^(1/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3))) + (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) - Sin[c + d*x]/(3*b*(a + b*x^3)) - ((-1)^(1/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(2/3)*b^(4/3)) - (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3)) - ((-1)^(2/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(2/3)*b^(4/3))}
{(x*Sin[c + d*x])/(a + b*x^3)^2, x, 34, -((d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a*b)) - (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b) - (d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b) - (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) - ((-1)^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) + ((-1)^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(4/3)*b^(2/3)) + Sin[c + d*x]/(3*a*b*x) - Sin[c + d*x]/(3*b*x*(a + b*x^3)) + ((-1)^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) - (d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a*b) - (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b) + ((-1)^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a*b)}
{Sin[c + d*x]/(a + b*x^3)^2, x, 36, ((-1)^(2/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) + (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) - ((-1)^(1/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) - (2*(-1)^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) + (2*(-1)^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(5/3)*b^(1/3)) + Sin[c + d*x]/(3*a*b*x^2) - Sin[c + d*x]/(3*b*x^2*(a + b*x^3)) + (2*(-1)^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) + ((-1)^(2/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(4/3)*b^(2/3)) + (2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) + ((-1)^(1/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(4/3)*b^(2/3))}
{Sin[c + d*x]/(x*(a + b*x^3)^2), x, 41, ((-1)^(1/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) - (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - ((-1)^(2/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) + (CosIntegral[d*x]*Sin[c])/a^2 - (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^2) - (CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^2) - (CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^2) + Sin[c + d*x]/(3*a*b*x^3) - Sin[c + d*x]/(3*b*x^3*(a + b*x^3)) + (Cos[c]*SinIntegral[d*x])/a^2 + (Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^2) + ((-1)^(1/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(5/3)*b^(1/3)) - (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^2) + (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3)) - (Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^2) + ((-1)^(2/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(5/3)*b^(1/3))}
{Sin[c + d*x]/(x^2*(a + b*x^3)^2), x, 47, (d*Cos[c]*CosIntegral[d*x])/a^2 + (d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^2) + (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^2) + (d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^2) + (4*b^(1/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(7/3)) + (4*(-1)^(2/3)*b^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(7/3)) - (4*(-1)^(1/3)*b^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(7/3)) + Sin[c + d*x]/(3*a*b*x^4) - (4*Sin[c + d*x])/(3*a^2*x) - Sin[c + d*x]/(3*b*x^4*(a + b*x^3)) - (d*Sin[c]*SinIntegral[d*x])/a^2 - (4*(-1)^(2/3)*b^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(7/3)) + (d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^2) + (4*b^(1/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)) - (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^2) - (4*(-1)^(1/3)*b^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)) - (d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^2)}
{Sin[c + d*x]/(x^3*(a + b*x^3)^2), x, 51, -((d*Cos[c + d*x])/(2*a^2*x)) - ((-1)^(2/3)*b^(1/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(7/3)) - (b^(1/3)*d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)) + ((-1)^(1/3)*b^(1/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)) - (d^2*CosIntegral[d*x]*Sin[c])/(2*a^2) - (5*b^(2/3)*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(9*a^(8/3)) + (5*(-1)^(1/3)*b^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(8/3)) - (5*(-1)^(2/3)*b^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(9*a^(8/3)) + Sin[c + d*x]/(3*a*b*x^5) - (5*Sin[c + d*x])/(6*a^2*x^2) - Sin[c + d*x]/(3*b*x^5*(a + b*x^3)) - (d^2*Cos[c]*SinIntegral[d*x])/(2*a^2) - (5*(-1)^(1/3)*b^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(8/3)) - ((-1)^(2/3)*b^(1/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(7/3)) - (5*b^(2/3)*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(8/3)) + (b^(1/3)*d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)) - (5*(-1)^(2/3)*b^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(8/3)) - ((-1)^(1/3)*b^(1/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3))}


{(x^3*Sin[c + d*x])/(a + b*x^3)^3, x, 71, (d*Cos[c + d*x])/(18*a*b^2*x) - (d*Cos[c + d*x])/(18*b^2*x*(a + b*x^3)) + (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(54*a*b^2) - ((-1)^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(54*a*b^2) + ((-1)^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(54*a*b^2) + Sin[c + d*x]/(18*a*b^2*x^2) - (x*Sin[c + d*x])/(6*b*(a + b*x^3)^2) - Sin[c + d*x]/(18*b^2*x^2*(a + b*x^3)) + ((-1)^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a*b^2) + (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) + (d^2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a*b^2) + ((-1)^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) + (d^2*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a*b^2)}
{(x^2*Sin[c + d*x])/(a + b*x^3)^3, x, 37, (d*Cos[c + d*x])/(18*a*b^2*x^2) - (d*Cos[c + d*x])/(18*b^2*x^2*(a + b*x^3)) - ((-1)^(1/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) + (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) + ((-1)^(2/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(54*a^(4/3)*b^(5/3)) - ((-1)^(2/3)*d^2*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(4/3)*b^(5/3)) + ((-1)^(1/3)*d^2*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(4/3)*b^(5/3)) - Sin[c + d*x]/(6*b*(a + b*x^3)^2) + ((-1)^(2/3)*d^2*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(5/3)*b^(4/3)) - (d^2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(4/3)*b^(5/3)) - (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3)) + ((-1)^(1/3)*d^2*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(4/3)*b^(5/3)) - ((-1)^(2/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(5/3)*b^(4/3))}
{(x*Sin[c + d*x])/(a + b*x^3)^3, x, 89, (d*Cos[c + d*x])/(18*a*b^2*x^3) - (d*Cos[c + d*x])/(18*b^2*x^3*(a + b*x^3)) - (2*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^2*b) - (2*d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b) - (2*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b) - (2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(27*a^(7/3)*b^(2/3)) + (d^2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(54*a^(5/3)*b^(4/3)) - (2*(-1)^(2/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d^2*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(5/3)*b^(4/3)) + (2*(-1)^(1/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(7/3)*b^(2/3)) + ((-1)^(2/3)*d^2*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(5/3)*b^(4/3)) - Sin[c + d*x]/(18*a*b^2*x^4) + (2*Sin[c + d*x])/(9*a^2*b*x) - Sin[c + d*x]/(6*b*x*(a + b*x^3)^2) + Sin[c + d*x]/(18*b^2*x^4*(a + b*x^3)) + (2*(-1)^(2/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(7/3)*b^(2/3)) + ((-1)^(1/3)*d^2*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(5/3)*b^(4/3)) - (2*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^2*b) - (2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(7/3)*b^(2/3)) + (d^2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(5/3)*b^(4/3)) + (2*d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b) + (2*(-1)^(1/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(7/3)*b^(2/3)) + ((-1)^(2/3)*d^2*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(5/3)*b^(4/3)) + (2*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^2*b)}
{Sin[c + d*x]/(a + b*x^3)^3, x, 99, (d*Cos[c + d*x])/(18*a*b^2*x^4) - (d*Cos[c + d*x])/(18*a^2*b*x) - (d*Cos[c + d*x])/(18*b^2*x^4*(a + b*x^3)) + ((-1)^(2/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(7/3)*b^(2/3)) + (d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)*b^(2/3)) + (5*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(54*a^2*b) - (5*(-1)^(1/3)*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(54*a^2*b) + (5*(-1)^(2/3)*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(54*a^2*b) - Sin[c + d*x]/(9*a*b^2*x^5) + (5*Sin[c + d*x])/(18*a^2*b*x^2) - Sin[c + d*x]/(6*b*x^2*(a + b*x^3)^2) + Sin[c + d*x]/(9*b^2*x^5*(a + b*x^3)) + (5*(-1)^(1/3)*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(8/3)*b^(1/3)) + (d^2*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^2*b) + ((-1)^(2/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(9*a^(7/3)*b^(2/3)) + (5*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3)) - (d^2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^2*b) - (d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)*b^(2/3)) + (5*(-1)^(2/3)*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3)) - (d^2*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^2*b) + ((-1)^(1/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(9*a^(7/3)*b^(2/3))}
{Sin[c + d*x]/(x*(a + b*x^3)^3), x, 110, (d*Cos[c + d*x])/(18*a*b^2*x^5) - (d*Cos[c + d*x])/(18*a^2*b*x^2) - (d*Cos[c + d*x])/(18*b^2*x^5*(a + b*x^3)) + (4*(-1)^(1/3)*d*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(8/3)*b^(1/3)) - (4*d*Cos[c - (a^(1/3)*d)/b^(1/3)]*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3)) - (4*(-1)^(2/3)*d*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3)) + (CosIntegral[d*x]*Sin[c])/a^3 - (CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(3*a^3) + (d^2*CosIntegral[(a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - (a^(1/3)*d)/b^(1/3)])/(54*a^(7/3)*b^(2/3)) - (CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(3*a^3) + ((-1)^(2/3)*d^2*CosIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x]*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(7/3)*b^(2/3)) - (CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(3*a^3) - ((-1)^(1/3)*d^2*CosIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x]*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)])/(54*a^(7/3)*b^(2/3)) - Sin[c + d*x]/(6*a*b^2*x^6) + Sin[c + d*x]/(3*a^2*b*x^3) - Sin[c + d*x]/(6*b*x^3*(a + b*x^3)^2) + Sin[c + d*x]/(6*b^2*x^6*(a + b*x^3)) + (Cos[c]*SinIntegral[d*x])/a^3 + (Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(3*a^3) - ((-1)^(2/3)*d^2*Cos[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(54*a^(7/3)*b^(2/3)) + (4*(-1)^(1/3)*d*Sin[c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x])/(27*a^(8/3)*b^(1/3)) - (Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(3*a^3) + (d^2*Cos[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(7/3)*b^(2/3)) + (4*d*Sin[c - (a^(1/3)*d)/b^(1/3)]*SinIntegral[(a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3)) - (Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(3*a^3) - ((-1)^(1/3)*d^2*Cos[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(54*a^(7/3)*b^(2/3)) + (4*(-1)^(2/3)*d*Sin[c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)]*SinIntegral[((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x])/(27*a^(8/3)*b^(1/3))}
