(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^n*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^1*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^4*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 7, -((8*b*(49*c^2*d + 30*e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(3675*c^7)) - (4*b*(49*c^2*d + 30*e)*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(3675*c^5) - (b*(49*c^2*d + 30*e)*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(1225*c^3) - (b*e*x^6*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(49*c) + (1/5)*d*x^5*(a + b*ArcCosh[c*x]) + (1/7)*e*x^7*(a + b*ArcCosh[c*x])}
{x^3*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 6, -((b*(9*c^2*d + 5*e)*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(96*c^5)) - (b*(9*c^2*d + 5*e)*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(144*c^3) - (b*e*x^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(36*c) - (b*(9*c^2*d + 5*e)*ArcCosh[c*x])/(96*c^6) + (1/4)*d*x^4*(a + b*ArcCosh[c*x]) + (1/6)*e*x^6*(a + b*ArcCosh[c*x])}
{x^2*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 5, -((2*b*(25*c^2*d + 12*e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(225*c^5)) - (b*(25*c^2*d + 12*e)*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(225*c^3) - (b*e*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(25*c) + (1/3)*d*x^3*(a + b*ArcCosh[c*x]) + (1/5)*e*x^5*(a + b*ArcCosh[c*x])}
{x^1*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 4, -((b*(8*c^2*d + 3*e)*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(32*c^3)) - (b*e*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*c) - (b*(8*c^2*d + 3*e)*ArcCosh[c*x])/(32*c^4) + (1/2)*d*x^2*(a + b*ArcCosh[c*x]) + (1/4)*e*x^4*(a + b*ArcCosh[c*x])}
{x^0*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 3, -((b*(9*c^2*d + 2*e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(9*c^3)) - (b*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(9*c) + d*x*(a + b*ArcCosh[c*x]) + (1/3)*e*x^3*(a + b*ArcCosh[c*x])}
{((d + e*x^2)*(a + b*ArcCosh[c*x]))/x^1, x, 13, -((b*e*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(4*c)) - (b*e*ArcCosh[c*x])/(4*c^2) + (1/2)*e*x^2*(a + b*ArcCosh[c*x]) - (I*b*d*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*d*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d*(a + b*ArcCosh[c*x])*Log[x] - (b*d*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*d*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)*(a + b*ArcCosh[c*x]))/x^2, x, 4, -((b*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/c) - (d*(a + b*ArcCosh[c*x]))/x + e*x*(a + b*ArcCosh[c*x]) + b*c*d*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]]}
{((d + e*x^2)*(a + b*ArcCosh[c*x]))/x^3, x, 11, (b*c*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*x) - (d*(a + b*ArcCosh[c*x]))/(2*x^2) - (I*b*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + e*(a + b*ArcCosh[c*x])*Log[x] - (b*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*e*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)*(a + b*ArcCosh[c*x]))/x^4, x, 4, (b*c*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(6*x^2) - (d*(a + b*ArcCosh[c*x]))/(3*x^3) - (e*(a + b*ArcCosh[c*x]))/x + (1/6)*b*c*(c^2*d + 6*e)*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]]}


{x^4*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 7, (b*(63*c^4*d^2 + 90*c^2*d*e + 35*e^2)*(1 - c^2*x^2))/(315*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (2*b*(63*c^4*d^2 + 135*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^2)/(945*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(21*c^4*d^2 + 90*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^3)/(525*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (2*b*e*(9*c^2*d + 14*e)*(1 - c^2*x^2)^4)/(441*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*(1 - c^2*x^2)^5)/(81*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^2*x^5*(a + b*ArcCosh[c*x]))/5 + (2*d*e*x^7*(a + b*ArcCosh[c*x]))/7 + (e^2*x^9*(a + b*ArcCosh[c*x]))/9}
{x^3*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 9, (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*x*(1 - c^2*x^2))/(3072*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*x^3*(1 - c^2*x^2))/(4608*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e*(64*c^2*d + 21*e)*x^5*(1 - c^2*x^2))/(1152*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*x^7*(1 - c^2*x^2))/(64*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (1/4)*d^2*x^4*(a + b*ArcCosh[c*x]) + (1/3)*d*e*x^6*(a + b*ArcCosh[c*x]) + (1/8)*e^2*x^8*(a + b*ArcCosh[c*x]) - (b*(288*c^4*d^2 + 320*c^2*d*e + 105*e^2)*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(3072*c^8*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{x^2*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 6, (b*(35*c^4*d^2 + 42*c^2*d*e + 15*e^2)*(1 - c^2*x^2))/(105*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*(35*c^4*d^2 + 84*c^2*d*e + 45*e^2)*(1 - c^2*x^2)^2)/(315*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e*(14*c^2*d + 15*e)*(1 - c^2*x^2)^3)/(175*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^2*(1 - c^2*x^2)^4)/(49*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^2*x^3*(a + b*ArcCosh[c*x]))/3 + (2*d*e*x^5*(a + b*ArcCosh[c*x]))/5 + (e^2*x^7*(a + b*ArcCosh[c*x]))/7}
{x^1*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 7, (b*(44*c^4*d^2 + 44*c^2*d*e + 15*e^2)*x*(1 - c^2*x^2))/(288*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (5*b*(2*c^2*d + e)*x*(1 - c^2*x^2)*(d + e*x^2))/(144*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*x*(1 - c^2*x^2)*(d + e*x^2)^2)/(36*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + ((d + e*x^2)^3*(a + b*ArcCosh[c*x]))/(6*e) - (b*(2*c^2*d + e)*(8*c^4*d^2 + 8*c^2*d*e + 5*e^2)*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(96*c^6*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{x^0*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 6, (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*(1 - c^2*x^2))/(15*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (2*b*e*(5*c^2*d + 3*e)*(1 - c^2*x^2)^2)/(45*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*(1 - c^2*x^2)^3)/(25*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^2*x*(a + b*ArcCosh[c*x]) + (2*d*e*x^3*(a + b*ArcCosh[c*x]))/3 + (e^2*x^5*(a + b*ArcCosh[c*x]))/5}
{((d + e*x^2)^2*(a + b*ArcCosh[c*x]))/x^1, x, 16, -((b*e*(16*c^2*d + 3*e)*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(32*c^3)) - (b*e^2*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*c) - (b*e*(16*c^2*d + 3*e)*ArcCosh[c*x])/(32*c^4) + d*e*x^2*(a + b*ArcCosh[c*x]) + (1/4)*e^2*x^4*(a + b*ArcCosh[c*x]) - (I*b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^2*(a + b*ArcCosh[c*x])*Log[x] - (b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*d^2*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]), -((b*d*e*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*c)) - (3*b*e^2*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(32*c^3) - (b*e^2*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*c) - (b*d*e*ArcCosh[c*x])/(2*c^2) - (3*b*e^2*ArcCosh[c*x])/(32*c^4) + d*e*x^2*(a + b*ArcCosh[c*x]) + (1/4)*e^2*x^4*(a + b*ArcCosh[c*x]) - (I*b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^2*(a + b*ArcCosh[c*x])*Log[x] - (b*d^2*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*d^2*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^2*(a + b*ArcCosh[c*x]))/x^2, x, 7, (b*e*(6*c^2*d + e)*(1 - c^2*x^2))/(3*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^2*(1 - c^2*x^2)^2)/(9*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^2*(a + b*ArcCosh[c*x]))/x + 2*d*e*x*(a + b*ArcCosh[c*x]) + (1/3)*e^2*x^3*(a + b*ArcCosh[c*x]) + b*c*d^2*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]], (b*e*(6*c^2*d + e)*(1 - c^2*x^2))/(3*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^2*(1 - c^2*x^2)^2)/(9*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^2*(a + b*ArcCosh[c*x]))/x + 2*d*e*x*(a + b*ArcCosh[c*x]) + (1/3)*e^2*x^3*(a + b*ArcCosh[c*x]) + (b*c*d^2*Sqrt[-1 + c^2*x^2]*ArcTan[Sqrt[-1 + c^2*x^2]])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^2*(a + b*ArcCosh[c*x]))/x^3, x, 14, (b*c*d^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*x) - (b*e^2*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(4*c) - (b*e^2*ArcCosh[c*x])/(4*c^2) - (d^2*(a + b*ArcCosh[c*x]))/(2*x^2) + (1/2)*e^2*x^2*(a + b*ArcCosh[c*x]) - (I*b*d*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (2*b*d*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + 2*d*e*(a + b*ArcCosh[c*x])*Log[x] - (2*b*d*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*d*e*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^2*(a + b*ArcCosh[c*x]))/x^4, x, 7, (b*e^2*(1 - c^2*x^2))/(c*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*c*d^2*(1 - c^2*x^2))/(6*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^2*(a + b*ArcCosh[c*x]))/(3*x^3) - (2*d*e*(a + b*ArcCosh[c*x]))/x + e^2*x*(a + b*ArcCosh[c*x]) + (b*c*d*(c^2*d + 12*e)*Sqrt[-1 + c^2*x^2]*ArcTan[Sqrt[-1 + c^2*x^2]])/(6*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}


{x^4*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 6, (b*(231*c^6*d^3 + 495*c^4*d^2*e + 385*c^2*d*e^2 + 105*e^3)*(1 - c^2*x^2))/(1155*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*(462*c^6*d^3 + 1485*c^4*d^2*e + 1540*c^2*d*e^2 + 525*e^3)*(1 - c^2*x^2)^2)/(3465*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(77*c^6*d^3 + 495*c^4*d^2*e + 770*c^2*d*e^2 + 350*e^3)*(1 - c^2*x^2)^3)/(1925*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e*(99*c^4*d^2 + 308*c^2*d*e + 210*e^2)*(1 - c^2*x^2)^4)/(1617*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*(11*c^2*d + 15*e)*(1 - c^2*x^2)^5)/(297*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^3*(1 - c^2*x^2)^6)/(121*c^11*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^3*x^5*(a + b*ArcCosh[c*x]))/5 + (3*d^2*e*x^7*(a + b*ArcCosh[c*x]))/7 + (d*e^2*x^9*(a + b*ArcCosh[c*x]))/3 + (e^3*x^11*(a + b*ArcCosh[c*x]))/11}
{x^3*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 10, -((b*(1232*c^8*d^4 - 2536*c^6*d^3*e - 7758*c^4*d^2*e^2 - 6615*c^2*d*e^3 - 1890*e^4)*x*(1 - c^2*x^2))/(76800*c^9*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x])) - (b*(136*c^6*d^3 - 1096*c^4*d^2*e - 1617*c^2*d*e^2 - 630*e^3)*x*(1 - c^2*x^2)*(d + e*x^2))/(38400*c^7*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(26*c^4*d^2 + 201*c^2*d*e + 126*e^2)*x*(1 - c^2*x^2)*(d + e*x^2)^2)/(9600*c^5*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(11*c^2*d + 18*e)*x*(1 - c^2*x^2)*(d + e*x^2)^3)/(1600*c^3*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*x*(1 - c^2*x^2)*(d + e*x^2)^4)/(100*c*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d*(d + e*x^2)^4*(a + b*ArcCosh[c*x]))/(8*e^2) + ((d + e*x^2)^5*(a + b*ArcCosh[c*x]))/(10*e^2) + (b*(128*c^10*d^5 - 480*c^6*d^3*e^2 - 800*c^4*d^2*e^3 - 525*c^2*d*e^4 - 126*e^5)*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(5120*c^10*e^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{x^2*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 6, (b*(105*c^6*d^3 + 189*c^4*d^2*e + 135*c^2*d*e^2 + 35*e^3)*(1 - c^2*x^2))/(315*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*(105*c^6*d^3 + 378*c^4*d^2*e + 405*c^2*d*e^2 + 140*e^3)*(1 - c^2*x^2)^2)/(945*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e*(63*c^4*d^2 + 135*c^2*d*e + 70*e^2)*(1 - c^2*x^2)^3)/(525*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^2*(27*c^2*d + 28*e)*(1 - c^2*x^2)^4)/(441*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^3*(1 - c^2*x^2)^5)/(81*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (1/3)*d^3*x^3*(a + b*ArcCosh[c*x]) + (3/5)*d^2*e*x^5*(a + b*ArcCosh[c*x]) + (3/7)*d*e^2*x^7*(a + b*ArcCosh[c*x]) + (1/9)*e^3*x^9*(a + b*ArcCosh[c*x])}
{x^1*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 8, (5*b*(2*c^2*d + e)*(40*c^4*d^2 + 40*c^2*d*e + 21*e^2)*x*(1 - c^2*x^2))/(3072*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*(104*c^4*d^2 + 104*c^2*d*e + 35*e^2)*x*(1 - c^2*x^2)*(d + e*x^2))/(1536*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (7*b*(2*c^2*d + e)*x*(1 - c^2*x^2)*(d + e*x^2)^2)/(384*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*x*(1 - c^2*x^2)*(d + e*x^2)^3)/(64*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + ((d + e*x^2)^4*(a + b*ArcCosh[c*x]))/(8*e) - (b*(128*c^8*d^4 + 256*c^6*d^3*e + 288*c^4*d^2*e^2 + 160*c^2*d*e^3 + 35*e^4)*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(1024*c^8*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{x^0*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 6, (b*(35*c^6*d^3 + 35*c^4*d^2*e + 21*c^2*d*e^2 + 5*e^3)*(1 - c^2*x^2))/(35*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e*(35*c^4*d^2 + 42*c^2*d*e + 15*e^2)*(1 - c^2*x^2)^2)/(105*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (3*b*e^2*(7*c^2*d + 5*e)*(1 - c^2*x^2)^3)/(175*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^3*(1 - c^2*x^2)^4)/(49*c^7*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^3*x*(a + b*ArcCosh[c*x]) + d^2*e*x^3*(a + b*ArcCosh[c*x]) + (3*d*e^2*x^5*(a + b*ArcCosh[c*x]))/5 + (e^3*x^7*(a + b*ArcCosh[c*x]))/7}
{((d + e*x^2)^3*(a + b*ArcCosh[c*x]))/x^1, x, 23, -((3*b*d^2*e*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(4*c)) - (9*b*d*e^2*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(32*c^3) - (5*b*e^3*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(96*c^5) - (3*b*d*e^2*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*c) - (5*b*e^3*x^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(144*c^3) - (b*e^3*x^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(36*c) - (3*b*d^2*e*ArcCosh[c*x])/(4*c^2) - (9*b*d*e^2*ArcCosh[c*x])/(32*c^4) - (5*b*e^3*ArcCosh[c*x])/(96*c^6) + (3/2)*d^2*e*x^2*(a + b*ArcCosh[c*x]) + (3/4)*d*e^2*x^4*(a + b*ArcCosh[c*x]) + (1/6)*e^3*x^6*(a + b*ArcCosh[c*x]) - (I*b*d^3*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*d^3*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^3*(a + b*ArcCosh[c*x])*Log[x] - (b*d^3*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (I*b*d^3*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^3*(a + b*ArcCosh[c*x]))/x^2, x, 7, (b*e*(15*c^4*d^2 + 5*c^2*d*e + e^2)*(1 - c^2*x^2))/(5*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^2*(5*c^2*d + 2*e)*(1 - c^2*x^2)^2)/(15*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^3*(1 - c^2*x^2)^3)/(25*c^5*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^3*(a + b*ArcCosh[c*x]))/x + 3*d^2*e*x*(a + b*ArcCosh[c*x]) + d*e^2*x^3*(a + b*ArcCosh[c*x]) + (1/5)*e^3*x^5*(a + b*ArcCosh[c*x]) + (b*c*d^3*Sqrt[-1 + c^2*x^2]*ArcTan[Sqrt[-1 + c^2*x^2]])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^3*(a + b*ArcCosh[c*x]))/x^3, x, 18, -((b*c*d^3*(1 - c^2*x^2))/(2*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])) + (3*b*e^2*(8*c^2*d + e)*x*(1 - c^2*x^2))/(32*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^3*x^3*(1 - c^2*x^2))/(16*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^3*(a + b*ArcCosh[c*x]))/(2*x^2) + (3/2)*d*e^2*x^2*(a + b*ArcCosh[c*x]) + (1/4)*e^3*x^4*(a + b*ArcCosh[c*x]) - (3*I*b*d^2*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]^2)/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (3*b*e^2*(8*c^2*d + e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(32*c^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (3*b*d^2*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[1 - E^(2*I*ArcSin[c*x])])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + 3*d^2*e*(a + b*ArcCosh[c*x])*Log[x] - (3*b*d^2*e*Sqrt[1 - c^2*x^2]*ArcSin[c*x]*Log[x])/(Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (3*I*b*d^2*e*Sqrt[1 - c^2*x^2]*PolyLog[2, E^(2*I*ArcSin[c*x])])/(2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{((d + e*x^2)^3*(a + b*ArcCosh[c*x]))/x^4, x, 9, (b*e^2*(9*c^2*d + e)*(1 - c^2*x^2))/(3*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*c*d^3*(1 - c^2*x^2))/(6*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*e^3*(1 - c^2*x^2)^2)/(9*c^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (d^3*(a + b*ArcCosh[c*x]))/(3*x^3) - (3*d^2*e*(a + b*ArcCosh[c*x]))/x + 3*d*e^2*x*(a + b*ArcCosh[c*x]) + (1/3)*e^3*x^3*(a + b*ArcCosh[c*x]) + (b*c*d^2*(c^2*d + 18*e)*Sqrt[-1 + c^2*x^2]*ArcTan[Sqrt[-1 + c^2*x^2]])/(6*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}


{(d + e*x^2)^4*(a + b*ArcCosh[c*x]), x, 6, (b*(315*c^8*d^4 + 420*c^6*d^3*e + 378*c^4*d^2*e^2 + 180*c^2*d*e^3 + 35*e^4)*(1 - c^2*x^2))/(315*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (4*b*e*(105*c^6*d^3 + 189*c^4*d^2*e + 135*c^2*d*e^2 + 35*e^3)*(1 - c^2*x^2)^2)/(945*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (2*b*e^2*(63*c^4*d^2 + 90*c^2*d*e + 35*e^2)*(1 - c^2*x^2)^3)/(525*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (4*b*e^3*(9*c^2*d + 7*e)*(1 - c^2*x^2)^4)/(441*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^4*(1 - c^2*x^2)^5)/(81*c^9*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + d^4*x*(a + b*ArcCosh[c*x]) + (4*d^3*e*x^3*(a + b*ArcCosh[c*x]))/3 + (6*d^2*e^2*x^5*(a + b*ArcCosh[c*x]))/5 + (4*d*e^3*x^7*(a + b*ArcCosh[c*x]))/7 + (e^4*x^9*(a + b*ArcCosh[c*x]))/9}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^4*(a + b*ArcCosh[c*x]))/(d + e*x^2), x, 27, -((a*d*x)/e^2) + (b*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(c*e^2) - (2*b*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(9*c^3*e) - (b*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(9*c*e) - (b*d*x*ArcCosh[c*x])/e^2 + (x^3*(a + b*ArcCosh[c*x]))/(3*e) + ((-d)^(3/2)*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(5/2)) - ((-d)^(3/2)*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(5/2)) + ((-d)^(3/2)*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(5/2)) - ((-d)^(3/2)*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(5/2)) - (b*(-d)^(3/2)*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e^(5/2)) + (b*(-d)^(3/2)*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(5/2)) - (b*(-d)^(3/2)*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e^(5/2)) + (b*(-d)^(3/2)*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(5/2))}
{(x^3*(a + b*ArcCosh[c*x]))/(d + e*x^2), x, 23, -((b*x*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(4*c*e)) - (b*ArcCosh[c*x])/(4*c^2*e) + (x^2*(a + b*ArcCosh[c*x]))/(2*e) + (d*(a + b*ArcCosh[c*x])^2)/(2*b*e^2) - (d*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) - (d*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) - (d*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2) - (d*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2) - (b*d*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e^2) - (b*d*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) - (b*d*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e^2) - (b*d*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2)}
{(x^2*(a + b*ArcCosh[c*x]))/(d + e*x^2), x, 23, (a*x)/e - (b*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(c*e) + (b*x*ArcCosh[c*x])/e + (Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(3/2)) + (Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(3/2)) - (b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e^(3/2)) + (b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^(3/2)) - (b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e^(3/2)) + (b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^(3/2))}
{(x*(a + b*ArcCosh[c*x]))/(d + e*x^2), x, 18, -((a + b*ArcCosh[c*x])^2/(2*b*e)) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e)}
{(a + b*ArcCosh[c*x])/(d + e*x^2), x, 18, ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*Sqrt[-d]*Sqrt[e]) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*Sqrt[-d]*Sqrt[e]) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcCosh[c*x])/(x*(d + e*x^2)), x, 25, -(((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d)) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d) + ((a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*d) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*d) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d) + (b*PolyLog[2, -E^(2*ArcCosh[c*x])])/(2*d)}
{(a + b*ArcCosh[c*x])/(x^2*(d + e*x^2)), x, 23, -((a + b*ArcCosh[c*x])/(d*x)) + (b*c*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]])/d + (Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2)) + (Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2)) - (b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*(-d)^(3/2)) + (b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2)) - (b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*(-d)^(3/2)) + (b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(3/2))}
{(a + b*ArcCosh[c*x])/(x^3*(d + e*x^2)), x, 27, (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*d*x) - (a + b*ArcCosh[c*x])/(2*d*x^2) + (e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) + (e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) + (e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) + (e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) - (e*(a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d^2 + (b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*d^2) + (b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) + (b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*d^2) + (b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) - (b*e*PolyLog[2, -E^(2*ArcCosh[c*x])])/(2*d^2)}
{(a + b*ArcCosh[c*x])/(x^4*(d + e*x^2)), x, 28, (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(6*d*x^2) - (a + b*ArcCosh[c*x])/(3*d*x^3) + (e*(a + b*ArcCosh[c*x]))/(d^2*x) + (b*c^3*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]])/(6*d) - (b*c*e*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]])/d^2 + (e^(3/2)*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2)) - (e^(3/2)*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2)) + (e^(3/2)*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2)) - (e^(3/2)*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2)) - (b*e^(3/2)*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*(-d)^(5/2)) + (b*e^(3/2)*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2)) - (b*e^(3/2)*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*(-d)^(5/2)) + (b*e^(3/2)*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*(-d)^(5/2))}


{(x^3*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x, 24, (d*(a + b*ArcCosh[c*x]))/(2*e^2*(d + e*x^2)) - (a + b*ArcCosh[c*x])^2/(2*b*e^2) - (b*c*Sqrt[d]*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(2*e^2*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e^2) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^2) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e^2) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^2)}
{(x^1*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x, 4, -((a + b*ArcCosh[c*x])/(2*e*(d + e*x^2))) + (b*c*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(2*Sqrt[d]*e*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(a + b*ArcCosh[c*x])/(x^1*(d + e*x^2)^2), x, 29, (a + b*ArcCosh[c*x])/(2*d*(d + e*x^2)) - (b*c*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(2*d^(3/2)*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) + ((a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d^2 - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*d^2) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^2) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*d^2) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^2) + (b*PolyLog[2, -E^(2*ArcCosh[c*x])])/(2*d^2)}
{(a + b*ArcCosh[c*x])/(x^3*(d + e*x^2)^2), x, 31, (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*d^2*x) - (a + b*ArcCosh[c*x])/(2*d^2*x^2) - (e*(a + b*ArcCosh[c*x]))/(2*d^2*(d + e*x^2)) + (b*c*e*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(2*d^(5/2)*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/d^3 + (e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/d^3 + (e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/d^3 + (e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/d^3 - (2*e*(a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d^3 + (b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/d^3 + (b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/d^3 + (b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/d^3 + (b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/d^3 - (b*e*PolyLog[2, -E^(2*ArcCosh[c*x])])/d^3}

{(x^4*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x, 49, (a*x)/e^2 - (b*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(c*e^2) + (b*x*ArcCosh[c*x])/e^2 - (d*(a + b*ArcCosh[c*x]))/(4*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)) + (d*(a + b*ArcCosh[c*x]))/(4*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)) + (b*c*d*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(5/2)) - (b*c*d*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*e^(5/2)) - (3*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(4*e^(5/2)) + (3*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*e^(5/2)) - (3*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(4*e^(5/2)) + (3*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*e^(5/2))}
{(x^2*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x, 46, (a + b*ArcCosh[c*x])/(4*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)) - (a + b*ArcCosh[c*x])/(4*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)) - (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(3/2)) + (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(3/2)) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2)) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2)) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(4*Sqrt[-d]*e^(3/2)) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2)) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(4*Sqrt[-d]*e^(3/2)) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*Sqrt[-d]*e^(3/2))}
{(a + b*ArcCosh[c*x])/(d + e*x^2)^2, x, 26, -((a + b*ArcCosh[c*x])/(4*d*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x))) + (a + b*ArcCosh[c*x])/(4*d*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)) + (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(2*d*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[e]) - (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(2*d*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[e]) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e]) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e]) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(4*(-d)^(3/2)*Sqrt[e]) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e]) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(4*(-d)^(3/2)*Sqrt[e]) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(3/2)*Sqrt[e])}
{(a + b*ArcCosh[c*x])/(x^2*(d + e*x^2)^2), x, 49, -((a + b*ArcCosh[c*x])/(d^2*x)) + (Sqrt[e]*(a + b*ArcCosh[c*x]))/(4*d^2*(Sqrt[-d] - Sqrt[e]*x)) - (Sqrt[e]*(a + b*ArcCosh[c*x]))/(4*d^2*(Sqrt[-d] + Sqrt[e]*x)) + (b*c*ArcTan[Sqrt[-1 + c*x]*Sqrt[1 + c*x]])/d^2 - (b*c*Sqrt[e]*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(2*d^2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]) + (b*c*Sqrt[e]*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(2*d^2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]) - (3*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2)) - (3*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2)) + (3*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(4*(-d)^(5/2)) - (3*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2)) + (3*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(4*(-d)^(5/2)) - (3*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(4*(-d)^(5/2))}


{(x^5*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 29, (b*c*d*x*(1 - c^2*x^2))/(8*e^2*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2)) - (d^2*(a + b*ArcCosh[c*x]))/(4*e^3*(d + e*x^2)^2) + (d*(a + b*ArcCosh[c*x]))/(e^3*(d + e*x^2)) - (a + b*ArcCosh[c*x])^2/(2*b*e^3) - (b*c*Sqrt[d]*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(e^3*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*c*Sqrt[d]*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(8*e^3*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^3) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^3) + ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^3) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^3) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*e^3) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*e^3) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*e^3) + (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*e^3)}
{(x^3*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 9, -(b*c*x*(1 - c^2*x^2))/(8*e*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2)) + (x^4*(a + b*ArcCosh[c*x]))/(4*d*(d + e*x^2)^2) - (b*Sqrt[1 - c^2*x^2]*ArcSin[c*x])/(4*d*e^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*c*(2*c^2*d + 3*e)*Sqrt[1 - c^2*x^2]*ArcTan[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(8*Sqrt[d]*e^2*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]), -((b*c*x*(1 - c^2*x^2))/(8*e*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2))) + (x^4*(a + b*ArcCosh[c*x]))/(4*d*(d + e*x^2)^2) - (b*Sqrt[-1 + c^2*x^2]*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(4*d*e^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*c*(2*c^2*d + 3*e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(8*Sqrt[d]*e^2*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(x*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 5, (b*c*x*(1 - c^2*x^2))/(8*d*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2)) - (a + b*ArcCosh[c*x])/(4*e*(d + e*x^2)^2) + (b*c*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(8*d^(3/2)*e*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(a + b*ArcCosh[c*x])/(x*(d + e*x^2)^3), x, 34, -((b*c*e*x*(1 - c^2*x^2))/(8*d^2*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2))) + (a + b*ArcCosh[c*x])/(4*d*(d + e*x^2)^2) + (a + b*ArcCosh[c*x])/(2*d^2*(d + e*x^2)) - (b*c*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(2*d^(5/2)*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - (b*c*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(8*d^(5/2)*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^3) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^3) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^3) - ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^3) + ((a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d^3 - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*d^3) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^3) - (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*d^3) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^3) + (b*PolyLog[2, -E^(2*ArcCosh[c*x])])/(2*d^3)}
{(a + b*ArcCosh[c*x])/(x^3*(d + e*x^2)^3), x, 36, (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(2*d^3*x) + (b*c*e^2*x*(1 - c^2*x^2))/(8*d^3*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2)) - (a + b*ArcCosh[c*x])/(2*d^3*x^2) - (e*(a + b*ArcCosh[c*x]))/(4*d^2*(d + e*x^2)^2) - (e*(a + b*ArcCosh[c*x]))/(d^3*(d + e*x^2)) + (b*c*e*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(d^(7/2)*Sqrt[c^2*d + e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*c*e*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[c^2*d + e]*x)/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(8*d^(7/2)*(c^2*d + e)^(3/2)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (3*e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^4) + (3*e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^4) + (3*e*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^4) + (3*e*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^4) - (3*e*(a + b*ArcCosh[c*x])*Log[1 + E^(2*ArcCosh[c*x])])/d^4 + (3*b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(2*d^4) + (3*b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*d^4) + (3*b*e*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(2*d^4) + (3*b*e*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*d^4) - (3*b*e*PolyLog[2, -E^(2*ArcCosh[c*x])])/(2*d^4)}

{(x^4*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 80, -((b*c*Sqrt[-d]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*e^2*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x))) - (b*c*Sqrt[-d]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*e^2*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (Sqrt[-d]*(a + b*ArcCosh[c*x]))/(16*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)^2) + (5*(a + b*ArcCosh[c*x]))/(16*e^(5/2)*(Sqrt[-d] - Sqrt[e]*x)) + (Sqrt[-d]*(a + b*ArcCosh[c*x]))/(16*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)^2) - (5*(a + b*ArcCosh[c*x]))/(16*e^(5/2)*(Sqrt[-d] + Sqrt[e]*x)) - (b*c^3*d*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*e^(5/2)) - (5*b*c*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(5/2)) + (b*c^3*d*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*e^(5/2)) + (5*b*c*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(5/2)) + (3*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2)) + (3*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2)) - (3*b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(16*Sqrt[-d]*e^(5/2)) + (3*b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2)) - (3*b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(16*Sqrt[-d]*e^(5/2)) + (3*b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*Sqrt[-d]*e^(5/2))}
{(x^2*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 62, -((b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*Sqrt[-d]*e*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x))) - (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*Sqrt[-d]*e*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcCosh[c*x])/(16*Sqrt[-d]*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)^2) - (a + b*ArcCosh[c*x])/(16*d*e^(3/2)*(Sqrt[-d] - Sqrt[e]*x)) + (a + b*ArcCosh[c*x])/(16*Sqrt[-d]*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)^2) + (a + b*ArcCosh[c*x])/(16*d*e^(3/2)*(Sqrt[-d] + Sqrt[e]*x)) + (b*c^3*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*e^(3/2)) + (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(3/2)) - (b*c^3*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*e^(3/2)) - (b*c*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*e^(3/2)) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(3/2)*e^(3/2))}
{(a + b*ArcCosh[c*x])/(d + e*x^2)^3, x, 34, -((b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x))) - (b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcCosh[c*x])/(16*(-d)^(3/2)*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x)^2) - (3*(a + b*ArcCosh[c*x]))/(16*d^2*Sqrt[e]*(Sqrt[-d] - Sqrt[e]*x)) + (a + b*ArcCosh[c*x])/(16*(-d)^(3/2)*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)^2) + (3*(a + b*ArcCosh[c*x]))/(16*d^2*Sqrt[e]*(Sqrt[-d] + Sqrt[e]*x)) - (b*c^3*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*Sqrt[e]) + (3*b*c*ArcTanh[(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d^2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[e]) + (b*c^3*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d*(c*Sqrt[-d] - Sqrt[e])^(3/2)*(c*Sqrt[-d] + Sqrt[e])^(3/2)*Sqrt[e]) - (3*b*c*ArcTanh[(Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[1 + c*x])/(Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[-1 + c*x])])/(8*d^2*Sqrt[c*Sqrt[-d] - Sqrt[e]]*Sqrt[c*Sqrt[-d] + Sqrt[e]]*Sqrt[e]) + (3*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(16*(-d)^(5/2)*Sqrt[e]) + (3*b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*b*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(16*(-d)^(5/2)*Sqrt[e]) + (3*b*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(16*(-d)^(5/2)*Sqrt[e])}
(* {(a + b*ArcCosh[c*x])/(x^2*(d + e*x^2)^3), x, 102, (b*c*e*Sqrt[1 - c^2*x^2])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d] - Sqrt[e]*x)) + (b*c*e*Sqrt[1 - c^2*x^2])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d] + Sqrt[e]*x)) - (a + b*ArcCosh[c*x])/(d^3*x) - (Sqrt[e]*(a + b*ArcCosh[c*x]))/(16*(-d)^(5/2)*(Sqrt[-d] - Sqrt[e]*x)^2) + (7*Sqrt[e]*(a + b*ArcCosh[c*x]))/(16*d^3*(Sqrt[-d] - Sqrt[e]*x)) + (Sqrt[e]*(a + b*ArcCosh[c*x]))/(16*(-d)^(5/2)*(Sqrt[-d] + Sqrt[e]*x)^2) - (7*Sqrt[e]*(a + b*ArcCosh[c*x]))/(16*d^3*(Sqrt[-d] + Sqrt[e]*x)) - (b*c^3*Sqrt[e]*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*(c^2*d + e)^(3/2)) - (7*b*c*Sqrt[e]*ArcTanh[(Sqrt[e] - c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^3*Sqrt[c^2*d + e]) - (b*c^3*Sqrt[e]*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^2*(c^2*d + e)^(3/2)) - (7*b*c*Sqrt[e]*ArcTanh[(Sqrt[e] + c^2*Sqrt[-d]*x)/(Sqrt[c^2*d + e]*Sqrt[1 - c^2*x^2])])/(16*d^3*Sqrt[c^2*d + e]) - (b*c*ArcTanh[Sqrt[1 - c^2*x^2]])/d^3 + (15*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) - (15*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 - (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) - (15*Sqrt[e]*(a + b*ArcCosh[c*x])*Log[1 + (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] - Sqrt[c^2*d + e])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*E^(I*ArcCosh[c*x]))/(I*c*Sqrt[-d] + Sqrt[c^2*d + e])])/(16*(-d)^(7/2))} *)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x]) with m symbolic*)


{x^m*(d + e*x^2)^3*(a + b*ArcCosh[c*x]), x, 7, If[$VersionNumber>=8, (b*e*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4))*x^(2 + m)*(1 - c^2*x^2))/(c^5*(3 + m)^2*(5 + m)^2*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*(3*c^2*d*(7 + m)^2 + e*(30 + 11*m + m^2))*x^(4 + m)*(1 - c^2*x^2))/(c^3*(5 + m)^2*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^3*x^(6 + m)*(1 - c^2*x^2))/(c*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^3*x^(1 + m)*(a + b*ArcCosh[c*x]))/(1 + m) + (3*d^2*e*x^(3 + m)*(a + b*ArcCosh[c*x]))/(3 + m) + (3*d*e^2*x^(5 + m)*(a + b*ArcCosh[c*x]))/(5 + m) + (e^3*x^(7 + m)*(a + b*ArcCosh[c*x]))/(7 + m) - (b*((c^6*d^3*(3 + m)*(5 + m)*(7 + m))/(1 + m) + (e*(2 + m)*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4)))/((3 + m)*(5 + m)*(7 + m)))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^5*(2 + m)*(3 + m)*(5 + m)*(7 + m)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]), (b*e*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4))*x^(2 + m)*(1 - c^2*x^2))/(c^5*(3 + m)^2*(5 + m)^2*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*(3*c^2*d*(7 + m)^2 + e*(30 + 11*m + m^2))*x^(4 + m)*(1 - c^2*x^2))/(c^3*(5 + m)^2*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^3*x^(6 + m)*(1 - c^2*x^2))/(c*(7 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^3*x^(1 + m)*(a + b*ArcCosh[c*x]))/(1 + m) + (3*d^2*e*x^(3 + m)*(a + b*ArcCosh[c*x]))/(3 + m) + (3*d*e^2*x^(5 + m)*(a + b*ArcCosh[c*x]))/(5 + m) + (e^3*x^(7 + m)*(a + b*ArcCosh[c*x]))/(7 + m) - (b*((c^6*d^3*(3 + m)*(5 + m)*(7 + m))/(1 + m) + (e*(2 + m)*(3*c^2*d*e*(7 + m)^2*(12 + 7*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2)^2 + e^2*(360 + 342*m + 119*m^2 + 18*m^3 + m^4)))/(105 + 71*m + 15*m^2 + m^3))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^5*(2 + m)*(3 + m)*(5 + m)*(7 + m)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])]}
{x^m*(d + e*x^2)^2*(a + b*ArcCosh[c*x]), x, 6, If[$VersionNumber>=8, (b*e*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2))*x^(2 + m)*(1 - c^2*x^2))/(c^3*(3 + m)^2*(5 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*x^(4 + m)*(1 - c^2*x^2))/(c*(5 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^2*x^(1 + m)*(a + b*ArcCosh[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcCosh[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcCosh[c*x]))/(5 + m) - (b*((c^4*d^2*(3 + m)*(5 + m))/(1 + m) + (e*(2 + m)*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2)))/((3 + m)*(5 + m)))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^3*(2 + m)*(3 + m)*(5 + m)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]), (b*e*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2))*x^(2 + m)*(1 - c^2*x^2))/(c^3*(3 + m)^2*(5 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (b*e^2*x^(4 + m)*(1 - c^2*x^2))/(c*(5 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]) + (d^2*x^(1 + m)*(a + b*ArcCosh[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcCosh[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcCosh[c*x]))/(5 + m) - (b*((c^4*d^2*(3 + m)*(5 + m))/(1 + m) + (e*(2 + m)*(2*c^2*d*(5 + m)^2 + e*(12 + 7*m + m^2)))/((3 + m)*(5 + m)))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c^3*(2 + m)*(3 + m)*(5 + m)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])]}
{x^m*(d + e*x^2)*(a + b*ArcCosh[c*x]), x, 5, -((b*e*x^(2 + m)*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(c*(3 + m)^2)) + (d*x^(1 + m)*(a + b*ArcCosh[c*x]))/(1 + m) + (e*x^(3 + m)*(a + b*ArcCosh[c*x]))/(3 + m) - (b*(e*(1 + m)*(2 + m) + c^2*d*(3 + m)^2)*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (2 + m)/2, (4 + m)/2, c^2*x^2])/(c*(1 + m)*(2 + m)*(3 + m)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2), x, 0, Unintegrable[(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2), x]}
{(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x, 0, Unintegrable[(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2)^2, x]}
{(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x, 0, Unintegrable[(x^m*(a + b*ArcCosh[c*x]))/(d + e*x^2)^3, x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^2*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^2*)


{(d + e*x^2)^3*(a + b*ArcCosh[c*x])^2, x, 26, 2*b^2*d^3*x + (4*b^2*d^2*e*x)/(3*c^2) + (16*b^2*d*e^2*x)/(25*c^4) + (32*b^2*e^3*x)/(245*c^6) + (2*b^2*d^2*e*x^3)/9 + (8*b^2*d*e^2*x^3)/(75*c^2) + (16*b^2*e^3*x^3)/(735*c^4) + (6*b^2*d*e^2*x^5)/125 + (12*b^2*e^3*x^5)/(1225*c^2) + (2*b^2*e^3*x^7)/343 - (2*b*d^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/c - (4*b*d^2*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(3*c^3) - (16*b*d*e^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(25*c^5) - (32*b*e^3*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(245*c^7) - (2*b*d^2*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(3*c) - (8*b*d*e^2*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(25*c^3) - (16*b*e^3*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(245*c^5) - (6*b*d*e^2*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(25*c) - (12*b*e^3*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(245*c^3) - (2*b*e^3*x^6*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(49*c) + d^3*x*(a + b*ArcCosh[c*x])^2 + d^2*e*x^3*(a + b*ArcCosh[c*x])^2 + (3*d*e^2*x^5*(a + b*ArcCosh[c*x])^2)/5 + (e^3*x^7*(a + b*ArcCosh[c*x])^2)/7}
{(d + e*x^2)^2*(a + b*ArcCosh[c*x])^2, x, 17, 2*b^2*d^2*x + (8*b^2*d*e*x)/(9*c^2) + (16*b^2*e^2*x)/(75*c^4) + (4*b^2*d*e*x^3)/27 + (8*b^2*e^2*x^3)/(225*c^2) + (2*b^2*e^2*x^5)/125 - (2*b*d^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/c - (8*b*d*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(9*c^3) - (16*b*e^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(75*c^5) - (4*b*d*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(9*c) - (8*b*e^2*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(75*c^3) - (2*b*e^2*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(25*c) + d^2*x*(a + b*ArcCosh[c*x])^2 + (2*d*e*x^3*(a + b*ArcCosh[c*x])^2)/3 + (e^2*x^5*(a + b*ArcCosh[c*x])^2)/5}
{(d + e*x^2)*(a + b*ArcCosh[c*x])^2, x, 10, 2*b^2*d*x + (4*b^2*e*x)/(9*c^2) + (2*b^2*e*x^3)/27 - (2*b*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/c - (4*b*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(9*c^3) - (2*b*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/(9*c) + d*x*(a + b*ArcCosh[c*x])^2 + (e*x^3*(a + b*ArcCosh[c*x])^2)/3}
{(a + b*ArcCosh[c*x])^2, x, 3, 2*b^2*x - (2*b*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(a + b*ArcCosh[c*x]))/c + x*(a + b*ArcCosh[c*x])^2}
{(a + b*ArcCosh[c*x])^2/(d + e*x^2), x, 22, ((a + b*ArcCosh[c*x])^2*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcCosh[c*x])^2*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcCosh[c*x])^2*Log[1 - (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcCosh[c*x])^2*Log[1 + (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(2*Sqrt[-d]*Sqrt[e]) - (b*(a + b*ArcCosh[c*x])*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(Sqrt[-d]*Sqrt[e]) + (b*(a + b*ArcCosh[c*x])*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(Sqrt[-d]*Sqrt[e]) - (b*(a + b*ArcCosh[c*x])*PolyLog[2, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(Sqrt[-d]*Sqrt[e]) + (b*(a + b*ArcCosh[c*x])*PolyLog[2, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(Sqrt[-d]*Sqrt[e]) + (b^2*PolyLog[3, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e]))])/(Sqrt[-d]*Sqrt[e]) - (b^2*PolyLog[3, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] - Sqrt[(-c^2)*d - e])])/(Sqrt[-d]*Sqrt[e]) + (b^2*PolyLog[3, -((Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e]))])/(Sqrt[-d]*Sqrt[e]) - (b^2*PolyLog[3, (Sqrt[e]*E^ArcCosh[c*x])/(c*Sqrt[-d] + Sqrt[(-c^2)*d - e])])/(Sqrt[-d]*Sqrt[e])}


(* ::Section:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^3*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcCosh[c x])^1*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcCosh[c x])*)


{(d + e*x^2)^2/(a + b*ArcCosh[c*x]), x, 27, -(d*e*CoshIntegral[a/b + ArcCosh[c*x]]*Sinh[a/b])/(2*b*c^3) - (e^2*CoshIntegral[a/b + ArcCosh[c*x]]*Sinh[a/b])/(8*b*c^5) - (d^2*CoshIntegral[(a + b*ArcCosh[c*x])/b]*Sinh[a/b])/(b*c) - (d*e*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]]*Sinh[(3*a)/b])/(2*b*c^3) - (3*e^2*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]]*Sinh[(3*a)/b])/(16*b*c^5) - (e^2*CoshIntegral[(5*a)/b + 5*ArcCosh[c*x]]*Sinh[(5*a)/b])/(16*b*c^5) + (d*e*Cosh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(2*b*c^3) + (e^2*Cosh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(8*b*c^5) + (d*e*Cosh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(2*b*c^3) + (3*e^2*Cosh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(16*b*c^5) + (e^2*Cosh[(5*a)/b]*SinhIntegral[(5*a)/b + 5*ArcCosh[c*x]])/(16*b*c^5) + (d^2*Cosh[a/b]*SinhIntegral[(a + b*ArcCosh[c*x])/b])/(b*c)}
{(d + e*x^2)/(a + b*ArcCosh[c*x]), x, 15, -(e*CoshIntegral[a/b + ArcCosh[c*x]]*Sinh[a/b])/(4*b*c^3) - (d*CoshIntegral[(a + b*ArcCosh[c*x])/b]*Sinh[a/b])/(b*c) - (e*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]]*Sinh[(3*a)/b])/(4*b*c^3) + (e*Cosh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(4*b*c^3) + (e*Cosh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(4*b*c^3) + (d*Cosh[a/b]*SinhIntegral[(a + b*ArcCosh[c*x])/b])/(b*c)}
{(a + b*ArcCosh[c*x])^(-1), x, 4, -((CoshIntegral[(a + b*ArcCosh[c*x])/b]*Sinh[a/b])/(b*c)) + (Cosh[a/b]*SinhIntegral[(a + b*ArcCosh[c*x])/b])/(b*c)}
{1/((d + e*x^2)*(a + b*ArcCosh[c*x])), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcCosh[c*x])), x]}
{1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcCosh[c x])^2*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p / (a+b ArcCosh[c x])^2*)


{(d + e*x^2)^2/(a + b*ArcCosh[c*x])^2, x, 26, -((d^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x]))) - (2*d*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x])) - (e^2*x^4*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x])) + (d^2*Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(b^2*c) + (d*e*Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(2*b^2*c^3) + (e^2*Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(8*b^2*c^5) + (3*d*e*Cosh[(3*a)/b]*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(2*b^2*c^3) + (9*e^2*Cosh[(3*a)/b]*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(16*b^2*c^5) + (5*e^2*Cosh[(5*a)/b]*CoshIntegral[(5*a)/b + 5*ArcCosh[c*x]])/(16*b^2*c^5) - (d^2*Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(b^2*c) - (d*e*Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(2*b^2*c^3) - (e^2*Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(8*b^2*c^5) - (3*d*e*Sinh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(2*b^2*c^3) - (9*e^2*Sinh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(16*b^2*c^5) - (5*e^2*Sinh[(5*a)/b]*SinhIntegral[(5*a)/b + 5*ArcCosh[c*x]])/(16*b^2*c^5)}
{(d + e*x^2)/(a + b*ArcCosh[c*x])^2, x, 15, -((d*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x]))) - (e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x])) + (d*Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(b^2*c) + (e*Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(4*b^2*c^3) + (3*e*Cosh[(3*a)/b]*CoshIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(4*b^2*c^3) - (d*Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(b^2*c) - (e*Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(4*b^2*c^3) - (3*e*Sinh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcCosh[c*x]])/(4*b^2*c^3)}
{(a + b*ArcCosh[c*x])^(-2), x, 5, -((Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*(a + b*ArcCosh[c*x]))) + (Cosh[a/b]*CoshIntegral[a/b + ArcCosh[c*x]])/(b^2*c) - (Sinh[a/b]*SinhIntegral[a/b + ArcCosh[c*x]])/(b^2*c)}
{1/((d + e*x^2)*(a + b*ArcCosh[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcCosh[c*x])^2), x]}
{1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])^2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcCosh[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x^2)^p (a+b ArcCosh[c x])^(n/2)*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x^2)^2*Sqrt[a + b*ArcCosh[c*x]], x, 42, d^2*x*Sqrt[a + b*ArcCosh[c*x]] + (2*d*e*x^3*Sqrt[a + b*ArcCosh[c*x]])/3 + (e^2*x^5*Sqrt[a + b*ArcCosh[c*x]])/5 - (Sqrt[b]*d^2*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c) - (Sqrt[b]*d*e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c^3) - (Sqrt[b]*e^2*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(32*c^5) - (Sqrt[b]*d*e*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(24*c^3) - (Sqrt[b]*e^2*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(64*c^5) - (Sqrt[b]*e^2*E^((5*a)/b)*Sqrt[Pi/5]*Erf[(Sqrt[5]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(320*c^5) - (Sqrt[b]*d^2*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c*E^(a/b)) - (Sqrt[b]*d*e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c^3*E^(a/b)) - (Sqrt[b]*e^2*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(32*c^5*E^(a/b)) - (Sqrt[b]*d*e*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(24*c^3*E^((3*a)/b)) - (Sqrt[b]*e^2*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(64*c^5*E^((3*a)/b)) - (Sqrt[b]*e^2*Sqrt[Pi/5]*Erfi[(Sqrt[5]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(320*c^5*E^((5*a)/b))}
{(d + e*x^2)*Sqrt[a + b*ArcCosh[c*x]], x, 23, d*x*Sqrt[a + b*ArcCosh[c*x]] + (e*x^3*Sqrt[a + b*ArcCosh[c*x]])/3 - (Sqrt[b]*d*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c) - (Sqrt[b]*e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(16*c^3) - (Sqrt[b]*e*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(48*c^3) - (Sqrt[b]*d*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c*E^(a/b)) - (Sqrt[b]*e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(16*c^3*E^(a/b)) - (Sqrt[b]*e*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(48*c^3*E^((3*a)/b))}
{Sqrt[a + b*ArcCosh[c*x]], x, 7, x*Sqrt[a + b*ArcCosh[c*x]] - (Sqrt[b]*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c) - (Sqrt[b]*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*c*E^(a/b))}
{Sqrt[a + b*ArcCosh[c*x]]/(d + e*x^2), x, 0, Unintegrable[Sqrt[a + b*ArcCosh[c*x]]/(d + e*x^2), x]}
{Sqrt[a + b*ArcCosh[c*x]]/(d + e*x^2)^2, x, 0, Unintegrable[Sqrt[a + b*ArcCosh[c*x]]/(d + e*x^2)^2, x]}


{(d + e*x^2)*(a + b*ArcCosh[c*x])^(3/2), x, 32, (-3*b*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[a + b*ArcCosh[c*x]])/(2*c) - (b*e*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[a + b*ArcCosh[c*x]])/(3*c^3) - (b*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[a + b*ArcCosh[c*x]])/(6*c) + d*x*(a + b*ArcCosh[c*x])^(3/2) + (e*x^3*(a + b*ArcCosh[c*x])^(3/2))/3 - (3*b^(3/2)*d*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c) - (3*b^(3/2)*e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(32*c^3) - (b^(3/2)*e*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(96*c^3) + (3*b^(3/2)*d*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c*E^(a/b)) + (3*b^(3/2)*e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(32*c^3*E^(a/b)) + (b^(3/2)*e*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(96*c^3*E^((3*a)/b))}
{(a + b*ArcCosh[c*x])^(3/2), x, 8, (-3*b*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[a + b*ArcCosh[c*x]])/(2*c) + x*(a + b*ArcCosh[c*x])^(3/2) - (3*b^(3/2)*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c) + (3*b^(3/2)*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*c*E^(a/b))}
{(a + b*ArcCosh[c*x])^(3/2)/(d + e*x^2), x, 0, Unintegrable[(a + b*ArcCosh[c*x])^(3/2)/(d + e*x^2), x]}
{(a + b*ArcCosh[c*x])^(3/2)/(d + e*x^2)^2, x, 0, Unintegrable[(a + b*ArcCosh[c*x])^(3/2)/(d + e*x^2)^2, x]}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{(d + e*x^2)^2/Sqrt[a + b*ArcCosh[c*x]], x, 39, -(d^2*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c) - (d*e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*Sqrt[b]*c^3) - (e^2*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(16*Sqrt[b]*c^5) - (d*e*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(4*Sqrt[b]*c^3) - (e^2*E^((3*a)/b)*Sqrt[3*Pi]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(32*Sqrt[b]*c^5) - (e^2*E^((5*a)/b)*Sqrt[Pi/5]*Erf[(Sqrt[5]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(32*Sqrt[b]*c^5) + (d^2*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c*E^(a/b)) + (d*e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*Sqrt[b]*c^3*E^(a/b)) + (e^2*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(16*Sqrt[b]*c^5*E^(a/b)) + (d*e*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(4*Sqrt[b]*c^3*E^((3*a)/b)) + (e^2*Sqrt[3*Pi]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(32*Sqrt[b]*c^5*E^((3*a)/b)) + (e^2*Sqrt[Pi/5]*Erfi[(Sqrt[5]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(32*Sqrt[b]*c^5*E^((5*a)/b))}
{(d + e*x^2)/Sqrt[a + b*ArcCosh[c*x]], x, 21, -(d*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c) - (e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*Sqrt[b]*c^3) - (e*E^((3*a)/b)*Sqrt[Pi/3]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(8*Sqrt[b]*c^3) + (d*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c*E^(a/b)) + (e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(8*Sqrt[b]*c^3*E^(a/b)) + (e*Sqrt[Pi/3]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(8*Sqrt[b]*c^3*E^((3*a)/b))}
{1/Sqrt[a + b*ArcCosh[c*x]], x, 6, -(E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c) + (Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(2*Sqrt[b]*c*E^(a/b))}
{1/((d + e*x^2)*Sqrt[a + b*ArcCosh[c*x]]), x, 0, Unintegrable[1/((d + e*x^2)*Sqrt[a + b*ArcCosh[c*x]]), x]}
{1/((d + e*x^2)^2*Sqrt[a + b*ArcCosh[c*x]]), x, 0, Unintegrable[1/((d + e*x^2)^2*Sqrt[a + b*ArcCosh[c*x]]), x]}


{(d + e*x^2)/(a + b*ArcCosh[c*x])^(3/2), x, 21, (-2*d*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*Sqrt[a + b*ArcCosh[c*x]]) - (2*e*x^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*Sqrt[a + b*ArcCosh[c*x]]) + (d*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(b^(3/2)*c) + (e*E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*b^(3/2)*c^3) + (e*E^((3*a)/b)*Sqrt[3*Pi]*Erf[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(4*b^(3/2)*c^3) + (d*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(b^(3/2)*c*E^(a/b)) + (e*Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(4*b^(3/2)*c^3*E^(a/b)) + (e*Sqrt[3*Pi]*Erfi[(Sqrt[3]*Sqrt[a + b*ArcCosh[c*x]])/Sqrt[b]])/(4*b^(3/2)*c^3*E^((3*a)/b))}
{(a + b*ArcCosh[c*x])^(-3/2), x, 7, (-2*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(b*c*Sqrt[a + b*ArcCosh[c*x]]) + (E^(a/b)*Sqrt[Pi]*Erf[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(b^(3/2)*c) + (Sqrt[Pi]*Erfi[Sqrt[a + b*ArcCosh[c*x]]/Sqrt[b]])/(b^(3/2)*c*E^(a/b))}
{1/((d + e*x^2)*(a + b*ArcCosh[c*x])^(3/2)), x, 0, Unintegrable[1/((d + e*x^2)*(a + b*ArcCosh[c*x])^(3/2)), x]}
{1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])^(3/2)), x, 0, Unintegrable[1/((d + e*x^2)^2*(a + b*ArcCosh[c*x])^(3/2)), x]}


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x^2)^(p/2) (a+b ArcCosh[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x]), x]}
{(a + b*ArcCosh[c*x])/Sqrt[d + e*x^2], x, 0, Unintegrable[(a + b*ArcCosh[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcCosh[c*x])/(d + e*x^2)^(3/2), x, 7, (x*(a + b*ArcCosh[c*x]))/(d*Sqrt[d + e*x^2]) - (b*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(d*Sqrt[e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(a + b*ArcCosh[c*x])/(d + e*x^2)^(5/2), x, 8, -((b*c*Sqrt[-1 + c*x]*Sqrt[1 + c*x])/(3*d*(c^2*d + e)*Sqrt[d + e*x^2])) + (x*(a + b*ArcCosh[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcCosh[c*x]))/(3*d^2*Sqrt[d + e*x^2]) + (2*b*Sqrt[1 - c^2*x^2]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(3*d^2*Sqrt[e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x]), (b*c*(1 - c^2*x^2))/(3*d*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]) + (x*(a + b*ArcCosh[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcCosh[c*x]))/(3*d^2*Sqrt[d + e*x^2]) - (2*b*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(3*d^2*Sqrt[e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}
{(a + b*ArcCosh[c*x])/(d + e*x^2)^(7/2), x, 9, (b*c*(1 - c^2*x^2))/(15*d*(c^2*d + e)*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*(d + e*x^2)^(3/2)) + (2*b*c*(3*c^2*d + 2*e)*(1 - c^2*x^2))/(15*d^2*(c^2*d + e)^2*Sqrt[-1 + c*x]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]) + (x*(a + b*ArcCosh[c*x]))/(5*d*(d + e*x^2)^(5/2)) + (4*x*(a + b*ArcCosh[c*x]))/(15*d^2*(d + e*x^2)^(3/2)) + (8*x*(a + b*ArcCosh[c*x]))/(15*d^3*Sqrt[d + e*x^2]) - (8*b*Sqrt[-1 + c^2*x^2]*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(15*d^3*Sqrt[e]*Sqrt[-1 + c*x]*Sqrt[1 + c*x])}


{Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])^2, x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])^2, x]}
{(a + b*ArcCosh[c*x])^2/Sqrt[d + e*x^2], x, 0, Unintegrable[(a + b*ArcCosh[c*x])^2/Sqrt[d + e*x^2], x]}
{(a + b*ArcCosh[c*x])^2/(d + e*x^2)^(3/2), x, 0, Unintegrable[(a + b*ArcCosh[c*x])^2/(d + e*x^2)^(3/2), x]}
{(a + b*ArcCosh[c*x])^2/(d + e*x^2)^(5/2), x, 0, Unintegrable[(a + b*ArcCosh[c*x])^2/(d + e*x^2)^(5/2), x]}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{Sqrt[d + e*x^2]/(a + b*ArcCosh[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]/(a + b*ArcCosh[c*x]), x]}
{1/(Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])), x, 0, Unintegrable[1/(Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])), x]}
{1/((d + e*x^2)^(3/2)*(a + b*ArcCosh[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^(3/2)*(a + b*ArcCosh[c*x])), x]}
{1/((d + e*x^2)^(5/2)*(a + b*ArcCosh[c*x])), x, 0, Unintegrable[1/((d + e*x^2)^(5/2)*(a + b*ArcCosh[c*x])), x]}


{Sqrt[d + e*x^2]/(a + b*ArcCosh[c*x])^2, x, 0, Unintegrable[Sqrt[d + e*x^2]/(a + b*ArcCosh[c*x])^2, x]}
{1/(Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])^2), x, 0, Unintegrable[1/(Sqrt[d + e*x^2]*(a + b*ArcCosh[c*x])^2), x]}
{1/((d + e*x^2)^(3/2)*(a + b*ArcCosh[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^(3/2)*(a + b*ArcCosh[c*x])^2), x]}
{1/((d + e*x^2)^(5/2)*(a + b*ArcCosh[c*x])^2), x, 0, Unintegrable[1/((d + e*x^2)^(5/2)*(a + b*ArcCosh[c*x])^2), x]}
