(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form u (a+b ArcSech[c x])^n*)


(* ::Section::Closed:: *)
(*Integrands of the form (d x)^m (a+b ArcSech[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m ArcSech[a x]^n*)


{x^4*ArcSech[a*x]^2, x, 9, -((3*x)/(20*a^4)) - x^3/(30*a^2) - (3*x*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(20*a^4) - (x^3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(10*a^2) + (1/5)*x^5*ArcSech[a*x]^2 - (3*ArcSech[a*x]*ArcTan[E^ArcSech[a*x]])/(10*a^5) + (3*I*PolyLog[2, (-I)*E^ArcSech[a*x]])/(20*a^5) - (3*I*PolyLog[2, I*E^ArcSech[a*x]])/(20*a^5)}
{x^3*ArcSech[a*x]^2, x, 5, -(x^2/(12*a^2)) - (Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(3*a^4) - (x^2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(6*a^2) + (1/4)*x^4*ArcSech[a*x]^2 - Log[x]/(3*a^4)}
{x^2*ArcSech[a*x]^2, x, 8, -(x/(3*a^2)) - (x*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(3*a^2) + (1/3)*x^3*ArcSech[a*x]^2 - (2*ArcSech[a*x]*ArcTan[E^ArcSech[a*x]])/(3*a^3) + (I*PolyLog[2, (-I)*E^ArcSech[a*x]])/(3*a^3) - (I*PolyLog[2, I*E^ArcSech[a*x]])/(3*a^3)}
{x^1*ArcSech[a*x]^2, x, 4, -((Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/a^2) + (1/2)*x^2*ArcSech[a*x]^2 - Log[x]/a^2}
{x^0*ArcSech[a*x]^2, x, 7, x*ArcSech[a*x]^2 - (4*ArcSech[a*x]*ArcTan[E^ArcSech[a*x]])/a + (2*I*PolyLog[2, (-I)*E^ArcSech[a*x]])/a - (2*I*PolyLog[2, I*E^ArcSech[a*x]])/a}
{ArcSech[a*x]^2/x^1, x, 6, (1/3)*ArcSech[a*x]^3 - ArcSech[a*x]^2*Log[1 + E^(2*ArcSech[a*x])] - ArcSech[a*x]*PolyLog[2, -E^(2*ArcSech[a*x])] + (1/2)*PolyLog[3, -E^(2*ArcSech[a*x])]}
{ArcSech[a*x]^2/x^2, x, 4, -(2/x) + (2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/x - ArcSech[a*x]^2/x}
{ArcSech[a*x]^2/x^3, x, 4, -(((1 - a*x)*(1 + a*x))/(4*x^2)) + (Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(2*x^2) - (1/4)*a^2*ArcSech[a*x]^2 - ((1 - a*x)*(1 + a*x)*ArcSech[a*x]^2)/(2*x^2)}
{ArcSech[a*x]^2/x^4, x, 5, -(2/(27*x^3)) - (4*a^2)/(9*x) + (2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(9*x^3) + (4*a^2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x])/(9*x) - ArcSech[a*x]^2/(3*x^3)}


{x^4*ArcSech[a*x]^3, x, 14, (x*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(20*a^4) - (9*x*ArcSech[a*x])/(20*a^4) - (x^3*ArcSech[a*x])/(10*a^2) - (9*x*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(40*a^4) - (3*x^3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(20*a^2) + (1/5)*x^5*ArcSech[a*x]^3 - (9*ArcSech[a*x]^2*ArcTan[E^ArcSech[a*x]])/(20*a^5) + ArcTan[(Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(a*x)]/(2*a^5) + (9*I*ArcSech[a*x]*PolyLog[2, (-I)*E^ArcSech[a*x]])/(20*a^5) - (9*I*ArcSech[a*x]*PolyLog[2, I*E^ArcSech[a*x]])/(20*a^5) - (9*I*PolyLog[3, (-I)*E^ArcSech[a*x]])/(20*a^5) + (9*I*PolyLog[3, I*E^ArcSech[a*x]])/(20*a^5)}
{x^3*ArcSech[a*x]^3, x, 10, (Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(4*a^4) - (x^2*ArcSech[a*x])/(4*a^2) - ArcSech[a*x]^2/(2*a^4) - (Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(2*a^4) - (x^2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(4*a^2) + (1/4)*x^4*ArcSech[a*x]^3 + (ArcSech[a*x]*Log[1 + E^(2*ArcSech[a*x])])/a^4 + PolyLog[2, -E^(2*ArcSech[a*x])]/(2*a^4)}
{x^2*ArcSech[a*x]^3, x, 11, -((x*ArcSech[a*x])/a^2) - (x*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(2*a^2) + (1/3)*x^3*ArcSech[a*x]^3 - (ArcSech[a*x]^2*ArcTan[E^ArcSech[a*x]])/a^3 + ArcTan[(Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(a*x)]/a^3 + (I*ArcSech[a*x]*PolyLog[2, (-I)*E^ArcSech[a*x]])/a^3 - (I*ArcSech[a*x]*PolyLog[2, I*E^ArcSech[a*x]])/a^3 - (I*PolyLog[3, (-I)*E^ArcSech[a*x]])/a^3 + (I*PolyLog[3, I*E^ArcSech[a*x]])/a^3}
{x^1*ArcSech[a*x]^3, x, 7, -((3*ArcSech[a*x]^2)/(2*a^2)) - (3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(2*a^2) + (1/2)*x^2*ArcSech[a*x]^3 + (3*ArcSech[a*x]*Log[1 + E^(2*ArcSech[a*x])])/a^2 + (3*PolyLog[2, -E^(2*ArcSech[a*x])])/(2*a^2)}
{x^0*ArcSech[a*x]^3, x, 9, x*ArcSech[a*x]^3 - (6*ArcSech[a*x]^2*ArcTan[E^ArcSech[a*x]])/a + (6*I*ArcSech[a*x]*PolyLog[2, (-I)*E^ArcSech[a*x]])/a - (6*I*ArcSech[a*x]*PolyLog[2, I*E^ArcSech[a*x]])/a - (6*I*PolyLog[3, (-I)*E^ArcSech[a*x]])/a + (6*I*PolyLog[3, I*E^ArcSech[a*x]])/a}
{ArcSech[a*x]^3/x^1, x, 7, (1/4)*ArcSech[a*x]^4 - ArcSech[a*x]^3*Log[1 + E^(2*ArcSech[a*x])] - (3/2)*ArcSech[a*x]^2*PolyLog[2, -E^(2*ArcSech[a*x])] + (3/2)*ArcSech[a*x]*PolyLog[3, -E^(2*ArcSech[a*x])] - (3/4)*PolyLog[4, -E^(2*ArcSech[a*x])]}
{ArcSech[a*x]^3/x^2, x, 5, (6*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/x - (6*ArcSech[a*x])/x + (3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/x - ArcSech[a*x]^3/x}
{ArcSech[a*x]^3/x^3, x, 6, (3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(8*x^2) - (3/8)*a^2*ArcSech[a*x] - (3*(1 - a*x)*(1 + a*x)*ArcSech[a*x])/(4*x^2) + (3*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(4*x^2) - (1/4)*a^2*ArcSech[a*x]^3 - ((1 - a*x)*(1 + a*x)*ArcSech[a*x]^3)/(2*x^2)}
{ArcSech[a*x]^3/x^4, x, 8, (14*a^2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x))/(9*x) + (2*((1 - a*x)/(1 + a*x))^(3/2)*(1 + a*x)^3)/(27*x^3) - (2*ArcSech[a*x])/(9*x^3) - (4*a^2*ArcSech[a*x])/(3*x) + (Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(3*x^3) + (2*a^2*Sqrt[(1 - a*x)/(1 + a*x)]*(1 + a*x)*ArcSech[a*x]^2)/(3*x) - ArcSech[a*x]^3/(3*x^3)}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (a+b ArcSech[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{x^6*(a + b*ArcSech[c*x]), x, 8, -((5*b*x*Sqrt[1 - c*x])/(112*c^6*Sqrt[1/(1 + c*x)])) - (5*b*x^3*Sqrt[1 - c*x])/(168*c^4*Sqrt[1/(1 + c*x)]) - (b*x^5*Sqrt[1 - c*x])/(42*c^2*Sqrt[1/(1 + c*x)]) + (1/7)*x^7*(a + b*ArcSech[c*x]) + (5*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(112*c^7)}
{x^5*(a + b*ArcSech[c*x]), x, 6, -((4*b*Sqrt[1 - c*x])/(45*c^6*Sqrt[1/(1 + c*x)])) - (2*b*x^2*Sqrt[1 - c*x])/(45*c^4*Sqrt[1/(1 + c*x)]) - (b*x^4*Sqrt[1 - c*x])/(30*c^2*Sqrt[1/(1 + c*x)]) + (1/6)*x^6*(a + b*ArcSech[c*x])}
{x^4*(a + b*ArcSech[c*x]), x, 6, -((3*b*x*Sqrt[1 - c*x])/(40*c^4*Sqrt[1/(1 + c*x)])) - (b*x^3*Sqrt[1 - c*x])/(20*c^2*Sqrt[1/(1 + c*x)]) + (1/5)*x^5*(a + b*ArcSech[c*x]) + (3*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(40*c^5)}
{x^3*(a + b*ArcSech[c*x]), x, 4, -((b*Sqrt[1 - c*x])/(6*c^4*Sqrt[1/(1 + c*x)])) - (b*x^2*Sqrt[1 - c*x])/(12*c^2*Sqrt[1/(1 + c*x)]) + (1/4)*x^4*(a + b*ArcSech[c*x])}
{x^2*(a + b*ArcSech[c*x]), x, 4, -((b*x*Sqrt[1 - c*x])/(6*c^2*Sqrt[1/(1 + c*x)])) + (1/3)*x^3*(a + b*ArcSech[c*x]) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(6*c^3)}
{x^1*(a + b*ArcSech[c*x]), x, 2, -((b*Sqrt[1 - c*x])/(2*c^2*Sqrt[1/(1 + c*x)])) + (1/2)*x^2*(a + b*ArcSech[c*x])}
{x^0*(a + b*ArcSech[c*x]), x, 3, a*x + b*x*ArcSech[c*x] + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/c}
{(a + b*ArcSech[c*x])/x^1, x, 6, (a + b*ArcSech[c*x])^2/(2*b) - (a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])] - (1/2)*b*PolyLog[2, -E^(2*ArcSech[c*x])]}
{(a + b*ArcSech[c*x])/x^2, x, 2, (b*Sqrt[1 - c*x])/(x*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/x}
{(a + b*ArcSech[c*x])/x^3, x, 5, (b*Sqrt[1 - c*x])/(4*x^2*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/(2*x^2) + (1/4)*b*c^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c*x]*Sqrt[1 + c*x]]}
{(a + b*ArcSech[c*x])/x^4, x, 4, (b*Sqrt[1 - c*x])/(9*x^3*Sqrt[1/(1 + c*x)]) + (2*b*c^2*Sqrt[1 - c*x])/(9*x*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/(3*x^3)}
{(a + b*ArcSech[c*x])/x^5, x, 7, (b*Sqrt[1 - c*x])/(16*x^4*Sqrt[1/(1 + c*x)]) + (3*b*c^2*Sqrt[1 - c*x])/(32*x^2*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/(4*x^4) + (3/32)*b*c^4*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c*x]*Sqrt[1 + c*x]]}
{(a + b*ArcSech[c*x])/x^6, x, 6, (b*Sqrt[1 - c*x])/(25*x^5*Sqrt[1/(1 + c*x)]) + (4*b*c^2*Sqrt[1 - c*x])/(75*x^3*Sqrt[1/(1 + c*x)]) + (8*b*c^4*Sqrt[1 - c*x])/(75*x*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/(5*x^5)}
{(a + b*ArcSech[c*x])/x^7, x, 9, (b*Sqrt[1 - c*x])/(36*x^6*Sqrt[1/(1 + c*x)]) + (5*b*c^2*Sqrt[1 - c*x])/(144*x^4*Sqrt[1/(1 + c*x)]) + (5*b*c^4*Sqrt[1 - c*x])/(96*x^2*Sqrt[1/(1 + c*x)]) - (a + b*ArcSech[c*x])/(6*x^6) + (5/96)*b*c^6*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c*x]*Sqrt[1 + c*x]]}


{x^3*(a + b*ArcSech[c*x])^2, x, 5, -((b^2*x^2)/(12*c^2)) - (b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(3*c^4) - (b*x^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(6*c^2) + (1/4)*x^4*(a + b*ArcSech[c*x])^2 - (b^2*Log[x])/(3*c^4)}
{x^2*(a + b*ArcSech[c*x])^2, x, 8, -((b^2*x)/(3*c^2)) - (b*x*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(3*c^2) + (1/3)*x^3*(a + b*ArcSech[c*x])^2 - (2*b*(a + b*ArcSech[c*x])*ArcTan[E^ArcSech[c*x]])/(3*c^3) + (I*b^2*PolyLog[2, (-I)*E^ArcSech[c*x]])/(3*c^3) - (I*b^2*PolyLog[2, I*E^ArcSech[c*x]])/(3*c^3)}
{x^1*(a + b*ArcSech[c*x])^2, x, 4, -((b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/c^2) + (1/2)*x^2*(a + b*ArcSech[c*x])^2 - (b^2*Log[x])/c^2}
{x^0*(a + b*ArcSech[c*x])^2, x, 7, x*(a + b*ArcSech[c*x])^2 - (4*b*(a + b*ArcSech[c*x])*ArcTan[E^ArcSech[c*x]])/c + (2*I*b^2*PolyLog[2, (-I)*E^ArcSech[c*x]])/c - (2*I*b^2*PolyLog[2, I*E^ArcSech[c*x]])/c}
{(a + b*ArcSech[c*x])^2/x^1, x, 6, (a + b*ArcSech[c*x])^3/(3*b) - (a + b*ArcSech[c*x])^2*Log[1 + E^(2*ArcSech[c*x])] - b*(a + b*ArcSech[c*x])*PolyLog[2, -E^(2*ArcSech[c*x])] + (1/2)*b^2*PolyLog[3, -E^(2*ArcSech[c*x])]}
{(a + b*ArcSech[c*x])^2/x^2, x, 4, -((2*b^2)/x) + (2*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/x - (a + b*ArcSech[c*x])^2/x}
{(a + b*ArcSech[c*x])^2/x^3, x, 4, -((b^2*(1 - c*x)*(1 + c*x))/(4*x^2)) - (1/2)*a*b*c^2*ArcSech[c*x] - (1/4)*b^2*c^2*ArcSech[c*x]^2 + (b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(2*x^2) - ((1 - c*x)*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(2*x^2)}
{(a + b*ArcSech[c*x])^2/x^4, x, 5, -((2*b^2)/(27*x^3)) - (4*b^2*c^2)/(9*x) + (2*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(9*x^3) + (4*b*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(9*x) - (a + b*ArcSech[c*x])^2/(3*x^3)}
{(a + b*ArcSech[c*x])^2/x^5, x, 5, -(b^2/(32*x^4)) - (3*b^2*c^2)/(32*x^2) + (3/16)*a*b*c^4*ArcSech[c*x] + (3/32)*b^2*c^4*ArcSech[c*x]^2 + (b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(8*x^4) + (3*b*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x]))/(16*x^2) - (a + b*ArcSech[c*x])^2/(4*x^4)}


{x^3*(a + b*ArcSech[c*x])^3, x, 10, (b^3*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(4*c^4) - (b^2*x^2*(a + b*ArcSech[c*x]))/(4*c^2) - (b*(a + b*ArcSech[c*x])^2)/(2*c^4) - (b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(2*c^4) - (b*x^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(4*c^2) + (1/4)*x^4*(a + b*ArcSech[c*x])^3 + (b^2*(a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/c^4 + (b^3*PolyLog[2, -E^(2*ArcSech[c*x])])/(2*c^4)}
{x^2*(a + b*ArcSech[c*x])^3, x, 11, -((b^2*x*(a + b*ArcSech[c*x]))/c^2) - (b*x*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(2*c^2) + (1/3)*x^3*(a + b*ArcSech[c*x])^3 - (b*(a + b*ArcSech[c*x])^2*ArcTan[E^ArcSech[c*x]])/c^3 + (b^3*ArcTan[(Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(c*x)])/c^3 + (I*b^2*(a + b*ArcSech[c*x])*PolyLog[2, (-I)*E^ArcSech[c*x]])/c^3 - (I*b^2*(a + b*ArcSech[c*x])*PolyLog[2, I*E^ArcSech[c*x]])/c^3 - (I*b^3*PolyLog[3, (-I)*E^ArcSech[c*x]])/c^3 + (I*b^3*PolyLog[3, I*E^ArcSech[c*x]])/c^3}
{x^1*(a + b*ArcSech[c*x])^3, x, 7, -((3*b*(a + b*ArcSech[c*x])^2)/(2*c^2)) - (3*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(2*c^2) + (1/2)*x^2*(a + b*ArcSech[c*x])^3 + (3*b^2*(a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/c^2 + (3*b^3*PolyLog[2, -E^(2*ArcSech[c*x])])/(2*c^2)}
{x^0*(a + b*ArcSech[c*x])^3, x, 9, x*(a + b*ArcSech[c*x])^3 - (6*b*(a + b*ArcSech[c*x])^2*ArcTan[E^ArcSech[c*x]])/c + (6*I*b^2*(a + b*ArcSech[c*x])*PolyLog[2, (-I)*E^ArcSech[c*x]])/c - (6*I*b^2*(a + b*ArcSech[c*x])*PolyLog[2, I*E^ArcSech[c*x]])/c - (6*I*b^3*PolyLog[3, (-I)*E^ArcSech[c*x]])/c + (6*I*b^3*PolyLog[3, I*E^ArcSech[c*x]])/c}
{(a + b*ArcSech[c*x])^3/x^1, x, 7, (a + b*ArcSech[c*x])^4/(4*b) - (a + b*ArcSech[c*x])^3*Log[1 + E^(2*ArcSech[c*x])] - (3/2)*b*(a + b*ArcSech[c*x])^2*PolyLog[2, -E^(2*ArcSech[c*x])] + (3/2)*b^2*(a + b*ArcSech[c*x])*PolyLog[3, -E^(2*ArcSech[c*x])] - (3/4)*b^3*PolyLog[4, -E^(2*ArcSech[c*x])]}
{(a + b*ArcSech[c*x])^3/x^2, x, 5, (6*b^3*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/x - (6*b^2*(a + b*ArcSech[c*x]))/x + (3*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/x - (a + b*ArcSech[c*x])^3/x}
{(a + b*ArcSech[c*x])^3/x^3, x, 6, (3*b^3*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(8*x^2) - (3/8)*b^3*c^2*ArcSech[c*x] - (3*b^2*(1 - c*x)*(1 + c*x)*(a + b*ArcSech[c*x]))/(4*x^2) + (3*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(4*x^2) - (1/4)*c^2*(a + b*ArcSech[c*x])^3 - ((1 - c*x)*(1 + c*x)*(a + b*ArcSech[c*x])^3)/(2*x^2)}
{(a + b*ArcSech[c*x])^3/x^4, x, 8, (14*b^3*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(9*x) + (2*b^3*((1 - c*x)/(1 + c*x))^(3/2)*(1 + c*x)^3)/(27*x^3) - (2*b^2*(a + b*ArcSech[c*x]))/(9*x^3) - (4*b^2*c^2*(a + b*ArcSech[c*x]))/(3*x) + (b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(3*x^3) + (2*b*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(3*x) - (a + b*ArcSech[c*x])^3/(3*x^3)}
{(a + b*ArcSech[c*x])^3/x^5, x, 10, (3*b^3*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(128*x^4) + (45*b^3*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(256*x^2) + (45/256)*b^3*c^4*ArcSech[c*x] - (3*b^2*(a + b*ArcSech[c*x]))/(32*x^4) - (9*b^2*c^2*(a + b*ArcSech[c*x]))/(32*x^2) + (3*b*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(16*x^4) + (9*b*c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x)*(a + b*ArcSech[c*x])^2)/(32*x^2) + (3/32)*c^4*(a + b*ArcSech[c*x])^3 - (a + b*ArcSech[c*x])^3/(4*x^4)}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{x^1/(a + b*ArcSech[c*x]), x, 0, Unintegrable[x/(a + b*ArcSech[c*x]), x]}
{x^0/(a + b*ArcSech[c*x]), x, 0, Unintegrable[1/(a + b*ArcSech[c*x]), x]}
{1/(x^1*(a + b*ArcSech[c*x])), x, 0, Unintegrable[1/(x*(a + b*ArcSech[c*x])), x]}
{1/(x^2*(a + b*ArcSech[c*x])), x, 4, (c*CoshIntegral[a/b + ArcSech[c*x]]*Sinh[a/b])/b - (c*Cosh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/b}
{1/(x^3*(a + b*ArcSech[c*x])), x, 6, (c^2*CoshIntegral[(2*a)/b + 2*ArcSech[c*x]]*Sinh[(2*a)/b])/(2*b) - (c^2*Cosh[(2*a)/b]*SinhIntegral[(2*a)/b + 2*ArcSech[c*x]])/(2*b)}
{1/(x^4*(a + b*ArcSech[c*x])), x, 9, (c^3*CoshIntegral[a/b + ArcSech[c*x]]*Sinh[a/b])/(4*b) + (c^3*CoshIntegral[(3*a)/b + 3*ArcSech[c*x]]*Sinh[(3*a)/b])/(4*b) - (c^3*Cosh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/(4*b) - (c^3*Cosh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcSech[c*x]])/(4*b)}


{x^1/(a + b*ArcSech[c*x])^2, x, 0, Unintegrable[x/(a + b*ArcSech[c*x])^2, x]}
{x^0/(a + b*ArcSech[c*x])^2, x, 0, Unintegrable[1/(a + b*ArcSech[c*x])^2, x]}
{1/(x^1*(a + b*ArcSech[c*x])^2), x, 0, Unintegrable[1/(x*(a + b*ArcSech[c*x])^2), x]}
{1/(x^2*(a + b*ArcSech[c*x])^2), x, 5, (Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(b*x*(a + b*ArcSech[c*x])) - (c*Cosh[a/b]*CoshIntegral[a/b + ArcSech[c*x]])/b^2 + (c*Sinh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/b^2}
{1/(x^3*(a + b*ArcSech[c*x])^2), x, 7, -((c^2*Cosh[(2*a)/b]*CoshIntegral[(2*a)/b + 2*ArcSech[c*x]])/b^2) + (c^2*Sinh[2*ArcSech[c*x]])/(2*b*(a + b*ArcSech[c*x])) + (c^2*Sinh[(2*a)/b]*SinhIntegral[(2*a)/b + 2*ArcSech[c*x]])/b^2}
{1/(x^4*(a + b*ArcSech[c*x])^2), x, 11, (c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(4*b*x*(a + b*ArcSech[c*x])) - (c^3*Cosh[a/b]*CoshIntegral[a/b + ArcSech[c*x]])/(4*b^2) - (3*c^3*Cosh[(3*a)/b]*CoshIntegral[(3*a)/b + 3*ArcSech[c*x]])/(4*b^2) + (c^3*Sinh[3*ArcSech[c*x]])/(4*b*(a + b*ArcSech[c*x])) + (c^3*Sinh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/(4*b^2) + (3*c^3*Sinh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcSech[c*x]])/(4*b^2)}


{x^1/(a + b*ArcSech[c*x])^3, x, 0, Unintegrable[x/(a + b*ArcSech[c*x])^3, x]}
{x^0/(a + b*ArcSech[c*x])^3, x, 0, Unintegrable[1/(a + b*ArcSech[c*x])^3, x]}
{1/(x^1*(a + b*ArcSech[c*x])^3), x, 0, Unintegrable[1/(x*(a + b*ArcSech[c*x])^3), x]}
{1/(x^2*(a + b*ArcSech[c*x])^3), x, 6, (Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(2*b*x*(a + b*ArcSech[c*x])^2) + 1/(2*b^2*x*(a + b*ArcSech[c*x])) + (c*CoshIntegral[a/b + ArcSech[c*x]]*Sinh[a/b])/(2*b^3) - (c*Cosh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/(2*b^3)}
{1/(x^3*(a + b*ArcSech[c*x])^3), x, 8, (c^2*Cosh[2*ArcSech[c*x]])/(2*b^2*(a + b*ArcSech[c*x])) + (c^2*CoshIntegral[(2*a)/b + 2*ArcSech[c*x]]*Sinh[(2*a)/b])/b^3 + (c^2*Sinh[2*ArcSech[c*x]])/(4*b*(a + b*ArcSech[c*x])^2) - (c^2*Cosh[(2*a)/b]*SinhIntegral[(2*a)/b + 2*ArcSech[c*x]])/b^3}
{1/(x^4*(a + b*ArcSech[c*x])^3), x, 13, (c^2*Sqrt[(1 - c*x)/(1 + c*x)]*(1 + c*x))/(8*b*x*(a + b*ArcSech[c*x])^2) + c^2/(8*b^2*x*(a + b*ArcSech[c*x])) + (3*c^3*Cosh[3*ArcSech[c*x]])/(8*b^2*(a + b*ArcSech[c*x])) + (c^3*CoshIntegral[a/b + ArcSech[c*x]]*Sinh[a/b])/(8*b^3) + (9*c^3*CoshIntegral[(3*a)/b + 3*ArcSech[c*x]]*Sinh[(3*a)/b])/(8*b^3) + (c^3*Sinh[3*ArcSech[c*x]])/(8*b*(a + b*ArcSech[c*x])^2) - (c^3*Cosh[a/b]*SinhIntegral[a/b + ArcSech[c*x]])/(8*b^3) - (9*c^3*Cosh[(3*a)/b]*SinhIntegral[(3*a)/b + 3*ArcSech[c*x]])/(8*b^3)}


(* ::Subsection::Closed:: *)
(*Integrands of the form (d x)^m (a+b ArcSech[c x])^n when m symbolic*)


{(d*x)^m*(a + b*ArcSech[c*x])^3, x, 0, Unintegrable[(d*x)^m*(a + b*ArcSech[c*x])^3, x]}
{(d*x)^m*(a + b*ArcSech[c*x])^2, x, 0, Unintegrable[(d*x)^m*(a + b*ArcSech[c*x])^2, x]}
{(d*x)^m*(a + b*ArcSech[c*x]), x, 3, ((d*x)^(1 + m)*(a + b*ArcSech[c*x]))/(d*(1 + m)) + (b*(d*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(d*(1 + m)^2)}
{(d*x)^m/(a + b*ArcSech[c*x]), x, 0, Unintegrable[(d*x)^m/(a + b*ArcSech[c*x]), x]}
{(d*x)^m/(a + b*ArcSech[c*x])^2, x, 0, Unintegrable[(d*x)^m/(a + b*ArcSech[c*x])^2, x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x)^m (a+b ArcSech[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x)^m (a+b ArcSech[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x)^3*(a + b*ArcSech[c*x]), x, 9, -((b*e*(9*c^2*d^2 + e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(6*c^4)) - (b*d*e^2*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(2*c^2) - (b*e^3*x^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(12*c^2) + ((d + e*x)^4*(a + b*ArcSech[c*x]))/(4*e) + (b*d*(2*c^2*d^2 + e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(2*c^3) - (b*d^4*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(4*e)}
{(d + e*x)^2*(a + b*ArcSech[c*x]), x, 8, -((b*d*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/c^2) - (b*e^2*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(6*c^2) + ((d + e*x)^3*(a + b*ArcSech[c*x]))/(3*e) + (b*(6*c^2*d^2 + e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(6*c^3) - (b*d^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(3*e)}
{(d + e*x)^1*(a + b*ArcSech[c*x]), x, 7, -((b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(2*c^2)) + ((d + e*x)^2*(a + b*ArcSech[c*x]))/(2*e) + (b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/c - (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(2*e)}
{(d + e*x)^0*(a + b*ArcSech[c*x]), x, 3, a*x + b*x*ArcSech[c*x] + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/c}
{(a + b*ArcSech[c*x])/(d + e*x)^1, x, 4, -(((a + b*ArcSech[c*x])*Log[1 + E^(-2*ArcSech[c*x])])/e) + ((a + b*ArcSech[c*x])*Log[1 + (e - Sqrt[(-c^2)*d^2 + e^2])/(E^ArcSech[c*x]*(c*d))])/e + ((a + b*ArcSech[c*x])*Log[1 + (e + Sqrt[(-c^2)*d^2 + e^2])/(E^ArcSech[c*x]*(c*d))])/e + (b*PolyLog[2, -E^(-2*ArcSech[c*x])])/(2*e) - (b*PolyLog[2, -((e - Sqrt[(-c^2)*d^2 + e^2])/(E^ArcSech[c*x]*(c*d)))])/e - (b*PolyLog[2, -((e + Sqrt[(-c^2)*d^2 + e^2])/(E^ArcSech[c*x]*(c*d)))])/e}
{(a + b*ArcSech[c*x])/(d + e*x)^2, x, 8, -((a + b*ArcSech[c*x])/(e*(d + e*x))) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(e + c^2*d*x)/(Sqrt[c^2*d^2 - e^2]*Sqrt[1 - c^2*x^2])])/(d*Sqrt[c^2*d^2 - e^2]) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(d*e)}
{(a + b*ArcSech[c*x])/(d + e*x)^3, x, 11, (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(2*d*(c^2*d^2 - e^2)*(d + e*x)) - (a + b*ArcSech[c*x])/(2*e*(d + e*x)^2) + (b*c^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(e + c^2*d*x)/(Sqrt[c^2*d^2 - e^2]*Sqrt[1 - c^2*x^2])])/(2*(c^2*d^2 - e^2)^(3/2)) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(e + c^2*d*x)/(Sqrt[c^2*d^2 - e^2]*Sqrt[1 - c^2*x^2])])/(2*d^2*Sqrt[c^2*d^2 - e^2]) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(2*d^2*e)}


(* ::Subsubsection:: *)
(*n<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x)^(m/2) (a+b ArcSech[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x)^(3/2)*(a + b*ArcSech[c*x]), x, 21, -((4*b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2])/(15*c^2)) + (2*(d + e*x)^(5/2)*(a + b*ArcSech[c*x]))/(5*e) - (28*b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*c*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*(2*c^2*d^2 + e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*c^3*Sqrt[d + e*x]) - (4*b*d^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*e*Sqrt[d + e*x])}
{(d + e*x)^(1/2)*(a + b*ArcSech[c*x]), x, 14, (2*(d + e*x)^(3/2)*(a + b*ArcSech[c*x]))/(3*e) - (4*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c*Sqrt[d + e*x]) - (4*b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*e*Sqrt[d + e*x])}
{(a + b*ArcSech[c*x])/(d + e*x)^(1/2), x, 8, (2*Sqrt[d + e*x]*(a + b*ArcSech[c*x]))/e - (4*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(c*Sqrt[d + e*x]) - (4*b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(e*Sqrt[d + e*x])}
{(a + b*ArcSech[c*x])/(d + e*x)^(3/2), x, 5, -((2*(a + b*ArcSech[c*x]))/(e*Sqrt[d + e*x])) + (4*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(e*Sqrt[d + e*x])}
{(a + b*ArcSech[c*x])/(d + e*x)^(5/2), x, 11, (4*b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*d*(c^2*d^2 - e^2)*Sqrt[d + e*x]) - (2*(a + b*ArcSech[c*x]))/(3*e*(d + e*x)^(3/2)) - (4*b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*d*(c^2*d^2 - e^2)*Sqrt[(c*(d + e*x))/(c*d + e)]) + (4*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*d*e*Sqrt[d + e*x])}
{(a + b*ArcSech[c*x])/(d + e*x)^(7/2), x, 18, (4*b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(15*d*(c^2*d^2 - e^2)*(d + e*x)^(3/2)) + (16*b*c^2*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(15*(c^2*d^2 - e^2)^2*Sqrt[d + e*x]) + (4*b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(5*d^2*(c^2*d^2 - e^2)*Sqrt[d + e*x]) - (2*(a + b*ArcSech[c*x]))/(5*e*(d + e*x)^(5/2)) - (16*b*c^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*(c^2*d^2 - e^2)^2*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*d^2*(c^2*d^2 - e^2)*Sqrt[(c*(d + e*x))/(c*d + e)]) + (4*b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*d*(c^2*d^2 - e^2)*Sqrt[d + e*x]) + (4*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[(c*(d + e*x))/(c*d + e)]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*d^2*e*Sqrt[d + e*x])}


(* ::Subsubsection:: *)
(*n<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x)^m (a+b ArcSech[c x])^n when m symbolic*)


{(d + e*x)^m*(a + b*ArcSech[c*x]), x, 1, ((d + e*x)^(1 + m)*(a + b*ArcSech[c*x]))/(e*(1 + m)) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Unintegrable[(d + e*x)^(1 + m)/(x*Sqrt[1 - c^2*x^2]), x])/(e*(1 + m))}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSech[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcSech[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^4*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 6, -((b*(42*c^2*d + 25*e)*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(560*c^6)) - (b*(42*c^2*d + 25*e)*x^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(840*c^4) - (b*e*x^5*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(42*c^2) + (1/5)*d*x^5*(a + b*ArcSech[c*x]) + (1/7)*e*x^7*(a + b*ArcSech[c*x]) + (b*(42*c^2*d + 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(560*c^7)}
{x^2*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 5, -((b*(20*c^2*d + 9*e)*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(120*c^4)) - (b*e*x^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(20*c^2) + (1/3)*d*x^3*(a + b*ArcSech[c*x]) + (1/5)*e*x^5*(a + b*ArcSech[c*x]) + (b*(20*c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(120*c^5)}
{x^0*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 4, -((b*e*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(6*c^2)) + d*x*(a + b*ArcSech[c*x]) + (1/3)*e*x^3*(a + b*ArcSech[c*x]) + (b*(6*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(6*c^3)}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x^2, x, 3, (b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/x - (d*(a + b*ArcSech[c*x]))/x + e*x*(a + b*ArcSech[c*x]) + (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/c}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x^4, x, 4, (b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(9*x^3) + (b*(2*c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(9*x) - (d*(a + b*ArcSech[c*x]))/(3*x^3) - (e*(a + b*ArcSech[c*x]))/x}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x^6, x, 5, (b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(25*x^5) + (b*(12*c^2*d + 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(225*x^3) + (2*b*c^2*(12*c^2*d + 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(225*x) - (d*(a + b*ArcSech[c*x]))/(5*x^5) - (e*(a + b*ArcSech[c*x]))/(3*x^3)}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x^8, x, 6, (b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(49*x^7) + (b*(30*c^2*d + 49*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(1225*x^5) + (4*b*c^2*(30*c^2*d + 49*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3675*x^3) + (8*b*c^4*(30*c^2*d + 49*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3675*x) - (d*(a + b*ArcSech[c*x]))/(7*x^7) - (e*(a + b*ArcSech[c*x]))/(5*x^5)}

{x^5*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 5, -((b*(4*c^2*d + 3*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(24*c^8)) + (b*(8*c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(3/2))/(72*c^8) - (b*(4*c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(5/2))/(120*c^8) + (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(7/2))/(56*c^8) + (1/6)*d*x^6*(a + b*ArcSech[c*x]) + (1/8)*e*x^8*(a + b*ArcSech[c*x])}
{x^3*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 5, -((b*(3*c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(12*c^6)) + (b*(3*c^2*d + 4*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(3/2))/(36*c^6) - (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(5/2))/(30*c^6) + (1/4)*d*x^4*(a + b*ArcSech[c*x]) + (1/6)*e*x^6*(a + b*ArcSech[c*x])}
{x*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 7, -((b*(2*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(4*c^4)) + (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(3/2))/(12*c^4) + ((d + e*x^2)^2*(a + b*ArcSech[c*x]))/(4*e) - (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(4*e)}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x, x, 12, -((b*e*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)/(2*c)) + (I*b*d*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]^2)/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (1/2)*e*x^2*(a + b*ArcSech[c*x]) - (b*d*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (b*d*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1/x])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - d*(a + b*ArcSech[c*x])*Log[1/x] + (I*b*d*Sqrt[1 - 1/(c^2*x^2)]*PolyLog[2, E^(2*I*ArcCsc[c*x])])/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])}
{((d + e*x^2)*(a + b*ArcSech[c*x]))/x^3, x, 14, (b*c*d*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(4*x) + (I*b*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]^2)/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (1/4)*b*c^2*d*ArcSech[c*x] - (d*(a + b*ArcSech[c*x]))/(2*x^2) - (b*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (b*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1/x])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - e*(a + b*ArcSech[c*x])*Log[1/x] + (I*b*e*Sqrt[1 - 1/(c^2*x^2)]*PolyLog[2, E^(2*I*ArcCsc[c*x])])/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])}


{x^2*(d + e*x^2)^2*(a + b*ArcSech[c*x]), x, 6, -((b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(1680*c^6)) - (b*e*(84*c^2*d + 25*e)*x^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(840*c^4) - (b*e^2*x^5*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(42*c^2) + (1/3)*d^2*x^3*(a + b*ArcSech[c*x]) + (2/5)*d*e*x^5*(a + b*ArcSech[c*x]) + (1/7)*e^2*x^7*(a + b*ArcSech[c*x]) + (b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(1680*c^7)}
{x^0*(d + e*x^2)^2*(a + b*ArcSech[c*x]), x, 5, -((b*e*(40*c^2*d + 9*e)*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(120*c^4)) - (b*e^2*x^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(20*c^2) + d^2*x*(a + b*ArcSech[c*x]) + (2/3)*d*e*x^3*(a + b*ArcSech[c*x]) + (1/5)*e^2*x^5*(a + b*ArcSech[c*x]) + (b*(120*c^4*d^2 + 40*c^2*d*e + 9*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(120*c^5)}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^2, x, 5, (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/x - (b*e^2*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(6*c^2) - (d^2*(a + b*ArcSech[c*x]))/x + 2*d*e*x*(a + b*ArcSech[c*x]) + (1/3)*e^2*x^3*(a + b*ArcSech[c*x]) + (b*e*(12*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/(6*c^3)}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^4, x, 5, (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(9*x^3) + (2*b*d*(c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(9*x) - (d^2*(a + b*ArcSech[c*x]))/(3*x^3) - (2*d*e*(a + b*ArcSech[c*x]))/x + e^2*x*(a + b*ArcSech[c*x]) + (b*e^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcSin[c*x])/c}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^6, x, 5, (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(25*x^5) + (2*b*d*(6*c^2*d + 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(225*x^3) + (b*(24*c^4*d^2 + 100*c^2*d*e + 225*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(225*x) - (d^2*(a + b*ArcSech[c*x]))/(5*x^5) - (2*d*e*(a + b*ArcSech[c*x]))/(3*x^3) - (e^2*(a + b*ArcSech[c*x]))/x}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^8, x, 6, (b*d^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(49*x^7) + (2*b*d*(15*c^2*d + 49*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(1225*x^5) + (b*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(11025*x^3) + (2*b*c^2*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(11025*x) - (d^2*(a + b*ArcSech[c*x]))/(7*x^7) - (2*d*e*(a + b*ArcSech[c*x]))/(5*x^5) - (e^2*(a + b*ArcSech[c*x]))/(3*x^3)}

{x^3*(d + e*x^2)^2*(a + b*ArcSech[c*x]), x, 5, -((b*(6*c^4*d^2 + 8*c^2*d*e + 3*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(24*c^8)) + (b*(6*c^4*d^2 + 16*c^2*d*e + 9*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(3/2))/(72*c^8) - (b*e*(8*c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(5/2))/(120*c^8) + (b*e^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(7/2))/(56*c^8) + (1/4)*d^2*x^4*(a + b*ArcSech[c*x]) + (1/3)*d*e*x^6*(a + b*ArcSech[c*x]) + (1/8)*e^2*x^8*(a + b*ArcSech[c*x])}
{x^1*(d + e*x^2)^2*(a + b*ArcSech[c*x]), x, 7, -((b*(3*c^4*d^2 + 3*c^2*d*e + e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(6*c^6)) + (b*e*(3*c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(3/2))/(18*c^6) - (b*e^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*(1 - c^2*x^2)^(5/2))/(30*c^6) + ((d + e*x^2)^3*(a + b*ArcSech[c*x]))/(6*e) - (b*d^3*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(6*e)}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^1, x, 13, -((b*e*(6*c^2*d + e)*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)/(6*c^3)) - (b*e^2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x^3)/(12*c) + (I*b*d^2*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]^2)/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + d*e*x^2*(a + b*ArcSech[c*x]) + (1/4)*e^2*x^4*(a + b*ArcSech[c*x]) - (b*d^2*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (b*d^2*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1/x])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - d^2*(a + b*ArcSech[c*x])*Log[1/x] + (I*b*d^2*Sqrt[1 - 1/(c^2*x^2)]*PolyLog[2, E^(2*I*ArcCsc[c*x])])/(2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])}
{((d + e*x^2)^2*(a + b*ArcSech[c*x]))/x^3, x, 15, (b*c*d^2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(4*x) - (b*e^2*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)/(2*c) + (I*b*d*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]^2)/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (1/4)*b*c^2*d^2*ArcSech[c*x] - (d^2*(a + b*ArcSech[c*x]))/(2*x^2) + (1/2)*e^2*x^2*(a + b*ArcSech[c*x]) - (2*b*d*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (2*b*d*e*Sqrt[1 - 1/(c^2*x^2)]*ArcCsc[c*x]*Log[1/x])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - 2*d*e*(a + b*ArcSech[c*x])*Log[1/x] + (I*b*d*e*Sqrt[1 - 1/(c^2*x^2)]*PolyLog[2, E^(2*I*ArcCsc[c*x])])/(Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{(x^2*(a + b*ArcSech[c*x]))/(d + e*x^2), x, 24, (x*(a + b*ArcSech[c*x]))/e - (b*ArcTan[Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]])/(c*e) + (Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) - (b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^(3/2)) + (b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) - (b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^(3/2)) + (b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2))}
{(x*(a + b*ArcSech[c*x]))/(d + e*x^2), x, 26, ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) - ((a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/e + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) - (b*PolyLog[2, -E^(2*ArcSech[c*x])])/(2*e)}
{(a + b*ArcSech[c*x])/(d + e*x^2), x, 19, ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcSech[c*x])/(x*(d + e*x^2)), x, 19, (a + b*ArcSech[c*x])^2/(2*b*d) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d)}
{(a + b*ArcSech[c*x])/(x^2*(d + e*x^2)), x, 24, (b*c*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/d - a/(d*x) - (b*ArcSech[c*x])/(d*x) + (Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) + (b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) + (b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2))}


{(x^5*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 32, -((b*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)/(2*c*e^2)) + (d*(a + b*ArcSech[c*x]))/(2*e^2*(e + d/x^2)) + (x^2*(a + b*ArcSech[c*x]))/(2*e^2) - (b*d*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - (d*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 + (2*d*(a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/e^3 - (b*d*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/e^3 - (b*d*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (b*d*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/e^3 - (b*d*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 + (b*d*PolyLog[2, -E^(2*ArcSech[c*x])])/e^3}
{(x^3*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 30, -((a + b*ArcSech[c*x])/(2*e*(e + d/x^2))) + (b*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(2*e^(3/2)*Sqrt[c^2*d + e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - ((a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/e^2 + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^2) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^2) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - (b*PolyLog[2, -E^(2*ArcSech[c*x])])/(2*e^2)}
{(x*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 8, -((a + b*ArcSech[c*x])/(2*e*(d + e*x^2))) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(2*d*e) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[(Sqrt[e]*Sqrt[1 - c^2*x^2])/Sqrt[c^2*d + e]])/(2*d*Sqrt[e]*Sqrt[c^2*d + e])}
{(a + b*ArcSech[c*x])/(x*(d + e*x^2)^2), x, 25, -((e*(a + b*ArcSech[c*x]))/(2*d^2*(e + d/x^2))) + (a + b*ArcSech[c*x])^2/(2*b*d^2) + (b*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(2*d^2*Sqrt[c^2*d + e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^2) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^2) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2)}

{(x^4*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 50, -((d*(a + b*ArcSech[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] - d/x))) + (d*(a + b*ArcSech[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (x*(a + b*ArcSech[c*x]))/e^2 + (b*d*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e^2) + (b*d*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e^2) - (b*ArcTan[Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]])/(c*e^2) + (3*Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*e^(5/2)) + (3*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*e^(5/2)) + (3*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2))}
{(x^2*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 27, (a + b*ArcSech[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSech[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e) - (b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2))}
{(a + b*ArcSech[c*x])/(d + e*x^2)^2, x, 47, -((a + b*ArcSech[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] - d/x))) + (a + b*ArcSech[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*d*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) + (b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*d*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e])}
{(a + b*ArcSech[c*x])/(x^2*(d + e*x^2)^2), x, 50, (b*c*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/d^2 - a/(d^2*x) - (b*ArcSech[c*x])/(d^2*x) + (e*(a + b*ArcSech[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (e*(a + b*ArcSech[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*e*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*d^2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) - (b*e*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(2*d^2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) - (3*Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) - (3*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) - (3*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2))}


{(x^5*(a + b*ArcSech[c*x]))/(d + e*x^2)^3, x, 35, (b*d*(c^2 - 1/x^2))/(8*c*e^2*(c^2*d + e)*(e + d/x^2)*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (a + b*ArcSech[c*x])/(4*e*(e + d/x^2)^2) - (a + b*ArcSech[c*x])/(2*e^2*(e + d/x^2)) + (b*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + (b*(c^2*d + 2*e)*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(8*e^(5/2)*(c^2*d + e)^(3/2)*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) - ((a + b*ArcSech[c*x])*Log[1 + E^(2*ArcSech[c*x])])/e^3 + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^3) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^3) + (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) - (b*PolyLog[2, -E^(2*ArcSech[c*x])])/(2*e^3)}
{(x^3*(a + b*ArcSech[c*x]))/(d + e*x^2)^3, x, 6, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(8*e*(c^2*d + e)*(d + e*x^2)) + (x^4*(a + b*ArcSech[c*x]))/(4*d*(d + e*x^2)^2) - (b*(c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[(Sqrt[e]*Sqrt[1 - c^2*x^2])/Sqrt[c^2*d + e]])/(8*d*e^(3/2)*(c^2*d + e)^(3/2))}
{(x*(a + b*ArcSech[c*x]))/(d + e*x^2)^3, x, 9, -((b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(8*d*(c^2*d + e)*(d + e*x^2))) - (a + b*ArcSech[c*x])/(4*e*(d + e*x^2)^2) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[1 - c^2*x^2]])/(4*d^2*e) - (b*(3*c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[(Sqrt[e]*Sqrt[1 - c^2*x^2])/Sqrt[c^2*d + e]])/(8*d^2*Sqrt[e]*(c^2*d + e)^(3/2))}
{(a + b*ArcSech[c*x])/(x*(d + e*x^2)^3), x, 30, -((b*e*(c^2 - 1/x^2))/(8*c*d^2*(c^2*d + e)*(e + d/x^2)*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)) + (e^2*(a + b*ArcSech[c*x]))/(4*d^3*(e + d/x^2)^2) - (e*(a + b*ArcSech[c*x]))/(d^3*(e + d/x^2)) + (a + b*ArcSech[c*x])^2/(2*b*d^3) + (b*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(d^3*Sqrt[c^2*d + e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - (b*Sqrt[e]*(c^2*d + 2*e)*Sqrt[-1 + 1/(c^2*x^2)]*ArcTanh[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[-1 + 1/(c^2*x^2)]*x)])/(8*d^3*(c^2*d + e)^(3/2)*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^3) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^3) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3)}

{(x^4*(a + b*ArcSech[c*x]))/(d + e*x^2)^3, x, 35, (b*c*Sqrt[-d]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[-d]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[-d]*(a + b*ArcSech[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (3*(a + b*ArcSech[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[-d]*(a + b*ArcSech[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (3*(a + b*ArcSech[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) - (3*b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e^2) - (b*d*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)*e) - (3*b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e^2) - (b*d*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)*e) + (3*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) + (3*b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) + (3*b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2))}
{(x^2*(a + b*ArcSech[c*x]))/(d + e*x^2)^3, x, 63, (b*c*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (a + b*ArcSech[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (a + b*ArcSech[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSech[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (a + b*ArcSech[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)) - (b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e) + (b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)) - (b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*e) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2))}
{(a + b*ArcSech[c*x])/(d + e*x^2)^3, x, 81, (b*c*Sqrt[e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[e]*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[e]*(a + b*ArcSech[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) - (5*(a + b*ArcSech[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[e]*(a + b*ArcSech[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) + (5*(a + b*ArcSech[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (5*b*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d^2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) - (b*e*ArcTan[(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)) + (5*b*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d^2*Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[c*d + Sqrt[-d]*Sqrt[e]]) - (b*e*ArcTan[(Sqrt[c*d + Sqrt[-d]*Sqrt[e]]*Sqrt[1 + 1/(c*x)])/(Sqrt[c*d - Sqrt[-d]*Sqrt[e]]*Sqrt[-1 + 1/(c*x)])])/(8*d*(c*d - Sqrt[-d]*Sqrt[e])^(3/2)*(c*d + Sqrt[-d]*Sqrt[e])^(3/2)) + (3*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*(a + b*ArcSech[c*x])*Log[1 - (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSech[c*x])*Log[1 + (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) + (3*b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*b*PolyLog[2, -((c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) + (3*b*PolyLog[2, (c*Sqrt[-d]*E^ArcSech[c*x])/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e])}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^(p/2) (a+b ArcSech[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^5*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, If[$VersionNumber>=8, 20, 13], (b*(23*c^4*d^2 + 12*c^2*d*e - 75*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(1680*c^6*e^2) + (b*(29*c^2*d - 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(840*c^4*e^2) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(5/2))/(42*c^2*e^2) + (d^2*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^3) - (2*d*(d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e^3) + ((d + e*x^2)^(7/2)*(a + b*ArcSech[c*x]))/(7*e^3) - (b*(105*c^6*d^3 - 35*c^4*d^2*e + 63*c^2*d*e^2 + 75*e^3)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(1680*c^7*e^(5/2)) - (8*b*d^(7/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(105*e^3)}
{x^3*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, If[$VersionNumber>=8, 11, 12], If[$VersionNumber>=8, -((b*(c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(120*c^4*e)) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(20*c^2*e) - (d*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e^2) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^5*e^(3/2)) + (2*b*d^(5/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(15*e^2), -((b*(c^2*d + 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(120*c^4*e)) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(20*c^2*e) - (d*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e^2) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^5*e^(3/2)) + (2*b*d^(5/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(15*e^2)]}
{x*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, 10, -((b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(6*c^2)) + ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e) - (b*(3*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^3*Sqrt[e]) - (b*d^(3/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*e)}
{Sqrt[d + e*x^2]*(a + b*ArcSech[c*x])/x^1, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/x, x]}
{Sqrt[d + e*x^2]*(a + b*ArcSech[c*x])/x^3, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/x^3, x]}

{x^2*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, 0, Unintegrable[x^2*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x]}
{x^0*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x]}
{Sqrt[d + e*x^2]*(a + b*ArcSech[c*x])/x^2, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/x^2, x]}
{Sqrt[d + e*x^2]*(a + b*ArcSech[c*x])/x^4, x, 9, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(9*x^3) + (2*b*(c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(9*d*x) - ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*d*x^3) + (2*b*c*(c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(9*d*Sqrt[1 + (e*x^2)/d]) - (b*(c^2*d + e)*(2*c^2*d + 3*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(9*c*d*Sqrt[d + e*x^2])}
{Sqrt[d + e*x^2]*(a + b*ArcSech[c*x])/x^6, x, If[$VersionNumber>=8, 10, 26], If[$VersionNumber>=8, (b*(12*c^2*d - e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(225*d*x^3) + (b*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(225*d^2*x) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(25*d*x^5) - ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(15*d^2*x^3) + (b*c*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(225*d^2*Sqrt[1 + (e*x^2)/d]) - (b*(c^2*d + e)*(24*c^4*d^2 + 7*c^2*d*e - 30*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(225*c*d^2*Sqrt[d + e*x^2]), (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(25*x^5) + (b*e*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(45*d*x^3) + (b*(4*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(75*d*x^3) - (2*b*e^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(15*d^2*x) + (b*e*(2*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(45*d^2*x) + (b*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(75*d^2*x) - ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(15*d^2*x^3) - (2*b*c*e^2*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(15*d^2*Sqrt[1 + (e*x^2)/d]) + (b*c*e*(2*c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(45*d^2*Sqrt[1 + (e*x^2)/d]) + (b*c*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(75*d^2*Sqrt[1 + (e*x^2)/d]) - (b*c*(8*c^2*d - e)*(c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(75*d*Sqrt[d + e*x^2]) - (2*b*c*e*(c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(45*d*Sqrt[d + e*x^2]) + (2*b*e^2*(c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(15*c*d^2*Sqrt[d + e*x^2])]}


{x^3*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x, 12, (b*(3*c^4*d^2 - 38*c^2*d*e - 25*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(560*c^6*e) - (b*(13*c^2*d + 25*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(840*c^4*e) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(5/2))/(42*c^2*e) - (d*(d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e^2) + ((d + e*x^2)^(7/2)*(a + b*ArcSech[c*x]))/(7*e^2) + (b*(35*c^6*d^3 - 35*c^4*d^2*e - 63*c^2*d*e^2 - 25*e^3)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(560*c^7*e^(3/2)) + (2*b*d^(7/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(35*e^2)}
{x^1*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x, 11, -((b*(7*c^2*d + 3*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(40*c^4)) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(20*c^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e) - (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(40*c^5*Sqrt[e]) - (b*d^(5/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(5*e)}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^1, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/x, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^3, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/x^3, x]}

{x^2*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x, 0, Unintegrable[x^2*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x]}
{x^0*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x, 0, Unintegrable[(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^2, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/x^2, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^4, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/x^4, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^6, x, 10, (4*b*(c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(75*x^3) + (b*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(75*d*x) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(25*x^5) - ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*d*x^5) + (b*c*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(75*d*Sqrt[1 + (e*x^2)/d]) - (b*(c^2*d + e)*(8*c^4*d^2 + 19*c^2*d*e + 15*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(75*c*d*Sqrt[d + e*x^2])}
{(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x])/x^8, x, 11, (b*(120*c^4*d^2 + 159*c^2*d*e - 37*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(3675*d*x^3) + (b*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(3675*d^2*x) + (b*(30*c^2*d + 11*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(1225*d*x^5) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(5/2))/(49*d*x^7) - ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(7*d*x^7) + (2*e*(d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(35*d^2*x^5) + (b*c*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3675*d^2*Sqrt[1 + (e*x^2)/d]) - (2*b*(c^2*d + e)*(120*c^6*d^3 + 204*c^4*d^2*e + 17*c^2*d*e^2 - 105*e^3)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3675*c*d^2*Sqrt[d + e*x^2])}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^5*(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x, 11, (b*(19*c^2*d - 9*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(120*c^4*e^2) - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*(d + e*x^2)^(3/2))/(20*c^2*e^2) + (d^2*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e^3 - (2*d*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^3) + ((d + e*x^2)^(5/2)*(a + b*ArcSech[c*x]))/(5*e^3) - (b*(45*c^4*d^2 - 10*c^2*d*e + 9*e^2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^5*e^(5/2)) - (8*b*d^(5/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(15*e^3)}
{x^3*(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x, 10, -((b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(6*c^2*e)) - (d*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e^2 + ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^2) + (b*(3*c^2*d - e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^3*e^(3/2)) + (2*b*d^(3/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*e^2)}
{x^1*(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x, 10, (Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(c*Sqrt[e]) - (b*Sqrt[d]*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/e}
{(a + b*ArcSech[c*x])/(x^1*Sqrt[d + e*x^2]), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x*Sqrt[d + e*x^2]), x]}
{(a + b*ArcSech[c*x])/(x^3*Sqrt[d + e*x^2]), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x^3*Sqrt[d + e*x^2]), x]}

{x^2*(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x, 0, Unintegrable[(x^2*(a + b*ArcSech[c*x]))/Sqrt[d + e*x^2], x]}
{x^0*(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x, 0, Unintegrable[(a + b*ArcSech[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcSech[c*x])/(x^2*Sqrt[d + e*x^2]), x, 9, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(d*x) - (Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/(d*x) + (b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[1 + (e*x^2)/d]) - (b*(c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(c*d*Sqrt[d + e*x^2])}
{(a + b*ArcSech[c*x])/(x^4*Sqrt[d + e*x^2]), x, 9, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(9*d*x^3) + (b*(2*c^2*d - 5*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(9*d^2*x) - (Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/(3*d*x^3) + (2*e*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/(3*d^2*x) + (b*c*(2*c^2*d - 5*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(9*d^2*Sqrt[1 + (e*x^2)/d]) - (2*b*(c^2*d - 3*e)*(c^2*d + e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(9*c*d^2*Sqrt[d + e*x^2])}


{x^5*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 10, -((b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(6*c^2*e^2)) - (d^2*(a + b*ArcSech[c*x]))/(e^3*Sqrt[d + e*x^2]) - (2*d*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e^3 + ((d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]))/(3*e^3) + (b*(9*c^2*d - e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^3*e^(5/2)) + (8*b*d^(3/2)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*e^3)}
{x^3*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 9, (d*(a + b*ArcSech[c*x]))/(e^2*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e^2 - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(c*e^(3/2)) - (2*b*Sqrt[d]*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/e^2}
{x^1*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 5, -((a + b*ArcSech[c*x])/(e*Sqrt[d + e*x^2])) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(Sqrt[d]*e)}
{(a + b*ArcSech[c*x])/(x^1*(d + e*x^2)^(3/2)), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x*(d + e*x^2)^(3/2)), x]}
{(a + b*ArcSech[c*x])/(x^3*(d + e*x^2)^(3/2)), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x^3*(d + e*x^2)^(3/2)), x]}

{x^4*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 0, Unintegrable[(x^4*(a + b*ArcSech[c*x]))/(d + e*x^2)^(3/2), x]}
{x^2*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 0, Unintegrable[(x^2*(a + b*ArcSech[c*x]))/(d + e*x^2)^(3/2), x]}
{x^0*(a + b*ArcSech[c*x])/(d + e*x^2)^(3/2), x, 4, (x*(a + b*ArcSech[c*x]))/(d*Sqrt[d + e*x^2]) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(c*d*Sqrt[d + e*x^2])}
{(a + b*ArcSech[c*x])/(x^2*(d + e*x^2)^(3/2)), x, 8, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2])/(d^2*x) - (a + b*ArcSech[c*x])/(d*x*Sqrt[d + e*x^2]) - (2*e*x*(a + b*ArcSech[c*x]))/(d^2*Sqrt[d + e*x^2]) + (b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[1 + (e*x^2)/d]) - (b*(c^2*d + 2*e)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(c*d^2*Sqrt[d + e*x^2])}


{x^5*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 10, -((b*d*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*e^2*(c^2*d + e)*Sqrt[d + e*x^2])) - (d^2*(a + b*ArcSech[c*x]))/(3*e^3*(d + e*x^2)^(3/2)) + (2*d*(a + b*ArcSech[c*x]))/(e^3*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]))/e^3 - (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTan[(Sqrt[e]*Sqrt[1 - c^2*x^2])/(c*Sqrt[d + e*x^2])])/(c*e^(5/2)) - (8*b*Sqrt[d]*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*e^3)}
{x^3*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 7, (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*e*(c^2*d + e)*Sqrt[d + e*x^2]) + (d*(a + b*ArcSech[c*x]))/(3*e^2*(d + e*x^2)^(3/2)) - (a + b*ArcSech[c*x])/(e^2*Sqrt[d + e*x^2]) + (2*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*Sqrt[d]*e^2)}
{x^1*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 6, -((b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[d + e*x^2])) - (a + b*ArcSech[c*x])/(3*e*(d + e*x^2)^(3/2)) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*ArcTanh[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[1 - c^2*x^2])])/(3*d^(3/2)*e)}
{(a + b*ArcSech[c*x])/(x^1*(d + e*x^2)^(5/2)), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x*(d + e*x^2)^(5/2)), x]}
{(a + b*ArcSech[c*x])/(x^3*(d + e*x^2)^(5/2)), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x^3*(d + e*x^2)^(5/2)), x]}

{x^6*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 0, Unintegrable[(x^6*(a + b*ArcSech[c*x]))/(d + e*x^2)^(5/2), x]}
{x^4*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 0, Unintegrable[(x^4*(a + b*ArcSech[c*x]))/(d + e*x^2)^(5/2), x]}
{x^2*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 8, -((b*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[d + e*x^2])) + (x^3*(a + b*ArcSech[c*x]))/(3*d*(d + e*x^2)^(3/2)) - (b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d*e*(c^2*d + e)*Sqrt[1 + (e*x^2)/d]) + (b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*c*d*e*Sqrt[d + e*x^2])}
{x^0*(a + b*ArcSech[c*x])/(d + e*x^2)^(5/2), x, 8, (b*e*x*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(3*d^2*(c^2*d + e)*Sqrt[d + e*x^2]) + (x*(a + b*ArcSech[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcSech[c*x]))/(3*d^2*Sqrt[d + e*x^2]) + (b*c*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*(c^2*d + e)*Sqrt[1 + (e*x^2)/d]) + (2*b*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*c*d^2*Sqrt[d + e*x^2])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSech[c x]) when m symbolic*)


{(f*x)^m*(d + e*x^2)^3*(a + b*ArcSech[c*x]), x, 5, If[$VersionNumber>=8, -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^6*f*(2 + m)*(3 + m)*(4 + m)*(5 + m)*(6 + m)*(7 + m))) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*(f*x)^(3 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^4*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)) - (b*e^3*(f*x)^(5 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^2*f^5*(6 + m)*(7 + m)) + (d^3*(f*x)^(1 + m)*(a + b*ArcSech[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSech[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSech[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSech[c*x]))/(f^7*(7 + m)) + (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/((3 + m)*(5 + m)*(7 + m)))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^6*f*(1 + m)*(2 + m)*(4 + m)*(6 + m)), -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^6*f*(6 + m)*(8 + 6*m + m^2)*(105 + 71*m + 15*m^2 + m^3))) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*(f*x)^(3 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^4*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)) - (b*e^3*(f*x)^(5 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^2*f^5*(6 + m)*(7 + m)) + (d^3*(f*x)^(1 + m)*(a + b*ArcSech[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSech[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSech[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSech[c*x]))/(f^7*(7 + m)) + (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/(105 + 71*m + 15*m^2 + m^3))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^6*f*(1 + m)*(2 + m)*(4 + m)*(6 + m))]}
{(f*x)^m*(d + e*x^2)^2*(a + b*ArcSech[c*x]), x, 5, If[$VersionNumber>=8, -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^4*f*(2 + m)*(3 + m)*(4 + m)*(5 + m))) - (b*e^2*(f*x)^(3 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^2*f^3*(4 + m)*(5 + m)) + (d^2*(f*x)^(1 + m)*(a + b*ArcSech[c*x]))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*ArcSech[c*x]))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*ArcSech[c*x]))/(f^5*(5 + m)) + (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^4*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)), -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^4*f*(4 + m)*(5 + m)*(6 + 5*m + m^2))) - (b*e^2*(f*x)^(3 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^2*f^3*(4 + m)*(5 + m)) + (d^2*(f*x)^(1 + m)*(a + b*ArcSech[c*x]))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*ArcSech[c*x]))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*ArcSech[c*x]))/(f^5*(5 + m)) + (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^4*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m))]}
{(f*x)^m*(d + e*x^2)*(a + b*ArcSech[c*x]), x, 4, -((b*e*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Sqrt[1 - c^2*x^2])/(c^2*f*(2 + m)*(3 + m))) + (d*(f*x)^(1 + m)*(a + b*ArcSech[c*x]))/(f*(1 + m)) + (e*(f*x)^(3 + m)*(a + b*ArcSech[c*x]))/(f^3*(3 + m)) + (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*(f*x)^(1 + m)*Sqrt[1/(1 + c*x)]*Sqrt[1 + c*x]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^2*f*(1 + m)^2*(2 + m)*(3 + m))}
{((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2), x, 0, Unintegrable[((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2), x]}
{((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x, 0, Unintegrable[((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2)^2, x]}


{(f*x)^m*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x, 0, Unintegrable[(f*x)^m*(d + e*x^2)^(3/2)*(a + b*ArcSech[c*x]), x]}
{(f*x)^m*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x, 0, Unintegrable[(f*x)^m*Sqrt[d + e*x^2]*(a + b*ArcSech[c*x]), x]}
{((f*x)^m*(a + b*ArcSech[c*x]))/Sqrt[d + e*x^2], x, 0, Unintegrable[((f*x)^m*(a + b*ArcSech[c*x]))/Sqrt[d + e*x^2], x]}
{((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2)^(3/2), x, 0, Unintegrable[((f*x)^m*(a + b*ArcSech[c*x]))/(d + e*x^2)^(3/2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^4)^p (a+b ArcSech[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^4)^(p/2) (a+b ArcSech[c x])*)


(* ::Subsubsection:: *)
(*p>0*)


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^11*(a + b*ArcSech[c*x])/Sqrt[1 - c^4*x^4], x, 15, -((4*b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(15*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)) + (7*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(3/2))/(90*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (13*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(5/2))/(150*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) + (3*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(7/2))/(70*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(9/2))/(90*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSech[c*x]))/(2*c^12) + ((1 - c^4*x^4)^(3/2)*(a + b*ArcSech[c*x]))/(3*c^12) - ((1 - c^4*x^4)^(5/2)*(a + b*ArcSech[c*x]))/(10*c^12) + (4*b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(15*c^13*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)}
{x^7*(a + b*ArcSech[c*x])/Sqrt[1 - c^4*x^4], x, 12, -((b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(3*c^9*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)) + (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(3/2))/(18*c^9*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(5/2))/(30*c^9*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSech[c*x]))/(2*c^8) + ((1 - c^4*x^4)^(3/2)*(a + b*ArcSech[c*x]))/(6*c^8) + (b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(3*c^9*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)}
{x^3*(a + b*ArcSech[c*x])/Sqrt[1 - c^4*x^4], x, 7, -((b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(2*c^5*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSech[c*x]))/(2*c^4) + (b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(2*c^5*Sqrt[-1 + 1/(c*x)]*Sqrt[1 + 1/(c*x)]*x)}
{(a + b*ArcSech[c*x])/(x^1*Sqrt[1 - c^4*x^4]), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x*Sqrt[1 - c^4*x^4]), x]}
{(a + b*ArcSech[c*x])/(x^5*Sqrt[1 - c^4*x^4]), x, 0, Unintegrable[(a + b*ArcSech[c*x])/(x^5*Sqrt[1 - c^4*x^4]), x]}


(* ::Section:: *)
(*Integrands of the form u (a+b ArcSech[c x])^n*)
