(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form u (a+b ArcSec[c x])^n*)


(* ::Section::Closed:: *)
(*Integrands of the form (d x)^m (a+b ArcSec[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (a+b ArcSec[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{x^6*(a + b*ArcSec[c*x]), x, 7, -((5*b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(112*c^5)) - (5*b*Sqrt[1 - 1/(c^2*x^2)]*x^4)/(168*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^6)/(42*c) + (1/7)*x^7*(a + b*ArcSec[c*x]) - (5*b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(112*c^7)}
{x^5*(a + b*ArcSec[c*x]), x, 4, -((4*b*Sqrt[1 - 1/(c^2*x^2)]*x)/(45*c^5)) - (2*b*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(45*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^5)/(30*c) + (1/6)*x^6*(a + b*ArcSec[c*x])}
{x^4*(a + b*ArcSec[c*x]), x, 6, -((3*b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(40*c^3)) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^4)/(20*c) + (1/5)*x^5*(a + b*ArcSec[c*x]) - (3*b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(40*c^5)}
{x^3*(a + b*ArcSec[c*x]), x, 3, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(6*c^3)) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(12*c) + (1/4)*x^4*(a + b*ArcSec[c*x])}
{x^2*(a + b*ArcSec[c*x]), x, 5, -((b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(6*c)) + (1/3)*x^3*(a + b*ArcSec[c*x]) - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(6*c^3)}
{x^1*(a + b*ArcSec[c*x]), x, 2, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c)) + (1/2)*x^2*(a + b*ArcSec[c*x])}
{x^0*(a + b*ArcSec[c*x]), x, 5, a*x + b*x*ArcSec[c*x] - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c}
{(a + b*ArcSec[c*x])/x^1, x, 6, (I*(a + b*ArcSec[c*x])^2)/(2*b) - (a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])] + (1/2)*I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])/x^2, x, 2, b*c*Sqrt[1 - 1/(c^2*x^2)] - (a + b*ArcSec[c*x])/x}
{(a + b*ArcSec[c*x])/x^3, x, 4, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(4*x) - (a + b*ArcSec[c*x])/(2*x^2) - (1/4)*b*c^2*ArcCsc[c*x]}
{(a + b*ArcSec[c*x])/x^4, x, 4, (1/3)*b*c^3*Sqrt[1 - 1/(c^2*x^2)] - (1/9)*b*c^3*(1 - 1/(c^2*x^2))^(3/2) - (a + b*ArcSec[c*x])/(3*x^3)}
{(a + b*ArcSec[c*x])/x^5, x, 5, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*x^3) + (3*b*c^3*Sqrt[1 - 1/(c^2*x^2)])/(32*x) - (a + b*ArcSec[c*x])/(4*x^4) - (3/32)*b*c^4*ArcCsc[c*x]}
{(a + b*ArcSec[c*x])/x^6, x, 4, (1/5)*b*c^5*Sqrt[1 - 1/(c^2*x^2)] - (2/15)*b*c^5*(1 - 1/(c^2*x^2))^(3/2) + (1/25)*b*c^5*(1 - 1/(c^2*x^2))^(5/2) - (a + b*ArcSec[c*x])/(5*x^5)}
{(a + b*ArcSec[c*x])/x^7, x, 6, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(36*x^5) + (5*b*c^3*Sqrt[1 - 1/(c^2*x^2)])/(144*x^3) + (5*b*c^5*Sqrt[1 - 1/(c^2*x^2)])/(96*x) - (a + b*ArcSec[c*x])/(6*x^6) - (5/96)*b*c^6*ArcCsc[c*x]}


{x^3*(a + b*ArcSec[c*x])^2, x, 5, (b^2*x^2)/(12*c^2) - (b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x]))/(3*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3*(a + b*ArcSec[c*x]))/(6*c) + (1/4)*x^4*(a + b*ArcSec[c*x])^2 + (b^2*Log[x])/(3*c^4)}
{x^2*(a + b*ArcSec[c*x])^2, x, 8, (b^2*x)/(3*c^2) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^2*(a + b*ArcSec[c*x]))/(3*c) + (1/3)*x^3*(a + b*ArcSec[c*x])^2 + (2*I*b*(a + b*ArcSec[c*x])*ArcTan[E^(I*ArcSec[c*x])])/(3*c^3) - (I*b^2*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/(3*c^3) + (I*b^2*PolyLog[2, I*E^(I*ArcSec[c*x])])/(3*c^3)}
{x^1*(a + b*ArcSec[c*x])^2, x, 4, -((b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x]))/c) + (1/2)*x^2*(a + b*ArcSec[c*x])^2 + (b^2*Log[x])/c^2}
{x^0*(a + b*ArcSec[c*x])^2, x, 7, x*(a + b*ArcSec[c*x])^2 + (4*I*b*(a + b*ArcSec[c*x])*ArcTan[E^(I*ArcSec[c*x])])/c - (2*I*b^2*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c + (2*I*b^2*PolyLog[2, I*E^(I*ArcSec[c*x])])/c}
{(a + b*ArcSec[c*x])^2/x^1, x, 6, (I*(a + b*ArcSec[c*x])^3)/(3*b) - (a + b*ArcSec[c*x])^2*Log[1 + E^(2*I*ArcSec[c*x])] + I*b*(a + b*ArcSec[c*x])*PolyLog[2, -E^(2*I*ArcSec[c*x])] - (1/2)*b^2*PolyLog[3, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])^2/x^2, x, 4, (2*b^2)/x + 2*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]) - (a + b*ArcSec[c*x])^2/x}
{(a + b*ArcSec[c*x])^2/x^3, x, 4, b^2/(4*x^2) - (1/2)*a*b*c^2*ArcSec[c*x] - (1/4)*b^2*c^2*ArcSec[c*x]^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(2*x) + (1/2)*(c^2 - 1/x^2)*(a + b*ArcSec[c*x])^2}
{(a + b*ArcSec[c*x])^2/x^4, x, 5, (2*b^2)/(27*x^3) + (4*b^2*c^2)/(9*x) + (4/9)*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]) + (2*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(9*x^2) - (a + b*ArcSec[c*x])^2/(3*x^3)}
{(a + b*ArcSec[c*x])^2/x^5, x, 5, b^2/(32*x^4) + (3*b^2*c^2)/(32*x^2) + (3/16)*a*b*c^4*ArcSec[c*x] + (3/32)*b^2*c^4*ArcSec[c*x]^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(8*x^3) + (3*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(16*x) - (a + b*ArcSec[c*x])^2/(4*x^4)}


{x^3*(a + b*ArcSec[c*x])^3, x, 10, -((b^3*Sqrt[1 - 1/(c^2*x^2)]*x)/(4*c^3)) + (b^2*x^2*(a + b*ArcSec[c*x]))/(4*c^2) + (I*b*(a + b*ArcSec[c*x])^2)/(2*c^4) - (b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x])^2)/(2*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3*(a + b*ArcSec[c*x])^2)/(4*c) + (1/4)*x^4*(a + b*ArcSec[c*x])^3 - (b^2*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/c^4 + (I*b^3*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*c^4)}
{x^2*(a + b*ArcSec[c*x])^3, x, 11, (b^2*x*(a + b*ArcSec[c*x]))/c^2 - (b*Sqrt[1 - 1/(c^2*x^2)]*x^2*(a + b*ArcSec[c*x])^2)/(2*c) + (1/3)*x^3*(a + b*ArcSec[c*x])^3 + (I*b*(a + b*ArcSec[c*x])^2*ArcTan[E^(I*ArcSec[c*x])])/c^3 - (b^3*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c^3 - (I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c^3 + (I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, I*E^(I*ArcSec[c*x])])/c^3 + (b^3*PolyLog[3, (-I)*E^(I*ArcSec[c*x])])/c^3 - (b^3*PolyLog[3, I*E^(I*ArcSec[c*x])])/c^3}
{x^1*(a + b*ArcSec[c*x])^3, x, 7, (3*I*b*(a + b*ArcSec[c*x])^2)/(2*c^2) - (3*b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x])^2)/(2*c) + (1/2)*x^2*(a + b*ArcSec[c*x])^3 - (3*b^2*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/c^2 + (3*I*b^3*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*c^2)}
{x^0*(a + b*ArcSec[c*x])^3, x, 9, x*(a + b*ArcSec[c*x])^3 + (6*I*b*(a + b*ArcSec[c*x])^2*ArcTan[E^(I*ArcSec[c*x])])/c - (6*I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c + (6*I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, I*E^(I*ArcSec[c*x])])/c + (6*b^3*PolyLog[3, (-I)*E^(I*ArcSec[c*x])])/c - (6*b^3*PolyLog[3, I*E^(I*ArcSec[c*x])])/c}
{(a + b*ArcSec[c*x])^3/x^1, x, 7, (I*(a + b*ArcSec[c*x])^4)/(4*b) - (a + b*ArcSec[c*x])^3*Log[1 + E^(2*I*ArcSec[c*x])] + (3/2)*I*b*(a + b*ArcSec[c*x])^2*PolyLog[2, -E^(2*I*ArcSec[c*x])] - (3/2)*b^2*(a + b*ArcSec[c*x])*PolyLog[3, -E^(2*I*ArcSec[c*x])] - (3/4)*I*b^3*PolyLog[4, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])^3/x^2, x, 5, -6*b^3*c*Sqrt[1 - 1/(c^2*x^2)] + (6*b^2*(a + b*ArcSec[c*x]))/x + 3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2 - (a + b*ArcSec[c*x])^3/x}
{(a + b*ArcSec[c*x])^3/x^3, x, 6, -((3*b^3*c*Sqrt[1 - 1/(c^2*x^2)])/(8*x)) + (3/8)*b^3*c^2*ArcSec[c*x] - (3/4)*b^2*(c^2 - 1/x^2)*(a + b*ArcSec[c*x]) + (3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(4*x) - (1/4)*c^2*(a + b*ArcSec[c*x])^3 + (1/2)*(c^2 - 1/x^2)*(a + b*ArcSec[c*x])^3}
{(a + b*ArcSec[c*x])^3/x^4, x, 8, (-(14/9))*b^3*c^3*Sqrt[1 - 1/(c^2*x^2)] + (2/27)*b^3*c^3*(1 - 1/(c^2*x^2))^(3/2) + (2*b^2*(a + b*ArcSec[c*x]))/(9*x^3) + (4*b^2*c^2*(a + b*ArcSec[c*x]))/(3*x) + (2/3)*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(3*x^2) - (a + b*ArcSec[c*x])^3/(3*x^3)}
{(a + b*ArcSec[c*x])^3/x^5, x, 10, -((3*b^3*c*Sqrt[1 - 1/(c^2*x^2)])/(128*x^3)) - (45*b^3*c^3*Sqrt[1 - 1/(c^2*x^2)])/(256*x) - (45/256)*b^3*c^4*ArcSec[c*x] + (3*b^2*(a + b*ArcSec[c*x]))/(32*x^4) + (9*b^2*c^2*(a + b*ArcSec[c*x]))/(32*x^2) + (3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(16*x^3) + (9*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(32*x) + (3/32)*c^4*(a + b*ArcSec[c*x])^3 - (a + b*ArcSec[c*x])^3/(4*x^4)}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{x^1/(a + b*ArcSec[c*x]), x, 0, Unintegrable[x/(a + b*ArcSec[c*x]), x]}
{x^0/(a + b*ArcSec[c*x]), x, 0, Unintegrable[1/(a + b*ArcSec[c*x]), x]}
{1/(x^1*(a + b*ArcSec[c*x])), x, 0, Unintegrable[1/(x*(a + b*ArcSec[c*x])), x]}
{1/(x^2*(a + b*ArcSec[c*x])), x, 4, -((c*CosIntegral[a/b + ArcSec[c*x]]*Sin[a/b])/b) + (c*Cos[a/b]*SinIntegral[a/b + ArcSec[c*x]])/b}
{1/(x^3*(a + b*ArcSec[c*x])), x, 6, -((c^2*CosIntegral[(2*a)/b + 2*ArcSec[c*x]]*Sin[(2*a)/b])/(2*b)) + (c^2*Cos[(2*a)/b]*SinIntegral[(2*a)/b + 2*ArcSec[c*x]])/(2*b)}
{1/(x^4*(a + b*ArcSec[c*x])), x, 9, -((c^3*CosIntegral[a/b + ArcSec[c*x]]*Sin[a/b])/(4*b)) - (c^3*CosIntegral[(3*a)/b + 3*ArcSec[c*x]]*Sin[(3*a)/b])/(4*b) + (c^3*Cos[a/b]*SinIntegral[a/b + ArcSec[c*x]])/(4*b) + (c^3*Cos[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSec[c*x]])/(4*b)}


{x^1/(a + b*ArcSec[c*x])^2, x, 0, Unintegrable[x/(a + b*ArcSec[c*x])^2, x]}
{x^0/(a + b*ArcSec[c*x])^2, x, 0, Unintegrable[1/(a + b*ArcSec[c*x])^2, x]}
{1/(x^1*(a + b*ArcSec[c*x])^2), x, 0, Unintegrable[1/(x*(a + b*ArcSec[c*x])^2), x]}
{1/(x^2*(a + b*ArcSec[c*x])^2), x, 5, -((c*Sqrt[1 - 1/(c^2*x^2)])/(b*(a + b*ArcSec[c*x]))) + (c*Cos[a/b]*CosIntegral[a/b + ArcSec[c*x]])/b^2 + (c*Sin[a/b]*SinIntegral[a/b + ArcSec[c*x]])/b^2}
{1/(x^3*(a + b*ArcSec[c*x])^2), x, 7, (c^2*Cos[(2*a)/b]*CosIntegral[(2*a)/b + 2*ArcSec[c*x]])/b^2 - (c^2*Sin[2*ArcSec[c*x]])/(2*b*(a + b*ArcSec[c*x])) + (c^2*Sin[(2*a)/b]*SinIntegral[(2*a)/b + 2*ArcSec[c*x]])/b^2}
{1/(x^4*(a + b*ArcSec[c*x])^2), x, 11, -((c^3*Sqrt[1 - 1/(c^2*x^2)])/(4*b*(a + b*ArcSec[c*x]))) + (c^3*Cos[a/b]*CosIntegral[a/b + ArcSec[c*x]])/(4*b^2) + (3*c^3*Cos[(3*a)/b]*CosIntegral[(3*a)/b + 3*ArcSec[c*x]])/(4*b^2) - (c^3*Sin[3*ArcSec[c*x]])/(4*b*(a + b*ArcSec[c*x])) + (c^3*Sin[a/b]*SinIntegral[a/b + ArcSec[c*x]])/(4*b^2) + (3*c^3*Sin[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSec[c*x]])/(4*b^2)}


{x^1/(a + b*ArcSec[c*x])^3, x, 0, Unintegrable[x/(a + b*ArcSec[c*x])^3, x]}
{x^0/(a + b*ArcSec[c*x])^3, x, 0, Unintegrable[1/(a + b*ArcSec[c*x])^3, x]}
{1/(x^1*(a + b*ArcSec[c*x])^3), x, 0, Unintegrable[1/(x*(a + b*ArcSec[c*x])^3), x]}
{1/(x^2*(a + b*ArcSec[c*x])^3), x, 6, -((c*Sqrt[1 - 1/(c^2*x^2)])/(2*b*(a + b*ArcSec[c*x])^2)) - 1/(2*b^2*x*(a + b*ArcSec[c*x])) + (c*CosIntegral[a/b + ArcSec[c*x]]*Sin[a/b])/(2*b^3) - (c*Cos[a/b]*SinIntegral[a/b + ArcSec[c*x]])/(2*b^3)}
{1/(x^3*(a + b*ArcSec[c*x])^3), x, 8, -((c^2*Cos[2*ArcSec[c*x]])/(2*b^2*(a + b*ArcSec[c*x]))) + (c^2*CosIntegral[(2*a)/b + 2*ArcSec[c*x]]*Sin[(2*a)/b])/b^3 - (c^2*Sin[2*ArcSec[c*x]])/(4*b*(a + b*ArcSec[c*x])^2) - (c^2*Cos[(2*a)/b]*SinIntegral[(2*a)/b + 2*ArcSec[c*x]])/b^3}
{1/(x^4*(a + b*ArcSec[c*x])^3), x, 13, -((c^3*Sqrt[1 - 1/(c^2*x^2)])/(8*b*(a + b*ArcSec[c*x])^2)) - c^2/(8*b^2*x*(a + b*ArcSec[c*x])) - (3*c^3*Cos[3*ArcSec[c*x]])/(8*b^2*(a + b*ArcSec[c*x])) + (c^3*CosIntegral[a/b + ArcSec[c*x]]*Sin[a/b])/(8*b^3) + (9*c^3*CosIntegral[(3*a)/b + 3*ArcSec[c*x]]*Sin[(3*a)/b])/(8*b^3) - (c^3*Sin[3*ArcSec[c*x]])/(8*b*(a + b*ArcSec[c*x])^2) - (c^3*Cos[a/b]*SinIntegral[a/b + ArcSec[c*x]])/(8*b^3) - (9*c^3*Cos[(3*a)/b]*SinIntegral[(3*a)/b + 3*ArcSec[c*x]])/(8*b^3)}


(* ::Subsection::Closed:: *)
(*Integrands of the form (d x)^m (a+b ArcSec[c x])^n with m symbolic*)


{(d*x)^m*(a + b*ArcSec[c*x])^3, x, 0, Unintegrable[(d*x)^m*(a + b*ArcSec[c*x])^3, x]}
{(d*x)^m*(a + b*ArcSec[c*x])^2, x, 0, Unintegrable[(d*x)^m*(a + b*ArcSec[c*x])^2, x]}
{(d*x)^m*(a + b*ArcSec[c*x])^1, x, 3, ((d*x)^(1 + m)*(a + b*ArcSec[c*x]))/(d*(1 + m)) - (b*(d*x)^m*Hypergeometric2F1[1/2, -(m/2), 1 - m/2, 1/(c^2*x^2)])/(c*m*(1 + m))}
{(d*x)^m/(a + b*ArcSec[c*x])^1, x, 0, Unintegrable[(d*x)^m/(a + b*ArcSec[c*x]), x]}
{(d*x)^m/(a + b*ArcSec[c*x])^2, x, 0, Unintegrable[(d*x)^m/(a + b*ArcSec[c*x])^2, x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x)^p (a+b ArcSec[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x)^m (a+b ArcSec[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x)^3*(a + b*ArcSec[c*x]), x, 11, -((b*e*(9*c^2*d^2 + e^2)*Sqrt[1 - 1/(c^2*x^2)]*x)/(6*c^3)) - (b*d*e^2*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(2*c) - (b*e^3*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(12*c) + (b*d^4*ArcCsc[c*x])/(4*e) + ((d + e*x)^4*(a + b*ArcSec[c*x]))/(4*e) - (b*d*(2*c^2*d^2 + e^2)*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(2*c^3)}
{(d + e*x)^2*(a + b*ArcSec[c*x]), x, 10, -((b*d*e*Sqrt[1 - 1/(c^2*x^2)]*x)/c) - (b*e^2*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(6*c) + (b*d^3*ArcCsc[c*x])/(3*e) + ((d + e*x)^3*(a + b*ArcSec[c*x]))/(3*e) - (b*(6*c^2*d^2 + e^2)*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(6*c^3)}
{(d + e*x)^1*(a + b*ArcSec[c*x]), x, 9, -((b*e*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c)) + (b*d^2*ArcCsc[c*x])/(2*e) + ((d + e*x)^2*(a + b*ArcSec[c*x]))/(2*e) - (b*d*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c}
{(d + e*x)^0*(a + b*ArcSec[c*x]), x, 5, a*x + b*x*ArcSec[c*x] - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c}
{(a + b*ArcSec[c*x])/(d + e*x)^1, x, 4, ((a + b*ArcSec[c*x])*Log[1 + ((e - Sqrt[(-c^2)*d^2 + e^2])*E^(I*ArcSec[c*x]))/(c*d)])/e + ((a + b*ArcSec[c*x])*Log[1 + ((e + Sqrt[(-c^2)*d^2 + e^2])*E^(I*ArcSec[c*x]))/(c*d)])/e - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e - (I*b*PolyLog[2, -(((e - Sqrt[(-c^2)*d^2 + e^2])*E^(I*ArcSec[c*x]))/(c*d))])/e - (I*b*PolyLog[2, -(((e + Sqrt[(-c^2)*d^2 + e^2])*E^(I*ArcSec[c*x]))/(c*d))])/e + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e)}
{(a + b*ArcSec[c*x])/(d + e*x)^2, x, 7, -((b*ArcCsc[c*x])/(d*e)) - (a + b*ArcSec[c*x])/(e*(d + e*x)) - (b*ArcTanh[(c^2*d + e/x)/(c*Sqrt[c^2*d^2 - e^2]*Sqrt[1 - 1/(c^2*x^2)])])/(d*Sqrt[c^2*d^2 - e^2])}
{(a + b*ArcSec[c*x])/(d + e*x)^3, x, 8, (b*c*e*Sqrt[1 - 1/(c^2*x^2)])/(2*d*(c^2*d^2 - e^2)*(e + d/x)) - (b*ArcCsc[c*x])/(2*d^2*e) - (a + b*ArcSec[c*x])/(2*e*(d + e*x)^2) - (b*(2*c^2*d^2 - e^2)*ArcTanh[(c^2*d + e/x)/(c*Sqrt[c^2*d^2 - e^2]*Sqrt[1 - 1/(c^2*x^2)])])/(2*d^2*(c^2*d^2 - e^2)^(3/2))}


(* ::Subsubsection:: *)
(*n<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (d+e x)^(m/2) (a+b ArcSec[c x])^n*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{(d + e*x)^(3/2)*(a + b*ArcSec[c*x]), x, 22, (4*b*e*Sqrt[d + e*x]*(1 - c^2*x^2))/(15*c^3*Sqrt[1 - 1/(c^2*x^2)]*x) + (2*(d + e*x)^(5/2)*(a + b*ArcSec[c*x]))/(5*e) + (28*b*d*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*c^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) + (4*b*(2*c^2*d^2 + e^2)*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*c^4*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) + (4*b*d^3*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*c*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}
{(d + e*x)^(1/2)*(a + b*ArcSec[c*x]), x, 15, (2*(d + e*x)^(3/2)*(a + b*ArcSec[c*x]))/(3*e) + (4*b*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) + (4*b*d*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) + (4*b*d^2*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}
{(a + b*ArcSec[c*x])/(d + e*x)^(1/2), x, 9, (2*Sqrt[d + e*x]*(a + b*ArcSec[c*x]))/e + (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(c^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) + (4*b*d*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(c*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}
{(a + b*ArcSec[c*x])/(d + e*x)^(3/2), x, 6, -((2*(a + b*ArcSec[c*x]))/(e*Sqrt[d + e*x])) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(c*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}
{(a + b*ArcSec[c*x])/(d + e*x)^(5/2), x, 12, -((4*b*e*(1 - c^2*x^2))/(3*c*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])) - (2*(a + b*ArcSec[c*x]))/(3*e*(d + e*x)^(3/2)) + (4*b*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(3*c*d*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}
{(a + b*ArcSec[c*x])/(d + e*x)^(7/2), x, 19, -((4*b*e*(1 - c^2*x^2))/(15*c*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*(d + e*x)^(3/2))) - (16*b*c*e*(1 - c^2*x^2))/(15*(c^2*d^2 - e^2)^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (4*b*e*(1 - c^2*x^2))/(5*c*d^2*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (2*(a + b*ArcSec[c*x]))/(5*e*(d + e*x)^(5/2)) + (4*b*(7*c^2*d^2 - 3*e^2)*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*(c^2*d^3 - d*e^2)^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*c*d^2*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]), -((4*b*e*(1 - c^2*x^2))/(15*c*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*(d + e*x)^(3/2))) - (16*b*c*e*(1 - c^2*x^2))/(15*(c^2*d^2 - e^2)^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (4*b*e*(1 - c^2*x^2))/(5*c*d^2*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (2*(a + b*ArcSec[c*x]))/(5*e*(d + e*x)^(5/2)) + (16*b*c^2*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*(c^2*d^2 - e^2)^2*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) + (4*b*Sqrt[d + e*x]*Sqrt[1 - c^2*x^2]*EllipticE[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*d^2*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[(c*(d + e*x))/(c*d + e)]) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticF[ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(15*d*(c^2*d^2 - e^2)*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x]) - (4*b*Sqrt[(c*(d + e*x))/(c*d + e)]*Sqrt[1 - c^2*x^2]*EllipticPi[2, ArcSin[Sqrt[1 - c*x]/Sqrt[2]], (2*e)/(c*d + e)])/(5*c*d^2*e*Sqrt[1 - 1/(c^2*x^2)]*x*Sqrt[d + e*x])}


(* ::Subsubsection:: *)
(*n<0*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSec[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcSec[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^4*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 7, -((b*(42*c^2*d + 25*e)*x^2*Sqrt[-1 + c^2*x^2])/(560*c^5*Sqrt[c^2*x^2])) - (b*(42*c^2*d + 25*e)*x^4*Sqrt[-1 + c^2*x^2])/(840*c^3*Sqrt[c^2*x^2]) - (b*e*x^6*Sqrt[-1 + c^2*x^2])/(42*c*Sqrt[c^2*x^2]) + (1/5)*d*x^5*(a + b*ArcSec[c*x]) + (1/7)*e*x^7*(a + b*ArcSec[c*x]) - (b*(42*c^2*d + 25*e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(560*c^6*Sqrt[c^2*x^2])}
{x^2*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 6, -((b*(20*c^2*d + 9*e)*x^2*Sqrt[-1 + c^2*x^2])/(120*c^3*Sqrt[c^2*x^2])) - (b*e*x^4*Sqrt[-1 + c^2*x^2])/(20*c*Sqrt[c^2*x^2]) + (1/3)*d*x^3*(a + b*ArcSec[c*x]) + (1/5)*e*x^5*(a + b*ArcSec[c*x]) - (b*(20*c^2*d + 9*e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(120*c^4*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*e*x^2*Sqrt[-1 + c^2*x^2])/(6*c*Sqrt[c^2*x^2])) + d*x*(a + b*ArcSec[c*x]) + (1/3)*e*x^3*(a + b*ArcSec[c*x]) - (b*(6*c^2*d + e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(6*c^2*Sqrt[c^2*x^2])}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^2, x, 4, (b*c*d*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*x^2] - (d*(a + b*ArcSec[c*x]))/x + e*x*(a + b*ArcSec[c*x]) - (b*e*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/Sqrt[c^2*x^2]}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^4, x, 4, (b*c*(2*c^2*d + 9*e)*Sqrt[-1 + c^2*x^2])/(9*Sqrt[c^2*x^2]) + (b*c*d*Sqrt[-1 + c^2*x^2])/(9*x^2*Sqrt[c^2*x^2]) - (d*(a + b*ArcSec[c*x]))/(3*x^3) - (e*(a + b*ArcSec[c*x]))/x}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^6, x, 5, (2*b*c^3*(12*c^2*d + 25*e)*Sqrt[-1 + c^2*x^2])/(225*Sqrt[c^2*x^2]) + (b*c*d*Sqrt[-1 + c^2*x^2])/(25*x^4*Sqrt[c^2*x^2]) + (b*c*(12*c^2*d + 25*e)*Sqrt[-1 + c^2*x^2])/(225*x^2*Sqrt[c^2*x^2]) - (d*(a + b*ArcSec[c*x]))/(5*x^5) - (e*(a + b*ArcSec[c*x]))/(3*x^3)}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^8, x, 6, (8*b*c^5*(30*c^2*d + 49*e)*Sqrt[-1 + c^2*x^2])/(3675*Sqrt[c^2*x^2]) + (b*c*d*Sqrt[-1 + c^2*x^2])/(49*x^6*Sqrt[c^2*x^2]) + (b*c*(30*c^2*d + 49*e)*Sqrt[-1 + c^2*x^2])/(1225*x^4*Sqrt[c^2*x^2]) + (4*b*c^3*(30*c^2*d + 49*e)*Sqrt[-1 + c^2*x^2])/(3675*x^2*Sqrt[c^2*x^2]) - (d*(a + b*ArcSec[c*x]))/(7*x^7) - (e*(a + b*ArcSec[c*x]))/(5*x^5)}

{x^5*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*(4*c^2*d + 3*e)*x*Sqrt[-1 + c^2*x^2])/(24*c^7*Sqrt[c^2*x^2])) - (b*(8*c^2*d + 9*e)*x*(-1 + c^2*x^2)^(3/2))/(72*c^7*Sqrt[c^2*x^2]) - (b*(4*c^2*d + 9*e)*x*(-1 + c^2*x^2)^(5/2))/(120*c^7*Sqrt[c^2*x^2]) - (b*e*x*(-1 + c^2*x^2)^(7/2))/(56*c^7*Sqrt[c^2*x^2]) + (1/6)*d*x^6*(a + b*ArcSec[c*x]) + (1/8)*e*x^8*(a + b*ArcSec[c*x])}
{x^3*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*(3*c^2*d + 2*e)*x*Sqrt[-1 + c^2*x^2])/(12*c^5*Sqrt[c^2*x^2])) - (b*(3*c^2*d + 4*e)*x*(-1 + c^2*x^2)^(3/2))/(36*c^5*Sqrt[c^2*x^2]) - (b*e*x*(-1 + c^2*x^2)^(5/2))/(30*c^5*Sqrt[c^2*x^2]) + (1/4)*d*x^4*(a + b*ArcSec[c*x]) + (1/6)*e*x^6*(a + b*ArcSec[c*x])}
{x^1*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 6, -((b*(2*c^2*d + e)*x*Sqrt[-1 + c^2*x^2])/(4*c^3*Sqrt[c^2*x^2])) - (b*e*x*(-1 + c^2*x^2)^(3/2))/(12*c^3*Sqrt[c^2*x^2]) + ((d + e*x^2)^2*(a + b*ArcSec[c*x]))/(4*e) - (b*c*d^2*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(4*e*Sqrt[c^2*x^2])}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^1, x, 11, -((b*e*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c)) - (1/2)*I*b*d*ArcCsc[c*x]^2 + (1/2)*e*x^2*(a + b*ArcSec[c*x]) + b*d*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - b*d*ArcCsc[c*x]*Log[1/x] - d*(a + b*ArcSec[c*x])*Log[1/x] - (1/2)*I*b*d*PolyLog[2, E^(2*I*ArcCsc[c*x])]}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^3, x, 13, (b*c*d*Sqrt[1 - 1/(c^2*x^2)])/(4*x) - (1/4)*b*c^2*d*ArcCsc[c*x] - (1/2)*I*b*e*ArcCsc[c*x]^2 - (d*(a + b*ArcSec[c*x]))/(2*x^2) + b*e*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - b*e*ArcCsc[c*x]*Log[1/x] - e*(a + b*ArcSec[c*x])*Log[1/x] - (1/2)*I*b*e*PolyLog[2, E^(2*I*ArcCsc[c*x])]}


{x^2*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 7, -((b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x^2*Sqrt[-1 + c^2*x^2])/(1680*c^5*Sqrt[c^2*x^2])) - (b*e*(84*c^2*d + 25*e)*x^4*Sqrt[-1 + c^2*x^2])/(840*c^3*Sqrt[c^2*x^2]) - (b*e^2*x^6*Sqrt[-1 + c^2*x^2])/(42*c*Sqrt[c^2*x^2]) + (1/3)*d^2*x^3*(a + b*ArcSec[c*x]) + (2/5)*d*e*x^5*(a + b*ArcSec[c*x]) + (1/7)*e^2*x^7*(a + b*ArcSec[c*x]) - (b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(1680*c^6*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 6, -((b*e*(40*c^2*d + 9*e)*x^2*Sqrt[-1 + c^2*x^2])/(120*c^3*Sqrt[c^2*x^2])) - (b*e^2*x^4*Sqrt[-1 + c^2*x^2])/(20*c*Sqrt[c^2*x^2]) + d^2*x*(a + b*ArcSec[c*x]) + (2/3)*d*e*x^3*(a + b*ArcSec[c*x]) + (1/5)*e^2*x^5*(a + b*ArcSec[c*x]) - (b*(120*c^4*d^2 + 40*c^2*d*e + 9*e^2)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(120*c^4*Sqrt[c^2*x^2])}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^2, x, 6, (b*c*d^2*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*x^2] - (b*e^2*x^2*Sqrt[-1 + c^2*x^2])/(6*c*Sqrt[c^2*x^2]) - (d^2*(a + b*ArcSec[c*x]))/x + 2*d*e*x*(a + b*ArcSec[c*x]) + (1/3)*e^2*x^3*(a + b*ArcSec[c*x]) - (b*e*(12*c^2*d + e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(6*c^2*Sqrt[c^2*x^2])}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^4, x, 6, (2*b*c*d*(c^2*d + 9*e)*Sqrt[-1 + c^2*x^2])/(9*Sqrt[c^2*x^2]) + (b*c*d^2*Sqrt[-1 + c^2*x^2])/(9*x^2*Sqrt[c^2*x^2]) - (d^2*(a + b*ArcSec[c*x]))/(3*x^3) - (2*d*e*(a + b*ArcSec[c*x]))/x + e^2*x*(a + b*ArcSec[c*x]) - (b*e^2*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/Sqrt[c^2*x^2]}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^6, x, 5, (b*c*(24*c^4*d^2 + 100*c^2*d*e + 225*e^2)*Sqrt[-1 + c^2*x^2])/(225*Sqrt[c^2*x^2]) + (b*c*d^2*Sqrt[-1 + c^2*x^2])/(25*x^4*Sqrt[c^2*x^2]) + (2*b*c*d*(6*c^2*d + 25*e)*Sqrt[-1 + c^2*x^2])/(225*x^2*Sqrt[c^2*x^2]) - (d^2*(a + b*ArcSec[c*x]))/(5*x^5) - (2*d*e*(a + b*ArcSec[c*x]))/(3*x^3) - (e^2*(a + b*ArcSec[c*x]))/x}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^8, x, 6, (2*b*c^3*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*Sqrt[-1 + c^2*x^2])/(11025*Sqrt[c^2*x^2]) + (b*c*d^2*Sqrt[-1 + c^2*x^2])/(49*x^6*Sqrt[c^2*x^2]) + (2*b*c*d*(15*c^2*d + 49*e)*Sqrt[-1 + c^2*x^2])/(1225*x^4*Sqrt[c^2*x^2]) + (b*c*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*Sqrt[-1 + c^2*x^2])/(11025*x^2*Sqrt[c^2*x^2]) - (d^2*(a + b*ArcSec[c*x]))/(7*x^7) - (2*d*e*(a + b*ArcSec[c*x]))/(5*x^5) - (e^2*(a + b*ArcSec[c*x]))/(3*x^3)}

{x^3*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 5, -((b*(6*c^4*d^2 + 8*c^2*d*e + 3*e^2)*x*Sqrt[-1 + c^2*x^2])/(24*c^7*Sqrt[c^2*x^2])) - (b*(6*c^4*d^2 + 16*c^2*d*e + 9*e^2)*x*(-1 + c^2*x^2)^(3/2))/(72*c^7*Sqrt[c^2*x^2]) - (b*e*(8*c^2*d + 9*e)*x*(-1 + c^2*x^2)^(5/2))/(120*c^7*Sqrt[c^2*x^2]) - (b*e^2*x*(-1 + c^2*x^2)^(7/2))/(56*c^7*Sqrt[c^2*x^2]) + (1/4)*d^2*x^4*(a + b*ArcSec[c*x]) + (1/3)*d*e*x^6*(a + b*ArcSec[c*x]) + (1/8)*e^2*x^8*(a + b*ArcSec[c*x])}
{x^1*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 6, -((b*(3*c^4*d^2 + 3*c^2*d*e + e^2)*x*Sqrt[-1 + c^2*x^2])/(6*c^5*Sqrt[c^2*x^2])) - (b*e*(3*c^2*d + 2*e)*x*(-1 + c^2*x^2)^(3/2))/(18*c^5*Sqrt[c^2*x^2]) - (b*e^2*x*(-1 + c^2*x^2)^(5/2))/(30*c^5*Sqrt[c^2*x^2]) + ((d + e*x^2)^3*(a + b*ArcSec[c*x]))/(6*e) - (b*c*d^3*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(6*e*Sqrt[c^2*x^2])}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^1, x, 12, -((b*e*(6*c^2*d + e)*Sqrt[1 - 1/(c^2*x^2)]*x)/(6*c^3)) - (b*e^2*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(12*c) - (1/2)*I*b*d^2*ArcCsc[c*x]^2 + d*e*x^2*(a + b*ArcSec[c*x]) + (1/4)*e^2*x^4*(a + b*ArcSec[c*x]) + b*d^2*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - b*d^2*ArcCsc[c*x]*Log[1/x] - d^2*(a + b*ArcSec[c*x])*Log[1/x] - (1/2)*I*b*d^2*PolyLog[2, E^(2*I*ArcCsc[c*x])]}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^3, x, 14, (b*c*d^2*Sqrt[1 - 1/(c^2*x^2)])/(4*x) - (b*e^2*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c) - (1/4)*b*c^2*d^2*ArcCsc[c*x] - I*b*d*e*ArcCsc[c*x]^2 - (d^2*(a + b*ArcSec[c*x]))/(2*x^2) + (1/2)*e^2*x^2*(a + b*ArcSec[c*x]) + 2*b*d*e*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - 2*b*d*e*ArcCsc[c*x]*Log[1/x] - 2*d*e*(a + b*ArcSec[c*x])*Log[1/x] - I*b*d*e*PolyLog[2, E^(2*I*ArcCsc[c*x])]}


(* ::Subsubsection::Closed:: *)
(*p<0*)


(* {x^3*(a + b*ArcSec[c*x])/(d + e*x^2), x, 47, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c*e)) + (I*b*d*ArcSec[c*x]^2)/(2*e^2) + (x^2*(a + b*ArcSec[c*x]))/(2*e) - (I*d*(a + b*ArcSec[c*x])^2)/(2*b*e^2) - (b*d*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + (d*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^2 - (a*d*Log[Sqrt[e] - Sqrt[-d]/x])/(2*e^2) - (a*d*Log[Sqrt[e] + Sqrt[-d]/x])/(2*e^2) + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - (I*b*d*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^2)} *)
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2), x, 25, (x*(a + b*ArcSec[c*x]))/e - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(c*e) + (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2))}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2), x, 26, ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e)}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2), x, 19, ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)), x, 19, (I*(a + b*ArcSec[c*x])^2)/(2*b*d) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d)}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)), x, 24, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d - a/(d*x) - (b*ArcSec[c*x])/(d*x) + (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2))}


{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 31, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c*e^2)) + (d*(a + b*ArcSec[c*x]))/(2*e^2*(e + d/x^2)) + (x^2*(a + b*ArcSec[c*x]))/(2*e^2) + (b*d*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]) - (d*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 + (2*d*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^3 + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/e^3 + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/e^3 + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 - (I*b*d*PolyLog[2, -E^(2*I*ArcSec[c*x])])/e^3}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 29, -((a + b*ArcSec[c*x])/(2*e*(e + d/x^2))) - (b*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(3/2)*Sqrt[c^2*d + e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^2 - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^2)}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 7, -((a + b*ArcSec[c*x])/(2*e*(d + e*x^2))) + (b*c*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(2*d*e*Sqrt[c^2*x^2]) - (b*c*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(2*d*Sqrt[e]*Sqrt[c^2*d + e]*Sqrt[c^2*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^2), x, 24, -((e*(a + b*ArcSec[c*x]))/(2*d^2*(e + d/x^2))) + (I*(a + b*ArcSec[c*x])^2)/(2*b*d^2) - (b*Sqrt[e]*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*d^2*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2)}

{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 51, -((d*(a + b*ArcSec[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] - d/x))) + (d*(a + b*ArcSec[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (x*(a + b*ArcSec[c*x]))/e^2 - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(c*e^2) - (b*Sqrt[d]*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*e^2*Sqrt[c^2*d + e]) - (b*Sqrt[d]*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*e^2*Sqrt[c^2*d + e]) + (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2))}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 27, (a + b*ArcSec[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSec[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*Sqrt[d]*e*Sqrt[c^2*d + e]) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*Sqrt[d]*e*Sqrt[c^2*d + e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2))}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 47, -((a + b*ArcSec[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] - d/x))) + (a + b*ArcSec[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(3/2)*Sqrt[c^2*d + e]) - (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(3/2)*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e])}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^2), x, 50, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d^2 - a/(d^2*x) - (b*ArcSec[c*x])/(d^2*x) + (e*(a + b*ArcSec[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (e*(a + b*ArcSec[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(5/2)*Sqrt[c^2*d + e]) + (b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(5/2)*Sqrt[c^2*d + e]) - (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2))}


{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 33, -((b*c*d*Sqrt[1 - 1/(c^2*x^2)])/(8*e^2*(c^2*d + e)*(e + d/x^2)*x)) - (a + b*ArcSec[c*x])/(4*e*(e + d/x^2)^2) - (a + b*ArcSec[c*x])/(2*e^2*(e + d/x^2)) - (b*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]) - (b*(c^2*d + 2*e)*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(8*e^(5/2)*(c^2*d + e)^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^3 - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^3)}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 6, (b*c*x*Sqrt[-1 + c^2*x^2])/(8*e*(c^2*d + e)*Sqrt[c^2*x^2]*(d + e*x^2)) + (x^4*(a + b*ArcSec[c*x]))/(4*d*(d + e*x^2)^2) - (b*c*(c^2*d + 2*e)*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(8*d*e^(3/2)*(c^2*d + e)^(3/2)*Sqrt[c^2*x^2])}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 8, -((b*c*x*Sqrt[-1 + c^2*x^2])/(8*d*(c^2*d + e)*Sqrt[c^2*x^2]*(d + e*x^2))) - (a + b*ArcSec[c*x])/(4*e*(d + e*x^2)^2) + (b*c*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(4*d^2*e*Sqrt[c^2*x^2]) - (b*c*(3*c^2*d + 2*e)*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(8*d^2*Sqrt[e]*(c^2*d + e)^(3/2)*Sqrt[c^2*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^3), x, 28, (b*c*e*Sqrt[1 - 1/(c^2*x^2)])/(8*d^2*(c^2*d + e)*(e + d/x^2)*x) + (e^2*(a + b*ArcSec[c*x]))/(4*d^3*(e + d/x^2)^2) - (e*(a + b*ArcSec[c*x]))/(d^3*(e + d/x^2)) + (I*(a + b*ArcSec[c*x])^2)/(2*b*d^3) - (b*Sqrt[e]*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(d^3*Sqrt[c^2*d + e]) + (b*Sqrt[e]*(c^2*d + 2*e)*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(8*d^3*(c^2*d + e)^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3)}

{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 35, (b*c*Sqrt[-d]*Sqrt[1 - 1/(c^2*x^2)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[-d]*Sqrt[1 - 1/(c^2*x^2)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[-d]*(a + b*ArcSec[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (3*(a + b*ArcSec[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[-d]*(a + b*ArcSec[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (3*(a + b*ArcSec[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e*(c^2*d + e)^(3/2)) + (3*b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e^2*Sqrt[c^2*d + e]) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e*(c^2*d + e)^(3/2)) + (3*b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e^2*Sqrt[c^2*d + e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2))}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 63, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (a + b*ArcSec[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (a + b*ArcSec[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSec[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (a + b*ArcSec[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*(c^2*d + e)^(3/2)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*e*Sqrt[c^2*d + e]) - (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*(c^2*d + e)^(3/2)) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*e*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2))}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 81, (b*c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[e]*(a + b*ArcSec[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) - (5*(a + b*ArcSec[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[e]*(a + b*ArcSec[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) + (5*(a + b*ArcSec[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*(c^2*d + e)^(3/2)) - (5*b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*Sqrt[c^2*d + e]) + (b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*(c^2*d + e)^(3/2)) - (5*b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*Sqrt[c^2*d + e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e])}
(* {(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^3), x, 96, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d^3 + (b*c*e^(3/2)*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*e^(3/2)*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) - a/(d^3*x) + (a*e^2)/(4*d^3*(e + d/x^2)^2*x) - (9*a*e)/(8*d^3*(e + d/x^2)*x) + (15*a*Sqrt[e]*ArcCot[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(7/2)) + (b*e^(3/2)*ArcSec[c*x])/(16*(-d)^(5/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (9*b*e*ArcSec[c*x])/(16*d^3*(Sqrt[-d]*Sqrt[e] - d/x)) - (b*e^(3/2)*ArcSec[c*x])/(16*(-d)^(5/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (9*b*e*ArcSec[c*x])/(16*d^3*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcSec[c*x])/(d^3*x) - (b*e^2*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*(c^2*d + e)^(3/2)) + (9*b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*Sqrt[c^2*d + e]) - (b*e^2*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*(c^2*d + e)^(3/2)) + (9*b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*Sqrt[c^2*d + e]) + (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) - (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) - (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2))} *)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^(p/2) (a+b ArcSec[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^5*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x, If[$VersionNumber>=8, 12, 13], (b*(23*c^4*d^2 + 12*c^2*d*e - 75*e^2)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(1680*c^5*e^2*Sqrt[c^2*x^2]) + (b*(29*c^2*d - 25*e)*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(840*c^3*e^2*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(5/2))/(42*c*e^2*Sqrt[c^2*x^2]) + (d^2*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^3) - (2*d*(d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^3) + ((d + e*x^2)^(7/2)*(a + b*ArcSec[c*x]))/(7*e^3) + (8*b*c*d^(7/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(105*e^3*Sqrt[c^2*x^2]) - (b*(105*c^6*d^3 - 35*c^4*d^2*e + 63*c^2*d*e^2 + 75*e^3)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(1680*c^6*e^(5/2)*Sqrt[c^2*x^2])}
{x^3*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x, If[$VersionNumber>=8, 11, 12], -((b*(c^2*d + 9*e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(120*c^3*e*Sqrt[c^2*x^2])) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*e*Sqrt[c^2*x^2]) - (d*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^2) - (2*b*c*d^(5/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(15*e^2*Sqrt[c^2*x^2]) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^4*e^(3/2)*Sqrt[c^2*x^2])}
{x^1*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x, 9, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*Sqrt[c^2*x^2])) + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e) + (b*c*d^(3/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*e*Sqrt[c^2*x^2]) - (b*(3*c^2*d + e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*Sqrt[e]*Sqrt[c^2*x^2])}
{Sqrt[d + e*x^2]*(a + b*ArcSec[c*x])/x^1, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/x, x]}
{Sqrt[d + e*x^2]*(a + b*ArcSec[c*x])/x^3, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/x^3, x]}

{x^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x, 0, Unintegrable[x^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}
{x^0*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x, 0, Unintegrable[Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}
{Sqrt[d + e*x^2]*(a + b*ArcSec[c*x])/x^2, x, 0, Unintegrable[(Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/x^2, x]}
{Sqrt[d + e*x^2]*(a + b*ArcSec[c*x])/x^4, x, 11, (2*b*c*(c^2*d + 2*e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*d*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*x^2*Sqrt[c^2*x^2]) - ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*d*x^3) - (2*b*c^2*(c^2*d + 2*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(9*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + e)*(2*c^2*d + 3*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(9*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{Sqrt[d + e*x^2]*(a + b*ArcSec[c*x])/x^6, x, If[$VersionNumber>=8, 12, 32], If[$VersionNumber>=8, (b*c*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(225*d^2*Sqrt[c^2*x^2]) + (b*c*(12*c^2*d - e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(225*d*x^2*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(25*d*x^4*Sqrt[c^2*x^2]) - ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(15*d^2*x^3) - (b*c^2*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(225*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + e)*(24*c^4*d^2 + 7*c^2*d*e - 30*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(225*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]), -((2*b*c*e^2*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(15*d^2*Sqrt[c^2*x^2])) + (b*c*e*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(45*d^2*Sqrt[c^2*x^2]) + (b*c*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*d^2*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(25*x^4*Sqrt[c^2*x^2]) + (b*c*e*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(45*d*x^2*Sqrt[c^2*x^2]) + (b*c*(4*c^2*d + e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*d*x^2*Sqrt[c^2*x^2]) - ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(15*d^2*x^3) + (2*b*c^2*e^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(15*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*c^2*e*(2*c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(45*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*c^2*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(75*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*c^2*(8*c^2*d - e)*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(75*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) + (2*b*c^2*e*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(45*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) - (2*b*e^2*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(15*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])]}


{x^3*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 12, (b*(3*c^4*d^2 - 38*c^2*d*e - 25*e^2)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(560*c^5*e*Sqrt[c^2*x^2]) - (b*(13*c^2*d + 25*e)*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(840*c^3*e*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(5/2))/(42*c*e*Sqrt[c^2*x^2]) - (d*(d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^2) + ((d + e*x^2)^(7/2)*(a + b*ArcSec[c*x]))/(7*e^2) - (2*b*c*d^(7/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(35*e^2*Sqrt[c^2*x^2]) + (b*(35*c^6*d^3 - 35*c^4*d^2*e - 63*c^2*d*e^2 - 25*e^3)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(560*c^6*e^(3/2)*Sqrt[c^2*x^2])}
{x^1*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 10, -((b*(7*c^2*d + 3*e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(40*c^3*Sqrt[c^2*x^2])) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*Sqrt[c^2*x^2]) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e) + (b*c*d^(5/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(5*e*Sqrt[c^2*x^2]) - (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(40*c^4*Sqrt[e]*Sqrt[c^2*x^2])}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^1, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^3, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x^3, x]}

{x^2*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Unintegrable[x^2*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}
{x^0*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Unintegrable[(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^2, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x^2, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^4, x, 0, Unintegrable[((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x^4, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^6, x, 12, (b*c*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*d*Sqrt[c^2*x^2]) + (4*b*c*(c^2*d + 2*e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*x^2*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(25*x^4*Sqrt[c^2*x^2]) - ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*d*x^5) - (b*c^2*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(75*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + e)*(8*c^4*d^2 + 19*c^2*d*e + 15*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(75*d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^8, x, 13, (b*c*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(3675*d^2*Sqrt[c^2*x^2]) + (b*c*(120*c^4*d^2 + 159*c^2*d*e - 37*e^2)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(3675*d*x^2*Sqrt[c^2*x^2]) + (b*c*(30*c^2*d + 11*e)*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(1225*d*x^4*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(5/2))/(49*d*x^6*Sqrt[c^2*x^2]) - ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(7*d*x^7) + (2*e*(d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(35*d^2*x^5) - (b*c^2*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3675*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (2*b*(c^2*d + e)*(120*c^6*d^3 + 204*c^4*d^2*e + 17*c^2*d*e^2 - 105*e^3)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3675*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^5*(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x, 11, (b*(19*c^2*d - 9*e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(120*c^3*e^2*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*e^2*Sqrt[c^2*x^2]) + (d^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 - (2*d*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^3) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^3) + (8*b*c*d^(5/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(15*e^3*Sqrt[c^2*x^2]) - (b*(45*c^4*d^2 - 10*c^2*d*e + 9*e^2)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^4*e^(5/2)*Sqrt[c^2*x^2])}
{x^3*(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x, 10, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*e*Sqrt[c^2*x^2])) - (d*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^2 + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^2) - (2*b*c*d^(3/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*e^2*Sqrt[c^2*x^2]) + (b*(3*c^2*d - e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*e^(3/2)*Sqrt[c^2*x^2])}
{x^1*(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x, 9, (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e + (b*c*Sqrt[d]*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(e*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(Sqrt[e]*Sqrt[c^2*x^2])}
{(a + b*ArcSec[c*x])/(x^1*Sqrt[d + e*x^2]), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x*Sqrt[d + e*x^2]), x]}
{(a + b*ArcSec[c*x])/(x^3*Sqrt[d + e*x^2]), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x^3*Sqrt[d + e*x^2]), x]}

{x^2*(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x, 0, Unintegrable[(x^2*(a + b*ArcSec[c*x]))/Sqrt[d + e*x^2], x]}
{x^0*(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x, 0, Unintegrable[(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcSec[c*x])/(x^2*Sqrt[d + e*x^2]), x, 11, (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d*Sqrt[c^2*x^2]) - (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(d*x) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^4*Sqrt[d + e*x^2]), x, 11, (b*c*(2*c^2*d - 5*e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*d^2*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*d*x^2*Sqrt[c^2*x^2]) - (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(3*d*x^3) + (2*e*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(3*d^2*x) - (b*c^2*(2*c^2*d - 5*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(9*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (2*b*(c^2*d - 3*e)*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(9*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^6*Sqrt[d + e*x^2]), x, 32, (8*b*c*e^2*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(15*d^3*Sqrt[c^2*x^2]) - (4*b*c*e*(2*c^2*d + e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(45*d^3*Sqrt[c^2*x^2]) + (b*c*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*d^3*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(25*d*x^4*Sqrt[c^2*x^2]) - (4*b*c*e*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(45*d^2*x^2*Sqrt[c^2*x^2]) + (b*c*(4*c^2*d + e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(75*d^2*x^2*Sqrt[c^2*x^2]) - (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(5*d*x^5) + (4*e*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(15*d^2*x^3) - (8*e^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(15*d^3*x) - (8*b*c^2*e^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(15*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (4*b*c^2*e*(2*c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(45*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*c^2*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(75*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*c^2*(8*c^2*d - e)*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(75*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) - (8*b*c^2*e*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(45*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) + (8*b*e^2*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(15*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}


{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 10, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*e^2*Sqrt[c^2*x^2])) - (d^2*(a + b*ArcSec[c*x]))/(e^3*Sqrt[d + e*x^2]) - (2*d*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^3) - (8*b*c*d^(3/2)*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*e^3*Sqrt[c^2*x^2]) + (b*(9*c^2*d - e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*e^(5/2)*Sqrt[c^2*x^2])}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 9, (d*(a + b*ArcSec[c*x]))/(e^2*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^2 + (2*b*c*Sqrt[d]*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(e^2*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(e^(3/2)*Sqrt[c^2*x^2])}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 4, -((a + b*ArcSec[c*x])/(e*Sqrt[d + e*x^2])) - (b*c*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(Sqrt[d]*e*Sqrt[c^2*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^(3/2)), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x*(d + e*x^2)^(3/2)), x]}
{(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(3/2)), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(3/2)), x]}

{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Unintegrable[(x^4*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Unintegrable[(x^2*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 5, (x*(a + b*ArcSec[c*x]))/(d*Sqrt[d + e*x^2]) - (b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^(3/2)), x, 10, (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d^2*Sqrt[c^2*x^2]) - (a + b*ArcSec[c*x])/(d*x*Sqrt[d + e*x^2]) - (2*e*x*(a + b*ArcSec[c*x]))/(d^2*Sqrt[d + e*x^2]) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + 2*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^4*(d + e*x^2)^(3/2)), x, 25, (2*b*c*(c^2*d - e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*d^3*Sqrt[c^2*x^2]) - (4*b*c*e*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(3*d^3*Sqrt[c^2*x^2]) + (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(9*d^2*x^2*Sqrt[c^2*x^2]) - (a + b*ArcSec[c*x])/(3*d*x^3*Sqrt[d + e*x^2]) + (4*e*(a + b*ArcSec[c*x]))/(3*d^2*x*Sqrt[d + e*x^2]) + (8*e^2*x*(a + b*ArcSec[c*x]))/(3*d^3*Sqrt[d + e*x^2]) - (2*b*c^2*(c^2*d - e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(9*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (4*b*c^2*e*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*c^2*(2*c^2*d - e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(9*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) - (4*b*c^2*e*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) - (8*b*e^2*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}


{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 10, -((b*c*d*x*Sqrt[-1 + c^2*x^2])/(3*e^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (d^2*(a + b*ArcSec[c*x]))/(3*e^3*(d + e*x^2)^(3/2)) + (2*d*(a + b*ArcSec[c*x]))/(e^3*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 + (8*b*c*Sqrt[d]*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*e^3*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(e^(5/2)*Sqrt[c^2*x^2])}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 7, (b*c*x*Sqrt[-1 + c^2*x^2])/(3*e*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (d*(a + b*ArcSec[c*x]))/(3*e^2*(d + e*x^2)^(3/2)) - (a + b*ArcSec[c*x])/(e^2*Sqrt[d + e*x^2]) - (2*b*c*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*Sqrt[d]*e^2*Sqrt[c^2*x^2])}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 5, -((b*c*x*Sqrt[-1 + c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (a + b*ArcSec[c*x])/(3*e*(d + e*x^2)^(3/2)) - (b*c*x*ArcTan[Sqrt[d + e*x^2]/(Sqrt[d]*Sqrt[-1 + c^2*x^2])])/(3*d^(3/2)*e*Sqrt[c^2*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^(5/2)), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x*(d + e*x^2)^(5/2)), x]}
{(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(5/2)), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(5/2)), x]}

{x^6*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 0, Unintegrable[(x^6*(a + b*ArcSec[c*x]))/(d + e*x^2)^(5/2), x]}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 0, Unintegrable[(x^4*(a + b*ArcSec[c*x]))/(d + e*x^2)^(5/2), x]}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 10, -((b*c*x^2*Sqrt[-1 + c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) + (x^3*(a + b*ArcSec[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d*e*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d*e*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 10, (b*c*e*x^2*Sqrt[-1 + c^2*x^2])/(3*d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (x*(a + b*ArcSec[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcSec[c*x]))/(3*d^2*Sqrt[d + e*x^2]) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (2*b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^(5/2)), x, 26, -((b*c*e*Sqrt[-1 + c^2*x^2])/(d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (4*b*c*e^2*x^2*Sqrt[-1 + c^2*x^2])/(3*d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (b*c*(c^2*d + 2*e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d^3*(c^2*d + e)*Sqrt[c^2*x^2]) - (a + b*ArcSec[c*x])/(d*x*(d + e*x^2)^(3/2)) - (4*e*x*(a + b*ArcSec[c*x]))/(3*d^2*(d + e*x^2)^(3/2)) - (8*e*x*(a + b*ArcSec[c*x]))/(3*d^3*Sqrt[d + e*x^2]) + (4*b*c^2*e*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*c^2*(c^2*d + 2*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) + (8*b*e*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcSec[c x]) when m symbolic*)


{(f*x)^m*(d + e*x^2)^3*(a + b*ArcSec[c*x]), x, 6, If[$VersionNumber>=8, -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*x*(f*x)^(1 + m)*Sqrt[-1 + c^2*x^2])/(c^5*f*(2 + m)*(3 + m)*(4 + m)*(5 + m)*(6 + m)*(7 + m)*Sqrt[c^2*x^2])) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*x*(f*x)^(3 + m)*Sqrt[-1 + c^2*x^2])/(c^3*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)*Sqrt[c^2*x^2]) - (b*e^3*x*(f*x)^(5 + m)*Sqrt[-1 + c^2*x^2])/(c*f^5*(6 + m)*(7 + m)*Sqrt[c^2*x^2]) + (d^3*(f*x)^(1 + m)*(a + b*ArcSec[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSec[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSec[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSec[c*x]))/(f^7*(7 + m)) - (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/((3 + m)*(5 + m)*(7 + m)))*x*(f*x)^(1 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^5*f*(1 + m)*(2 + m)*(4 + m)*(6 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]), -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*x*(f*x)^(1 + m)*Sqrt[-1 + c^2*x^2])/(c^5*f*(6 + m)*(8 + 6*m + m^2)*(105 + 71*m + 15*m^2 + m^3)*Sqrt[c^2*x^2])) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*x*(f*x)^(3 + m)*Sqrt[-1 + c^2*x^2])/(c^3*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)*Sqrt[c^2*x^2]) - (b*e^3*x*(f*x)^(5 + m)*Sqrt[-1 + c^2*x^2])/(c*f^5*(6 + m)*(7 + m)*Sqrt[c^2*x^2]) + (d^3*(f*x)^(1 + m)*(a + b*ArcSec[c*x]))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*ArcSec[c*x]))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*ArcSec[c*x]))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*ArcSec[c*x]))/(f^7*(7 + m)) - (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/(105 + 71*m + 15*m^2 + m^3))*x*(f*x)^(1 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^5*f*(1 + m)*(2 + m)*(4 + m)*(6 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2])]}
{(f*x)^m*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 6, If[$VersionNumber>=8, -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*x*(f*x)^(1 + m)*Sqrt[-1 + c^2*x^2])/(c^3*f*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2])) - (b*e^2*x*(f*x)^(3 + m)*Sqrt[-1 + c^2*x^2])/(c*f^3*(4 + m)*(5 + m)*Sqrt[c^2*x^2]) + (d^2*(f*x)^(1 + m)*(a + b*ArcSec[c*x]))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*ArcSec[c*x]))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*ArcSec[c*x]))/(f^5*(5 + m)) - (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*x*(f*x)^(1 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^3*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]), -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*x*(f*x)^(1 + m)*Sqrt[-1 + c^2*x^2])/(c^3*f*(4 + m)*(5 + m)*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) - (b*e^2*x*(f*x)^(3 + m)*Sqrt[-1 + c^2*x^2])/(c*f^3*(4 + m)*(5 + m)*Sqrt[c^2*x^2]) + (d^2*(f*x)^(1 + m)*(a + b*ArcSec[c*x]))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*ArcSec[c*x]))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*ArcSec[c*x]))/(f^5*(5 + m)) - (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*x*(f*x)^(1 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^3*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2])]}
{(f*x)^m*(d + e*x^2)^1*(a + b*ArcSec[c*x]), x, 5, -((b*e*x^(2 + m)*Sqrt[-1 + c^2*x^2])/(c*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) + (d*x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) + (e*x^(3 + m)*(a + b*ArcSec[c*x]))/(3 + m) + (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*x^(2 + m)*Sqrt[-1 + c^2*x^2]*Hypergeometric2F1[1, (2 + m)/2, (3 + m)/2, c^2*x^2])/(c*(1 + m)^2*(2 + m)*(3 + m)*Sqrt[c^2*x^2]), -((b*e*x*(f*x)^(1 + m)*Sqrt[-1 + c^2*x^2])/(c*f*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) + (d*(f*x)^(1 + m)*(a + b*ArcSec[c*x]))/(f*(1 + m)) + (e*(f*x)^(3 + m)*(a + b*ArcSec[c*x]))/(f^3*(3 + m)) - (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*x*(f*x)^(1 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c*f*(1 + m)^2*(2 + m)*(3 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2])}
{(f*x)^m*(a + b*ArcSec[c*x])/(d + e*x^2)^1, x, 0, Unintegrable[((f*x)^m*(a + b*ArcSec[c*x]))/(d + e*x^2), x]}
{(f*x)^m*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 0, Unintegrable[((f*x)^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^2, x]}


{(f*x)^m*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Unintegrable[(f*x)^m*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}
{(f*x)^m*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, 0, Unintegrable[(f*x)^m*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}
{(f*x)^m*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 0, Unintegrable[((f*x)^m*(a + b*ArcSec[c*x]))/Sqrt[d + e*x^2], x]}
{(f*x)^m*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Unintegrable[((f*x)^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^4)^p (a+b ArcSec[c x])^n*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^4)^(p/2) (a+b ArcSec[c x])*)


(* ::Subsubsection:: *)
(*p>0*)


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^11*(a + b*ArcSec[c*x])/Sqrt[1 - c^4*x^4], x, 16, (4*b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(15*c^13*Sqrt[1 - 1/(c^2*x^2)]*x) - (7*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(3/2))/(90*c^13*Sqrt[1 - 1/(c^2*x^2)]*x) + (13*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(5/2))/(150*c^13*Sqrt[1 - 1/(c^2*x^2)]*x) - (3*b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(7/2))/(70*c^13*Sqrt[1 - 1/(c^2*x^2)]*x) + (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(9/2))/(90*c^13*Sqrt[1 - 1/(c^2*x^2)]*x) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSec[c*x]))/(2*c^12) + ((1 - c^4*x^4)^(3/2)*(a + b*ArcSec[c*x]))/(3*c^12) - ((1 - c^4*x^4)^(5/2)*(a + b*ArcSec[c*x]))/(10*c^12) - (4*b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(15*c^13*Sqrt[1 - 1/(c^2*x^2)]*x)}
{x^7*(a + b*ArcSec[c*x])/Sqrt[1 - c^4*x^4], x, 13, (b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(3*c^9*Sqrt[1 - 1/(c^2*x^2)]*x) - (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(3/2))/(18*c^9*Sqrt[1 - 1/(c^2*x^2)]*x) + (b*Sqrt[1 - c^2*x^2]*(1 + c^2*x^2)^(5/2))/(30*c^9*Sqrt[1 - 1/(c^2*x^2)]*x) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSec[c*x]))/(2*c^8) + ((1 - c^4*x^4)^(3/2)*(a + b*ArcSec[c*x]))/(6*c^8) - (b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(3*c^9*Sqrt[1 - 1/(c^2*x^2)]*x)}
{x^3*(a + b*ArcSec[c*x])/Sqrt[1 - c^4*x^4], x, 8, (b*x*Sqrt[1 - c^4*x^4])/(2*c^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSec[c*x]))/(2*c^4) - (b*x*ArcTan[Sqrt[1 - c^4*x^4]/Sqrt[-1 + c^2*x^2]])/(2*c^3*Sqrt[c^2*x^2]), (b*Sqrt[1 - c^2*x^2]*Sqrt[1 + c^2*x^2])/(2*c^5*Sqrt[1 - 1/(c^2*x^2)]*x) - (Sqrt[1 - c^4*x^4]*(a + b*ArcSec[c*x]))/(2*c^4) - (b*Sqrt[1 - c^2*x^2]*ArcTanh[Sqrt[1 + c^2*x^2]])/(2*c^5*Sqrt[1 - 1/(c^2*x^2)]*x)}
{(a + b*ArcSec[c*x])/(x^1*Sqrt[1 - c^4*x^4]), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x*Sqrt[1 - c^4*x^4]), x]}
{(a + b*ArcSec[c*x])/(x^5*Sqrt[1 - c^4*x^4]), x, 0, Unintegrable[(a + b*ArcSec[c*x])/(x^5*Sqrt[1 - c^4*x^4]), x]}


(* ::Section:: *)
(*Integrands of the form u (a+b ArcSec[c x])^n*)
